### ISSUE TITLE
Redirect URI state parameter is not properly decoded

### ISSUE THREAD

**Issue by miltador** [websanova/vue-auth#100]
I faced the problem with decoding state query param in redirect URI when trying to use Amazon OAuth2 provider.

Amazon redirects on the following URI (taken from real life app):
```localhost:8080/login/amazon?code=some_code&scope=profile&state={&#34;rememberMe&#34;:false}```

The `state` query param value is: `{&#34;rememberMe&#34;:false}`

Current decoding code is (simplified for testing purpose):
```
var queryState = '{&#34;rememberMe&#34;:false}';
var state = JSON.parse(decodeURIComponent(queryState));
```

**Expected result:**
```
console.log('state', state);
state Object { rememberMe: false }
```

**Actual result:**
```
SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data 
```

**Comment by websanova** [comment]
Can you paste the link that is actually getting sent to Amazon

**Comment by miltador** [comment]
Here:
`https://na.account.amazon.com/ap/oa?appActionToken=2hhkhvM83LMWHqgIa0lo2e5gNXIj3D&appAction=actionField&savedParameters=eyJwIjoiOUljTjRVeXJJazZDTmZjQndaZk5oZVh2Z0J3aHdGbVNlM0pVTW1wczM4OW9SV1preCtpeDUyMHpqcGdSMWdiQktyTnU0dFlMN2xwcFIycS9oYW5HUHBiUXAwMzlJWHF3MG9JRlZmWVBSNU13cGwxb0FmTFR5eUFRWStZOTVQajNvcnQ0dzYveUNuUmtlQTByQ1BrVFlIRHZiZUw4aUw3Y2lJcVh0Yi8vV3cwZHBsaTFZR2gyWmpaUGRZOWJLUkU1blZnUU5ZMUNsWkVvQnllRVo2VkVONVI0OTFzdTBzSTIrbnFHMEFBa0htY2NxVXZ2WnJzb3IvU1NFM1hXQXlrbml4bUtGaDhwT2JhdzRxZEVDbjlRYmtVM2lScVFiNFREVHFYdHBUSjZGL05QeDFsVFFoRmZSVjZsc2VOUEoxQXJ1ZmkxWmlnUHVYalkybE5pa2NING1BbjBwQ0JkbWk5QTZyaVM4RDZGZ1FIK2krWm5NZy9oR0s0S1ZzRDQraWpORzFFNHRoK3dyLzNSc0o2NVg1QWVQalhxUDBJNzl4V0EzNTI2dTJ1SGRDRTJvbEUzdWdZWDBmNEg1MGVCa01sNmVlY0l1ZkUyRzhZVWU4cEgzQ2ZNdXh2U1BWNGtSczArK2lYSFJUMGREQnYxT3hUaiswRWNBY1N6U0ZIMG5mUWVzelJWVWoyTVh3NEQyRXpWWXUzbHExbFExQUZoRWxQSkl2U3JaNU5WTHI5S0J2OS90SDl0Yjh6ZlUvNjZmMjRDa2xBencyWnZXdlJjWEVkNlFmZit0aXpWZVdLbTIwdmlpbUdwbUNaQnloSk0rY3V5VnJZR2hRV2s0WnQxSVJVUm1oSE1VSGRubjFrZ0g4Q0wvb0tzejZIWXBhL1VTdXRkVldPTURqTUFTR1BUcENrZjFtOWFTWk1BYU5MejcyNWJiK2hKNVlJcVh4M1kyMUtCZE0xeCtsV094bk5ETTdEY2VGSnZKVE4zampXZVBTNXRLQ2VEWFVrR3dhY2FBc2wzcERrTTNBaXNtVTU3dEJhMVpZTmQzbE5ZM3JrWHhHK1lTdkJ4MGZFWmFJWDlzM0tVb2h3RzVMa2krc0llZ0U1TFJtK0haOS83N2VDNUs3Q2trd0VOZjVVbmRoRHBkTlpNZWhaN0hkTnltUWFVTHg2MnNROFZZd0k0QmpKZFJndUt1M0VBUHN0TEM5VHZQcmgrMFdRWWUyM2dBYlRic1pDRS9BV2hnOExpcGVzMDl4U0lvaVdDdzh5aUEySHBMS0Y1QWN2eENPYmdBc2hXbWlOZndQNzB4c01HaHlYMXZzenMwTldOQTR2Mmt0UVBDSllBS2tVS0haL2QyT3BJM0EyaTZUeWNtb1pLdGZGQldGMmZZNEp3b1RrSUdwQjdZcERudHExUGVsSW5ZckZobUR1aFV3b1dqVml3dkkxT0Y2WmM3ekNGSHcraGNwSk8rbE9qUkdGbUJhL3BnUzNsVVB2dzYveDE3NnVaMTFCZ0Uvb05LUjd0VnppeUR4OTRNMU8xeVpvU2g5dTg1MW81RWRYOHlib0pzZy9Galdyd01TRWFDL0NGZXZPZHY3M3RLbm16VWdRSFRyMUNmSGtocUZnVjF0M1BWZ0w0NDNlVU9QVXo1d1hQaUN0TllkQ0Z5S1FuV0VwUEFrNEFTYmI4b1NyYXBKem4yMEF5UVpGbzIrNzciLCJpIjoiUm1vVFlYb0dpMkUxMXRKLzl0dERSUT09IiwicyI6IkNLU0ZmRlIvQnBLeUZpR1hLODcxM2ZjS3FHdG1sWXJnMDdaMmZVVmJ3TE09IiwiZXYiOjEsImh2IjoxfQ&aToken=Atza|IwEBICPczrEXDvceVAraRTfmUzwEi3Ybx9YfbN1tT7ORxJIRWylaeG9OeOvFUThWUOfV6jWR_a_YIbKaM9m20nj5w0zbvxL_-pyL-1MBDMp5DKB9t7oJ_5JEp3V37fzY1ASI9LJpK5MaWCFaFRN5iX2cynpcYpnXd9M9Tx0tT5I1ZwCwfAGrxadzKt0eQEF-5l3vX1ahHFWcFG85fHsw9jQyutk4mnEGfzbwwSp-8douEx5Sfy30DQ33vo5m3EcjWhKGEUOD6or28snBQnzFXnkr-WDCRWIAFL714OtoaV0v3cX522AL5bQZ2DK5V7He3J5AuIf5QBXxsSIi8sSMJ-uPir7CZ8gfsc9w44hhXFIcFfwBKAO00mlZEEqgasHxr376Hw97YIT8PAuP_tFTyIaDsJs3&openid.pape.auth_policies=http://schemas.openid.net/pape/policies/2007/06/none&language=en_US&acknowledgementApproved=`

**Comment by websanova** [comment]
Or also just maybe use the he library locally before parsing state. You should still be able to get a valid state param back

**Comment by websanova** [comment]
There is not state parameter in that url

**Comment by miltador** [comment]
Yes, because I sent you a link that redirects me to amazon. Can you clarify what link do you need?

**Comment by miltador** [comment]
Sorry, wrong link.
Here it is:
`https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.f6c22f2bcae04f1994cdda497c1b235a&redirect_uri=http://localhost:8080/login/amazon&scope=profile&response_type=code&state={"rememberMe":false}`

**Comment by websanova** [comment]
Ok, so the current version seems to work fine with Facebook and Google which will make up a majority of the use cases. I also use this with Buffer's API which seems fine.

So Amazon seems to be a special case, but it's to low volume to justify adding the bloat. I've opted to add an option for parsing the oAuth state.

Default:
~~~
parseOauthState: function (data) {
    return JSON.parse(decodeURIComponent(data));
}
~~~

You can just override it.

**Comment by miltador** [comment]
@websanova, thanks!
