### ISSUE TITLE
feature request global header authorization. 

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#101]
If you take a look at Peter's implementation its very interesting.  If the token is valid it will set globaly set the headers for a Bearer.  This way it will be easier to do post or get requests that require token authorization using AXIOS.

https://github.com/petervmeijgaard/vue-2.0-boilerplate/blob/master/src/app/store/modules/auth/mutations.js#L12

**Comment by websanova** [comment]
OK, but dont think I'll be doing any rewrites for now.

**Comment by kyoukhana** [comment]
I know you are busy but it would really be nice to have this feature if possible.

**Comment by websanova** [comment]
Not sure I would add this, couldn't you just set your own interceptor?

**Comment by websanova** [comment]
btw, the plugin is already sending these headers on each request, so not
quite sure what you're really going for anyway.

**Comment by kyoukhana** [comment]
I came up with a solution basically use a custom auth driver  and then when the token response returns assign it to axios

```
var myBaerer = {

    request: function (req, token) {
        this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
    },

    response: function (res) {
        var headers = this.options.http._getHeaders.call(this, res),
            token = headers.Authorization || headers.authorization;



        if (token) {
            token = token.split(/Bearer\:?\s?/i);

            /*we can get the token for AXIOS */
           // console.log(token+'==================');

            Vue.axios.defaults.baseURL = domainUrl;
            Vue.axios.defaults.headers.common['Authorization'] = token;



            return token[token.length > 1 ? 1 : 0].trim();
        }
    }
};
```

**Comment by websanova** [comment]
Ok, nice.

Just curious, what's reason for this global header? The driver is already
adding the header to each request.

**Comment by kyoukhana** [comment]
Hope you had a great weekend.  The reason is to set the global default headers for axios if it requires for POST or get that requires a Bearer auth token.  

```
var myBaerer = {

    request: function (req, token) {
        this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
    },

    response: function (res) {
        var headers = this.options.http._getHeaders.call(this, res),
            token = headers.Authorization || headers.authorization;



        if (token) {
            token = token.split(/Bearer\:?\s?/i);

            /*we can get the token for AXIOS */
           // console.log(token+'==================');

            Vue.axios.defaults.baseURL = domainUrl;
            Vue.axios.defaults.headers.common.Authorization = token ? `Bearer ${token}` : '';



            return token[token.length > 1 ? 1 : 0].trim();
        }
    }
};
```

**Comment by websanova** [comment]
Yes, the plugin is already setting those on each request through the
interceptors (or should be) by default.

**Comment by kyoukhana** [comment]
Yea since I am still using vue 1.x i find it hard to mix match vue-resource with axios.  When I rewrite my app I will have to move everything to axios
