### ISSUE TITLE
No token is sent to /auth /user

### ISSUE THREAD

**Issue by Friday14** [websanova/vue-auth#105]
Hello, I can not understand what's going on, please help. Upon receipt of the token on the auth / login, sent a request to / auth / user. But headers do not have a token.
P.S Sorry for my bad english

![screenshot_1](https://cloud.githubusercontent.com/assets/19715579/23192346/fb372ea0-f8b3-11e6-88f5-cea37e5f936c.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/19715579/23192347/fedc2664-f8b3-11e6-87d9-a488926a326a.jpg)

**Comment by websanova** [comment]
And if you refresh after login, is the token still missing?

**Comment by Friday14** [comment]
I hope I understand correctly.
Yes the token is not saved.

**Comment by websanova** [comment]
OK, but strange. Do you have any other intercepts in your code, perhaps
from other plugins.

Can I see some code also. Like how you are including the plugin.

**Comment by Friday14** [comment]
https://gist.github.com/Friday14/50de921d94261ce69b47c6ec53cc4924

**Comment by websanova** [comment]
Ah ok, I see the issue.

So you are using bearer auth which requires the token to be in the form
`Bearer: kfjdfkdjfd....`.

If you want to go without it you should use the basic driver.

https://github.com/websanova/vue-auth/blob/master/drivers/auth/bearer.js

https://github.com/websanova/vue-auth/blob/master/drivers/auth/basic.js

I will admit this needs some more documentation :-)

**Comment by Friday14** [comment]
Do not quite understand, to make it work, I should give a header Authorization: `Bearer: kfjdfkdjfd ....`?
Or send a token in the request body?

And still do not understand Bearer driver of headers can only get Content-Type,
Appropriately token = headers.Authorization || headers.authorization;
Always undefined

Thank you very much for helping me

**Comment by websanova** [comment]
Oh man, it's just format dude.

Did you try the basic driver?

**Comment by Friday14** [comment]
It worked, thank you, and again, I apologize for my English, many probably did not understand :)

**Comment by SkyNetRu** [comment]
in my situation I opened site via http:// and requests was via https://
so there was CORS request and browser filtered headers and I was can't get auth token
https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields

for those who make a similar mistake =)
