### ISSUE TITLE
Can't get 2.x.demo (with axios) worked, returns 400 (Bad request) error

### ISSUE THREAD

**Issue by patrin** [websanova/vue-auth#107]
I'm trying to run 2.x.demo with axios.
Here is a part of my 2.x.demo/src/app.js file:
```
import axios from 'axios';
import VueAxios from 'vue-axios';
Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = 'https://api-demo.websanova.com/api/v1';

// Http 
// Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';

// Vue Auth
Vue.use(require('../../src/index.js'), {
    auth: require('../../drivers/auth/bearer.js'),
    // http: require('../../drivers/http/vue-resource.1.x.js'),
    http: require('../../drivers/http/axios.1.x.js'),
    router: require('../../drivers/router/vue-router.2.x.js'),
    rolesVar: 'role',
    facebookOauth2Data: {
        clientId: '196729390739201'
    },
    googleOauth2Data: {
        clientId: '337636458732-tatve7q4qo4gnpfcenbv3i47id4offbg.apps.googleusercontent.com'
    }
});
```
(I uncommented axios-related lines and and commented vue-resource lines).
When i'm trying to login as admin on https://0.0.0.0:8002/login page, I get error 400.
`{"status":"error","error":"invalid.credentials","msg":"Invalid Credentials."}`
 Also I can't see username and password data in request body.

**Comment by websanova** [comment]
Yes, of course, they are two different libraries. There is a reason it's commented out :-)

All the code in the demo is written on this.$http not this.axios ;)

The plugin can be made to work on both, but this is not meant to demo the portability of the two.
