### ISSUE TITLE
fetchUser option & parameter both ignored

### ISSUE THREAD

**Issue by jkubecki** [websanova/vue-auth#108]
I'm having an issue with the `loginData.fetchUser` option being ignored, as well as the `fetchUser` parameter passed to the `login` method.

I've reproduced the behavior in a small app, and posted on GitHub here: https://github.com/jkubecki/vue-auth-from-cli

When building the small app, I...

1. Created the new app using `vue-cli`. I used the `webpack` template, and took all defaults, _including_ vue-router, but _excluded_ eslint and tests, for simplicity.
1. Added in `vue-resource` and `vue-auth`, using `npm install --save`
1. Added the code to `main.js` to support both. *Note:* I'm using the websanova API endpoint, like the demo apps.
1. Added a simple login page (Login.vue), using the code from the 2.x demo app.
1. Tried adding both the `fetchUser` option in `main.js`, as well as the `fetchUser` parameter in `Login.vue`.
1. Upon logging in, if you watch network activity in Chrome Dev Tools, you'll still see a request to the *user* endpoint.

(I found the issue when attempting to incorporate vue-auth into my _own_ app, which does not as yet have the user endpoint, so it was throwing a 404 in the console upon login, even with the options set.)

Any ideas on why this may be occurring? Is this perhaps related to #95 ?

**Comment by websanova** [comment]
Ok, this is fixed in `v2.8.1-beta`.

**Comment by hurradieweltgehtunter** [comment]
Hi,
i just updated to 2.8.1 and now i'm getting a lot of errors. 
`[Vue warn]: Error in beforeCreate hook: 
(found in <Root>)
warn @ vue.js:569
handleError @ vue.js:1450
callHook @ vue.js:2229
Vue._init @ vue.js:3639
Vue$3 @ vue.js:3733
(anonymous) @ index.js:94
__webpack_require__ @ bootstrap 15b28a1…:555
fn @ bootstrap 15b28a1…:86
(anonymous) @ bootstrap 15b28a1…:578
__webpack_require__ @ bootstrap 15b28a1…:555
(anonymous) @ bootstrap 15b28a1…:578
(anonymous) @ bootstrap 15b28a1…:578
vue.js:1454 RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at matchRoute (http://localhost:9000/js/index.js:65462:21)
    at Object.match (http://localhost:9000/js/index.js:65345:14)
    at VueRouter.match (http://localhost:9000/js/index.js:66251:24)
    at HTML5History.transitionTo (http://localhost:9000/js/index.js:65686:28)
    at HTML5History.push (http://localhost:9000/js/index.js:66005:11)
    at http://localhost:9000/js/index.js:65746:79
    at Auth.<anonymous> (http://localhost:9000/js/index.js:26069:26)
    at Auth._transitionEach (http://localhost:9000/js/index.js:26168:21)`

I'm using axios. 
No errors occur when I uninstall the plugin und no errors before updating.

**Comment by websanova** [comment]
Whoops, try `2.8.2-beta` :-)

**Comment by hurradieweltgehtunter** [comment]
errors are solved, thank you.
But "fetchUser: false" still gets ignored.
-> /login gets called, username & password (in "data", not "body") are present
-> response: {token: <token>}
-> /auth/user gets called, although "fetchUser: false" is set
-> fails, because method is OPTIONS

**Comment by websanova** [comment]
Well it will still log the user in, it just doesn't fetch the user.

**Comment by hurradieweltgehtunter** [comment]
isn't the /auth/user call controlled by the fetchUser option?
If not, why doesn't get the token set in the header?

**Comment by websanova** [comment]
Not really sure what you mean. But yes the auth/user should not get called
if fetchUser is set to false.

**Comment by hurradieweltgehtunter** [comment]
sry, fetchUser was set to true for testing case. updated prev comment. req to /auth/user still gets called

**Comment by websanova** [comment]
So seems it only works at the global config. If you pass it through locally
at $auth.login it will get lost.

I don't really have to time to fix this right now though. Can you just use
it globally for now? Or you can set it directly on/off at login using $auth.

**Comment by hurradieweltgehtunter** [comment]
no problem. 
bigger question is why the get request to /auth/user becomes OPTIONS.
I think the headers are not set correctly although in index.js:
`axios.defaults.headers.common['Content-Type'] = 'application/x-www-form-urlencoded'`

**Comment by websanova** [comment]
What do you mean OPTIONS? Are you doing CORS request?

**Comment by hurradieweltgehtunter** [comment]
Yes but the first request to /login works, so i think the CORS headers are set correctly.
But the global set header 'application/x-www-form-urlencoded' is not present on the following call to /auth/user

**Comment by websanova** [comment]
Hmm, should just be whatever is default. It doesn't touch the headers
much.  If you need headers I believe you can just create a simple intercept
in the app though.

**Comment by hurradieweltgehtunter** [comment]
already doing
```
axios.interceptors.request.use(function (config) {
  // Do something before request is sent
    config.headers.common['Content-Type'] = 'application/x-www-form-urlencoded'
  return config
}, function (error) {
  // Do something with request error
  return Promise.reject(error)
})`

/auth/user:
![image](https://cloud.githubusercontent.com/assets/16665512/23555020/9604fef6-0027-11e7-8378-82224f1f0b38.png)

**Comment by websanova** [comment]
ah ok, I don't have so much experience with axios. But last time I tried
them the interceptors weren't working. Try a console.log in there and see
if anything shows up.

**Comment by hurradieweltgehtunter** [comment]
i'm switching to vue-resource right now :(

**Comment by jkubecki** [comment]
@hurradieweltgehtunter, /auth/user shouldn't need a content-type header, as it's just a GET request - i.e., there is no body. Looks like it's designed to hit an endpoint (/auth/user) that just returns data about the _currently authenticated_ user.

@websanova, haven't checked my test app with 2.8.2 just yet, will do so shortly.

**Comment by websanova** [comment]
OK, thx James. Try those interceptors outside of the plugin. I was having
some issues with it in axios.

**Comment by jkubecki** [comment]
Confirmed working on 2.8.2 beta.
