### ISSUE TITLE
How can i add axios.interceptors.response.use ?

### ISSUE THREAD

**Issue by gongzza** [websanova/vue-auth#110]
For example:
```
Vue.axios.interceptors.response.use(function(data) {
  console.log('axios res data')
  return data
})

this.axios.interceptors.response.use(function(data) {
  console.log('app res data')
  return data
})
```
and i called `this.$auth.fetch` but i couldn't get the message

**Comment by websanova** [comment]
I think there is bug with axios interceptors...I have not been able to get
them to work properly myself.

**Comment by gongzza** [comment]
i called it before `vue-auth`, so it worked

**Comment by gongzza** [comment]
um... dosen't work.. T.T

**Comment by Fuhrmann** [comment]
I am having the same problem. 

When the "refresh" request return a 401 error, meaning the token is invalid, the app doesnt redirect to the login page.

`
this.options.http._interceptor.call(this, this.options.requestIntercept, this.options.responseIntercept);
`

I've tried to debug the call to the interceptor (_responseIntercept function), but it never gets called. Using axios 0.16.1 and vue-axios 2.0.2.
