### ISSUE TITLE
Keep user logged in after page refresh

### ISSUE THREAD

**Issue by rambii** [websanova/vue-auth#112]
In my app I do the Authentication with Laravel and Blade at first. Once the user is logged in (via blade)  the Vue Applicationis mounted. The authentication with vue-auth works fine so far. I use the Passport implementation of laravel on the server side to access the client object.

Currently I fetch the user in created method of the main Vue-App.

Problem:
But when I refresh the page on a route that is protected by an auth role I get redirected to the login because the user is not yet loaded via the fetch method. 

Question:
Is there a way to prevent the router to redirect me as long as the request is not done yet?

I tried to fetch the user before mounting the app, but I don't have access the the fetch method as it needs an Vue instance - I guess.

Am I missing something here? Any help appreciated.

**Comment by websanova** [comment]
Yes, this should all be automatic.

Would have to see some code

**Comment by rambii** [comment]
Ok, that would be awesome. 

So I tried to condense it a little. Can you see some mistake? Thanks for you help.

app.blade.layout
```
<body>
    <div id="wrapper">
    ....
            <router-link to="/">Index</router-link>
            <router-link to="/orders">Bestellungen</router-link>
   ....
        <div>
            <app>loading..</app>
        </div>
    </div>
</body>
```

app.js
```
import './bootstrap.js';

Vue.component('app', require('./components/App.vue'));
const app = new Vue({
    el: '#wrapper',
    router: Vue.router,
});
```

bootstrap.js
```
import VueRouter from 'vue-router';
Vue.use(VueRouter);
import router from './routes';
Vue.router = router;

import VueAuth from '@websanova/vue-auth'
Vue.use(VueAuth, {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
});
```

routes.js
```
import VueRouter from 'vue-router';

let routes = [
    {
        path: '/',
        name: 'index',
        component: require('./components/Example')
    },
    {
        path: '/orders',
        name: 'orders',
        meta: {auth: 'view_orders'},
        component: require('./components/Orders')
    },
    ...
];

export default new VueRouter({
    mode: 'history',
    linkActiveClass: 'active',
    routes: routes
});
```

App.vue
```
<template>
    <div>
        <div v-if="$auth.ready() && $auth.check()">
             logged in
             <router-view></router-view>
        </div>

        <div v-if="!$auth.ready() || !$auth.check()">
            application loading...
        </div>
    </div>
</template>

<script>
    export default {
        name: 'App',
        created() {
            this.$auth.fetch({url: '/api/user', method: 'get'});
        },
    }
</script>
```

**Comment by websanova** [comment]
Your router should not be routes, should be router ;)

**Comment by rambii** [comment]
You mean the filename or the variable? Tried changing both but does not help.
Changing the routes key when instantiating the VueRouter breaks the routing.

Do you have any other idea?

**Comment by websanova** [comment]
import router from './routes';
Vue.router = router;


Should be a router like a xios or Vue resource. Not your set of routes.

**Comment by rambii** [comment]
But the file exports a VueRouter, doesn't it?

```
export default new VueRouter({
    mode: 'history',
    linkActiveClass: 'active',
    routes: routes
});
```

**Comment by HelloTiago** [comment]
I'm having the same issue with a similar setup. I used the [vue-cli webpack template](https://github.com/vuejs-templates/webpack).

main.js:
```
import Vue from 'vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueAuth from '@websanova/vue-auth';
import App from './App';
import router from './router';

Vue.config.productionTip = false;

Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = '/api';

Vue.router = router;

Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: { fetchUser: false },
  facebookOauth2Data: {
    clientId: 'xxxxxx',
  },
});

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App },
});
```

And `router/index.js`:
```
import Vue from 'vue';
import Router from 'vue-router';
import LandingPage from '@/views/LandingPage';
import NotFound from '@/views/NotFound';

Vue.use(Router);

export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'home',
      component: LandingPage,
    },
    {
      // Fall back for 404 Not Found routes
      path: '*',
      component: NotFound,
    },
  ],
});
```

**Comment by HelloTiago** [comment]
I managed to find a solution to my problem, it turns out I was returning the token on the backend via JSON rather than setting the Auth header - which is what vue-auth is expecting apparently.

Changed from this:
```
return response()->json([
            'token' => $token,
            'status' => 'success',
        ]);
```

To this:
```
return response()->json([
            'status' => 'success',
        ])->header('Authorization', $token);
```

For those using Laravel/Lumen, the demo Laravel API project is a good resource but easy to miss on the documentation: https://github.com/websanova/laravel-api-demo

**Comment by rambii** [comment]
What is the content of the $token?
Is it possible to just pass a default string without any user information? Or does vue-auth use the token to get the information about the user after a page refresh without issuing another ajax request to the auth api?

In my project I use Laravel Passport which is incompatible with JWTAuth, that's why I pass a string instead of a token.

**Comment by websanova** [comment]
What vue auth expects depends on the driver you are using. the drivers typically look for an `authorzation: Bearer: tokengoeshere` response.

However it's not difficult to write a custom driver, just take a look at the code for the available ones ;)

**Comment by gezichenshan** [comment]
I stuck in the same situation.

In my Login.vue, I store the token send from server in `axios.defaults.headers.common['Authorization'] = token` and going to a Dropdown.vue page.
but when I refresh the page , the axios.defaults.headers.common['Authorization']  is undefined,and refirect me to the Login.vue.

**Comment by websanova** [comment]
Well you would have to reset it each time, seems bit strange to do it this
way. just use the drivers to set the header is the intended way.

**Comment by icangku** [comment]
Anyone have done this issue?

**Comment by lsocha** [comment]
I have resolved this issue, by adding `refreshData: { enabled: false },` 
In index.js file I have now:

`Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  refreshData: { enabled: false },
});`

Now, after refreshing whole page user keep logged in.

**Comment by dxxd116** [comment]
You should have a setTimeout function in the main Vue component, 
e.g., in the mounted callback

`
mounted() {
            var _this = this;
            // Set up $auth.ready with other arbitrary loaders (ex: language file).
            setTimeout(function () {
                _this.loaded = true;
            }, 500);
        }
`
This will let the Vue-Auth to fetch the user info and setting this.$auth.user() properly. Though I think this should have been done inside 
`
this.$auth.ready(function(){ 
   // Get this.$auth.user() here.
})
`

**Comment by websanova** [comment]
No, just use auth.ready, it accepts a callback

**Comment by dvikas** [comment]
> I stuck in the same situation.
> 
> In my Login.vue, I store the token send from server in
> 
> `axios.defaults.headers.common['Authorization'] = token` and route to a Dropdown.vue page.
> 
> but when I refresh the page , the axios.defaults.headers.common['Authorization'] is undefined,and refirect me to the Login.vue.

Hello, 
you can use "vuex-persistedstate" library to make persist "token" on page load.
I am also using in your way with vuex-persistedstate.

**Comment by hominhnhat181** [comment]
hi everyone, i'm new here, i'm using ajax to fetch data but when everything done in function success i have to use window.reload to reload the data but when using it then my bearer token is gone and middw push me back to the login page, anyone could help

**Comment by websanova** [comment]
@hominhnhat181  Can you verify the token exists in local/session storage before the refresh?

**Comment by nashgc** [comment]
Hi there! I have a similar issue. I'm new to vue-auth but anyway this situation is confusing.
I have a couple simple buttons on my app bar, there is an "if"- "else" statement based on "!$auth.check()" method. So when I logged in it shows me right button "logout". Then I just press F5 and reload the page, after that I see "login" button instead. With my curiosity after reload I go to local storage and it still has two params "auth_token_default" and "auth_stay_signed_in". So I wonder wtf ;) Please let me know hot to deal with this situation, I can provide anything for resolve this situation, just say what I should to do.
