### ISSUE TITLE
Cant use vue resource or axios http

### ISSUE THREAD

**Issue by jkirkby91-2** [websanova/vue-auth#113]
I used the v1 of this package building upon the demo provided a few months ago, im now starting a new project using the webpack template trying to integrate vue-auth v2 into it with no luck.

i have my main.js in the root of my src folder like so

```
import Vue from 'vue'
import App from './App'
import router from './router'
import 'vue-material/dist/vue-material.css'

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```

then in the router folder i have a index.js looking like

```
import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'
import VueRouter from 'vue-router'
import VueMaterial from 'vue-material'
import VueAuth from '@websanova/vue-auth'

Vue.use(VueRouter, VueMaterial)

export default new VueRouter({
  hashbang: false,
  linkActiveClass: 'active',
  mode: 'history',
  base: __dirname,
  routes: [
    {
      path: '/oauth2',
      name: 'oauth2',
      component: require('../components/auth/Oauth2.vue')
    },
    {
      path: '/register',
      name: 'register',
      component: require('../components/auth/Register.vue'),
      meta: {auth: false}
    },
    {
      path: '/',
      name: 'login',
      component: require('../components/auth/Login.vue'),
      meta: {auth: false}
    }
  ]
})

// Vue Auth
Vue.use(VueRouter, VueMaterial, VueAxios, axios, VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  facebookOauth2Data: {
    clientId: '196729390739201'
  }
})
```

following the readme regardless if i use axios or vue-resource either Vue.http or Vue.axios is always undefined. Im not sure if the demos use the the vue-cli template or a different one but i think moving forward they should be based off one of these as it would help new users understand more how to integrate the pack or i might just be missing something real simple ;)

any help appreciated!

**Comment by websanova** [comment]
I dont see any import for axios or Vue resource

**Comment by jkirkby91-2** [comment]
@websanova hmm seemed to cut some of my imports

**Comment by RussNZ** [comment]
@jkirkby91-2 I'm also using the vue cli webpack template but not have much luck with this ... did you get it working? would love to see a working example if you have one :)
