### ISSUE TITLE
Accessing public pages

### ISSUE THREAD

**Issue by rajf** [websanova/vue-auth#114]
I've been working though the demo site, which is fine but when I role the code into my own build I encounter the following issue:

When not logged in I can access routes with a meta definition aka

`{
        path: '/register',
        name: 'register',
        component: require('./components/pages/Register.vue'),
        meta: {auth: false}
    }`

but any public routes without a meta definition such as 

`{
        path: '/async',
        name: 'async',
        component: function(resolve) { require(['./components/pages/Async.vue'], resolve); }
    }`

are inaccessible and redirect to the login page. If I login I can access protected routes but the aforementioned route and any other public route result in  

`Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at matchRoute (http://chert.dev:8000/chert/scripts/chert.js:10969:21)
    at Object.match (http://chert.dev:8000/chert/scripts/chert.js:10852:14)
    at VueRouter.match (http://chert.dev:8000/chert/scripts/chert.js:11758:24)
    at HTML5History.transitionTo (http://chert.dev:8000/chert/scripts/chert.js:11193:28)
    at HTML5History.push (http://chert.dev:8000/chert/scripts/chert.js:11512:11)
    at http://chert.dev:8000/chert/scripts/chert.js:11253:79
    at Auth.<anonymous> (http://chert.dev:8000/chert/scripts/chert.js:15835:26)
    at Auth._transitionEach (http://chert.dev:8000/chert/scripts/chert.js:15068:21)`

This appears to be because the code is trying to do a redirect to /403. The /403 route 

'{
        path: '/403',
        name: 'error-403',
        component: require('./components/pages/403.vue'),
    }'

returns returns the same call stack exception.

Complete code:

`import Vue from 'vue'
import VueRouter from 'vue-router'
import VueResource from 'vue-resource'

// Install plugins
Vue.use(VueRouter)
Vue.use(VueResource)

Vue.config.devtools = true

// Router
Vue.router = new VueRouter({
    hashbang: false,
    linkActiveClass: 'active',
    mode: 'history',
    base: __dirname,
    routes: [{
        path: '/',
        name: 'default',
        component: require('./components/pages/Home.vue')
    }, {
        path: '/login',
        name: 'login',
        component: require('./components/pages/Login.vue'),
        meta: {auth: false}
    }, {
        path: '/login/:type',
        name: 'oauth2-type',
        component: require('./components/pages/Oauth2.vue')
    }, {
        path: '/register',
        name: 'register',
        component: require('./components/pages/Register.vue'),
        meta: {auth: false}
    }, {
        path: '/oauth1',
        name: 'oauth1',
        component: require('./components/pages/Oauth1.vue')
    }, {
        path: '/oauth2',
        name: 'oauth2',
        component: require('./components/pages/Oauth2.vue')
    }, {
        path: '/account',
        name: 'account',
        component: require('./components/pages/Account.vue'),
        meta: {auth: true}
    }, {
        path: '/async',
        name: 'async',
        component: function(resolve) { require(['./components/pages/Async.vue'], resolve); }
    }, {
        path: '/admin',
        name: 'admin',
        component: require('./components/pages/Admin.vue'),
        meta: {auth: 'admin'},
        children: [{
            path: 'products',
            name: 'admin-products',
            component: require('./components/pages/admin/Products.vue'),
            children: [{
                path: ':product_id',
                name: 'admin-product',
                component: require('./components/pages/admin/Product.vue'),
                children: [{
                    path: 'info',
                    name: 'admin-product-info',
                    component: require('./components/pages/admin/ProductInfo.vue'),
                    meta: {auth: undefined}
                }, {
                    path: 'media',
                    name: 'admin-product-media',
                    component: require('./components/pages/admin/ProductMedia.vue')
                }]
            }]
        }]
    }, {
        path: '/users',
        name: 'users',
        component: require('./components/pages/Users.vue'),
        meta: {auth: ['admin']},
    }, {
        path: '/404',
        name: 'error-404',
        component: require('./components/pages/404.vue'),
        meta: {auth: undefined}
    }, {
        path: '/403',
        name: 'error-403',
        component: require('./components/pages/403.vue'),
    }, {
        path: '/502',
        name: 'error-502',
        component: require('./components/pages/502.vue'),
    }]
});

// Http 
Vue.http.options.root = 'https://api-demo.websanova.com/api/v1'

// Vue Auth
Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    rolesVar: 'role',
    facebookOauth2Data: {
        clientId: '196729390739201'
    },
    googleOauth2Data: {
        clientId: '337636458732-tatve7q4qo4gnpfcenbv3i47id4offbg.apps.googleusercontent.com'
    },

})

// Start
var component = require('./components/App.vue');

component.router = Vue.router;

new Vue(component).$mount('#app');`

The rest is as per [https://github.com/websanova/vue-auth/tree/master/2.x.demo](https://github.com/websanova/vue-auth/tree/master/2.x.demo) but I'm building my project using vue-loader so amended for the relevant imports.

I set my package.json to use the same versions as [https://github.com/websanova/vue-auth/tree/master/2.x.demo/src/assets/js](https://github.com/websanova/vue-auth/tree/master/2.x.demo/src/assets/js) but got the same errors. I'm now using:

`"@websanova/vue-auth": "^2.8.1-beta",
    "vue": "^2.1.10",
    "vue-resource": "^1.2.0",
    "vue-router": "^2.2.1"`

but still not joy. I've searched for days but can't find anything on what might be causing this redirect. Any help would be greatly appreciated.

**Comment by websanova** [comment]
Can you setup a jsfiddle or something, who knows what's going on in there ;)
