### ISSUE TITLE
Delimiter in api url

### ISSUE THREAD

**Issue by litvinenkow** [websanova/vue-auth#116]
My own api server has address like
`http://api.url/api/mobile.php?code=123`
And when i try to get some info i add something like `&action=user` but plugin adds another `/` which causes full url to be like `http://api.url/api/mobile.php?code=123/&action=user` . Can i change this delimiter to `&` or nothing at all?

**Comment by websanova** [comment]
I don't think that's from the plugin.

Can you provide a fiddle?

**Comment by litvinenkow** [comment]
Sorry, too much configs there and dependencies, dunno how to copypaste them in the working way to the fiddle.

Can provide just this.
`
Vue.axios.defaults.baseURL = (process.env.NODE_ENV == 'production')?'https://www.site.com/api/mobile.php?code=123':'http://shop/api/mobile.php?code=123';

Vue.use(VueAuth, {
	auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
	http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
	router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
	token: [{request: 'token', response: 'token', authType: 'bearer', foundIn: 'header'}],
	authRedirect: {path: '/account/login.html'},
	loginData: {url: '&action=auth', method: 'GET', redirect: '/account/', fetchUser: true},
	logoutData: {url: '&action=logout', method: 'GET', redirect: '/account/login.html', makeRequest: false},
	refreshData: {url: '&action=refresh', method: 'GET', enabled: false},
	fetchData: {url: '&action=user', method: 'GET', enabled: true,  authType: 'bearer'},
	rolesVar: 'role_id'
});
`
Resultting url looks like
`http://shop/api/mobile.php?code=982jdyug3bks**/**&action=user`

**Comment by websanova** [comment]
Yes, it's not really anyway for me to test this. Could be from anywhere in
your code.

If you can at least reproduce in my demo code that would help.

**Comment by litvinenkow** [comment]
You can copy and paste code below to your 2.x example and you can see that requests go to 

`http://shop/api/mobile.php?code=123/&action=user`

Vue.axios.defaults.baseURL = 'http://shop/api/mobile.php?code=123';

Vue.use(require('../../src/index.js'), {
	auth: require('../../drivers/auth/bearer.js'),
	http: require('../../drivers/http/axios.1.x.js'),
	router: require('../../drivers/router/vue-router.2.x.js'),
	token: [{request: 'token', response: 'token', authType: 'bearer', foundIn: 'header'}],
	authRedirect: {path: '/account/login.html'},
	loginData: {url: '&action=auth', method: 'GET', redirect: '/account/', fetchUser: true},
	logoutData: {url: '&action=logout', method: 'GET', redirect: '/account/login.html', makeRequest: false},
	refreshData: {url: '&action=refresh', method: 'GET', enabled: false},
	fetchData: {url: '&action=user', method: 'GET', enabled: true,  authType: 'bearer'},
	rolesVar: 'role'
});

**Comment by websanova** [comment]
How are you adding action=user ?

**Comment by litvinenkow** [comment]
it adds in the config, as you can see i don't perform any concatinations by myself

**Comment by litvinenkow** [comment]
also don't understand how to fetch user
user sets authenticated, but object is empty, in what parameter of the response must be user?
my response looks like 
```
{"status":"success",
"data":"id":"1","login":"admin","name":"Administrator","email":"dalimo@yandex.ru","phone":"79033347838","reg_date":"0000-00-00 00:00:00"}}
```
overriding of method `_parseUserData` gives nothing in console
```
_parseUserData: function (data) {
		console.log('_parseUserData');
		console.log(data);
		return data.data;
	}
```
please help, can't undestand nothing in your plugin for the week already(((

**Comment by litvinenkow** [comment]
also such routing works not well
```
{
	name: 'account',
	path: '/account',
	component: account,
	meta: {auth: true},
	children: [
		{
			name: 'login',
			path:'login.html',
			component:login,
			meta: {auth: false},
		},
		{
			name: 'orders',
			path:'orders.html',
			component:empty,
			meta: {auth: true}
		}
	]
},
```
if i go to /account/ at once get unauthorized and redirected to /account/login.html and get an error with ssr like "The client-side rendered virtual DOM tree is not matching server-rendered content."
as i go from / to /account/ it works well cause i think it fetches user from server right
as i go to /account/login.html at once, got redirected to 404
how i can program this?

**Comment by websanova** [comment]
One issue at a time please :-)

did you try with vue-resource, I'm not sure what axios may be doing...

**Comment by litvinenkow** [comment]
Tryed vue-resource and it generates the same path.

**Comment by websanova** [comment]
Sry, I know this is old issue, but just got time to work on this today:

So yes, if this is your base path of course you will have issues. It's not from vue auth. You can test the issue by making any call directly with axios. It's your `baseURL`

```
Vue.axios.defaults.baseURL = 'http://shop/api/mobile.php?code=123';
```

I don't really use axios but I would imagine you can preset the query parameter `code` somewhere in the config or write a small intercept for it.
