### ISSUE TITLE
jwt bad?!

### ISSUE THREAD

**Issue by musicformellons** [websanova/vue-auth#117]
Uh, maybe you could comment on this?:
https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid?utm_source=webopsweekly&utm_medium=email

**Comment by websanova** [comment]
Meh, my plugin is not biased, it can support sessions or whatever your
token is doing. The actual token/auth part is quite small. At the end of
the day you pass a token back and forth, jwt, session, etc.

This is typical JS world stuff :-)
