### ISSUE TITLE
Nested auth login don't working

### ISSUE THREAD

**Issue by litvinenkow** [websanova/vue-auth#118]
all that written below belongs to 2.x demo
if we just somekind modify app.js file like below, the route /acccount/login stop working as well, even if we add `<router-view>` tag to Acccount.vue

app.js
```
... // routes
/*
     {
     path: '/login',
     name: 'login',
     component: require('./components/pages/Login.vue'),
     meta: {auth: false}
     },
     */
    {
        path: '/account',
        name: 'account',
        component: require('./components/pages/Account.vue'),
        meta: {auth: true},
        children:[
	        {
		        path: '/login',
		        name: 'login',
		        component: require('./components/pages/Login.vue'),
		        meta: {auth: false}
	        }
        ]
    },
...
```

**Comment by websanova** [comment]
Well for starters, you have 2 routes with the same name. Second for nested routes I believe the forward slash needs to be removed.

**Comment by litvinenkow** [comment]
Yes, removing slash works well. Thanks for your answer.
