### ISSUE TITLE
API server not responding

### ISSUE THREAD

**Issue by lobosan** [websanova/vue-auth#126]
Hi, I'm trying to test the 2.x.demo with axios and the webpack vue-cli template, but the baseURL

`https://api-demo.websanova.com/api/v1`

isn't responding. I also downloaded the laravel api but same result.

Is there any way I can test the demo?

**Comment by websanova** [comment]
If you put it in the browser, nothing shows you? You should at least see
some method not found error.

**Comment by lobosan** [comment]
Yes I see that message but I guess the API should be returning json right?

**Comment by websanova** [comment]
Looks like json to me.

{"status":"error","exception":"Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException","code":"NotFound","msg":"Not
Found."}

**Comment by lobosan** [comment]
Hehe yes but is that what should be returning? Or are there other endpoints?

**Comment by websanova** [comment]
Yes, there are other end points, just look at your console in browser ;)
