### ISSUE TITLE
where is AuthBearer in " Install with Vue-Axios"

### ISSUE THREAD

**Issue by mingliao** [websanova/vue-auth#128]
hi,I'am new to vue-auth ,and thanks for the lib :) 
now  i want to use axios demo ,
and i follow the code in *Install with Vue-Axios*

```
Vue.use(VueAuth, {
    auth: AuthBearer,
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
    ...
});
```

but I don't know where is the the AuthBearer, and i think 
`import {AuthBearer } from './../../src/auth';`
but this make error when i stand up the server .
it show me the error info 
**Error (@websanova/vue-auth): "auth" driver must be set.**
here is my app.js in 2.x.demo  i comment some  route code 

```
import App from './components/App.vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueAuth from '@websanova/vue-auth';
import {AuthBearer } from './../../src/auth';

Vue.router = new VueRouter({
....
});
Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = 'https://api-demo.websanova.com/api/v1';

Vue.use(VueAuth, {
    auth: AuthBearer,
    // http: require('../../drivers/http/vue-resource.1.x.js'),
    http: require('../../drivers/http/axios.1.x.js'),
    router: require('../../drivers/router/vue-router.2.x.js'),
    rolesVar: 'role',
    facebookOauth2Data: {
        clientId: '196729390739201'
    },
    googleOauth2Data: {
        clientId: '337636458732-tatve7q4qo4gnpfcenbv3i47id4offbg.apps.googleusercontent.com'
    }
});

var component = require('./components/App.vue');

component.router = Vue.router;

new Vue(component).$mount('#app');
```
where is the **AuthBearer** ? 
tks :)

**Comment by websanova** [comment]
It's in the package, use that as your root.

**Comment by mingliao** [comment]
@websanova  thanks for reply，

i change my code like  this .but it also make error .

```
import App from './components/App.vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import {VueAuth,AuthBearer} from '@websanova/vue-auth'

Vue.use(VueAuth, {
    auth: AuthBearer,
   .....
});

```

and the console show these  error message 
**Uncaught TypeError: Cannot read property 'installed' of undefined**

I don't konw is the **AuthBearer** ref to the diver? and I change my code like this  *require("../../drivers/auth/bearer.js")*,  I change my code  like  the following and  it make effect,:)
```
import App from './components/App.vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueAuth from '@websanova/vue-auth'

Vue.router = new VueRouter({
.....
});


Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = 'https://api-demo.websanova.com/api/v1';

// Http 
Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';

// Vue Auth
Vue.use(VueAuth, {
    auth: require("../../drivers/auth/bearer.js"), //just like the initial code in github.
    http: require('../../drivers/http/axios.1.x.js'),
    router: require('../../drivers/router/vue-router.2.x.js'),
    rolesVar: 'role',
    facebookOauth2Data: {
        clientId: '196729390739201'
    },
    googleOauth2Data: {
        clientId: '337636458732-tatve7q4qo4gnpfcenbv3i47id4offbg.apps.googleusercontent.com'
    }
});

// Start
var component = require('./components/App.vue');

component.router = Vue.router;

new Vue(component).$mount('#app');
```

haha , but with this , if i have some auths (like admin,vistor, login,register  and so on ) how could i  config these auths? ,  i found in */src/auth.js* you have the **defaultOptions**  and in the */src/index.js*  there are some code like `login register` and is it config the auths  ?   is there an example to config the auths? tks .

,and  in the login.vue I change the login behavior `body: this.data.body,` like the [issues/106](https://github.com/websanova/vue-auth/issues/106)   and it make effect,i can't make sure it is a bug ?

```
login() {
                var redirect = this.$auth.redirect();
                this.$auth.login({
                    data: this.data.body,
                    rememberMe: this.data.rememberMe,
                    redirect: {name: redirect ? redirect.from.name : 'account'},
                    success() {
                        console.log('success ' + this.context);
                    },
                    error(res) {
                        console.log('error ' + this.context);

                        this.error = res.data;
                    }
                });
            }
```

**Comment by mingliao** [comment]
ohh，I know   i use the libs in the wrong way，haha，tks you for the libs。 i try to solve the problom i met :)

**Comment by HarleyTan** [comment]
@mingliao hi,how do you fix this problem?

I still don't understand

**Comment by kenanbalija** [comment]
@HarleyTan 

He did this
...
```
import VueAuth from '@websanova/vue-auth' 
import AuthBearer from '@websanova/vue-auth' 
```
...

**Comment by OmgImAlexis** [comment]
@websanova this should be updated on the installation page as it still shows `AuthBearer` being used without an import.

Ref: https://github.com/websanova/vue-auth/blame/master/docs/Installation.md#L40

**Comment by emtiazzahid** [comment]
> @websanova this should be updated on the installation page as it still shows `AuthBearer` being used without an import.
> 
> Ref: https://github.com/websanova/vue-auth/blame/master/docs/Installation.md#L40

link not working
