### ISSUE TITLE
vue-auth not logging out when token expires

### ISSUE THREAD

**Issue by campbellr** [websanova/vue-auth#129]
I'm using vue-auth with the axios driver and I noticed an issue where if i let my token expire, vue-auth doesn't log out (and subsequent requests fail because an expired token is used).

It took some digging, but I *think* the problem is that the axios driver doesn't install an error handler when registering the `responseIntercept` method, so in the error case, the function ( and therefore  `_invalidToken`) method never actually gets called.

The following patch *seems* to restore the expected behavior: 

```diff
diff --git a/drivers/http/axios.1.x.js b/drivers/http/axios.1.x.js
index 0b7da0e..4111e29 100644
--- a/drivers/http/axios.1.x.js
+++ b/drivers/http/axios.1.x.js
@@ -16,10 +16,16 @@ module.exports = {
     }
 
     if (res) {
-      this.options.Vue.axios.interceptors.response.use(function (response) {
-        res.call(_this, response);
-        return response;
-      })
+      this.options.Vue.axios.interceptors.response.use(
+        function (response) {
+          res.call(_this, response);
+          return response;
+        },
+        function (error) {
+          res.call(_this, error.response);
+          return Promise.reject(error);
+        }
+      )
     }
   },

```

@websanova  can you provide any comments? I'd be happy to submit a PR with this fix if it is correct and i'm not overlooking something.

**Comment by campbellr** [comment]
It turns out i was still seeing some weird behaviour even with this change (errors not propagating properly).

I ended up just switching to vue-resource instead of axios and everything seems to work properly.

**Comment by websanova** [comment]
Yes, I've had the same.issue with axios and it's intercepts not
intercepting.

**Comment by imzedi** [comment]
I have the same issue. does anybody find a solution?

**Comment by imzedi** [comment]
By the way, I have changed something and it's now working fine.

**Problem:**  Axios intercepts not intercepting an error. (Flagged Bug on Axios GitHub)

**Temporary solution:** intercepts not recognizing error so ignore `function (error)` , and add condition just like below.

```
if (res) {
      this.options.Vue.axios.interceptors.response.use(function (response) {
        
          if (response.data.error) {

            response.status = 401;
            res.call(_this, response);
            return Promise.reject(response);
          }
            res.call(_this, response);
            return response;

      }, function (error) {
        // Ignore this function
        if (error && error.response) {
          res.call(_this, error.response);
        }
        
        return Promise.reject(error);
      })
    }
```
