### ISSUE TITLE
build the app on axios with vue-cli

### ISSUE THREAD

**Issue by mingliao** [websanova/vue-auth#131]
I use the **vue-cli** for building the example **axios** in demo2 these day with some problem，
if i use the lastest version of *axios*,*vue-axios*... to build the 2.x.demo,it will show some error :(
and i make the demo with the verson on **vue-auth** package.json, and it make work, 
haha, here is the [github link](https://github.com/mingliao/vue-auth) with demo2 for [axios ](https://github.com/mingliao/vue-auth/tree/master/vue-cli-demo2-axios)and[ vue-resource](https://github.com/mingliao/vue-auth/tree/master/vue-cli-demo2-vue-resource) 
and in the axios demo ,in main.js must use the vue-resource and axios like below ,  i think it is a bug but without it the demo can't not work. i hope someone to fix it :)
```
import Vue from 'vue';
import VueResource from 'vue-resource';
import router from './router'
import App from './components/App.vue';
import axios from 'axios'
import VueAxios from 'vue-axios'
import VueAuth from '@websanova/vue-auth';


Vue.use(VueResource);
Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = 'https://api-demo.websanova.com/api/v1';
// Router
Vue.router = router;

Vue.use(VueAuth, {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    rolesVar: 'type',
    facebookOauth2Data: {
        clientId: '196729390739201'
    },
    googleOauth2Data: {
        clientId: '337636458732-tatve7q4qo4gnpfcenbv3i47id4offbg.apps.googleusercontent.com'
    }
});

// Start
new Vue({
  el: '#app',
  router,
  render: h => h(App)
})

```

**Comment by websanova** [comment]
I've had many issues myself with axios, so I just stick with vue-resource. Can't really comment on it.

**Comment by websanova** [comment]
I think this may be fixed in latest version now.
