### ISSUE TITLE
Access $auth in store (vuex)

### ISSUE THREAD

**Issue by rmartins90** [websanova/vue-auth#132]
What's the best way to access $auth object inside vuex store module?

**Comment by websanova** [comment]
Not sure, I don't use vuex. What shows up when you are console(this). Also
I suppose you could use use .bind or .call

**Comment by rmartins90** [comment]
`this` is undefined. I have `context` that has only store stuff. There's any way to import vue-auth instance in use?

**Comment by rmartins90** [comment]
I've imported Vue instance from app.js on my store file but I don't thinks this is a good practice.

**Comment by websanova** [comment]
Well, if you just import it locally it won't be the proper instance of Vue,
unless you somehow create on instance and import that in both the app and
vuex. Im surprised Vuex doesn't have a way to deal with this though. Would
seem it has access to the current instance somehow.

Don't really have time to check their docs right now though.

**Comment by websanova** [comment]
Just came across this on SO:

http://stackoverflow.com/questions/40676416/cant-access-store-when-importing-vuex-instance-from-an-external-file

Anything to do with how you are initially importing?

**Comment by miguelpinto98** [comment]
@rmartins90 did you find any solutions? I have the same problem.

**Comment by websanova** [comment]
How do you access Vue instance in vuex normally? Like for other modules?

Also can't you just define some property to $auth.user() ?

**Comment by miguelpinto98** [comment]
@websanova For now, I need to import the Vue instance into my store. For example, I import and set [VueLodash](https://github.com/Ewocker/vue-lodash) in main.js, but in the store I can not access it by 'this._.random(20) ', but if I declare the Vue instance I access the lodash methods by 'Vue.\_.random (20) '. I try to use 'Vue.$Auth ', but is undefined. Is Vue-auth incompatible with vuex?

Another question, if you want to call the '$auth' methods in a separate file, how do you access the methods? Thus, for example:

LoginForm.vue
```js
...
import auth from '../api/auth'
...
methods: {
    login () {
      auth.loginSubmit(this.user)
    },
}...
```

api/auth.js
```js
export default {
   loginSubmit(data) {
     this.$auth.login({...})
     ^- how i access $auth.login here? This it is undefined.
   }
}
```

**Comment by websanova** [comment]
Do you install the auth plugin or are you just trying to import?

On Jul 17, 2017 23:36, "Miguel Pinto" <notifications@github.com> wrote:

@websanova <https://github.com/websanova> For now, I need to import the Vue
instance into my store. For example, I import and set VueLodash
<https://github.com/Ewocker/vue-lodash> in main.js, but in the store I can
not access it by 'this._.random(20) ', but if I declare the Vue instance I
access the lodash methods by 'Vue._.random (20) '. I try to use 'Vue.$Auth
', but is undefined. Is Vue-auth incompatible with vuex?

Another question, if you want to call the '$auth' methods in a separate
file, how do you access the methods? Thus, for example:

LoginForm.vue

...import auth from '../api/auth'...
methods: {
    login () {
      auth.loginSubmit(this.user)
    },
}...

api/auth.js

export default {
   loginSubmit(data) {
     this.$auth.login({...})
     ^- how i access $auth.login here? This it is undefined.
   }
}

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/132#issuecomment-315775454>,
or mute the thread

**Comment by miguelpinto98** [comment]
yes, of course. I used the plugin without any problems while I was not using vuex. But since I moved to store vuex I found the described problems.

**Comment by websanova** [comment]
Right, but I can see a few potential issues with your code.

For the loginSubmit, it has the proper context? If you console.log? I think
you would need to pass it in using either call or apply.

Also for the vuex, you show $Auth with a capital. Again when you
console.log(this) do you see proper context?

**Comment by websanova** [comment]
Also, $auth is the instanced version anyway, you can take a look at
Vue.auth but it's not really meant to work that way.

It's not a library like lodash, it's a plugin requiring proper vue instance.

**Comment by greenbackrus** [comment]
Hi
I faced same issue and used this._vm inside of my vuex module.

**Comment by Malieh** [comment]
console.log(this) in vuex returns an object with state and getters

**Comment by Malieh** [comment]
[{"_custom":1},{"type":2,"display":3,"value":4,"fields":8},"store","Store",{"state":5,"getters":7},{"saved":6},{"a":0},{},{"abstract":9},true]

**Comment by toudidel** [comment]
I have the same problem: how to reference to auth from store.
What's the conclusion? Is it possible or not?

**Comment by vinnygambiny** [comment]
Any news with this ?

**Comment by phirab** [comment]
I access $auth object inside my vuex store module like this:
`this._vm.$auth`

To setup my authentication I used this tutorial
https://medium.com/@ripoche.b/create-a-spa-with-role-based-authentication-with-laravel-and-vue-js-ac4b260b882f

**Comment by Zyberg** [comment]
Had this same question and found a much better solution than hacking through vue's vm (thanks to SO: https://stackoverflow.com/a/55118053 )

Simply use `Vue.auth` to access what otherwise would be in `this.$auth`
