### ISSUE TITLE
Update user data; different methods GET/PUT

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [websanova/vue-auth#133]
Hi!

Is it somehow possible to use different methods for getting and setting user data?
fetchUser() gets the user data from the server.
fetchUser({name: 'abc'}) sets user data (and gets it too).
I set fetchData to
```
fetchData: {
    method: 'PUT'
}
```
But this gets used in both cases (get/set). So i'm using the same method for setting and getting.
Is it possible to change the used method based on whether params are set for fetchUser or not?

Thanks in advance!

**Comment by websanova** [comment]
not really sure what you're trying to accomplish, but you can also try
using `$auth.user(<user>)` directly.

**Comment by hurradieweltgehtunter** [comment]
Basically I want to get and set user values via fetchUser over my API.

Idea behind is, that when i'm sending new user data via `fetchUser(userObject)` my API returns a user object which then gets nicely parsed and becomes accessible by `$auth.user.<something>`
To this point it's working.

But I want to differ between a GET request to only receive user data (`fetchUser()` without params) and a PUT request, to save user data in the backend (`fetchUser({name: 'xyz'})`)

So the question is, if the `fetchUser(params)` method can switch between GET and PUT based on whether `params` is set or not

The reason why I need the user object my API returns is, that the backend calculates a true/false value which cannot be set by frontend. So I can't rely only on the data the user entered in the frontend.

**Comment by websanova** [comment]
Yea, so in this case just use $auth.user()

With Vue resource:

this.$http.put(data).then((res) => {
this.$auth.user(res.data.newuserdtata); }

**Comment by hurradieweltgehtunter** [comment]
Works like a charm. Thank you!

**Comment by augnustin** [comment]
For the records, now, this would be `this.$auth.setUser(newuserdtata);`

**Comment by augnustin** [comment]
My bad, I got confused with the nuxt-auth library. Sorry for the disturbance.
