### ISSUE TITLE
Potential issue with Axios?

### ISSUE THREAD

**Issue by T-Bod** [websanova/vue-auth#134]
I'm successfully getting the token on login and after the login redirect successfully perform a get request however if I refresh the page or navigate to any other page and then try making a request the token is no longer included in the header, am I forgetting something?

**Comment by websanova** [comment]
Actually, seems many people are reporting issues with axios, I had a lot of
trouble with it myself and the interceptors not firing.

**Comment by websanova** [comment]
Should be fixed in `2.11.1-beta`.
