### ISSUE TITLE
Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by xazinji** [websanova/vue-auth#137]
Hi,

I've started using this plugin in combination with laravel, axios and such. But for some reason even after setting everything up perfectly fine.. I end up with the following errors.

`Uncaught (in promise) TypeError: Cannot read property 'register' of undefined`
`Uncaught (in promise) TypeError: Cannot read property 'login' of undefined`

Looks like for some reason $auth isn't defined, but no idea why.

Any clue? Thanks!

**Comment by websanova** [comment]
Where are you calling it? Maybe this.$auth?

**Comment by xazinji** [comment]
Yes, I'm using the methods described in the wiki. Such as this.$auth.login.

The way I'm importing is also mostly as described.
`Vue.use(VueRouter, VueAxios, axios, VueAuth, {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
})`

**Comment by websanova** [comment]
maybe just try setting up separate Vue.use ??

**Comment by xazinji** [comment]
After placing `Vue.router = router` in my file and seperating the Vue.use calls, it worked like a charm.

Thanks for the help and the work!
