### ISSUE TITLE
Login - redirect

### ISSUE THREAD

**Issue by DefunctExodus** [websanova/vue-auth#141]
I have been having issues today getting this to work with a redirect after login, It seems to only work with `fetchUser` set to true.

Without this enable it appears to bypass the redirect option based on the code located [Here](https://github.com/websanova/vue-auth/blob/master/src/auth.js#L227-L245
)
Is this the intended functionality?

**Comment by websanova** [comment]
Yep, you're right, fixed in `v2.9.3-beta`. thx :-)
