### ISSUE TITLE
this.$auth.token() returns [object Object]

### ISSUE THREAD

**Issue by Kuchiriel** [websanova/vue-auth#142]
I am using vue-admin which uses vue-auth and I can't get the current token. :/

I think this is related to my hapijs server.

`return reply({'status': 'success'})
      .header('Authorization', 'Bearer ' + token)`

I don't think this is the expected header format.

**Comment by pwnz22** [comment]
I'm also using vue-admin. In response i have this: `return (res.data.meta || {}).token`

**Comment by websanova** [comment]
You mean getting the token from the response?

If it's not in the response at all, then I'm not sure this is really an issue for `vue-auth`.

**Comment by Kuchiriel** [comment]
Yes I mean the reply coming from the back-end server, this code is from reply statement of hapijs framework. `return reply({'status': 'success'}) .header('Authorization', 'Bearer ' + token)`

I actually receive the reply in the header, but somehow, vue-auth don't recognize. :/

**Comment by websanova** [comment]
You can see the token in dev console?

**Comment by Kuchiriel** [comment]
No, **this.$auth** returns:
`Auth {currentToken: null, options: Object, watch: Vue$2, login: function, fetch: function…}`

And **this.$auth.token()** returns:
`[object Object]` 

And I am unable to strinfigy.

**Comment by websanova** [comment]
I mean can you see the token in the response header of the request?

**Comment by Kuchiriel** [comment]
![image](https://cloud.githubusercontent.com/assets/4648891/25263495/80cba244-2636-11e7-9e1d-647aed3fab27.png)

**Comment by websanova** [comment]
What version vue-auth are you using?

**Comment by websanova** [comment]
I just tested this in the demo,`$auth.token()` it's definitely returning me
a string. Not sure what you could be doing here to get an object instead of
that string.

**Comment by Kuchiriel** [comment]
I am using vue-admin which uses vue-atuh 2.8.2-beta.

**Comment by websanova** [comment]
I see, should be ok, maybe vue-admin is doing something with the token, who
knows... What about if you just fetch it directly

`localStorage.getItem('default-auth-token')`

**Comment by Kuchiriel** [comment]
I think I know the problem, I am with the "[object Object]" curse. ;-;

![image](https://cloud.githubusercontent.com/assets/4648891/25276165/33d8dfc2-266f-11e7-97d7-e02336fa76f7.png)

I will report this in vue-admin repository, might be a problem with their implementation of vue-auth.

**Comment by websanova** [comment]
Ya seems bit strange, good to check there.

**Comment by Kuchiriel** [comment]
Hi @websanova , first of all, thanks for your help. I've discovered the problem, vue-admin don't receive tokens in the request header, instead, it receives from the body of the request. I was trying to send in the header.
