### ISSUE TITLE
[FEATURE REQUEST] refresh user's data beforeEach routes

### ISSUE THREAD

**Issue by darkylmnx** [websanova/vue-auth#143]
i was wodering if you could add the refresh of the user object when the visitor changes route and is authenticated, the use case is simple, most website want the user info to be up to date from one page to another unless you expect keeping user sync at many other parts of the app.

For a long time i thought refreshData was it, but i then realized refreshData is for the refresh token only.

Anyway what do you think about the general use case ? I could give you a more specific use case if needed.

**Comment by websanova** [comment]
I'm not really sure what you mean?

You have a single page app or it's static website?

**Comment by darkylmnx** [comment]
i have an SPA. This is what i mean below : 

```
this.$router.beforeEach((to, from, next) => {
        this.axios
          .get('me')
          .then(response => {
            var user = response.data

            this.$auth.user(user)
            next()
          })
```
currently this is my workaround, because when a i go from page A to page B, and let's say a specific action updated the user on the server side, i woun't be aware if i don't refresh the user's data from page to page.

**Comment by websanova** [comment]
vue auth already does this on refresh automatically, so not sure what you
got going on in there.

Did you disable fetchUser?

Also maybe try updating to latest

**Comment by darkylmnx** [comment]
well, i didn't disable it, and i'm with the latest version, but it doesn't refresh when i change page (or route if you prefer)

**Comment by darkylmnx** [comment]
**fetchUser** seems to only load the user on app start and after login, but it's doesn't refresh the user during navigation.

**Comment by websanova** [comment]
why do you want to refresh after navigation?

**Comment by darkylmnx** [comment]
sorry, what i meant by after navigation was

- app starts - user is got from the server
- i go to page A - user is still the old data
- i go to page B - user is still the old data
- i go to page c - user is still the old data... and so on

Why do i want user to be refresh from one route to another ? Well because that's how to be have a synced info from the server for the current user if not, you end up having outdated info about your current user on the client.

User case : 
- my user logs in
- he hase a number of people thank can fav him, so the fav counter is on the user object 
- as he navigates let's say somebody favs him (so on another client right ?)
- lets say this fav counter was in the header, which is a fixed bar
- well do you see where i'm heading ? If the user object / data is not updated from page to page he'll never be sync with the server info, thus, my user would never see his fav counter going up as he navigates
- this would be the same thing for a money counter or a level or notification count or any of those info that you see often through nav

**Comment by darkylmnx** [comment]
![image](https://cloud.githubusercontent.com/assets/1426357/25160873/f2942e3e-24b8-11e7-8a0e-4ca1ad8ec690.png)
basic example here,

**Comment by websanova** [comment]
ok.

So your can easily do this with `$auth.user(newuserdata)`

```
this.$http.get('users/' + $auth.user().id).then((res) => {
this.$auth.user(res.data.newuserdata);  });
```

But seems you are basically just long polling here. Probably better to keep
this in your root component and do it on an interval :-)

```
created() {
    var _this = this;

    setInterval(() => {
        _this.$http.get('users/' + _this.$auth.user().id).then((res) => {
_this.$auth.user(res.data.newuserdata);  });
    }, 30 * 1000);
}
```

**Comment by websanova** [comment]
Just remembered there is also already a shorthand for this. You can just call `$auth.fetch();`

```
created() {
    var _this = this;

    setInterval(() => { _this.$auth.fetch(); }, 30 * 1000);
}
```

**Comment by mutumarieru** [comment]
Thanks for the `$auth.fetch();` it will avoid some code repetition, but i assume if you closed the issue, you don't find the use case interesting enough to add this is a basic feature that can be enabled or disabled ?

**Comment by websanova** [comment]
I don't think so, it's not really an "auth" feature, it's more an app
feature. Also it seems like too many ways to implement, on a timer or route
change, or socket connection. Doesn't make much sense to add this I think.
