### ISSUE TITLE
Route On reload

### ISSUE THREAD

**Issue by DefunctExodus** [websanova/vue-auth#144]
I am using the latest version and I am running into issues, Perhaps I am missing something but everything seems to function until i reload the browser at which time nothing will render from the router (Login or Home) in this example. But i see my valid token sitting in local storage.

I am using a bare bones setup [Webpack Template](https://github.com/vuejs-templates/webpack)

Thanks

**Comment by DefunctExodus** [comment]
It seems like this [Function](https://github.com/websanova/vue-auth/blob/master/drivers/router/vue-router.2.x.js#L29-L58) is not being called after a browser reload

**Comment by websanova** [comment]
Are you using axios?

**Comment by DefunctExodus** [comment]
Nope, I have tried to keep it as simple as possible.

Even without refresh enabled it still won't render the actual route even ones that don't require authentication

**Comment by DefunctExodus** [comment]
It `appears` that this [segment](https://github.com/websanova/vue-auth/blob/master/drivers/router/vue-router.2.x.js#L29-L58) of is not called after a page reload

**Comment by websanova** [comment]
what version of vue, , vue-auth etc, are you using?

**Comment by DefunctExodus** [comment]
```
@websanova/vue-auth@^2.10.0-beta:
  version "2.10.0-beta"
vue-router@^2.0.0:
  version "2.4.0"
vue-resource@^1.3.1:
  version "1.3.1"
vue@^2.1.10, vue@^2.2.6:
  version "2.2.6"
vuex@^2.3.1:
  version "2.3.1"
vuex-router-sync@^4.1.2:
  version "4.1.2"
```

Thanks for the help. I have started from scratch a few times just to make sure it's not something strange but it's the same result.

**Comment by websanova** [comment]
hmm, seems strange, maybe related to vuex-router-sync, can you make a test
without it?

**Comment by DefunctExodus** [comment]
I had actually just tried that after i pasted that list thinking the same thing.

**Comment by DefunctExodus** [comment]
Okay so I have it working,

If i set
```
fetchData: { url: 'someurl', method: 'GET', enabled: true },
```
to `enabled: false`  it will fail to load the route

**Comment by websanova** [comment]
It should be true by default

**Comment by DefunctExodus** [comment]
Right but i don't want it to make a call for user data.

So if it fails to load a route(on reload)  when diabled should it actually
be an option?

**Comment by websanova** [comment]
did you set it globally or on login?

**Comment by DefunctExodus** [comment]
Set globally.

**Comment by websanova** [comment]
I don't really understand what you're trying to do.

**Comment by DefunctExodus** [comment]
Not at my computer currently. But essentially I don't want to try and fetch
user data unless in explicaltly call for it by another method.

Disabling `fetchdata`  is the only way Ihave found to turn it off.

Since it's a global option I am not sure why disabling it would prevent any
routes from rendering only after a full page reload

**Comment by websanova** [comment]
Ok, I think I found the issue. I've just pushed a fix to `v2.10.1-beta`.

Note that setting `fetchData: {enabled: false}` will disable it globally. But you will also need to set `loginData: {fetchUser: false}` either in the options or during `$auth.login` call.

Please let me know if that works for you.

**Comment by DefunctExodus** [comment]
Sorry for the late response.

It works as expected now, Thanks for helping me out with this issue.

**Comment by websanova** [comment]
Glad to hear, thx for reporting :-)
