### ISSUE TITLE
Where is the app being redirected to when {auth: false} ?

### ISSUE THREAD

**Issue by xxRockOnxx** [websanova/vue-auth#145]
I am currently being redirected to `/404`. Is it possible to set where to go to instead?

I have `{ auth: false }` on my login route. After logging in, I tried going back but I get 404 instead.

**Comment by websanova** [comment]
you can set authRedirect option, check the docs.

Also you can just remove auth from there and do a $auth.check() in the
mounted/ready method, lots of options.

**Comment by xxRockOnxx** [comment]
`authRedirect` ? Isn't that used if you are not authenticated yet? That's how I currently use it. That's the location where I am being redirected if I need to authenticate.

What I am asking is, if for example I am already authenticated, and I went back to login form which has `auth: false` on meta, I am being redirected to `/404`

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth#notfoundredirect-path-404
