### ISSUE TITLE
Privileges API response

### ISSUE THREAD

**Issue by brunokunace** [websanova/vue-auth#146]
Hello, I did not find any forum or wiki for questions, so I opened the issue.

I'm wondering what is the default response I have to create in my Privilege Control API, such as admin, users, etc.

At the moment now I only have the token for authentication and it is working fine:
{'authorization': 'beaver 566789.....'}

Thanks for all.

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth/blob/master/README.md#privileges

**Comment by brunokunace** [comment]
Ok, i see this.

For example:

     path: '/private',
        meta: {auth: [{"people": "administrator", "people": "superadmin"}]},
        component: require('./Account')
    }, 

I need api response like:

{
      'authorization':'beaver 124...',
      'people': 'admin'
}

?

How vue-auth take the information from my api response?

Thanks!

**Comment by brunokunace** [comment]
*fix

'people' : 'administrator'

**Comment by websanova** [comment]
It will check whatever you send back for your user in the "role" parameter.
It's in the docs.

**Comment by brunokunace** [comment]
Thanks for the instantly response, i will make test for rolesVar.
I think, it need on the docs a example for api response defaults, for peoples create the api exactly thw vue-auth needs.

Thanks again for the awesome plugin.
