### ISSUE TITLE
Response interceptor not being called (axios)

### ISSUE THREAD

**Issue by Fuhrmann** [websanova/vue-auth#149]
The response interceptor is not being called when using axios after the "refresh" request returns a 401.

When the "refresh" request return a 401 error, meaning the token is invalid, the app doesnt redirect to the login page.

I've tried to debug the call to the interceptor (_responseIntercept function), but it never gets called. Using axios 0.16.1 and vue-axios 2.0.2.

But after checking out the issues on axios, the problem is that:

`If the response isn't successful then the second parameter of axios.interceptors.response.use is used`. (https://github.com/mzabriskie/axios/issues/721#issuecomment-281772931) But vue-auth is only using the first parameter. meaning that the response interceptor will only be called if the "refresh" request returns a request that is successful:

This is the code from the axios.1.x.js auth driver from vue-auth package:
`
this.options.Vue.axios.interceptors.response.use(function (response) {
    res.call(_this, response);
    return response;
})
`

**Comment by websanova** [comment]
Would need pull request for this, I'm not really using axios.

I can see the example here for interceptors: https://github.com/mzabriskie/axios#interceptors

But not sure what's in that `error` object or if it needs to return a `Promise`?

**Comment by websanova** [comment]
This should be fixed in `2.11.1-beta`.
