### ISSUE TITLE
Safari Private Browsing

### ISSUE THREAD

**Issue by jgerbes** [websanova/vue-auth#151]
When attempting `$auth.login()` in Safari while using private browsing, the following error occurs:
`QuotaExceededError (DOM Exception 22): The quota has been exceeded.`

This error does not occur when using private browsing in other browsers.

**Comment by websanova** [comment]
http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

The tokens are stored in local storage.

Maybe I'll have to switch to cookies instead. I'm already using cookies for
the remember me anyway.

I dont think I will have time to get to this until Monday though.

**Comment by jgerbes** [comment]
https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

Cookies would fix the compatibility issue, but they come with two drawbacks:
- Size limited to 4kb (unlikely to be a problem unless the JWT has many claims)
- Vulnerable to CSRF/XSRF attacks

I think cookies are the way to go forward. What are your thoughts?

**Comment by websanova** [comment]
Well, putting in support for the cookies is easy enough, and it can just be made as option.

The size, not such a big issue unless they decide to stuff a lot of data in the token.

The bigger issue is the CSRF. There are too many potential set-ups to consider so probably needs to be handled separately. It would depend on what kind of app it is, SPA, static, mixed. Multiple tokens, single tokens. If they are using Origin/Referer header which then also has browser support issue. Also SSR could have some effects.

Probably in the "generic" SPA setup with XSRF token, it would be easy enough to write an interceptor. But this requires some leg work on the back-end as well.

I think... For full support, and for best security ad browser support it's cookies with XSRF token. I'm tempted to add support for XSRF, but I feel that should be a separate plugin altogether.

**Comment by jgerbes** [comment]
How about using localstorage by default, with cookies as a fallback?

You could use a function like this to determine if localstorage is accessible:
```
isLocalStorageSupported() {
  try {
    if (!window.localStorage || !window.sessionStorage) throw "exception";
    localStorage.setItem('storage_test', 1);
    localStorage.removeItem('storage_test');
    return true;
  } catch (error) {
    return false;
  }
}
```
If accessible, store token in localstorage. Otherwise, store token in a cookie.

The `token()` methods would need to check both locations for a token (unless you can think of a better way to handle this).

What are your thoughts?

**Comment by websanova** [comment]
I guess there is also option of just using a dud cookie. With some key we
hope would not be used on any back-end. It will send the token with each
request (API) but I suppose if it's not being used it will not create any
security issues. Just a small bit of overhead in few situations I suppose.

Do we need to delete the dud cookie if the local storage check passes? I
guess private mode will already did this.

**Comment by jgerbes** [comment]
Not too sure what you mean by dud cookie. Would you mind explaining?

My thought were that local storage would be the primary location for storing the token. Only in the event that the local storage test fails would a cookie be created to store the token.

This makes the cookie storage method a backup solution only, minimising the CSRF risk to cases where local storage is not available (typically only when some browsers are in private mode).

**Comment by websanova** [comment]
Well, the idea is to store the token in the cookie but not actually use it
on the server. It would strictly be for local storage.

It would still send the cookie on request depending on the setup, but it
would not be recognized by there server.

This would avoid any csrf issues (I think) since we are still using
JavaScript to set and fetch the cookie value and use it in the
"authorization" header.

Thing is if we have a single page app at "www.example.com" and an API at "
api.example.com". It would be fine since we could set the cookie for www.
So we would see the dud cookie being sent on refresh. But on apps that are
using a single domain it would be there for all requests.

**Comment by websanova** [comment]
Okay, I've added an update for this, should just work automagically. Let me know how it works out `v2.11.0-beta`.

**Comment by jgerbes** [comment]
It works beautifully :)

**Comment by websanova** [comment]
awesome :-)
