### ISSUE TITLE
i not find token res.body.token

### ISSUE THREAD

**Issue by xzees** [websanova/vue-auth#153]
Login.vue

> <script>
export default {
  name: 'Login',
  data () {
    return {
      data: {
        body: {
          email: '',
          password: ''
        },
        rememberMe: false,
        fetchUser: false
      },
      error: null
    }
  },
  mounted () {
    console.log(localStorage)
  },
  methods: {
    login () {
      this.$auth.login({
        params: this.data.body,
        rememberMe: true,
        fetchUser: false,
        redirect: '/dashboard',
        success (res) {
          console.log(res.body.token)
        },
        error () {
          this.error = true
        }
      })
    }
  }
}
</script>

**Comment by websanova** [comment]
That would be issue with server maybe. Also not sure but I guess it should be `res.data`?
