### ISSUE TITLE
Emit "authentication status changed" event

### ISSUE THREAD

**Issue by crossRT** [websanova/vue-auth#16]
Hi websanova,
Thanks for creating this awesome plugin for vue.js community! It's really helpful!
I have a simple suggestion, will you consider to emit a "authentication status changed" event?
So that we can know the authentication status was changed and perform different logic without refreshing the page.
Please correct me if I'm on the wrong way to design my app, I'm still new to vue.js.
Sincerely appreciate your effort, thank you!

**Comment by websanova** [comment]
I'm not sure what you mean by changing authentication. Like a logout /
login or logging in as other user?

**Comment by crossRT** [comment]
I mean authentication status changing. 
This idea is from [AngularFire](https://github.com/firebase/angularfire/blob/master/docs/reference.md#onauthstatechangedcallback-context) and not sure whether it's suitable for vuejs or not.
Every time we loaded the page, `authenticated` will remain false until `check()` fired to the server.
Existing `ready()` function only fire once, but I have some components depend on the authentication, it should become disabled without refreshing the page when user log out.

**Comment by websanova** [comment]
I'm a bit confused about what you mean.

$auth.check and ready are already implemented.

Do you have some code?

**Comment by websanova** [comment]
Not really sure what you mean here but the new v1.0.x-dev version has some sample code.
