### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by brunokunace** [websanova/vue-auth#160]
Hi, again...

my app.js

```
Vue.use(VueAxios, axios)
Vue.use(VueAuth, {
  auth: {
    request: function (req, token) {
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    },
    response: function (res) {
      var token = res.data.access_token

      if (token) {
        token = token.split('Bearer ')
        return token[token.length > 1 ? 1 : 0]
      }
    }
  },
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: { url: 'http://localhost:8091/api/token.php' },
  refreshData: { enabled: false },
  fetchData: { url: 'http://localhost:8091/login/me.php' },
  rolesVar: 'role'

})
```
my login data works fine, i receive token and still works.

but fetchData send a get from my endpoint and get the error on console log

`XMLHttpRequest cannot load http://localhost:8091/login/me.php. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

How to set header on fetchData?

thanks!

**Comment by websanova** [comment]
That's from your server.
