### ISSUE TITLE
$auth.fetch() works only on button click

### ISSUE THREAD

**Issue by limatheus** [websanova/vue-auth#164]
Hi!

Im trying fetch the user again when he is already logged and the page is open, so I put this on my mounted() hook,

```(javascript)
mounted(){
    this.$auth.fetch()
}
```
And don't works...

Just for test I put it on a button click and works, the user is successful fetched

```(html)
<button @click="$auth.fetch()"> Test</button>
```
What i'm missing? can you help me?

**Comment by websanova** [comment]
Are you using $auth.ready at all?

**Comment by limatheus** [comment]
Hi @websanova

Yes, I'm using ``` $auth.ready ``` on login form, and for test I put it on mounted() too.

Like this:

```(javascript)
mounted(){
     if(this.$auth.ready()){
        this.$auth.fetch()
     }
 }
```

But don't  works

**Comment by websanova** [comment]
It's not gonna work like this. You need to set it on a component, there are
some examples in the docs.

**Comment by websanova** [comment]
You have to realize that $auth.ready() just returns a binded variable. So you can do something like:

```
data() {
    ready: this.$auth.ready()
}
```

And then just watch this variable for changes. But my primary way is to have the main app vue just have a simple wrapper into the site with a wrapper.

```
<div>
    <div v-if="$auth.ready()">
           <router-view></router-view>
    </div>

    <div v-if="!$auth.ready()">
        Loading...
    </div>
</div>
```
