### ISSUE TITLE
refresh doesn't call _invalidToken when getting 401 or 400 error.

### ISSUE THREAD

**Issue by ultraN** [websanova/vue-auth#169]
I'm using default Axios driver, getting 

> .Uncaught (in promise) Error: Request failed with status code 401
    at createError (eval at <anonymous> (app.js:1071), <anonymous>:15:15)
    at settle (eval at <anonymous> (app.js:1301), <anonymous>:18:12)
    at XMLHttpRequest.handleLoad (eval at <anonymous> (app.js:1050), <anonymous>:77:7)

 I've read through issues that people have, author said this problem is resolved in latest, which is 2.11.1-beta. But I still get this error when my api server return 401 and 400 (I know this needs override driver), and I tried to print hello when _invalidToken is called, however nothing is printed.

I can catch and display the error in _interceptor if(res) block, but this response is not forwarded to _invalidToken function.

I found _responseIntercept function in auth.js is not called when I refresh the page, which means for some reason the _invalidToken function is not called at first priority so causes unhandled 401 error.

FYI: My server response is {error: 'Token expired'} with code 401, I think this is standard reply.

**Comment by ultraN** [comment]
`    function _routerBeforeEach(cb) {
        var _this = this;

        if (this.watch.authenticated && !__token.get.call(this)) {
            this.options.logoutProcess.call(this, null, {});
        }

        if (this.options.refreshData.enabled && this.options.tokenExpired.call(this)) {
          console.log('hello')
            this.options.refreshPerform.call(this, {
                success: function () {
                    this.options.checkAuthenticated.call(_this, cb);
                }
            });

            return;
        }

        _checkAuthenticated.call(this, cb);
    }`
This tokenExpired function is not handling errors, that's why the 401 error is uncaught. Any solution?

**Comment by ultraN** [comment]
After test between Axios driver and Vue-resource driver, I found out _invalidToken() function is called when using vue-resource driver, but not in Axios driver. This is the reason why app doesn't logout user when token is invalid or expired.

**Comment by websanova** [comment]
Seems fine for me (axios and vue-router).

Maybe need to update some of your other modules?

~~~
    "@websanova/vue-auth": "2.11.1-beta",
    "axios": "^0.16.1",
    "vue-axios": "^2.0.2"
~~~

**Comment by silver8ack** [comment]
I'm still having this same problem after upgrading.  Originally posted in #155

**Comment by websanova** [comment]
I just tested this yesterday, maybe make sure you update axios and related
packages as well. You can check the 2.x.demo package.json file.

**Comment by websanova** [comment]
Sry, didn't realize that was same thread..

**Comment by websanova** [comment]
Have you tested the demo? Or can you provide isolated for of the issue in the demo?

**Comment by ultraN** [comment]
I tried use your 2.x demo before. By uncomment thise axios related stuff, but not working.
I think the best solution for now is use vue resource. It's pretty much the same as axios.
