### ISSUE TITLE
No data available in ParseUserData(data)

### ISSUE THREAD

**Issue by tavakyan** [websanova/vue-auth#170]
Hello,

I have authentication and login working and I'm able to see my user session data (with the roles and everything) come in as a response.  I need to extract the roles to hide some user-interface features so I'm looking for the easiest way to get user data by calling something like 

`this.$auth.user()`

However, whenever I override the ParseUserData function it doesn't show the user session data.  

This is the code I currently have:

`
parseUserData: function (data) {
    console.log(data)
    return data.user || {}
  },
`

It just outputs an empty object.  Yet my response looks like:

`
{"token":"eyJhbGciOiJIUzI1NiIasnR5cCI6IkpXVCJ9.eyJpfI6IjU5MWExZGM3OGI2ZDIxNzBmOGQ5YjBiMCIsImlhdCI6MTQ5NjIwMzczMX0.rGXeUILz9-lkW0eZe4FH5Wo6_tBT_xlqU5JDV2qfQTI","user":{"id":"591a1dc78b6f2170f8d9b0b0","name":"testaccount","picture":"https://gravatar.com/avatar/c2494964ec54d3df340fz4b9cd3d2735?d=identicon","role":"admin","email":"testaccount@example.com","createdAt":"2017-05-15T21:29:43.985Z"}}
`

I'm using the latest beta version of vue-auth and I'm not sure what's going on.

**Comment by websanova** [comment]
Works fine for me, will need to see a fiddle.

~~~
Vue.use(require('@websanova/vue-auth')), {
    ...
    parseUserData: function (data) {
        console.log('test');

        return data;
    }
});
~~~

**Comment by websanova** [comment]
No response, so assuming resolved or non issue.
