### ISSUE TITLE
The login method saves automatically the token?

### ISSUE THREAD

**Issue by ecuation** [websanova/vue-auth#174]
HI,

I'm trying to implement this plugin to my project, at the moment I have some doubts... I use the login method like in the documentation, but the fetch_user action, does not send any Bearer authorization header. Do I have to set it manually? Do I have to save in localStorage with an specific name?

Thanks in advance.

**Comment by websanova** [comment]
It should be setting automatically. Did you check with using the auth.ready?

**Comment by ecuation** [comment]
Thanks @websanova  for your quick answer,
 
I set an if my login fragment

`if(this.$auth.ready())
                {
                    this.$auth.login({
                        body: {
                            client_id: 2,
                            client_secret: 'gDTj4hNO1ihNQOTtL3qITpRmCZXtpyWqomlP5q6S',
    //                        username: self.credentials.username,
    //                        password: self.credentials.password,
                            username: 'admin@test.com',
                            password: 'secret',
                            grant_type: 'password'
                        },
                        success: function (response) {
                            console.log(response.body.access_token);
                            //console.log(this.check());
                            //localStorage.setItem('auth_token', response.body.access_token);

                        },
                        error: function () {
                            console.log('test');
                            //console.log(this.check());
                        },
                        rememberMe: true,
                        redirect: '/user/dashboard',
                        fetchUser: true,
                    });
                }`

Is probably bacause I am using Laravel 5.4 passport package?? This is what Laravel response in the oauth request: 

<img width="2559" alt="screen shot 2017-06-08 at 17 07 03" src="https://user-images.githubusercontent.com/6634376/26935722-fd25a068-4c6c-11e7-8d81-59cdbe8c3f00.png">

Do I have to make extra configurations maybe?


Thanks again @websanova!

**Comment by ecuation** [comment]
I just checking that the Laravel passport response does not send the data in the headers.

<img width="2558" alt="screen shot 2017-06-08 at 17 50 13" src="https://user-images.githubusercontent.com/6634376/26937946-1884018c-4c73-11e7-82d3-7ce226dbf225.png">


There is any way to get from the body?

Thanks again!

**Comment by websanova** [comment]
Seems you need to setup your driver's

**Comment by ecuation** [comment]
Thanks, I set up my own auth driver and now all the things works.

**Comment by sargilla** [comment]
i have the same problem, where i must set up the driver in passport or in webnova??
