### ISSUE TITLE
issue with meta auth

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#176]
I am using the following version

```
 "@websanova/vue-auth": "^2.11.0-beta",
```

Lets say you have the following route
```
{path: '/usr/login',name: 'login', meta: {auth: false}, component: (resolve) => { require(['../components/views/users/login.vue'], resolve)}},
 ```
If I try to access this page when a token exits it will redirect to a 404.  If I remove 

```
meta: {auth: false}
```
It will redirect to that page.  

Not sure if this a issue.  So i am not sure if its a bug.

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth#routes

Yes, so what's the question or issue here?

**Comment by kyoukhana** [comment]
The issue is why does it redirect to 404 when that page doesn't require authentication.

**Comment by websanova** [comment]
Did you read the docs I just sent?

false does not mean not requiring authentication, what you're looking for
is "undefined".

**Comment by kyoukhana** [comment]
Thanks for the help
