### ISSUE TITLE
code obtained in step 1 is not POSTed to API server in OAuth2 flow

### ISSUE THREAD

**Issue by chrzrdx** [websanova/vue-auth#177]
Using `vue 2.3.4`, and axios `0.16`

auth is configured as such:

```
// Vue Auth
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  facebookData: {url: 'http://localhost:8274/api/v1/auth/facebook/', method: 'POST', redirect: '/'},
  facebookOauth2Data: {
    redirect: function () { return this.options.getUrl() + '/auth/login/callback/facebook' },
    clientId: 'CLIENT_ID',
    scope: 'public_profile,email,user_friends'
  }
})
```

After making a call to FB in step 1, I get a callback on `/auth/login/callback/google` on the client side with the query parameter `code` set to whatever FB decides to reply with.

Next, I check if code has been set and call the oauth2 convenience method again, with code param set to true:

```
    if (this.$route.query.code) {
      this.$auth.oauth2({
        code: true,
        provider: this.$route.params.type,
        params: {
          code: this.$route.query.code
        }
      })
    }
```

However, even though I had configured my `facebookData` parameter to use POST, the library calls the url set there with the query parameter `code` with an empty body, like this:

```
http://localhost:8274/api/v1/auth/google/?code=GOOGLE_CODE
```

Shouldn't it call the URL with `x-www-form-urlencoded` headers, and:
```
{ "code" : CODE_HERE }
```
in the body?

I guess I could write my own convenience method (as a replacement for the oauth2 method), but is this intended behaviour? Without changing the source files of the package, is there a way to modify this?

**Comment by chrzrdx** [comment]
On that note, if I make a POST request and get my user data and a token from my backend server, how do I manually log the user in using vue-auth?

I can set the user params by calling `this.$auth.user(response.data.users)`, but how do I set the token?

**Comment by LuigiMigliardi93** [comment]
I have the same issue

**Comment by websanova** [comment]
Try changing `params` to `data` if you are using axios.

**Comment by chrzrdx** [comment]
Thanks! That works. I'll configure the auth driver next as shown in the docs so as to set my user and the token correctly. I leave it up to you to close the issue @websanova

That being said, is there away to manually authenticate a user if some code and user data is already obtained via other methods (that don't involve making a request to the server)?

**Comment by websanova** [comment]
Well, the manual thing is what the drivers are for.

Using data instead of params is just a result of making a post request with
axios. Nothing to do with the auth plugin

**Comment by chrzrdx** [comment]
I apologise for reopening the issue. Wasn't sure if I needed to make a new issue for this. Here's where I'm stuck now:

On making the oauth2 request, this is what the API server returns in the response:

```
{ token: TOKEN, user: USER_OBJECT }
```

So, I changed my auth driver options as shown in the docs to this:

```
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  custom1Auth: {
    request: function (req, token) {
      req.headers.set('Authorization', token)
    },
    response: function (res) {
      return (res.data || {}).token
    }
  },
```
The first request made to my google oauth endpoint API returns fine with the object I mentioned above.

But in the immediate request made to `auth/user/`, the request headers are not set. Why would this be? How may I go about setting it?

Just to give you a context, this is the chain of requests:

- from client (/login)

  call the oauth2 method, pass the code in the data, 
  request returns with a response containing token and user details in body

  GET request made to API_SERVER/auth/user/ 
  returns with Authorization credentials missing, because header is not set.

**Comment by LuigiMigliardi93** [comment]
@websanova thanks! That works!

**Comment by websanova** [comment]
Ah, ok so I will need to update the docs. That is based on old model.

You just need to replace the auth part with your driver directly. 

```
  auth: {
    request: function (req, token) {
      req.headers.set('Authorization', token)
    },
    response: function (res) {
      return (res.data || {}).token
    }
  },
```

Instead if the bearer include there.

**Comment by chrzrdx** [comment]
That works. 

Now, I can check that I have a token with this.$auth.token(). But when I try to refresh it with:

```
      this.$auth.refresh({
        data: {
          token: this.$auth.token()
        }
      })
```

I get this error. Using axios 0.16, and vue2.

```
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at Auth._invalidToken (eval at <anonymous> (app.js:1623), <anonymous>:33:12)
    at Auth._responseIntercept (eval at <anonymous> (app.js:1635), <anonymous>:133:45)
    at eval (eval at <anonymous> (app.js:1623), <anonymous>:26:13)
    at <anonymous>
```

I need to POST  `{ "token" : TOKEN }` to `auth/token-refresh/`. This URL I've set in the refreshData parameter. 

```
  refreshData: {url: 'auth/token-refresh/', method: 'POST', enabled: false, interval: 30},
```

Why would the 'invalidToken' error be coming? The token is fresh. How can I debug it on my end better?

**Comment by websanova** [comment]
You shouldn't have to send the token. Just a refresh call on it's own
should suffice, the drivers are to handle everything else for standardized
set and fetch of your token with your server.

**Comment by chrzrdx** [comment]
Simply calling `this.$auth.refresh()` gives the same error. In the background, it's not making any calls to the server. It fails before that.

Probably an axios quirk. I'm going to try this in a new, clean project, with vue-resource and let you know.

For what it's worth, here's how my vue-auth is setup:

```
Vue.use(require('@websanova/vue-auth'), {
  auth: {
    request: function (req, token) {
      req.headers.set('Authorization', token)
    },
    response: function (res) {
      return (res.data || {}).token
    }
  },
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  tokenName: 'jwt_auth_token', // name of token in localstorage
  refreshData: {url: 'auth/token-refresh/', method: 'POST', enabled: false, interval: 30},
  authRedirect: {path: '/auth/login'},
  googleData: {url: 'auth/google/', method: 'POST', redirect: '/'},
  googleOauth2Data: {
    redirect: function () { return this.options.getUrl() + '/auth/login/callback/google' },
    clientId: IDHERE,
    scope: 'profile email'
  },
  parseUserData: function (data) {
    return data.user
  }
})
```

**Comment by websanova** [comment]
Hmm, why is refreshData.enabled set to false?

**Comment by chrzrdx** [comment]
The app doesn't load (same error). I guess the `refresh()` method is being called once on app load?

I kept it to false so that I can call `this.$auth.refresh()` manually (bound it to the click handler of a button).

**Comment by websanova** [comment]
Whats the error?

**Comment by chrzrdx** [comment]
Sorry, here it is:

```
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at Auth._invalidToken (eval at <anonymous> (app.js:1623), <anonymous>:33:12)
    at Auth._responseIntercept (eval at <anonymous> (app.js:1635), <anonymous>:133:45)
    at eval (eval at <anonymous> (app.js:1623), <anonymous>:26:13)
    at <anonymous>
```

**Comment by websanova** [comment]
Hmm, what version of Vue auth are you using also?

**Comment by chrzrdx** [comment]
`"@websanova/vue-auth": "^2.12.1-beta`

**Comment by chrzrdx** [comment]
Here's the error stack:
```
"TypeError: req.headers.set is not a function
    at Auth.request (webpack-internal:///151:30:19)
    at Auth._requestIntercept (webpack-internal:///182:123:39)
    at eval (webpack-internal:///185:13:13)
    at <anonymous>"
```

This is probably because I'm defining the auth driver as such:
```
  auth: {
    request: function (req, token) {
      req.headers.set('Authorization', token)
    },
    response: function (res) {
      return (res.data || {}).token
    }
```

**Comment by websanova** [comment]
Yes, would seem so.

**Comment by chrzrdx** [comment]
The headers are getting set now, so I'm closing the issue. This is how my auth driver looks now (vue:2.3.4, axios:0.16.2):

```
  auth: {
    request: function (req, token) {
      req.headers = {'Authorization': token}
    },
    response: function (res) {
      return (res.data || {}).token
    }
  },
```
