### ISSUE TITLE
vue-router.2.x.js : Vue.router must be set.

### ISSUE THREAD

**Issue by eybarta** [websanova/vue-auth#179]
Hi,

thanks for your work.

I'm trying to use your plugin with vue app connected to .NET webservice for authentication..

I was getting the error in the title when trying to Vue.use(...) as in your examples,
the error went away only if I did this:
`
var router = new VueRouter(routes);
Vue.router = router;
`

Is this how I'm supposed to do it? or am I missing something?

thx

**Comment by eybarta** [comment]
just noticed from your read me:

> NOTE: If you do not set your router as Vue.router = new VueRouter() then you will need to feed the router in directly through the options. Also true for http.

it was just under 1.x but relevant for 2.x also :)

**Comment by websanova** [comment]
Right, so try setting

var router = ....
Vue.router  = router

 after that line

**Comment by eybarta** [comment]
thx for your reply.

sorry for piggybacking on this issue but few questions if I may:

currently I'm initializing user and siging up user (looking in localStorage or calling login api) from Vuex action, with your plugin, where should I be doing this and how?
where do I have access to $auth?

thanks alot for your help.

**Comment by websanova** [comment]
this.$auth should always be available in any component.

Not sure what context gets loaded into vuex since I don't use it but I
would assume you could `.apply` or `.call` the context in.
