### ISSUE TITLE
$auth.login making the request using the OPTION method insted of POST

### ISSUE THREAD

**Issue by marcusos** [websanova/vue-auth#183]
I am trying to using the $auth.login() but they sent the request using OPTION instead of POST. What I am doing wrong?

My configs:
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'type',
  loginData: {url: 'user_token', method: 'POST', redirect: '/', fetchUser: false},
  fetchData: {url: 'auth/user', method: 'GET'},
  refreshData: {url: 'auth/refresh', method: 'GET', atInit: false}
})

**Comment by websanova** [comment]
uhh, that's your browser, not the plugin.

This standard for any CORS request. Just check it on Google :-)

**Comment by marcusos** [comment]
Thank you, I will check it out

**Comment by aislanmaia** [comment]
That's strange to me as well. I'm using a Phoenix (1.4) endpoint that requires my request to be a POST method to sign in. What happens is exactly this, the OPTION method is fired up and my server returns an `(Phoenix.Router.NoRouteError) no route found for OPTIONS /api/v1/sign_in (ApiWeb.Router)` message. 

I've done this before using Fetch and React frontend (and the same browser) manually and I can confirm my server is just ok. 
Through `POSTMAN` application my requests just work as well.
