### ISSUE TITLE
Request from external API overwriting auth token

### ISSUE THREAD

**Issue by chrzrdx** [websanova/vue-auth#187]
I'm communicating with an external API that sends a token in the response body like:
```
{
  "token" : TOKEN_HERE
}
```
similar to my jwt authentication backend endpoints.

How can I rewrite my auth response interceptor to only change the token when served from the auth backend?

This is what I have now:
```
  auth: {
    request: function (req, token) {
      this.options.http._setHeaders.call(this, req, {Authorization: 'JWT ' + token})
    },
    response: function (res) {
      return (res.data || {}).token
    }
  },
```

I suspect I need to put an if condition in the response function, but what can I check for? Should I set special headers from the authentication backend?

**Comment by websanova** [comment]
Not sure I understand, by default it will update it if it finds it in the
Authorization header of any response.

This is based on the driver you set, you can just look at the drivers here
and just write your own for whatever behaviour you need.

https://github.com/websanova/vue-auth/blob/master/drivers/auth/bearer.js

**Comment by chrzrdx** [comment]
I namespaced the external API, so now it sends tokens as: 
```
{
   "external_api_token" : TOKEN
}
```
instead of 
```
{
    "token" : TOKEN
}
```
so that the vue-auth axios intereceptor doesn't use that to overwrite the auth token.
