### ISSUE TITLE
Page refresh

### ISSUE THREAD

**Issue by alanrivetta** [websanova/vue-auth#188]
Hello!
I need to know how this default plugin should behave when refreshing page.

I log in $auth.login ({..}) correctly
I surf in my SPA
When upgrades appear the blocked routes (Not permissions, not loged), but localStorage.default_auth_token remains.
When I want to log in again, it causes error

If I perform localStorage.removeItem ('default_auth_token') and log me in again it does it correctly

In my main template use

        <div v-if="$auth.ready()">
            ready : {{$auth.ready()}}
            user : {{$auth.user()}}
            <router-view></router-view>
        </div>
        <div v-if="!$auth.ready()">
            Site loading...
        </div>

LOG:
ready : true user : {}

**Comment by websanova** [comment]
Do you have an end point for fetchUser?

**Comment by alanrivetta** [comment]
`                this.$auth.login({
                    redirect: '/',
                    data: jsonToFormEncoded({
                        '_username': 'testuser',
                        '_password': 'p@ssword'
                    }),
                    success: function (response) {
                        this.$auth.user(response.data.data)
                    },
                    error: function () {
                        console.log('noecho')
                    }
                });`

**Comment by websanova** [comment]
ah,

you don't need to set the response, the plugin will do that automatically.
Also when you refresh the app needs to re-fetch the user so you will need
to add an end point for that in your server.

**Comment by heisjoe** [comment]
hi @websanova 

when i refresh page, the console will output 
```
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at Auth._invalidToken (main.js:71889)
    at Auth._responseIntercept (main.js:69074)
    at main.js:71882
    at <anonymous>

Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at Auth._invalidToken (main.js:71889)
    at Auth._responseIntercept (main.js:69074)
    at main.js:71882
    at <anonymous>
```
and i clean my google brower **cookie cache and data**, it will work good;

but i refresh page again, it will appear again;

my vue-auth version is 2.12.1-beta

**Comment by websanova** [comment]
Need details man, how I can know where this is happening

**Comment by alanrivetta** [comment]
Sorry for the delay.


I have corrected the code with fetchUser,
But I can not get it working properly since I can not implement the refresh.

According to my backend, I need to send an additional parameter to /auth/refresh, which arrives at the login.
I would need to be able to do this:

Vue.use(VueAuth, {

    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    auth: {
        request: function (req, token) {
            req.headers.set('Authorization', 'Bearer ' + token);
        },
        response: function (res) {
            console.log(res.data)
            return (res.data.token || {});
        }
    },
    loginData: {url: '/api/login_check', method: 'POST', fetchUser: true},
    fetchData: {url: '/api/login_fetch', method: 'GET', enabled: true},
    refreshData: {url: '/api/login_refresh', method: 'POST', data: JsonToData({**token:refresh:this.user().refresh_token**}), enabled: true, interval: 30},
    authRedirect: {path: '/loginFE'},
    parseUserData(response){
        let data = response.data;
        data.refresh = response.refresh_token;
        console.log(data);
        return data;
    }
});

Do you need me to ask you a new question?

**Comment by websanova** [comment]
Ok, so you already have it setup right there....not sure what the issue
is...

```

auth: {
    request: function (req, token) {

        // You can also pass your token or whatever was stored here

        // ex: if (token) { token = token.split(':'); }


        req.headers.set('Authorization', 'Bearer ' + token);

                // Set any additional fields in the request from the token.


    },
    response: function (res) {

        if (/* conditions for token */) {

           // If there are more tokens/fields just set them

           return /* token */;

        }

    }
},

```

**Comment by martosoler** [comment]
Hi,

I'm having a similar issue, in my case when I refresh the page (having a valid token in a cookie) I want to set a Vuex store state with the information returned of the fetchUser.

The steps would be:

1. User logs in (cookie created and store state updated)
2. User refresh the page
3. Internally I would like to use the token in the cookie to call fetchUser and store the response again in the Vuex store

What would be the right moment to call fetchUser? this.$auth is undefined in most of the lifecycles hooks.

Thanks

**Comment by websanova** [comment]
Hard to say, no idea what you got going on there.

Is there any hook for when the app is loaded. I would assume any plugin
would be undefined in this situation so would need a point when your app is
loaded the and the instance contains this.$auth (or any other).

**Comment by martosoler** [comment]
Thanks for answering, I think my problem is related to the fact I'm using a cookie to store the token.

Is there an example on how to configure the library to work only with cookies?

**Comment by websanova** [comment]
Well, you can just write a driver to store and pull the token from the
cookie

**Comment by alanrivetta** [comment]
Hello, sorry for the delay asking that the problem solves the inconvenience I had by modifying the response/request interceptor a bit to make it work with OAuth2 in Symfony 3!
I close the subject and I thank you very much!
