### ISSUE TITLE
Login programmatically

### ISSUE THREAD

**Issue by nkostadinov** [websanova/vue-auth#189]
I have a backend and the user is already logged. Is it possible to programmatically login the user. I set the user data via $auth->user(data) but don't know where to set the token ?

**Comment by websanova** [comment]
You don't have to set the token manually, the plugin already does that,
take a look at the drivers.

**Comment by nkostadinov** [comment]
I already checked the bearer driver (which I am using) and saw that it intercepts the response and extracts the token from the authorization header.
But the user is already logged in my backend (PHP) and I want to login the user in Vue without any more requests.

**Comment by websanova** [comment]
Ok, I guess you have static pages mixed with dynamic calls?





On Wed, Jul 5, 2017 at 10:09 PM, Nikola Kostadinov <notifications@github.com

**Comment by websanova** [comment]
ok, I added ability to set a token, grab the latest `v2.13.0-beta`.

```
this.$auth.token(null, token);
```

The first argument is the name of the token, but you can just leave it with default.

**Comment by nkostadinov** [comment]
Thanks for the addition, I believe it will be useful. But there is some strange behavior or I am doing something wrong. In order to log the user I do the following :
```
                this.$auth.user(user)
                this.$auth.token(null, user.token)
                this.$auth.watch.authenticated = true
```
Only after I set the "authenticated" to true the user is logged and the check function returns true - is this normal behavior or I am doing it wrong ?

**Comment by websanova** [comment]
Hmm, I guess you will need to set loaded to true as well.
