### ISSUE TITLE
Login successfully, but don't find the  default_auth_token in session storage

### ISSUE THREAD

**Issue by liuyatao** [websanova/vue-auth#191]
1. I login in successfully. and the authorization  is in the response header ,
2. But the default_auth_token can't be found in session storage.
3. And fetch the /user  get a 401 error beacuse there is not a authorization in  request header.

 Login in successfully.
![image](https://user-images.githubusercontent.com/4133185/27985056-42a2ebf8-6416-11e7-8848-2f46cf2d4047.png)
Can't find the default_auth_token.
![image](https://user-images.githubusercontent.com/4133185/27985072-a69ca5d6-6416-11e7-89eb-9e27792e4ed8.png)
Get  a 401 error beacuse there is not a authorization in  request header

<img width="806" alt="wx20170708-195604 2x" src="https://user-images.githubusercontent.com/4133185/27985119-98560cc8-6417-11e7-9dbd-e6232b5315b0.png">

**Comment by websanova** [comment]
Well which auth driver are you using?  From what I see you should be using
the basic one

**Comment by zexingguo** [comment]
You can mannually save your token into localStorage using $auth.token(null, res.body.token).

this.$auth.login({
  success(res){
    this.$auth.token(null, res.body.token)
  }
})

you can name the token by replacing null with a string

**Comment by websanova** [comment]
Well I can see the token that is being passed is plain without the `Bearer:` in front. So likely just using wrong driver since it's trying to parse out the token using the bearer driver. Just switch to basic driver should work.

**Comment by Yaty** [comment]
Hi, thanks for vue-auth !
I also have this issue. I tried with the basic and bearer driver (I didn't forget to add `Bearer` in front).
POST /auth/login works well and return me the token in headers but it's not saved.
In the success callback of $auth.login there is no evidence of Authorization header (using the basic driver) :
 
![](https://image.prntscr.com/image/uHMkXY-qQ9CqJ5f6DfW7Pw.png)

**Comment by nkostadinov** [comment]
I dont see bearer in front of the token. The auth header should look like :
Authorization: Bearer FGWERDG#$tDT34GDFGDt4#

**Comment by websanova** [comment]
I'm not really sure what your issue is. Maybe we need to define what you're
trying to achieve first. Because I see the token in your response there.

On Wed, Jul 26, 2017 at 4:37 PM, Nikola Kostadinov <notifications@github.com

**Comment by Yaty** [comment]
@nkostadinov In the example I was trying with the basic driver, so if I understood well there is no need to have Bearer in front. I already tried with the bearer driver and with : `Authorization: Bearer X.Y.Z`, it didn't work either.

@websanova Ok I'll try to explain myself : 
I simply want to login, to do that I use $auth.login like so : 
`this.$auth.login({
          body: {
            email: this.email,
            password: this.password,
          },
          fetchUser: true,
          rememberMe: this.rememberMe,
          redirect: { name: redirect ? redirect.from.name : 'Panel' },
          success(res) {
            console.log('login success', res);
          },
          error(e) {
            console.log('login failed', e);
          },
        });`
Then there is a call to my API with the credentials in parameters (email and password), the response is a JSON object containing `status: "success"` with a new header : `Authorization: the JWToken`

What I expect is that Vue-auth will save this header in the localstorage, sessionstorage or cookies in order to reuse this token later for future API calls. However, that's not the case. Did I misunderstand how Vue-auth is working or am I doing something wrong ?

Thanks for your time :)

**Comment by websanova** [comment]
Check if anything comes up with $auth.token();

**Comment by Yaty** [comment]
Nothing, it's`null`.

**Comment by websanova** [comment]
Can I see your code for how you installed the plugin, and what version of
vue-auth you are using.

Also, which browser are you testing, is it incognito mode etc?

**Comment by Yaty** [comment]
``` javascript
// Vue
import Vue from 'vue';
import VueResource from 'vue-resource';

// Vue Auth
import VueAuth from '@websanova/vue-auth';
import VueAuthDriver from '@websanova/vue-auth/drivers/auth/bearer';
import VueAuthHttp from '@websanova/vue-auth/drivers/http/vue-resource.1.x';
import VueAuthRouter from '@websanova/vue-auth/drivers/router/vue-router.2.x';

// App
import App from './App';
import router from './router';

Vue.use(VueResource);
Vue.router = router;
Vue.http.options.root = process.env.BACKEND; // http://localhost:8081/
Vue.use(VueAuth, {
  auth: VueAuthDriver,
  http: VueAuthHttp,
  router: VueAuthRouter,
});

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App },
});
```

My $auth.login : 
``` javascript
        this.$auth.login({
          body: {
            username: this.email,
            password: this.password,
          },
          fetchUser: false,
          rememberMe: this.rememberMe,
          success(res) {
            const token = this.$auth.token();
            console.log('login success', res, token);
          },
          error(e) {
            console.log('login failed', e);
          },
        });
```

And my backend is a Node.js app running with express, here are the login route : 
``` javascript
router.post('/login', (req, res, next) => {
    jwt.sign({ username: req.body.username, password: req.body.password }, config.secret, (e, token) => {
        if (e) {
            logger.error('Error when creating a JWT token', {
                username: req.body.username,
                password: req.body.password,
                token,
                error: e
            });
            return next(e);
        }

        mongodb.login(req.body.username, req.body.password)
            .then((isLoginSuccessful) => {
                if (isLoginSuccessful) {
                    logger.debug('Login successful', { username: req.body.username, password: req.body.password, token });
                    res.set('Authorization', 'Bearer ' + token);
                    return res.json({
                        status: 'success'
                    });
                } else {
                    logger.debug('Login unsuccessful', { username: req.body.username, password: req.body.password, token });
                    return res.status(400).json({
                        status: 'error',
                        error: 'invalid.credentials',
                        msg: 'Invalid credentials'
                    });
                }
            })
            .catch((e) => {
                logger.info('Error while login', { username: req.body.username, password: req.body.password, token, error: e });
                return next(e);
            });
    });
});
```

I'm using Firefox 54.0.1 in normal mode. I also tried with IE11.
Vue-auth : 2.13.2-beta

**Comment by websanova** [comment]
When you write your custom driver there...

For the response are you able to console out the headers and see see `Authorization` header?

```
auth: {
    request: function (req, token) {
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    },
    response: function (res) {
      return res.data.token
    }
  },
```

**Comment by Yaty** [comment]
To use my auth driver I had to change my API to return the token in the data and not in the header.
If I put back the token in headers to test like that: 
```
return res.set('Authorization', 'Bearer ' + token).json({
  status: 'success',
  token
});
```

res looks like that after a login : 
```
{
"url":"http://127.0.0.1:8081/auth/login",
"ok":true,
"status":200,
"statusText":"OK",
"headers":{"map":{"Content-Type":["application/json; charset=utf-8"]}},
"body":{"status":"success","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllhdHkiLCJwYXNzd29yZCI6IllhdHkiLCJpYXQiOjE1MDEyNTMzODR9.vmf_OsFoS3buaduoRIBH4YsES1LRdOGWqpqIB6hNYWo"},
"bodyText":"{\"status\":\"success\",\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllhdHkiLCJwYXNzd29yZCI6IllhdHkiLCJpYXQiOjE1MDEyNTMzODR9.vmf_OsFoS3buaduoRIBH4YsES1LRdOGWqpqIB6hNYWo\"}"}
```

**Comment by websanova** [comment]
Ok, so seems your login is not returning any authorization header?

**Comment by Yaty** [comment]
If I look at the response in Firefox I have an authorization header : ![](https://image.prntscr.com/image/E7u4l4xQTNC_Bo1db4Y8AA.png)

**Comment by websanova** [comment]
I'm not sure what's going on your end. But i see a lot of ports also, 8080 8081, 8083. Also the example from above has no Authorization header.

```
"headers":{"map":{"Content-Type":["application/json; charset=utf-8"]}},
```

I see this console screenshot, but the  `res` output is where we really need to see it to fully confirm.

1. Are there multiple apps running/test on different ports, can make sure we are looking at the correct one.

2. Is it possible the app has some other interceptors that could be altering the response?

3. Also make sure you get the latest and perhaps try running one of the standalone demos with the app server.

https://github.com/websanova/vue-auth/blob/master/docs/Demo.md

**Comment by BiletskiyDmitriy** [comment]
<img width="1027" alt="00000769" src="https://user-images.githubusercontent.com/12006505/29248249-4179f79a-801c-11e7-965f-685c96c4391e.png">
Hi guys, I've got the same behavior, when I'm not be able to send any request after successful login. That's difference between opera 46.0 and chrome 60.0 on mac os.

So when I changed my custom response interceptor to 
`response(res) {
    let headers = this.options.http._getHeaders.call(this, res);
    let token = headers.Authorization || headers.authorization;

    if (token) {
      token = token.split(`${constants.TOKEN_PREFIX} `);

      return token[token.length > 1 ? 1 : 0];
    }
  }`

it works

**Comment by Yaty** [comment]
Solved by setting this header : `Access-Control-Expose-Headers: Authorization` 😋
