### ISSUE TITLE
Cannot redefine property $http

### ISSUE THREAD

**Issue by untilyou89** [websanova/vue-auth#194]
Hi,
I use axios and  Vue-Axios . Can you hellp me the error "Cannot redefine property $http"

Code 
[http://imgur.com/K2cpFtg](http://imgur.com/K2cpFtg)

Error 
[http://imgur.com/nfVBnRF](http://imgur.com/nfVBnRF)

**Comment by websanova** [comment]
Axios doesn't set $http, that's vue-resource

**Comment by untilyou89** [comment]
So how to config use if i want use  axios and vue-axios . I follow the instructions "Install with Vue-Axios" but the above error occurred

**Comment by websanova** [comment]
Can you provide a fiddle?

**Comment by untilyou89** [comment]
I solved the problem.Please close

**Comment by PurwadiPw** [comment]
How you solved the problem @untilyou89 ?

**Comment by etune** [comment]
@untilyou89 - how did you solve the problem?

**Comment by etune** [comment]
What fixed it for me was setting `Vue.http.options.root` only after instantiating Vue.

```
new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App }
})
Vue.http.options.root = 'https://api-demo.websanova.com/api/v1' //not before
```

**Comment by untilyou89** [comment]
Iam so Sorry .I can see the answer now . I solved the problem.I cannot use require  VueAxios .i require Axios and  config after with libary axios (not use VueAxios)
  `window.axios = require('axios');Vue.axios = axios;`

and config vue-auth
`Vue.use(VeeValidate);
Vue.use(VueAuth, {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
........
});`

This is my solution . you can try

**Comment by dxxd116** [comment]
What is VeeValidate in 
`Vue.use(VeeValidate);`

**Comment by schoolmeister** [comment]
For anyone who ran into this problem when trying to use axios instead of vue-resource in the 2.x demo, look at your `index.html` file. It contains the following import: `
    <script type="text/javascript" src="/js/vue-resource-1.3.4.min.js"></script>`. This causes it to be loaded even though you might have commented it in `app.js`. Simply remove or comment the line and the above error will be gone.

**Comment by volkersmit** [comment]
I had the same error... solved by removing VueResource from my project
