### ISSUE TITLE
Strange error with loginData: {},

### ISSUE THREAD

**Issue by Kuchiriel** [websanova/vue-auth#195]
Somehow if I set fetchUser to true, my url changes to /auth/user instead of /v1/login which is the one I want.

```
loginData: {
    fetchUser: true,
    url: defaultURL + '/v1/login', // checkURL(),
  },
```

Someone have any idea why?

Thanks!

**Comment by websanova** [comment]
Are you sure it's only the one call being made?

**Comment by Kuchiriel** [comment]
I am just calling  this.$auth.login to login.

**Comment by Kuchiriel** [comment]
I think I will try to put the data I want inside the token, and then, decode the token in the browser until I find how to solve this.

**Comment by websanova** [comment]
What is the value of defaultUrl?

And are you using vue-resource?

**Comment by zexingguo** [comment]
@Kuchiriel I ran into the same problem, you can change the URL in loginData option to whatever your endpoint is and that should solve your problem. 

Here's my config for vue-auth in main.js

`Vue.use(require('@websanova/vue-auth'),
{
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
	router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  tokenName: 'token',
  authType: 'bearer',
  tokenHeader: 'Authorization',
  rolesVar: 'permissions',
  refreshData: {
		url: '/auth/refresh',
		method: 'GET',
		enabled: false
	},
	fetchData: {
		url: '',
		method: 'GET',
		enabled: true
	},
	loginData: {
		url: 'http://xx.xxx.xxx.xx/v1/login',
		method: 'POST',
		redirect: { name: 'DashboardIndex' }
	}
})`

**Comment by Kuchiriel** [comment]
@websanova, defaultURL is just http://localhost:5000

**Comment by Kuchiriel** [comment]
@zexingguo Thank you, I think it will help!

**Comment by websanova** [comment]
If you are using vue-resource then probably you should just set your root:

https://github.com/pagekit/vue-resource/blob/develop/docs/config.md#configuration

If it's an end point that happens to be completely different then you should be setting the full url and it should be fine. But this is really a vue-resource thing not really from vue-auth end at this point. Really vue-auth is just passing the parameters straight through to it.

**Comment by Kuchiriel** [comment]
@websanova So it's all right, I'll make it right now. I think this is not a issue at all so I'l be closing. Thank you guys very much for the help!
