### ISSUE TITLE
Relative route path issue

### ISSUE THREAD

**Issue by jgerbes** [websanova/vue-auth#196]
I'm having an issue where the auth routes are appending the current route, rather than the base url.

**Example**
Base url: www.example.com
Correct login route: www.example.com/auth/login
Current path: www.example.com/page/subpage
Current login route: www.example.com/page/subpage/auth/login

**Possible solution**
It seems that the solution is to add "/" to the start of each of the auth routes:

```
registerData: { url: '/auth/register' },
loginData: { url: '/auth/login' },
logoutData: { url: '/auth/logout' },
oauth1Data: { url: '/auth/login' },
fetchData: { url: '/auth/user' },
refreshData: { url: '/auth/refresh' },
loginOtherData: { url: '/auth/login-other' },
logoutOtherData: { url: '/auth/logout-other' },
```

**Comment by websanova** [comment]
Probably you just need to set base url for vue-resource?

```
Vue.http.options.root = https://api.example.com
```

You should not have to prepend with "/" for vue-resource. I think same for
Axios.

If you are using something else, then I'm not sure.

**Comment by ConsoleTVs** [comment]
Is there a way to redirect to named routes tho ?

**Comment by websanova** [comment]
Did you try? ;)

**Comment by ConsoleTVs** [comment]
How? The redirect option accepts a string, and it's the path I guess? how should I tell it to use the name instead?

**Comment by ConsoleTVs** [comment]
nvm.

```
var redirect = this.$auth.redirect();

this.$auth.login({
    redirect: {name: redirect ? redirect.from.name : 'account'},
});
```

Thanks haha

**Comment by jgerbes** [comment]
Setting the base url did fix the issue. It may be worth adding this to the documentation(?)

**Comment by ConsoleTVs** [comment]
I think it's there already, at least it's in the demo provided.

**Comment by websanova** [comment]
Well the routes and url are really dependant on the library you're using,
Vue resource or axios for example ;)
