### ISSUE TITLE
$auth.redirect() with autoLogin is ignoring redirect parameter

### ISSUE THREAD

**Issue by jgerbes** [websanova/vue-auth#197]
When performing `$auth.register()` with `autoLogin: true`, the redirect parameter is being ignored - it will redirect to the root '/', no matter what the redirect parameter is set to.
```
this.$auth.register({
    params: this.formData,
    autoLogin: true,
    redirect: { name: 'account' },
    success: (res) => this.success(res),
    error: (res) => this.error(res)
});
```

**Comment by nkostadinov** [comment]
i have the same issue, I think that the merge of the parameters is the problem.

**Comment by websanova** [comment]
ok, Just pushed fix for this, it's in `v2.13.1-beta`.

thx :-)

**Comment by jgerbes** [comment]
I'm still experiencing the issue in the `v2.13.2-beta`.

**Comment by jgerbes** [comment]
@websanova Could you please revisit this issue?

**Comment by websanova** [comment]
Sure, will take a look today

**Comment by websanova** [comment]
Just verified again. Directly from 2.x demo...

```
this.$auth.register({
    body: formData, // Vue-resoruce
    data: formData, // Axios
    autoLogin: this.data.autoLogin,
    rememberMe: this.data.rememberMe,
    redirect: {name: 'async'}, // Works with autoLogin false or true.
    success: function () {
        console.log('success ' + this.context);
    },
    error: function (res) {
        console.log('error ' + this.context);

        this.error = res.data;
    }
});
```

**Comment by jgerbes** [comment]
I have looked into it and realised that my issue is a bit more specific. When passing `null` as the `redirect`, I am expecting no redirect to occur (like with `login()`), but instead it is redirecting to the root.

**Comment by websanova** [comment]
Ahhh, Okk, yes, in that case it's gonna be an issue...I'll fix that shortly

**Comment by jgerbes** [comment]
Much appreciated!

**Comment by websanova** [comment]
ok, just updated it `v2.15.1-beta`.

So it will strictly use the register's redirect field or the overridden one provided regardless of autoLogin set to true/false.

Makes more sense this way, thx :-)

**Comment by jgerbes** [comment]
Excellent, that did it :-)

Thanks for your continued work on this package!
