### ISSUE TITLE
$auth.user() Issue

### ISSUE THREAD

**Issue by zexingguo** [websanova/vue-auth#200]
I've been having a problem with $auth.user that after I login and refresh the page $auth.user() becomes empty. I'm still authenticated but my auth user object is empty which is werid. 

I set my $auth.user() with res.body.token after I login in. and I enabled 
fetchData. 

login() {
	this.$auth.login({
          body: this.user,
          fetchData: false,
	  fetchUser: false,
          success(res) {
		console.log('Success ' + JSON.stringify(res))
		this.$auth.token(null, res.body.token)
		this.$auth.user(res.body.user)
        },
        error(res) {
          console.log('Error ' + JSON.stringify(res))
          this.error = res.data
        }
      })
}

**Comment by websanova** [comment]
Are you using $auth.ready?

**Comment by zexingguo** [comment]
@websanova No, but I checked it returns true and $auth.user still empty

**Comment by websanova** [comment]
Hmm, are you using $auth.ready() in a component though?

Keep in ind it's just a binded variable that's being returned. It should be
used in a component.

https://github.com/websanova/vue-auth#ready

**Comment by zexingguo** [comment]
I sloved the problem by store my user object in LocalStoarge and clear once the browser is closed. I'm using $auth.ready() in my component. Thank you for the help !
