### ISSUE TITLE
it is  so hard to understand this...

### ISSUE THREAD

**Issue by lemos1235** [websanova/vue-auth#203]
i could not find the applicability of this project for some kind of common occasions. maybe it contains lots of 
 functions and options ,but most of them are less flexible and difficult to understand

**Comment by websanova** [comment]
ok, thx for the feedback. But the purpose of this area is for reporting issues.

**Comment by DaAwesomeP** [comment]
@websanova a tutorial to go along with the demos that goes through each required step (from initial options to logging out) and what is expected in each API response would be very helpful.
