### ISSUE TITLE
Undefined error / success response from login function

### ISSUE THREAD

**Issue by ConsoleTVs** [websanova/vue-auth#204]
So.. I can't seem to have this working, no response ever returned (always undefined) fron your success and error methods. Also, the first error (error 442) is from laravel's unable to verify the data and the other (error 401) is the bad credentials error. I need to parse theese errors and show diferent messages to the user. I know how to do this with axios, but really can't get it working with this...

- Vue 2.0
- Axios 
- Laravel 5.4

NOTE: error function parameter (res) returns a string: Request failed with status code 422 (for example)

![image](https://user-images.githubusercontent.com/6124435/28739110-6705631c-73f8-11e7-9dae-56c38b4476bb.png)

![image](https://user-images.githubusercontent.com/6124435/28739131-983f843a-73f8-11e7-8384-04b42edc45e1.png)

![image](https://user-images.githubusercontent.com/6124435/28739222-7eb5ad04-73f9-11e7-837e-44d275630f99.png)

![image](https://user-images.githubusercontent.com/6124435/28739116-7583d00e-73f8-11e7-80c3-8f945e979e6c.png)

![image](https://user-images.githubusercontent.com/6124435/28739120-7fd0830e-73f8-11e7-9c66-06d26017da94.png)

auth = the export above it.

**Comment by ConsoleTVs** [comment]
That's your 2.X demo with axios rather then vue resources:

![image](https://user-images.githubusercontent.com/6124435/28740120-6639b614-7401-11e7-8894-18106805348d.png)

So it's the same error, as you can see there's no  response in the HTML page, othwise with the vue-resources as default, you get a nice response if the data is incorrect in the screen

**Comment by ConsoleTVs** [comment]
Some testing was made. It's an axios issue, please fix it as soon as possible, vue-resource is working fine :)

**Comment by websanova** [comment]
what if you just console.log this or res?

**Comment by ConsoleTVs** [comment]
I told you in the text ( i edited it after a few minutes) it logs a string:

NOTE: error function parameter (res) returns a string: Request failed with
status code 422 (for example)

**Comment by websanova** [comment]
I'm not really sure what your issue is.

If you see a definite issue you can either provide a sample fiddle or pull
request.

All I can see now is that you are having some issues with the response
which may or may not be related to the plugin.

Perhaps you can take a look at overriding the httpData method in the axios
driver.

https://github.com/websanova/vue-auth/blob/master/drivers/http/axios.1.x.js

**Comment by ConsoleTVs** [comment]
The issue, once again, as my photos attached here suggested is the fact that using axios, your login function sends a request, but the error() and success() functions recive a string as an argument rather than the http response. Using vue-resource however, everything works as expected.

To make sure it was not my issue, I changed your 2.X demo, commented vue-resource lines, and uncomented axios ones.

The final result it's the same, vue-resource sends a response to the success() and error() functions of the $auth.login while axios sends a string wtih Request failed with status code 422 (for example).

I assume this is a problem releated to the library itself...

**Comment by websanova** [comment]
I don't use Axios, so I can't comment much on it.

But looking at their docs for interceptors.

https://github.com/mzabriskie/axios#interceptors

There is nothing too magical going on with the auth plugin.

https://github.com/websanova/vue-auth/blob/master/drivers/http/axios.1.x.js#L25

It's pretty much copy and pasted from their docs. It's sending the error right through.

I assume you are just doing `console.log(res)`. But it seems with Axios it's hidden in a response variable. `console.log(res.response)`. But this is Axios not from the plugin...

**Comment by ConsoleTVs** [comment]
console.log(res) gives me a string using axios

console.log(res.response) gives error, because of the fact that res is a string.

I don't know what's the issue with this, but I would recommend you to try it out... I think the issue is how the data is transfered, I followed your docs and did not work... 

vue-resource works great meanwhile.

**Comment by websanova** [comment]
I literally just tried this now (direct from the demo code with Axios).

```
this.$auth.login({
    body: this.data.body, // Vue-resource
    data: this.data.body, // Axios
    rememberMe: this.data.rememberMe,
    redirect: {name: redirect ? redirect.from.name : 'account'},
    fetchUser: this.data.fetchUser,
    success() {
        console.log('success ' + this.context);
    },
    error(res) {

        console.log(res.response);

        console.log('error ' + this.context);

        this.error = res.data;
    }
});
```
It shows me the object in the console

```
> Object {data: Object, status: 400, statusText: "", headers: Object, config: Object…}
```

**Comment by websanova** [comment]
What version of Axios do you have btw?

**Comment by ConsoleTVs** [comment]
The latest one I'm afraid, let me try it out again, I will paste more information, give me a second ^^

**Comment by ConsoleTVs** [comment]
I downloaded the current repo, and when I do npm run demo I get this:

![image](https://user-images.githubusercontent.com/6124435/28744761-15c73fdc-7468-11e7-87e8-1d3f5249c360.png)

**Comment by websanova** [comment]
aha... ya, there have been changes tonight :-)

https://github.com/websanova/vue-auth/blob/master/docs/Demo.md

But really this should be working. In the example above it shows `res.data`. I'm guessing this should just be `res.response.data`.

**Comment by ConsoleTVs** [comment]
If I recived the object like your picture there would be no problem :p 

The point is that for an unknown reason i get a string, that's why I wanted to try it again.

I followed the steps there but got that error :o

Followed:

> cd demos/2.x
> npm install
> npm run demo

**Comment by websanova** [comment]
Well that's the thing, when I `console.log(res)` it shows the string also. But `console.log(res.response)` does exist.

Not sure about this error though.

maybe try removing `node_modules` and try again...

**Comment by ConsoleTVs** [comment]
Ok finally managed to make it working with my laravel application + axios. Indeed res was a string but res.response was not. I was too tired to realize yesterday night, thanks a lot for the efforts, everything works back to normal using axios, great library.

One last question:

Is there a possibility of accesing the $auth variable outside instance / components? I've seen ways of doing this with the Vue.auth but seems it's not working, althought the library prototype its currently set in your library. Imagine I wanna define a custom navigation guard that makes use of the auth, is there a way of doing this since the $auth is not defined yet?

**Comment by websanova** [comment]
Yes, not sure why they would do it this way in Axios. But glad it's all working for you :-)

Depends, would have to see some sample to get a better idea of what you mean. For instance where you are accessing these components? Generally `$auth` should be available to any component in the app. 

If you mean like a plugin, this is always tricky and why you see this plugin setup with the drivers for auth, http, etc.

If you open a separate issue with more details we can take a look to see what can be done.

**Comment by ConsoleTVs** [comment]
Sure thing, let me open a new issue with more details! Thanks!
