### ISSUE TITLE
Vue.auth outside components and instances.

### ISSUE THREAD

**Issue by ConsoleTVs** [websanova/vue-auth#205]
Reegarding to the details, this video shows exactly what I'm refering to:

https://youtu.be/_IhhtEX9WvA?t=5m23s

Minute: 5:23

The point is to have access to the auth component even outside the components, eg; in the routes.

I know the redirection is already done by vue-auth but the point of the video is just to show the example usage.

**Comment by websanova** [comment]
Ah, well yes. You're never gonna have access there.

But yes, you can get access in the interceptors, just depends when you
declare them.

You will see that auth plugin check the meta property auth during each
route change.

**Comment by ConsoleTVs** [comment]
Yeah yeah, I already know the plugin does such thing but imagine I wanna create an interceptor that if ur logged in it does somethign else (just as an example). There's no way of doing such thing like in the video? In the video he has acces there, I see you told me we can never have access there.

In that case, feel free to close the issue ^^

**Comment by websanova** [comment]
Well there is nothing that special about accessing auth there, it's just an object. I could add `Vue.auth` and it should work the same. It just wouldn't have any context. That's pretty much only difference.

**Comment by websanova** [comment]
Grab `v2.14.2-beta`.  You could do this in your bootstrap js file (similar to the video)...

```
....

Vue.use(require('@websanova/vue-auth'), {
    ...
});

Vue.router.beforeEach(function (transition, location, next) {

    console.log(Vue.auth);
    console.log(Vue.auth.check());

    next();
});

...
```

**Comment by ConsoleTVs** [comment]
That's very cool.

![image](https://user-images.githubusercontent.com/6124435/28746046-0449864e-7485-11e7-9b1c-b59832cc6ea3.png)

is there any way to check this when it loads? I need to set the page title / description. I have a beforeEach code as well:

![image](https://user-images.githubusercontent.com/6124435/28746056-276807ea-7485-11e7-9dfa-b814ec6e8808.png)

This is in fact done to change a page title. But the beforeEach event is not fired in the first load, (maybe because of $auth not .ready() yet?) I'm kinda confused...

If I do this on the mounted() event, the data is not correct. If I do it on a created() same, but in a updated() it does it correct. but fires twice each time (same for beforeUpdate)

I know this is not probably releated to the library but perhaps you could help me... Im very new on vue <.<

**Comment by ConsoleTVs** [comment]
PD; check the comments in the first picture

**Comment by ConsoleTVs** [comment]
BTW; fixed with computed and watched statements. nevermind
