### ISSUE TITLE
Maybe some tutorial?

### ISSUE THREAD

**Issue by outluch** [websanova/vue-auth#208]
Like what is it? What is main features (integration with router/axios/http) How is it intended to work?
Common usecase? Common scenario of integration? 
It is quite hard to get into with docs I see here.
Thank you.

**Comment by websanova** [comment]
Hmm, good point, you're right, would be good to have some getting started
guide.

Will get this up shortly :-)

**Comment by websanova** [comment]
I've update the docs a bit, but really would be better if you could tell me specific issues and confusion you are having so I can answer questions directly. I don't want to risk filling docs with a bunch of bloat text.

**Comment by outluch** [comment]
Thank you very much. I had no time lately, but will write you some ideas.

**Comment by nitePhyyre** [comment]
One thing that would be great to have in the docs is that the server needs to send the 'Access-Control-Expose-Headers: Authorization' header.

Took me a day and a half to figure that one out.

**Comment by outluch** [comment]
Ok, I have read your beginners guide. It is nice but I think it is like "what are components, this plugin utilize?" I think one remaining thing to add - step by step guide how to make this work :)
I will try from my experience here:
1) yarn add @websanova/vue-auth (NOTE: not simple vue-auth, as expected)
2) use it like that in your main file:
```
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
})
```
NOTE: You have to connect your router to Vue instance before usage of vue-auth. Like that:

**Comment by websanova** [comment]
I've added a step by step guide following your suggestions :-)

https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md

Let me know if I'm missing anything or can make some improvements.

**Comment by outluch** [comment]
Looks nice.
One note here: 
How to add this to project:
`npm install @websanova/vue-auth` (**NOTE**: not simple `vue-auth`, as usually)
It is not trivial gotcha. :)

**Comment by nafiux** [comment]
I'm new in Vue (coming from Angular), Could you please explain more about how the things works under the hood? I understand that you're intercepting each response and request. Which format are you expecting to receive the JWT from the Server? It's confusing the info about the route setup. Thanks

**Comment by websanova** [comment]
Did you check the guides at all?

**Comment by nafiux** [comment]
Yes I did, perhaps is there that I'm not understanding well. I have an API with a v1/auth/login POST method which is receiving the request from Vue, I'm returning the JWT in an Authorizacion header with the content "Bearer X.Y.Z", and I can see the Header in the Dev Console for Google Chrome. But, when Vue-auth send the request to auth/user isn't attaching the Authorization header. I have the Bearer driver, http Axios and Vue Router, Any idea?

**Comment by websanova** [comment]
A typo maybe? "Authorizacion"...

**Comment by nafiux** [comment]
Nope, that was a typo from my response because of my mobile, apologies.

This is what I have:

**main.js**

```
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'

// Axios
import axios from 'axios'
import VueAxios from 'vue-axios'
Vue.use(VueAxios, axios)
Vue.axios.defaults.baseURL = 'http://localhost:8081/api/uaa/v1'

Vue.router = router

// Vue Auth
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'roles'
})

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```

**router/index.js**

```
import Vue from 'vue'
import Router from 'vue-router'
import Hello from '@/components/Hello'
import Login from '@/components/Login'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: Hello
    },
    {
      path: '/login',
      name: 'login',
      component: Login,
      meta: {auth: false}
    }
  ]
})
```

I copy your Login.vue to my components/ folder.

Do you see any wrong with the code? Thanks

**Comment by websanova** [comment]
Looks ok to me, can you fully verify a token is being sent?

**Comment by jap1968** [comment]
Same problem here. Have a look at the comment from @nitePhyyre, who pointed what was causing this problem

In my case that was fixed just adding the missing header:
`return $response->withHeader('Access-Control-Expose-Headers', 'Authorization')->withHeader('Authorization', 'Bearer '.$token)`

**Comment by Rockson** [comment]
In the step-by-step guide in the hook section, for axios it would be vue.axios.interceptors.response.use(successFn, errorFn)

Anyway in my case I had trouble setting up the refresh of tokens, actually I didn't even know when and why to do it.
Moreover I struggled understanding what the flag 'rememberMe' would do because the token stored in localstorage persists after closing the browser. So setting rememberMe=true was useless

**Comment by jap1968** [comment]
I would appreciate some tutorial for building the vue-auth library, too. I want to test some changes but I am unable to build the library. This is the error I am getting:

```
npm install webpack --save-dev
webpack --config build/webpack.config.js

module.js:544
    throw err;
    ^

Error: Cannot find module 'replace-webpack-plugin'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/informatica/desarrollo/vue-auth/vue-auth/build/webpack.config.js:2:25)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

**Comment by oluudeh** [comment]
@jap1968 take a look at this [tutorial](https://codeburst.io/api-authentication-in-laravel-vue-spa-using-jwt-auth-d8251b3632e0) if you still need it.

**Comment by itdpong** [comment]
I'm new in webpack, npm, vue, node.js, so this is the first time I use a module name with @ and /
so I spend many time on install the module and require the module.

so would you please add the following command in your step by step guide?(maybe you have included it , just I miss it.)
npm install @websanova/vue-auth

**Comment by eyaylagul** [comment]
I cant understand document for how can i use package. If you want to explain clearly how to use, those who understand should return api endpoint ex: .user () data or rolesVars? parseUserblalba function right way but how that api return? Refresh or Options request how work with endpoint? What is common or specific method while using.


while i use that package, i am can getting token but only i can getting token. $auth.user() method return null, so i cant define role based middleware for route. But its not worse than that i can not find any simple working example.

i dont want misunderstanding, thank you for package. I'm only bored find to try right way for hours, sorry :)

**Comment by jonnykio** [comment]
How can i use `vue-auth` with facebook oauth for setting a token on the localstorage, i've been able to do this with email/password confirmation now i need to do facebook oauth.
