### ISSUE TITLE
The fetchUser request is blocked for a while when pressing Enter in the address bar

### ISSUE THREAD

**Issue by zhangzhen** [websanova/vue-auth#211]
Suppose http://localhost:4000/#/analysis/tasks is in the address bar. I press Enter, and then I get a blank page. An request http://0.0.0.0:5000/user needs to be issued because of some authentication. After an investigation with devtools, I found that the request was pending about 2-3 mins. How can i solve this problem? 

The code of using vue-auth is listed below:
```
Vue.use(VueAuth, {
  auth: {
    request: function (req, token) {
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    },
    response: function (res) {
      return (res.data || {}).access_token
    }
  },
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  loginData: { url: 'http://0.0.0.0:5000/login', fetchUser: true },
  refreshData: { enabled: false },
  fetchData: { url: 'http://0.0.0.0:5000/user' }
})

```

**Comment by zhangzhen** [comment]
chrome://net-internals/#events shows:
```
t=3126 [st= 0] +REQUEST_ALIVE  [dt=13]
                --> priority = "HIGHEST"
                --> url = "http://localhost:4000/#/analysis/viewpgstask"
t=3126 [st= 0]    DELEGATE_INFO  [dt=2]
                  --> delegate_blocked_by = "NavigationResourceThrottle"
t=3128 [st= 2]    URL_REQUEST_DELEGATE  [dt=0]
...
```

**Comment by websanova** [comment]
Well if your request is hanging, it's maybe not to do with the front end
right

**Comment by zhangzhen** [comment]
the request is hanging on Chromium, but not no Firefox. It's weird!

**Comment by websanova** [comment]
Maybe try running the request directly? As a GET request in the browser and see if anything is occurring.
