### ISSUE TITLE
Get user and token from login response

### ISSUE THREAD

**Issue by DaAwesomeP** [websanova/vue-auth#213]
I'm very confused which data vue-auth expects from which API calls. I currently login like this:
```js
this.$auth.login({
  body: this.data.body,
  redirect: {name: redirect ? redirect.from.name : 'AdminHome'},
  fetchUser: true,
  success () {
    this.success = true
  }, error (res) {
    console.log('error ' + res.data)
    this.error = res.data
  }
})
```
This API responds with this:
```json
{
  "success": true,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZGJhNjczLWNjYzMtNDJkYi04NzQ1LWQ5ZTE5ZjBkYTRmMyIsIm5hbWUiOiJQZXJyeSIsInN1cm5hbWUiOiJOYXNlY2siLCJlbWFpbCI6IjE4bmFzZWNrcEBzbXRleGFzLm9yZyIsImRpc2FibGVkIjpmYWxzZSwicm9sZSI6MiwiZGV2aWNlSWQiOiI3YzU2NTUzYS1lZDI3LTQ1OWEtOGIxOC04MzA2N2MwMWU0MjUiLCJpYXQiOjE1MDA2NjA2NTcsImV4cCI6MTUwMTI2NTQ1N30.LjsW4fDJAUvZLWjAXDwAkikluwxiwEoxaLpG14SRqnE",
  "data": {
    "id": "52dba673-ccc3-42db-8745-d9e19f0da4f3",
    "name": "ExFirstName",
    "surname": "ExLastName",
    "email": "exmaple@example.com",
    "disabled": false,
    "role": 2,
    "deviceId": "7c56553a-ed27-459a-8b18-83067c01e425"
  }
}
```
But then the library makes another call to `api/user`, but it doesn't include the token in that request, so my API doesn't know what to do (well, really it just gives a 400 as it's supposed to).

Also, is it supposed to decode the JWT to get the user data, or am I supposed to hand it to it in an object like this?

Thank you for making this awesome library and saving me a lot of time trying to implement a full auth system myself.

**Comment by DaAwesomeP** [comment]
OK, so I got it to work for the most part. When logging in, I included the token in the `Authorization` header. Then, in `api/user`, I simply decode the token sent via the request header and dump it in the `data` object. Is there any way to have the library simply decode the JWT when it logs in? The user request seems redundant if the JWT already contains the needed user data.

**Comment by guilhermewaess** [comment]
I think that is a feature request, because isn't everyone wants to send user on token.
You can avoid that disabling fetchData in configuration:

```
Vue.use('@websanova/vue-auth', {
    ...
    fetchData: { enabled: false},
    ...
});
```
And fetchUser: false, on $auth.login(). Then send user on login response:

```
this.$auth.login({
  body: this.data.body,
  redirect: {name: redirect ? redirect.from.name : 'AdminHome'},
  fetchUser: false,
  success (res) {
    Here you can save you user anywhere.
  }, error (res) {
    console.log('error ' + res.data)
    this.error = res.data
  }
})
```

**Comment by DaAwesomeP** [comment]
Can I manually write to the `$auth` user object?

**Comment by websanova** [comment]
Yes, just pass the object in to $auth.user();

**Comment by DaAwesomeP** [comment]
Beautiful! Thank you!

**Comment by steveops** [comment]
How can I go about the login process if for some reason the token is sent back in the request body, and not as a Authorization header? I have no control of the api so I cant change the way the login token is delivered.

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth/blob/master/docs/Guide.md#authentication--drivers

**Comment by steveops** [comment]
Hi sorry to bother you mate,  am back again, something seems not to work for me here.
In my login request, the user data is sent back together with the token, currently this is how I attempt to store the user, in the success callback
```
this.$auth.login({
          fetchUser: false,
          url: 'login',
          data: {username: this.username, password: this.password},
          rememberMe: true,
          success: (response) => {
            this.$auth.user(response.data.user)
          },
          error: () => {
            this.error = 'Invalid username or password'
          },
          redirect: {name: 'Home'}
        })
```
However it doesnt seem to work since I cant find the user anywhere in local storage, though it redirects to `Home`. Is that the correct approach to storing the user data?

My issue number two is on page reload, I get this error and the page doesnt render
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Auth._setHeaders (axios.1.x.js?13ff:54)
    at Auth.request (bearer.js?d93d:4)
    at Auth._requestIntercept (auth.js?df86:135)
    at eval (axios.1.x.js?13ff:13)
    at <anonymous>
```
I have added `$auth.ready()` in the part where I render `router-view`, and this is my global config:
```
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  fetchData: {
    enabled: false
  }
})
```
What could be causing this error on page reload?

**Comment by websanova** [comment]
well, you are going completely manual here which is not really the best approach.

a) write a custom driver to parse your auth token in / out. Just look at the examples, they are one liners. You should be able to manage.

b) use the parseData, look it up in options docs to parse your user data if it's not set to the default way.

**Comment by steveops** [comment]
The auth token comes in the Authorization header and it gets retrieved and stored by the default `bearer` driver, my issue is just the user data.

**Comment by websanova** [comment]
Ok so search the options doc for "parse" ;)

**Comment by steveops** [comment]
I've read about it, I assume it comes into play when user data is fetched after login, i.e if `fetchUser = true`, or when using global `fetchData` option. But my case is different, the token and user data are both sent back on login, token in the header and user data in the response body. What am asking is the correct way to set this user data that I have received from the login response, so I dont have to make another request to fetch the user.

**Comment by websanova** [comment]
And what happens if you refresh? How do you get the user data again?

**Comment by steveops** [comment]
Thats the part I need some clarification on. I expected that if I do `$auth.user(user)`, the user object is persisted in local storage until logout is called. But `$auth.user(user)` does not save the user, that is my problem, then there is this error when I reload the page, which I guess is caused by user being null from local storage
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Auth._setHeaders (axios.1.x.js?13ff:54)
    at Auth.request (bearer.js?d93d:4)
    at Auth._requestIntercept (auth.js?df86:135)
    at eval (axios.1.x.js?13ff:13)
    at <anonymous>
```
I would really appreciate if I you gave me a pointer on how to handle the user data that comes with the login response, as at now am blocked because everything else depends on this authentication part. Thanks in advance ;)

**Comment by websanova** [comment]
Right, you should only save the token, or at least that's what the plugin
does, and grabs a fresh user each refresh.

On Nov 28, 2017 9:31 PM, "Steve Ops" <notifications@github.com> wrote:

Thats the part I need some clarification on. I expected that if I do
$auth.user(user), the user object is persisted in local storage until
logout is called. But $auth.user(user) does not save the user, that is my
problem, then there is this error when I reload the page, which I guess is
caused by user being null from local storage

Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Auth._setHeaders (axios.1.x.js?13ff:54)
    at Auth.request (bearer.js?d93d:4)
    at Auth._requestIntercept (auth.js?df86:135)
    at eval (axios.1.x.js?13ff:13)
    at <anonymous>

I would really appreciate if I you gave me a pointer on how to handle the
user data that comes with the login response, as at now am blocked because
everything else depends on this authentication part. Thanks in advance ;)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/213#issuecomment-347540745>,
or mute the thread

**Comment by steveops** [comment]
Alright, thanks mate, let me see if I can find a work-around.

**Comment by steveops** [comment]
Hi @websanova, I dont know why I cant get this thing to work for me.  I have now set `fetchUser = true` for login, but I dont see it sending any request(in the network tab) to fetch the user after the login response, and it remains stuck on the login page. I dont know what I am missing in this whole process. Also when I reload the page, I dont see any request to fetch the user. Here is my setup:

`main.js`
```
Vue.router = router
Vue.use(VeeValidate)
Vue.use(BootstrapVue)
Vue.use(VueAxios, axios)
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  fetchData: {url: 'api/users', method: 'GET', enabled: true},
  parseUserData: function (response) {
    console.log('found the user')
    return response.data.user
  }
})

Vue.axios.defaults.baseURL = 'https://demo-services.tabbs.co.za/'
Vue.axios.defaults.headers = {'Debug-Token': 'ae72ef40-8cb1-11e7-971b-1b34839cb2e9'}
Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: {App}
})
```

`index.html`
```
<body>
    <div v-if="$auth.ready()" id="app"></div>
  </body>
```
`and in Login.vue`
```
this.$auth.login({
   fetchUser: true,
   url: 'login',
   data: {username: this.username, password: this.password},
   rememberMe: false,
   error: () => {
       this.error = 'Invalid username or password'
   },
  redirect: {name: 'Home'}
})
```

Also when I reload the page, I keep getting this error in the console:
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Auth._setHeaders (axios.1.x.js?13ff:54)
    at Auth.request (bearer.js?d93d:4)
    at Auth._requestIntercept (auth.js?df86:135)
    at eval (axios.1.x.js?13ff:13)
    at <anonymous>
```

Kindly help with this, I've been stuck on it for 2 days now.
Many thanks

**Comment by websanova** [comment]
It shouldn't be that complicated.

Just check the console. Either the url is off, header or returned data is
off.

**Comment by gwvt** [comment]
Hello @websanova. I'm having the same set of issues. I want to load the user object from claims in the JWT payload. I would think to do this in the $auth.login() call, like this:
```
<script>
import jwt from 'jwt-simple'

...
    this.$auth.login({
        ...
        success(response) {
          this.$auth.user(jwt.decode(response.data.token, null, 'base64'))
        }
...
```
which correctly sets the user object, but it is then overwritten with an empty object. (You can see this by putting a `console.log(this.$auth.user())` in the success callback to show the populated user object, then after the login entering `this.$auth.user()` in the console, which now shows an empty object).

the parseUserData(data) option only works when you are fetching the user data, so the data parameter is empty if you have fetchUser set to false in the login method, which you obviously do if you are loading the user from the JWT payload and not a separate call to the API.

I can store the token to Vuex and on mounting the redirect page call `this.$auth.user(jwt.decode(response.data.accessToken, null, 'base64'))`, but going outside of the login method to set the user object seems very roundabout and presumably unnecessary.

What's the best practice for loading the user object from a JWT payload?

**Comment by websanova** [comment]
Depends how you are returning it.

Did you check parseUserData ?

https://github.com/websanova/vue-auth/blob/master/docs/Options.md#parseuserdata-_parseuserdata

**Comment by gwvt** [comment]
I did. The parseUserData(data) option only works when you are fetching the user data, so the data parameter is empty if you have fetchUser set to false in the login method.

**Comment by websanova** [comment]
Wait, what?

You just want to store the user manually?

Then what you have is fine `$auth.user(Object)` will do the job.

If something is not working the recheck your object.

**Comment by gwvt** [comment]
It seems that vue-auth is set up to follow the workflow of 1) authenticate, then 2) send an authenticated request with fetchUser to load the user object. I want to load the user object with the authentication request from claims in the JWT, not send a second request. My question is what is the best practice for doing so.

**Comment by websanova** [comment]
hmm,

try this:

~~~
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: {fetchUser: false},
  fetchData: {enabled: false, success: function () { var token = Vue.auth.token(); Vue.auth.user(/* parse token */); } },
})
~~~

Make sure you `console.log(token)` first though. It "should" be stored there locally already.

Let me know if that works at all.

**Comment by gwvt** [comment]
It didn't work. fetchData is that second, authenticated request, right? All the data needed for the user object is being sent in the JWT payload. It's there and accessible in the success callback to $auth.login(), where I can write to the user object, but then it's overwritten unless I store the token to Vuex and afterwards manually load the user object. It just seems that you should be able to do this directly in the $auth.login() call.

**Comment by gwvt** [comment]
If you have 

```
Vue.use(require('@websanova/vue-auth'), {
  ...
  fetchData: {
    enabled: false,
    error () {
      Vue.auth.user({ a: 2 })
    },
    success () {
      Vue.auth.user({ a: 1 })
    }
  }
  ...
```
neither callback loads the user object (at least in a persistent way).

**Comment by websanova** [comment]
Ahh,

When you refresh you will need to set it again, so your login is not going to help you.

I'm trying to get you going for all scenarios.

Can you first just try the example I sent you and tell me if the `console.log(token)` prints your token?

**Comment by websanova** [comment]
NOTE: you can also set the token using `$auth.token('my token')` which you may need to do manually via login.

**Comment by gwvt** [comment]
Thank you!

Ah yes, right about the refresh.

You mean console.log(token) in fetchData.success()? It's not printing anything (even a string). But I can see the token in the console with $vm.$auth.token().

**Comment by websanova** [comment]
Can you try the example again and make sure we are hitting success at all.

~~~
console.log('success');
console.log(Vue.auth.token());
~~~

**Comment by gwvt** [comment]
No, nothing at all is being logged from the fetchData.success() call.

**Comment by websanova** [comment]
@gwvt 

Ok, so I made a little fix so that it will trigger success/error callbacks on fetchData if set.

Make sure you get the latest `2.21.6-beta` and try the example with the token again.

I didn't fully test it, but it "should" be in sequence. Meaning the success callback fires, set the data in there, then it continues to do the other checks for routes, etc.

Let me know your progress with that.

**Comment by gwvt** [comment]
It works like a charm, thank you so much for your help!!

**Comment by websanova** [comment]
sweet :-)

**Comment by morfair** [comment]
Hello @websanova !!
The page https://github.com/websanova/vue-auth/blob/master/docs/Authentication.md has instruction how to wrtie custom driver (Example 1: Token in sub object of body). But where is this code supposed to be? How to apply my changes?

**Comment by websanova** [comment]
Just load it in as any other driver, there are examples in the docs.

**Comment by morfair** [comment]
@websanova , thanks fow answer!
So, I just rewrite your bearer driver and include it like this:

```javescript
Vue.use(VueAuth, {
 ...
 auth: require('./lib/vue-auth_driver_custom.js'),
 ...
})

But your docs says that I can user named drivers (custom1/custom1Auth). Where are I should set my custom driver name (authType: 'custom1')?

**Comment by websanova** [comment]
your just assigning an object, no need about names:

https://github.com/websanova/vue-auth/blob/master/docs/Installation.md#install-2x

**Comment by mochafizIH** [comment]
Hi @websanova, I still confused on how to set response data from login response. 

Actually, I have implemented the custom authentication token, but I stuck on how to pass the data response and use it as "rolesVar"

my response is:
`{
    "success": true,
    "data": {
        "user-id": 60,
        "email-user": "mochaxxx@xxx.com",
        "mobile-phone": "+62816xxx",
        "roles": [
            {
                "id": 24,
                "name": "member"
            }
        ],
        "access-token": "f9f18fdc-8181-492d-89e9-7580b3fc64d4",
        "created-at": "2019-03-21T03:19:34"
    },
    "message": null
}`

on main.js:
`Vue.use(VueAuth, {
  auth: require('./plugin/modules/customAuth.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  authRedirect: {path: '/pages/login'},
  refreshData: true,
  rememberMe: true,
  tokenStore: ['cookie'],
  parseUserData: function (data) {
    console.log("ParseUserData");
    console.log(data);
    return data;
  },
  rolesVar: 'roles.name'
});`

on customAuth.js: 
`module.exports = {
  request: function (req, token) {
    this.options.http._setHeaders.call(this, req, {'access-token': token});
    // req.headers.set('access-token', token);
  },

  response: function (res) {
    let token = (res.data.data || {})['access-token'];
    return token;
  }
};`

on login script:
`this.$auth.login({
          data: t.userLogin, // Axios
          rememberMe: false,
          fetchUser: false,
          url: process.env.UMS_URL + '/v1/users/login',
          success(res) {
            t.isLoading = false;
          },
          error(err) {
            t.notifyVue('top', 'center', err.message);
            t.loading = false
          }
        })`


please help me with this. I have been stuck with this for a week.
