### ISSUE TITLE
hide link if user is not authorized to enter route

### ISSUE THREAD

**Issue by christianmalek** [websanova/vue-auth#218]
Is it possible to automatically hide a router-link if the user's not authorized to enter it?
I've already set the `meta.auth` data. So shouldn't it be possible to create this behaviour without appending an redundant `v-if="$auth.check(...)"` to every link-router?

**Comment by websanova** [comment]
I'm not sure if it's possible to tweak router link or if I would even want
to.

But I think the whole point of components is that you can write your own ;)

Just make a <router-link-my-special-wrapper>

**Comment by christianmalek** [comment]
I'll give it a try. Thanks for your fast answer. :)
