### ISSUE TITLE
unwanted redirect after login

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [websanova/vue-auth#223]
Hi,

I have a strange issue. After i try to login with wrong credentials on /anyotherpage i get redirected to /login. Doing the same on /login does not reload the page and works fine. As I cannot find any of my code doing this, i wanted to ask if this intended or if i need to look further in my code.
The user should stay on the same page and should get shown a error message.
The error() function gets executed, tho.

My setup:
```
Vue.use(VueAuth, {
  parseUserData: function (data) {
    return data
  },
  auth: require('./auth/symfony-jwt'),
  refreshData: {
    url: 'auth/refresh',
    method: 'POST',
    atInit: true
  },
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  fetchData: {
    url: 'users/me',
    method: 'PUT'
  },
  loginData: {
    fetchUser: true
  }
})
```

My login function:
```
this.$auth.login({
  url: 'login_check',
  body: this.login.data,
  rememberMe: this.login.rememberMe,
  redirect: false, // does not work
  success() {},
  error(res) {
    alert('hi i am an error') // this gets executed before the redirect
  }
})
```

Thank you in advance

**Comment by hurradieweltgehtunter** [comment]
I'm using 2.16.3-beta. My API is returning a http 401. Is your plugin reacting to status codes in any way?

**Comment by websanova** [comment]
Ah ok, I see, yes you would need to override the `_invalidToken` function in the auth driver.

Although not sure it should be a `401` returned with invalid credentials. I mean if you are trying to login then this is an "authorized" route so to speak. Probably it should return `400` for bad data?

**Comment by martosoler** [comment]
Actually, what the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) describes is:

> The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource. The client MAY repeat the request with a suitable Authorization header field (section 14.8). **If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials.** If the 401 response contains the same challenge as the prior response, and the user agent has already attempted authentication at least once, then the user SHOULD be presented the entity that was given in the response, since that entity might include relevant diagnostic information. HTTP access authentication is explained in "HTTP Authentication: Basic and Digest Access Authentication"

**Comment by websanova** [comment]
Hmm, you're right. Will take a look at your tonight, for now you can just
set the `_invalidToken` method to `false`.

So I'm.not really sure anything needs to be occuring here actually. 403
doesn't seem appropriate either. And any other catch all should likely just
be handled by the app.

**Comment by hurradieweltgehtunter** [comment]
where do I do that?
setting it in my login function
```
this.$auth.login({
  url: 'login_check',
  body: this.data.body,
  redirect: '/account/dashboard',
  _invalidToken: false,
  success() {},
  error(res) {}
})
```
has no effect same as setting it in the root config
```
Vue.use(VueAuth, {
  parseUserData: function (data) {
    return data
  },
  auth: require('./auth/symfony-jwt'),
  refreshData: {
    url: 'auth/refresh',
    method: 'POST',
    atInit: true
  },
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  fetchData: {
    url: 'users/me',
    method: 'PUT'
  },
  loginData: {
    fetchUser: true,
    _invalidToken: false
  },
  _invalidToken: false
})
```

**Comment by websanova** [comment]
It's a property on the driver.

So:

```
var http = require(....)...
http._invalidToken = false;
```

**Comment by hurradieweltgehtunter** [comment]
working. Thx alot. Will you keep this issue updated on any news regarding the http status codes?

**Comment by websanova** [comment]
Yes, I will take a look into this shortly.

**Comment by websanova** [comment]
Ok, I've updated this in `v2.16.4`. It's just an empty method now so you can remove any override you've made in the http drivers.

I will leave it up to the app for now to handle these as there are far too many possible ways this can be handled to add a default for now.

**Comment by hurradieweltgehtunter** [comment]
thx for clarifying.
