### ISSUE TITLE
Unable to get response data from Login method using Axios.

### ISSUE THREAD

**Issue by smtlk** [websanova/vue-auth#225]
Hi everyone, i'm using the Axios driver and i need to get specific data from the response i get to the Login method, namely validation information which comes from my backend

However in my `error()` hook, when i set a `response` parameter it seems to just be a string describing an exception

```
error: function (response) {
         console.log(response);
          this.showSnackbar("Unable to authenticate with the credentials given.")
}
```

dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise resolved (async)
request @ Axios.js:58
wrap @ bind.js:9
_http @ axios.1.x.js:46
__duckPunch @ auth.js:25
_loginPerform @ auth.js:232
__bindContext @ auth.js:31
Auth.login @ auth.js:568
(anonymous) @ Login.vue:88
Promise resolved (async)
handleFormSubmit @ Login.vue:85
boundFn @ vue.common.js:184
invoker @ vue.common.js:1816
Login.vue:97 Error: Request failed with status code 422
    at createError (createError.js:16)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
```

Is there a way for me to get the actual HTTP response instead of this? Thank you in advance for your help!

**Comment by smtlk** [comment]
*Figured it out*

In `axios.1.x.js` the promise is rejecting the actual error instead of the error response as some other libs do, `return Promise.reject(error);`

You can still get the response easily by just referencing the response of the error as follows.

```
error: function (error) {
    console.log(error.response);
}
```

**Comment by nkostadinov** [comment]
This is the same as my issue https://github.com/websanova/vue-auth/issues/206 . Most people expect console.log to output some kind of object so they are confused. May be it should be stated somewhere in the documentation.

**Comment by websanova** [comment]
It's in the FAQ, and aside from that, this is axios, nothing to do with
vue-auth

**Comment by nkostadinov** [comment]
Great that it is in the FAQ I obviously missed that. I know its axios but the people write issues here because they dont know an axios object is returned and just log it and see error message.
