### ISSUE TITLE
How to pass the payload for refreshData

### ISSUE THREAD

**Issue by abishekrsrikaanth** [websanova/vue-auth#226]
When defining the configuration for `refreshData` how do I go about defining the payload for the request?

**Comment by websanova** [comment]
Just as you would normally.

**Comment by abishekrsrikaanth** [comment]
@websanova not sure I understand, I don't see a way to override the payload on https://github.com/websanova/vue-auth/blob/master/docs/Options.md#refreshdata-url-authrefresh-method-get-enabled-true-interval-30

**Comment by websanova** [comment]
What are you trying to send there?

**Comment by websanova** [comment]
What are you trying to send there?

On Aug 23, 2017 13:07, "Abishek R Srikaanth" <notifications@github.com>
wrote:

@websanova <https://github.com/websanova> not sure I understand, I don't
see a way to override the payload on https://github.com/websanova/
vue-auth/blob/master/docs/Options.md#refreshdata-url-authrefresh-method-get-
enabled-true-interval-30

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/226#issuecomment-324222131>,
or mute the thread

**Comment by abishekrsrikaanth** [comment]
The `refreshData` currently sends the Bearer token to request for a refresh token, instead I wanted to send a token that is specific to `refresh` the token.

**Comment by websanova** [comment]
Ok, do you have two tokens? Seems like this should be a custom driver. Do
you send both tokens using the same header?

**Comment by abishekrsrikaanth** [comment]
If I am right, refreshToken is an oAuth standard. https://tools.ietf.org/html/rfc6749#section-1.5

**Comment by websanova** [comment]
Huh? I'm not sure about that. I would assume many login implementations use
a refresh token. It doesn't apply specifically for oAuth.

Plus if this whole issue has been related to oAuth then we're talking about
something a but  different as it's a third party authentication.

However, without knowing any details I would assume we are just trying to
get some token to the server? And this token is different than the
credential one?

**Comment by abishekrsrikaanth** [comment]
you could consider this a custom solution, but if there was a way to send custom payload for `refreshData` it would make sense for custom authentication.

**Comment by websanova** [comment]
I'm not sure, you still didn't give me any details about what you are tying to send there. This would help ;)

**Comment by abishekrsrikaanth** [comment]
with the initial authentication with the oAuth server, I receive an `access_token` and `refresh_token`. The `access_token` is used for all the endpoints, but to refresh my `access_token` upon expiry, I have to send the `refresh_token` to the `refresh` endpoint with the parameter `refresh_token`. Currently, I can configure the endpoint to call when refreshing the token, but not the payload. So the `refreshData` uses the access_token as the param and the value to the refresh endpoint which does not work with my implementation which is why I require to change the payload being sent to refresh the token. Please let me know if that clarifies.

**Comment by websanova** [comment]
Ok, and what does the payload look like when you receive the token s and
what does the request look like when you see them. An example of each.

**Comment by abishekrsrikaanth** [comment]
When you authenticate initially, the response is 

```
HTTP/1.1 200 OK
{
  "token_type": "Bearer",
  "expires_in": 315360000,
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbG...",
  "refresh_token": "ZFDPA1S7H8Wydjkjl+xt+hPGWTagX..."
}
```

Ther request to refresh the token happens to an endpoint `POST /oauth/refresh` and the request payload is

```
{
  "refresh_token": "ZFDPA1S7H8Wydjkjl+xt+hPGWTagX..."
}
```

**Comment by vitaoloureiro** [comment]
Facing same problem here, in the meanwhile I'm using a Refresh Token function

     refreshToken () {
        axios({
          method: 'post',
          url: '/auth/RefreshToken',
          data: { grant_type: 'refresh_token' },
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + localStorage.getItem('refresh_token')
          }
        })
          .then(response => {
            localStorage.setItem('default_auth_token', this.tokenData.access_token)
            localStorage.setItem('exp', this.tokenData.exp)
            localStorage.setItem('refresh_token', this.tokenData.refresh_token)
            location.reload() // reload window to avoid a 2nd call to /auth/user as vue-auth already do that (lol)
          }).catch((e) => {})

**Comment by abishekrsrikaanth** [comment]
@vitaoloureiro, how and where do you call this?

**Comment by vitaoloureiro** [comment]
Actually, I'm using a countdown, and when the timer is close to 1 minute to expire, a dialog shows a Refresh Button <button @onClick="refreshToken">Refresh Token</button>
But I'm sure there is a better option

**Comment by websanova** [comment]
This I'd case for a custom driver. Just look at the Authorization section
in the docs.

**Comment by vitaoloureiro** [comment]
Well, that's my custom driver

    auth: {
      request (req, token) {
        if (req.url.indexOf('refresh') !== -1) {
          this.options.http._setHeaders.call(this, req, {Authorization: `Bearer ${localStorage.getItem('refresh_token')}`})
        }
        this.options.http._setHeaders.call(this, req, {Authorization: `Bearer ${token}`})
      },
      response: function (res) {
        if (res.config.url.indexOf('refresh') !== -1) {
          localStorage.setItem('access_token', res.data.access_token)
          localStorage.setItem('refresh_token', res.data.refresh_token)
          localStorage.setItem('expires_in', res.data.expires_in)
        }
        return res.data.access_token
      }
    }

Need improvement, i know,  but it's working

**Comment by websanova** [comment]
Ahh, bit messy and doesn't follow the guide:

It's right there in example 2.

https://github.com/websanova/vue-auth/blob/master/docs/Authentication.md


You should follow the example otherwise you will have issues with other features like impersonate.

```
customAuth: {
     request: function (req, token) {
           token = token.split(';');
           token = req.url.indexOf('refresh') > -1 ? token[1] : token[0];

           this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer: ' + token});
    },
    response: function (res) {
        if (res.data.access_token && res.data.refresh_token && res.data.expires_in) {
            return res.data.access_token + ';' + res.data.refresh_token+ ';' + res.data.expires_in;
        }
    }
}
```

**Comment by vitaoloureiro** [comment]
Sorry, i'm just a rookie, but now i can see clearly what you did in example 2. Maybe you should add this one as Example 3.

**Comment by ishapkin** [comment]
I know that is too old, but for my backend (Symfony and JWT) the best solution was adding data inside interceptor for refresh url:

1. In custom bearer.js:

```javascript
module.exports = {
  request: function (req, token) {
    this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
  },
  response: function (res) {
    if(!res.data) {
      return;
    }
    let token = res.data.token;
    this.token('refresh_token', res.data.refresh_token);
    if (token) {
      return token;
    }
  }
};
```
2. In main.js

```javascript
Vue.axios.interceptors.request.use((config) => {
  if(config.url === 'token/refresh') {
    config.data = {...config.data, refresh_token: localStorage.getItem('refresh_token')}
  }
  return config;
});
```
