### ISSUE TITLE
Two cookies created after login

### ISSUE THREAD

**Issue by martosoler** [websanova/vue-auth#228]
Hi,

I was testing your solution to the issue [#214](https://github.com/websanova/vue-auth/issues/214) and found that the cookie was created twice, one has the correct domain and the other has the same domain but with a period in front.

![image](https://user-images.githubusercontent.com/651079/29667541-254faf0c-88b3-11e7-9400-c1eb9c37f2f3.png)

I'm not creating any cookie in my code so I guess the creation is taking place in some part of the library, maybe here:
```
function processToken(action, name, token) {
        var i, ii,
            args = [tokenName.call(this, name)];

        if (token) {
            args.push(token);
        }

        for (i = 0, ii = this.options.tokenStore.length; i < ii; i++) {
            if (this.options.tokenStore[i] === 'localStorage' && isLocalStorageSupported()) {
                return localStorage[action + 'Item'](args[0], args[1]);
            }

            else if (this.options.tokenStore[i] === 'cookie' && isCookieSupported()) {
                return __cookie[action].apply(this, args);
            }
        }
    }
```

Just for education purposes, why is the library trying to create a cookie if the browser should be doing that when receiving the response header SET-COOKIE?

I'm using the latest version of the library.

Let me know if you need something else from my side to help on this issue.

**Comment by websanova** [comment]
I'm not sure, I don't see this happening.

It gets the domain for the cookie from this method:

```
function _cookieDomain () {
    return window.location.hostname;
}
```

Also note you should not use the same token name for `default` and `other`.
