### ISSUE TITLE
Passport JWT

### ISSUE THREAD

**Issue by CoveTechnologyAus** [websanova/vue-auth#23]
Hi

I am looking at implementing vue-auth into an upcoming app and was wondering how I would make this work with a Passport (JWT) backed. The documentation is a little confusing on how I set the endpoints and receive back the token from Passport.

Does vue-auth just "auto-magically" handle all the Token handling?

Also, if I wanted to send the token along with a post request to a REST endpoint protected by Passport, how do I get access to the Token the I have already received from Passport (if vue-auth even works that way as I know it is a client only auth engine)

Thanks in advance.

**Comment by websanova** [comment]
Yes it should all work out of the box. Probably you just need to set the
end points for your api.

**Comment by CoveTechnologyAus** [comment]
@websanova , thanks for the response.
That is great news, I will try and just set to endpoint then.

The one final question I had though was getting access to the token so I can send it along with other REST api calls. How do I get access to the token that vue-auth is holding onto?
Because this will be client-server access, I am guessing vue-auth only secures the client side so I need the token to send along with other POST/GET calls to the api.

**Comment by websanova** [comment]
If you are using vue-resource it will do it automatically. If not you can
use token method to get the token.

**Comment by CoveTechnologyAus** [comment]
Magic! , thank you very much for your patience.
I am using vue-resource so that is going to be great.

Keep up the great work, I really like this component!

**Comment by websanova** [comment]
cheers.

**Comment by patrickbolle** [comment]
@CoveTechnologyAus  have you gotten this working yet?
