### ISSUE TITLE
Once you refresh the page, it will logout when using the loginOther method

### ISSUE THREAD

**Issue by nadelicious** [websanova/vue-auth#230]
I'm not sure if this is an issue or a feature.

**Comment by websanova** [comment]
What? No idea what you're trying to do here.

**Comment by nadelicious** [comment]
I'm using this method for login `this.$auth.loginOther()`  and it successfully logged in .. however when I refresh the page, it will be logged out.

**Comment by websanova** [comment]
Are you using auth ready?

**Comment by nadelicious** [comment]
I'm not using $auth.ready() in my template

**Comment by websanova** [comment]
Maybe take a look at the step by step guide and let me know if you're still having issues after.

https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md

**Comment by garhbod** [comment]
I've got the same issue but I'm not using loginOther(). If I have the developer tools open on chrome I don't need to login again on refresh but if I am on the site and refresh without developer tools open it redirects me to the authRedirect

**Comment by websanova** [comment]
Can you send me a fiddle or sample of that? Sounds a bit strange.

**Comment by garhbod** [comment]
I don't know how to create a fiddle without having an API to communicate with but I've created one with the essential/stripped down setup of my app with regards to Vue Auth

https://jsfiddle.net/3voam34y/1/

**Comment by garhbod** [comment]
I added a request and response intercepter to Axios and dumped the request/response in the html body so I could view it both with and without developer tools open. Here is a diffcheck to see what the differences are. The one on the left is without developer tools open and appears like it never makes the second request as there is no response logged.

https://www.diffchecker.com/R4m57r8v

**Comment by garhbod** [comment]
Am using Laravel for the backend and it is blacklisting the token for some reason. Will investigate further and let you know. Odd that one way works and the other gets blacklisted but I will let you know what I find

**Comment by nadelicious** [comment]
When I used loginOther() method I can do multiple login, but again once you refresh the browser it will be logged out.

**Comment by websanova** [comment]
Are you using the tymon/jwt-auth ?

Because they have a setting for this. Also depends what version of it you
are using as I think there have been quite a few changes if perhaps you are
upgrading from an older one.

**Comment by garhbod** [comment]
Thanks @websanova 
I am using tymondesigns/jwt-auth and was able to find what I needed to fix the issue I was having.

The solution is described here if anyone else is having the same problem with the same package
https://github.com/tymondesigns/jwt-auth/issues/983#issuecomment-327079639

**Comment by nadelicious** [comment]
@websanova yup I'm using the new one.

**Comment by garhbod** [comment]
Try `JWT_BLACKLIST_GRACE_PERIOD=30` in your `.env` @nadelicious 
Or change the default value in `jwt.php` config file

**Comment by garhbod** [comment]
Okay this only fixed the issue for 30 seconds for me delaying the inevitable `401 - Token has been black listed`

I now have two options as I see it.
1) make a custom refresh middleware or closure where the refresh is called once and simple refreshes the token but doesn't blacklist it straight away
2) refresh after or before every request

or is there a way for vue-auth to detect the 401 and refreshToken and retry the request

Thoughts?

**Comment by garhbod** [comment]
Okay I think I've worked out what the issue is.
Chrome is caching the response for the request to "auth/refresh" so the new token is never received on the front end and the old token is being invalidated because of the refresh request. Will post solution once I work out how to set that request route not to be cached

**Comment by garhbod** [comment]
Okay for those have the same issue I have with the `tymondesigns/jwt-auth` package here is my solution. I changed my refresh api endpoint from 
```
            $api->get('refresh', [ 'middleware' => 'jwt.refresh',
                function() {
                    return response()
                        ->json([ 'message' => 'Token refreshed!' ]);
                }
            ]);
```

to

```
            $api->get('refresh', [ 'middleware' => 'jwt.refresh',
                function() {
                    return response()
                        ->json([ 'message' => 'Token refreshed!' ])
                        ->header('Cache-Control', 'no-cache, no-store, must-revalidate');
                }
            ]);
```

This prevents the endpoint being cached by the browser which means that the new/refreshed token is always received.

Should the following header be added to the refresh request(not response) to try and limit this issue arising again when a backend isn't responding with the correct cache headers?

**Comment by websanova** [comment]
I'm not sure, I've never had issues with caching. But maybe because my
tokens are long lived.

And for catching the invalid token just out an interceptor. In my apps I
just funnel everything through the exception handler so I send back a
status code (like 401) and an error code like (AuthorizationFailed).

In my front end I have the same to pick up auth errors or things like
maintenance mode.

On the auth example, you could call refresh with a success callback before
calling "next" in the interceptor or redirect to login or whatever you need.

**Comment by garhbod** [comment]
I reverted my change to the backend(removed the extra headers that control cache) and added the following to the option to my `vue-auth` and it still works(no cached responses)
```
        refreshData: {
            url: 'auth/refresh',
            headers: {'Cache-Control': 'no-cache, no-store'},
            method: 'GET',
            enabled: true,
            interval: 30
        }
```
Are we able to add `headers: {'Cache-Control': 'no-cache, no-store'},` for the default `refreshData` or will that only work with the `axios` driver?

**Comment by websanova** [comment]
I have never had issues with caching on tokens personally. As for the headers, this of course depends on the driver, so I think for now I will just leave it be set in the options if someone needs it.
