### ISSUE TITLE
feature request Different route re-direct if no permission to access

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#234]
This feature should be simple to implement then again I am not 100% sure.  So currently we have routes like this

We have the meta field
```
meta: {auth: ['1','2']}
```

So if you don't have access fo that speicifc route you can add different access routes like payment is needed, your credit card has field so the new meta field would be this

```
meta: {auth: ['1','2'],errorroute:'trialexpire'}
```

This is just a suggesstion but I am sure there is better ways to do this.

**Comment by websanova** [comment]
Not really sure what you mean.

How the route know what the issue is?

I would assume this information would be in the user object or perhaps from an api call returning some error code.

**Comment by kyoukhana** [comment]
So we have 

```
meta: {auth: ['admin','user']}
```

If the user doesn't have the proper permissions you will be redirected to a specific route so hence the new field called errorroute whatever you decide the name.  So you can specifiy the route name that it will be redirected to if the user doesn't have the following permissions to access the route.  I know currenlty you have one for global if the user doesn't have the permissions to acccess a route it will go to a global redirect permission denied. 

This field will give the developer the option to redirect the route to another route other than the one specified globaly.

**Comment by websanova** [comment]
ah I see, ya that would be nice actually. But its' gonna require some
restructuring and backwards compatibility. I'll try to get it in over the
weekend.

**Comment by kyoukhana** [comment]
Thanks a million.  It would be a great feature to have.  I am sure you will you will have better ways of doing this as well.

**Comment by websanova** [comment]
Ok, this is in at version `2.17.0-beta`.

Check privilege docs for new format. It's also backwards compatible so you only need to modify routes where you need a custom redirect.

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md

Also check change log as there have been some other updates.

https://github.com/websanova/vue-auth/blob/master/docs/ChangeLog.md

**Comment by websanova** [comment]
FYI, I've added a callback feature for $auth.ready() method in v2.18.0-beta.
