### ISSUE TITLE
Improve documentation!

### ISSUE THREAD

**Issue by cristijora** [websanova/vue-auth#235]
This is good library overall and very handy if you want some complex authentication rules.
I was trying to help an intern integrate this library into an existing vue project which used an API with access token and refresh token. 
It took me 2-3 hours to implement everything and had to look several times in the source code, make some guesses around some parts and really fight finding the stuff that I needed in the docs.

Now imagine how long it would've taken for the non-experienced guy to implement this.
The docs should have some step by step examples and explain what vue-auth assumes by default (A token in headers) and what you have to do to override. 

Would be glad to help and contribute or at least start a guide/documentation.
More recently there are online editors such as https://codesandbox.io/s/vue where we could built full working examples with npm packages.

**Comment by websanova** [comment]
Well there is pretty big documentation section already.

If you have specific issues feel free to let me know where or submit a pull request.

**Comment by cristijora** [comment]
Had issues around the whole thing works.
How to send auth requests with custom post data
How to send refresh token requests with custom POST data instead of auth header.
When to override the auth token driver.
What vue-auth assumes by default ( api url, request type etc) for both auth and refresh token requests. 
What params do certain methods accept 
How are roles checked and what does vue-auth assume by default when checking for roles.

All these questions can be answered by playing around and debugging but the whole integration can be done faster if these things are presented in the docs.

**Comment by websanova** [comment]
Umm, have you seen the docs?

Right off the bat I can see majority of your questions would be answered
under Authentication, Privileges, Methods, and Options.

I mean the Methods section has a detail of exactly what you are asking for
in regards to what options are available for the methods.

https://github.com/websanova/vue-auth/blob/master/README.md

Maybe some more specific examples of what you got stuck on and couldn't
find would help.

**Comment by cristijora** [comment]
Ok. I will take it step by step.

- [Refresh data](https://github.com/websanova/vue-auth/blob/master/docs/Options.md#refreshdata-url-authrefresh-method-get-enabled-true-interval-30) 
has listed under defaults `{url: 'auth/refresh', method: 'GET', enabled: true, interval: 30}`, however it doesn't specify all possible keys. This also applies to loginData. 
In my case I needed to send custom POST data in order to refresh the token like so

```js
headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
},
data: querystring.stringify({
           client_id: '----',
           grant_type: 'refresh_token',
           refresh_token: localStorage.getItem('refresh_token')
 }),
```
- Methods from [https://github.com/websanova/vue-auth/blob/master/docs/Options.md#options] don't have any information about what parameters they can accept.
- [Step by step guide](https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md) uses both `import` and `require statements` which is not consistent. Although [Login method for axios](https://github.com/websanova/vue-auth/blob/master/docs/Methods.md#login) suggests that the data for the request should be placed inside `data`, in the [Guide](https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md#using-vue-auth) `body` is used.
- What do `success` and `error` functions from [Login method](https://github.com/websanova/vue-auth/blob/master/docs/Methods.md#login)  do have as parameters ? There is a statements at the beginning of methods that says 
> All success and error functions will receive proper context from currently called component.
Looking at the [Example](https://github.com/websanova/vue-auth/blob/master/demos/2.x/src/components/pages/Login.vue#L63) it's still not clear how is this context passed? Is it bound to `this` or there is a parameter for it?

**Comment by websanova** [comment]
You are overthinking it.

I try to mention it in the docs multiple times.

https://github.com/websanova/vue-auth/blob/master/docs/BeginnersGuide.md#http-driver
https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md#using-vue-auth
https://github.com/websanova/vue-auth/blob/master/docs/Faq.md#why-is-the-body-param-not-sending-my-data

The plugin is just an intermediary, it doesn't handle headers or any parameters like that. The object used in the methods just gets forwarded to whatever ajax library you are using. For instance vue-resource or axios.

For instance the `header` parameter you have there has nothing to do with vue auth. Same goes for success and error.

For the context... how about just do a `console.log(this)` and you will see right away what is there ;)

Same answer for the other options, it's just listing what ADDITIONAL options you can set related to auth plugin itself like "rememberMe" or "autoLogin", etc. Everything else is just forwarded to the ajax lib.

Otherwise for things like setting tokens you should really write a custom driver.

https://github.com/websanova/vue-auth/blob/master/docs/Authentication.md

**Comment by cristijora** [comment]
Well the thing is that it was not an issue for me to figure out this stuff and make it work. I'm trying to point out that it's pretty hard for someone with less experience to understand the plugin and to implement something based on it very easily. Anyway, we can skip this. I was willing to help and was trying to point some parts that can be improved. It seems that you are not opened too much towards such refinements :)

**Comment by websanova** [comment]
If you have suggestions about how to actually improve the docs, just submit
a pull request.

Seems to mme you just had a frustrating day and are taking it out on my
documentation ;)

**Comment by cristijora** [comment]
That's not true about frustrating day 😄 Will find some time to submit a PR

**Comment by Mohammad-Alavi** [comment]
Its 2019 and all the problems mentioned here is still in docs. it took me 2 whole days to figure out the docs and i still have some minor problems left. If you release something good for open source community please find some time to make a decent document for it.
