### ISSUE TITLE
Access Token disappear when I refresh the page

### ISSUE THREAD

**Issue by carlosnakazawa** [websanova/vue-auth#236]
I have a backend written in Grails, with [Spring Security Rest plugin](http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_delegating_authentication_to_oauth_providers). In frontend I implemented the OAuth using the vue-auth, using the following steps:

1. Login page calls a URL from backend and the backend redirects to Facebook or Linkedin;
1. After the user login in Facebook or Linkedin, the backend callback a URL from frontend with the access_token
1. I validate the access_token with a call from frontend to backend and the user enter into logged section

Inside the logged section, when I refresh the page (F5 key), the access_token simply disappers from local storage. I also tried with cookies, but have same problem.

This is the code after validate the access_token in backend:

```
this.$auth.refresh({
        params: {},
        success: function (res) {
          this.$auth.user(res.data)
          this.$auth.token(null, this.token)
          this.$auth.watch.authenticated = true
          this.$auth.watch.loaded = true
          this.$router.replace('/home')
        },
        error: function () {
          console.log('error')
        }
      })
```

I use the latest version (2.16.4-beta). Does anyone have any idea what I'm doing wrong?

**Comment by websanova** [comment]
Are you sure this.token is set to begin with?

**Comment by carlosnakazawa** [comment]
I have changed the call to $auth.login and the access_token don´t disappear now when I refresh the page. But I still need to set the user otherwise the roles are not set. 

```
this.$auth.login({
        params: {},
        success: function (res) {
          this.$auth.user(res.data)
        },
        error: function () {
          console.log('error')
        }
      })
```

In all pages I need put a call to refresh method to set the user and the roles. Can I change the code of refresh method?

**Comment by websanova** [comment]
Huh? HOw are you sending back your user? just in the raw `data`? You will
need to look at parseData function, check the docs.

**Comment by carlosnakazawa** [comment]
parseUserData method?
The return of login method is the following:

`{"username":"1529","roles":["ROLE_USER"],"token_type":"Bearer","access_token":"fkdlskfslçdkfsd","expires_in":3598,"email":"carlos@gmail.com","displayName":"Carlos Alberto Nakazawa"}`

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth/blob/master/src/auth.js#L143

But probably you should put your user data separately in a "data" field.
And for that matter the token in  header.

**Comment by carlosnakazawa** [comment]
I've implement the parseUserData method and I can discard set user in login method:

```
parseUserData (response) {
    return response
  }
```

I still need call in any page for the following reasons:

1. Set the roles in the user
1. Call logout method if the response for the refresh method is 401.

```
this.$auth.refresh({
      params: {},
      success: function (res) {
        this.$auth.user(res.data)
      },
      error: function (res) {
        if (res.status === 401) {
          this.$auth.logout({
            makeRequest: false,
            success () {
              this.$router.replace('/login')
            },
            error () {
              console.log('error ' + this.context)
            }
          })
        }
      }
    })
```

**Comment by websanova** [comment]
The roles? On the routes you mean?

Really I'm not sure why you're using `$auth.refresh` this way. Seems all this functionality you are trying to achieve is already built in by default.

Just add an interceptor for the 401 check and call `Vue.auth.logout()` in there. The rest should work out of the box if you just use `$auth.login()`.

**Comment by carlosnakazawa** [comment]
Do you have some example to implement an interceptor that call logout?

**Comment by websanova** [comment]
How about you just check docs for vue router or axios or whatever library
you're using. How I can know what library or version you are using?

You just need to call Vue.auth.logout()
