### ISSUE TITLE
Instructions to use in Quasar Framework

### ISSUE THREAD

**Issue by manelclos** [websanova/vue-auth#237]
I tried to use vue-auth with Quasar Framework, but I did not succeeded. Can anyone provide pointers or documentation about how it should work?

**Comment by websanova** [comment]
Did you ask Quasar Framework guys?

**Comment by manelclos** [comment]
I thought into asking here first, as this seems closely related to vue-auth supporting Quasar, but you can see it the other way around. Will do.

**Comment by websanova** [comment]
I'm all for it if someone wants to take the lead.

**Comment by dhax** [comment]
what exactly seems to be your problem using it within quasar? I don't see any difference regarding usage as quasar basically only adds to the visual part of a standard vue app by providing components.
If you can be more specific about your problem I am happy to help.

**Comment by onurkose** [comment]
Well, you can find an implementation [on this fork](https://github.com/onurkose/vue-auth) but if you want to use vue-auth with Laravel Passport, not JWT Auth.

> If you want to use with JWT Auth specifically take a look at drivers/axios.1.x.js and nevermind the rest of the forked code. The only difference in the axios driver from the original code is all **this.options.Vue.axios** usages replaced with **this.options.Vue.prototype.$axios**

To create the plugin type on your terminal:
`quasar new plugin auth`

Then find the auth.js created in the src/plugins of your app. Nothing to import or require here outside of the export default function. Just import your vue-auth installation code like this:

`
export default ({ app, router, Vue }) => {
  Vue.router = router
  Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/laravel-passport-bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),

    authRedirect: 'auth/login',

    passportData: {
      client_id: laravel passport client id in Int,
      client_secret: 'laravel passport cilent secret in String'
    }
  })
}

`

Of course those bearer/axios drivers and passportData variable are specific to my fork (and Laravel Passport). But you can change them all with the original code of @websanova if you prefer to use with JWT Auth.
