### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by MacgyverMartins** [websanova/vue-auth#238]
I see that have a lot of issues like this, but I look through all those issues and I can't fix my problem.
And my app build, I see this error on Chrome Console
`auth.js?9c12:505 Uncaught TypeError: Cannot read property 'call' of undefined`

I use Vue-cli to generate a app boilerplate, so this is my `main.js`:

<img width="737" alt="screen shot 2017-09-01 at 11 37 23" src="https://user-images.githubusercontent.com/4551671/29977249-b58d12aa-8f0a-11e7-8288-635f9e4d944d.png">

And my `App.vue` had this template:

<img width="639" alt="screen shot 2017-09-01 at 11 38 29" src="https://user-images.githubusercontent.com/4551671/29977285-e69d7e48-8f0a-11e7-9a60-7591def39128.png">

Does anyone know why this is happening and how to fix that?
I am using `@websanova/vue-auth@2.16.4-beta`

## UPDATE
Even if I put `Vue.router = router` on 14 line at `main.js`, this still not working

**Comment by websanova** [comment]
Well Vue.router needs to be set for sure. Is it different error when you do that?

**Comment by MacgyverMartins** [comment]
@websanova no. I got the same error.

**Comment by websanova** [comment]
Looks fine, what's in your app.vue?

**Comment by websanova** [comment]
I mean if you comment out router view.

**Comment by MacgyverMartins** [comment]
This is my app.vue

```
<template>
  <div>
    <div v-if="$auth.ready()">
      <router-view></router-view>
    </div>

    <div v-if="!$auth.ready()">
      Loading ...
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
};
</script>

<style lang="scss">
</style>
```

**Comment by websanova** [comment]
Strange, maybe try removing your node modules folder and reinstall

**Comment by MacgyverMartins** [comment]
It didn't work too :(

**Comment by websanova** [comment]
Of you take out the router-view, just put some.dummy text, make sure it's not something else.

Also do you have more error output? Which variable is not defined?

**Comment by Imboga** [comment]
I was facing the same issue until I realized that this error came with version `"@websanova/vue-auth": "^2.21.15-beta",`
So I just downgraded to `"@websanova/vue-auth": "^2.21.14-beta",` and everything worked fine.
FYI, the catch error does not stop to plugin working as usual
