### ISSUE TITLE
laravel-echo integration

### ISSUE THREAD

**Issue by nikolaynesov** [websanova/vue-auth#239]
Is there any way to integrate it with laravel-echo correctly? Did not find anything in docs.

**Comment by websanova** [comment]
Not sure, i have not tried Laravel echo. I suppose a token just need to be
sent?

**Comment by nikolaynesov** [comment]
Yes, but the interceptor does not effect on `laravel-echo` request (token is not added) to authorize the private channel. But for other requests token is applied.
I am using `vue-resource`, that is supported by `laravel-echo`.

**Comment by websanova** [comment]
You have single page app with API or just static page?

**Comment by nikolaynesov** [comment]
@websanova I have SPA. So what I need to do first - get an authorised user with token with vue-auth. Then if I have the user, I need to pass the token to laravel echo, but we usually init echo globally in bootstrap file. How about to watch for the token and assign it to laravel-echo dynamically?

**Comment by nikolaynesov** [comment]
@websanova I found this: 
https://github.com/laravel/echo/issues/26#issuecomment-248178873
But it did not work for me.  Also, changing token dynamically for `laravel-echo` didn't work (it is not sending the auth header).

`
watch: {

        token(val) {

            Echo.config.auth.headers['Authorization'] = 'Bearer '+val;
            Echo.connector.pusher.config.auth.headers['Authorization'] = 'Bearer '+val;


        }

    }

`

**Comment by websanova** [comment]
Ok, but your user needs to login first?

**Comment by nikolaynesov** [comment]
@websanova yes, I can check if user is logged in or token is not null in watcher. But the problem is that setting the header on fly does not work for laravel-echo... Still searching for a way to make it work.

**Comment by nikolaynesov** [comment]
Ok, I managed to get over it. But it's better to see some better native solution from `vue-auth` if possible. Closing the issue. I hope it will help somebody.

```
new Vue({

    el: '#reactive',
    router,
    store,
    mounted() {
        // Set up $auth.ready with other arbitrary loaders (ex: language file).
        setTimeout(() => {
            this.loaded = true;
        }, 500);

    },

    watch: {

        isAuthenticated() {

            if (this.$auth.check()) {

                Echo.connector.pusher.config.auth.headers['Authorization'] = 'Bearer ' + this.$auth.token();

            }

        }

    },

    computed: {

        isAuthenticated() {

            return this.$auth.check();

        },

    }

});

```

**Comment by websanova** [comment]
Did you follow the guidelines on using auth.ready?

https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md#checking-for-the-ready-state

On Sep 5, 2017 02:17, "Nikolay" <notifications@github.com> wrote:

Ok, I managed to get over it. But it's better to see some better native
solution from vue-auth if possible. Closing the issue. I hope it will help
somebody.

new Vue({

    el: '#reactive',
    router,
    store,
    mounted() {
        // Set up $auth.ready with other arbitrary loaders (ex: language file).
        setTimeout(() => {
            this.loaded = true;
        }, 500);

    },

    watch: {

        isAuthenticated() {

            if (this.$auth.check()) {


Echo.connector.pusher.config.auth.headers['Authorization'] = 'Bearer '
+ this.$auth.token();

            }

        }

    },

    computed: {

        isAuthenticated() {

            return this.$auth.check();

        },

    }

});


—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/239#issuecomment-327011132>,
or mute the thread

**Comment by nikolaynesov** [comment]
@websanova Yes, I think so. Do you think we can improve my solution some how?

**Comment by websanova** [comment]
So actually you need auth.ready() check.

Not sure how you are doing this echo, is it another plugin or inside a
component?

Because if it's in a component then you should wrap that component with
$auth.ready() check.

**Comment by nikolaynesov** [comment]
@websanova https://github.com/laravel/echo
http://laravel.com/docs/broadcasting

Yes, I see what do you mean with `auth.ready()` but it does not guarantee that the token will be there. But watching `this.$auth.check()` makes it work. Additional check for value to be true can be added to the "isAuthenticated" watcher.

**Comment by pSchaub** [comment]
Will this also work if the token is updated through a token refresh?

**Comment by vesper8** [comment]
@nikolaynesov first of all thank you very much for sharing your solution. it does work for me and I was having the exact same issue.. thank god I didn't have to waste several more hours getting it to work!

I was wondering if you've had a chance to improve on your code and the strategy you use to set this up? If so could you share how you're doing it today? I don't really like having to add these additional watchers and computed properties to my main vue initialization.. and I'm also concerned that this will break if the token is refreshed.

**Comment by websanova** [comment]
Well, if you have some suggestions I'm all years. Otherwise not sure why you would have issues with one extra computed property or watcher.

**Comment by gileneusz** [comment]
@websanova 
on `Echo.connector.pusher.config.auth.headers['Authorization'] = 'Bearer ' + this.$auth.token();`
I've got: 

> [Vue warn]: Error in callback for watcher "isAuthenticated": "TypeError: Cannot read property 'pusher' of undefined"
