### ISSUE TITLE
Vue router get $auth object

### ISSUE THREAD

**Issue by akaNightmare** [websanova/vue-auth#240]
Hello I have beforeRouter hook and I want get $auth object
```
router.beforeEach((to, from, next) => {
   // todo: get auth
})
```

**Comment by websanova** [comment]
Did you try Vue.auth ?

**Comment by akaNightmare** [comment]
@websanova `undefined`

**Comment by akaNightmare** [comment]
@websanova `Vue.prototype.$auth` - working, so if it's ok for you, I can close the task

**Comment by websanova** [comment]
Are you trying to set it before installing the plugin? Or do you have old
version?

**Comment by websanova** [comment]
If you have no other issues here then sure

**Comment by icangku** [comment]
doesnt work
