### ISSUE TITLE
Refresh token. Double refresh.

### ISSUE THREAD

**Issue by nikolaynesov** [websanova/vue-auth#242]
Hi, 

Spent a lot of time time trying to fix this with no result. 

To reproduce:
1. Log in
2. Go to protected route page
3. Reload the page 

Results:
1. Redirects to Login page 
2. Creates token request twice one by one
3. Fetches user data with token got from 1st refresh

Expected:
1. Open the same page before page reload, no redirects

At the same time: user is fetched successfully, check() function returns true, loaded/ready is used like in docs. When reloading page (route) with `meta: {auth: undefined}` it just tries to refresh token twice but does not redirect to login page. When I disable token refresh it works fine, but I need this refresh token feature enabled.

Setup info:

package.json
```
"@websanova/vue-auth": "^2.16.4-beta"
"vue-router": "^2.0.1",
```

app.js
```
var reactive = require('./components/reactive.vue');
reactive['router'] = router;
reactive['store']  = store;

new Vue(reactive).$mount('#reactive');
```

reactive.vue
```
<script>

 import mixinAuthReady from './mixins/auth-ready';
 import navMain from './partials/nav-main.vue';
 import pageSpinner from './partials/page-spinner.vue';

 export default {

  mixins: [ mixinAuthReady ],

  components: { navMain, pageSpinner }

}

</script>

<template>

  <div>

    <page-spinner :busy="!authReadyLoaded"></page-spinner>

    <div v-if="authReadyLoaded">

      <nav-main></nav-main>

      <router-view></router-view>

    </div>

  </div>

</template>
```

auth-ready mixin:
```
export default {

    data() {

        return {

            loaded: false

        }

    },

    mounted() {

        setTimeout(()=>{

            this.loaded = true;

        }, 500);

    },

    computed : {

        authReadyLoaded() {

            return (this.loaded && this.$auth.ready());

        }

    }

}
```

The refresh server Response Headers:
```
authorization:Bearer BLABLABLATOKENISHERE
cache-control:no-cache
content-type:application/json
date:Wed, 06 Sep 2017 13:14:24 GMT
phpdebugbar-id:41f48f2049628224ec766c0dd3a13c41
server:nginx/1.11.5
status:200
x-ratelimit-limit:60
x-ratelimit-remaining:59
```

Fetch user json from server response:
`{"data":{"name"...`

**Comment by websanova** [comment]
I think you are not using auth.ready correctly

**Comment by nikolaynesov** [comment]
Can that happen because I use `this.$auth` in computed methods for main Vue component?

**Comment by nikolaynesov** [comment]
Looks like it runs routerBeforeEach Guard several times for each route ... I registered a separate `vue-router` hook to test if it's a `vue-router` issue, but it works fine and gets called only once per route...
```
router.beforeEach((to, from, next) => {

    console.log("==============");
    console.log('global beforeEach Guard ');
    console.log(to);
    console.log(from);
    console.log("==============");

    next();

})
```

**Comment by websanova** [comment]
Well, yes, it's gonna `beforeEach` any time your route changes. 

As far you getting logged out, no idea, maybe the token is a dud or some other issue there.

For the multiple requests, what method are they, is one of them OPTIONS request?
