### ISSUE TITLE
Vuex auth sync?

### ISSUE THREAD

**Issue by etune** [websanova/vue-auth#244]
Has anyone synced their auth user data with a vuex store? It would be cool if it were was as easy as [vuex-router-sync](https://github.com/vuejs/vuex-router-sync). Having time-travel debugging would be helpful with auth development and debugging.

**Comment by websanova** [comment]
Well it's just a binded property and you can fetch the user object with `$auth.user()`. I would assume can set it as any other binded property in vuex.

Or you can just call `$auth.fetch()` if you need an updated user or call `$auth.user(obj)` to update the user directly.

**Comment by etune** [comment]
I just realized that i can pass in a callback function when I call `fetch()`. I'll update my store with that. Thanks
