### ISSUE TITLE
How to make a request to the server without changing the path

### ISSUE THREAD

**Issue by newbie78** [websanova/vue-auth#245]
Hello everyone!

There is a large form on one of the pages. During the interaction with the user, I need to make several requests to the server api. In the settings of the router these paths are not specified.
I use the vue-resource as the http driver.
How to do this with vue-auth?

**Comment by websanova** [comment]
Don't understand what you are trying to do here.

If you are just sending requests to your api the only thing coming from vue-auth is the auth method, defining how the token information is attached.

**Comment by newbie78** [comment]
I just need to make a request to the server api
directly specifying the path part. Do not specify it in the settings of the router. for it there is no separate vue-component. But in such a way that the current jwt-token is present in the request.

I'm new to node.js-vue.js. if you can short some example. thanks!

**Comment by websanova** [comment]
lol, I still don't really have an idea what you're asking or how it's related to vue-auth.

I think maybe more question with vue-resource here?

If you are just trying to make a request to the api then you can set the `Vue.http.options.root` and when making relative path calls make sure you don't set a leading slash.

```
this.$http.get('some/path')
```

Or if you are making a request to a different end poing you can always set the full path:

```
this.$http.get('https://someotherdomain.com/path');
```

But you're probably better off checking the vue-resource docs.
