### ISSUE TITLE
could i set the authenticator into the request body , any example ?

### ISSUE THREAD

**Issue by prettyyjnic** [websanova/vue-auth#247]
by default authenticator is set to the request header,
could i set the authenticator into the request body ?
could you give me a example ? thanks

**Comment by websanova** [comment]
did you check the docs at all???

**Comment by prettyyjnic** [comment]
i fix it by using this, but i have no idea it is the best way or not
```
request: function (req, token) {
      req.params.Authorization = token
      this.options.http._setHeaders.call(this, req)
},
```
