### ISSUE TITLE
Login POST missing body data

### ISSUE THREAD

**Issue by kahwooi** [websanova/vue-auth#25]
I post email, and password, but when I debug the body, it only has password data:

```
context.$auth.login({
        body: {
            email: creds.email,
            password: creds.password
        },
```

**Comment by websanova** [comment]
Debug it where? On the api side?

Is it empty or not set?

**Comment by kahwooi** [comment]
Using a Telerik web debugger. It is not set, only password is set.

**Comment by websanova** [comment]
Ok, so can we double check if it's getting set at all....

**Comment by kahwooi** [comment]
My mistake, I pass in undefined. It is working correctly now.
