### ISSUE TITLE
Nested routes, roles and forbiddenRedirect

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [websanova/vue-auth#252]
Hi there.

I came across a problem which I cannot solve on my own although searching through everything.
I have a nested routes config:
```
{
  path: '/account',
  component: require('../views/user/_abstract.vue'),
  meta: {
    name: 'user'
  },
  children: [
    {
      name: 'user',
      path: 'dashboard',
      component: require('../views/user/dashboard.vue')
    },
    {
      path: 'profile',
      component: require('../views/user/profile.vue'),
      children: [
        {
          name: 'user-profile-general',
          path: 'general',
          component: require('../views/user/Profile/General.vue')
        },
        {
          name: 'user-organization',
          path: 'organization',
          component: require('../views/user/Profile/Organization.vue'),
          meta: {
            loading: false,
            auth: {
              roles: 'ROLE_ORGANIZATION_ADMIN',
              forbiddenRedirect: '/account/profile/general'
            }
          }
        }
      ]
    }
  ]
}
```

My user roles are :
```
roles:"ROLE_PUBLISHER"
```

With this config I can access /account/profile/organization, which should be forbidden because of the missing ROLE_ORGANIZATION_ADMIN role.
When I'm changing the user-organization-route config to 
```
{
  name: 'user-organization',
  path: 'organization',
  component: require('../views/user/Profile/Organization.vue'),
  meta: {
    loading: false,
    auth: 'ROLE_ORGANIZATION_ADMIN'
  }
}
```
i get redirected to /403 - which is correct. But I want to define a route specific forbidden-redirect, not use the global one.

What am I doing wrong? 
Any help is greatly appreciated and will boost your karma 100 points!

**Comment by websanova** [comment]
What version are you using?

**Comment by hurradieweltgehtunter** [comment]
Thanks to your comment I upgraded from 2.16.1-beta to 2.18.1-beta. This did the trick, working now.
Thanks for your quick response.
