### ISSUE TITLE
Uglify errors

### ISSUE THREAD

**Issue by tho068** [websanova/vue-auth#255]
ERROR in static/js/vendor.d563c85c6b315b0467cd.js from UglifyJs
Unexpected token: punc (() [./~/@websanova/vue-auth/src/auth.js:502,0][static/js/vendor.d563c85c6b315b0467cd.js:3021,22]

Only fix I found is to revert to an older version.

**Comment by tho068** [comment]
This happens when using the vue-cli webpack setup

**Comment by wptad** [comment]
@tho068 I have the some problem too.
I fix it by using older version of vue-auth.
```
npm install @websanova/vue-auth@v2.16.4-beta 
```

**Comment by websanova** [comment]
Bit busy this week, will look into this later, or just submit a pull
request.

**Comment by websanova** [comment]
Should be ok now in `v2.18.3-beta`.

**Comment by tho068** [comment]
Thanks for looking in to it. Will test when i am back at work on monday.

Sendt fra min iPhone

30. sep. 2017 kl. 06:42 skrev Rob <notifications@github.com<mailto:notifications@github.com>>:


Closed #255<https://github.com/websanova/vue-auth/issues/255>.

-
