### ISSUE TITLE
[LOGIN] Manual Login

### ISSUE THREAD

**Issue by caminhounico** [websanova/vue-auth#256]
I want login user after a API response, without call $auth.login().
My API return Token (in header) and user object.

```
this.$auth.watch.authenticated = true
this.$auth.watch.loaded = true      
this.$user(response.user)
this.$router.push('/dashboard')
```

The user is perfect redirect as expected. But when this page is reloaded, vue not fetch user and redirect back from the login route.

I need help please.

**Comment by websanova** [comment]
Well yes, you would need to call $auth.refresh manually as well.

**Comment by caminhounico** [comment]
Tanks @websanova.

I discovered the problem. 
It's required set the rememberMe cookie.  

```
this.$auth.watch.authenticated = true
this.$auth.watch.loaded = true      
this.$user(response.user)
this.$router.push('/dashboard')
document.cookie='rememberMe=false' 

```
works fine! It's could be a method of this plugin. What you think?
