### ISSUE TITLE
OAuth flow

### ISSUE THREAD

**Issue by alxppp** [websanova/vue-auth#257]
Is it possible to configure vue-auth's OAuth flow similar to ng-token-auth's? Essentially having the first request go the the API server instead of the third party?

![](https://raw.githubusercontent.com/lynndylanhurley/ng-token-auth/master/test/app/images/flow/omniauth-flow.jpg)

**Comment by websanova** [comment]
Your API, is just providing the login page url?

**Comment by alxppp** [comment]
Yes, I'm using devise_token_auth - it provides two endpoints:
<img width="1075" alt="screen shot 2017-09-26 at 10 59 24" src="https://user-images.githubusercontent.com/4237216/30851761-da78b3c8-a2a9-11e7-89de-acab856bdd71.png">
The first one is the first request to the API endpoint (passthru), the second one the third party callback

**Comment by websanova** [comment]
Right, so just call oaut2 with that url after you receive the token from
3rd party.

**Comment by alxppp** [comment]
You mean calling "/api/v1/auth/google_oauth2/callback" from vue-auth using the .oauth2() method?

I get an `Uncaught TypeError: Cannot read property 'params' of undefined` when doing that

**Comment by websanova** [comment]
Try without the forward slash or the full url.

**Comment by alxppp** [comment]
In the last step in the upper graphic I get the auth token passed into the frontend through a param. Basically, the backend redirects to the frontend with the following params (**token, client_id, expiry, and uid**). E.g.:

`https://frontend.website.com/auth/login?auth_token=lYm_Xj8u3c9yLBsFGx_V7A&client_id=UlA2fibUJerAbpAsWrixND&expiry=1507887302&uid=email%40website.com`

How do I store the received token in vue-auth and set the vue-auth state to logged-in?

Thanks for your help!

**Comment by websanova** [comment]
Seems you need custom driver maybe.

**Comment by websanova** [comment]
By the way, when you are making a call typically the forward slash is not included or you need to put the full url.

`api/v1/auth/google_oauth2/callback` instead of `/api/v1/auth/google_oauth2/callback`.

**Comment by alxppp** [comment]
A custom driver for Oauth with devise_token_auth solved it for me:

```
export default {
  tokens: ['Token-Type', 'Access-Token', 'Client', 'Uid', 'Expiry',
    'token-type', 'access-token', 'client', 'uid', 'expiry'],

  request(req, token) {
    const headers = {};
    const tokens = token.split(';');

    const auth = this.options.deviseAuth || this.options.auth;
    auth.tokens.forEach((tokenName, index) => {
      if (tokens[index]) {
        headers[tokenName] = tokens[index];
      }
    });

    this.options.http._setHeaders.call(this, req, headers);
  },

  response(res) {
    const token = [];
    const headers = this.options.http._getHeaders.call(this, res);

    if (headers['access-token'] || headers['Access-Token']) {
      const auth = this.options.deviseAuth || this.options.auth;
      auth.tokens.forEach((tokenName) => {
        if (headers[tokenName]) {
          token.push(headers[tokenName]);
        }
      });

      return token.join(';');
    }

    return '';
  },

  redirectToOauth2(provider) {
    let url;
    url = `${Vue.$http.options.root}/auth/${provider}`;
    url += `?omniauth_window_type=${'sameWindow'}`;
    url += `&auth_origin_url=${encodeURIComponent(window.location.origin +
      Vue.$router.resolve({ name: 'login-oauth2-callback', params: { type: provider } }).href)}`;
    url += '&resource_class=User';

    window.location.href = url;
  },

  resolveOauth2Callback(auth, route, successCallback) {
    if (route.query['auth_token']) {
      auth.token('token-type', route.query['token-type']);
      auth.token('access-token', route.query['auth_token']);
      auth.token('client', route.query['client_id']);
      auth.token('uid', route.query['uid']);
      auth.token('expiry', route.query['expiry']);

      auth.watch.authenticated = true;
      auth.watch.loaded = true;

      auth.fetch({
        success() {
          if (successCallback && (typeof successCallback === 'function')) {
            successCallback();
          }
        },
      });
    }
  },
};
```
