### ISSUE TITLE
Login callback

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [websanova/vue-auth#258]
Hi,

is there any possibility to globally call a function after every successful login?
Like
```
Vue.use(VueAuth, {
  loginData: {
    fetchUser: true,
    callback: () => {
      // do stuff
    }
  }
})

I don't want to do this in this.$auth.login({}).success() because i have multiple places where users can log in and I want one global callback call.

**Comment by websanova** [comment]
Well, you should probably use events for this. I'm sure there are many
plugin for it.

I have one called websanova/vue-act as well.

**Comment by hurradieweltgehtunter** [comment]
Where do I emit the event?
- user logs in -> emit event
- user refreshes the page/returns on page and is still logged in (/refresh gets called) -> where to emit the event?

**Comment by websanova** [comment]
Well refresh is not a login.

But you could do it in auth.ready callback

**Comment by hurradieweltgehtunter** [comment]
This was the point i missed.
Thank you for helping out!
