### ISSUE TITLE
how to use rememberMe option?

### ISSUE THREAD

**Issue by elvisyang2016** [websanova/vue-auth#260]
there is a parameter rememberMe with login API.
If rememeberMe is set, it will be saved in cookie. Without username and password saved, how it works, how to re-auto login?

**Comment by websanova** [comment]
It just uses the token saved if it's there.

**Comment by elvisyang2016** [comment]
Get it. and the token is saved in localstorage, right?

**Comment by websanova** [comment]
Yes, but you shouldn't have to mess with anything directly.

**Comment by faistoiplaisir** [comment]
Hi,

I don't understand how that "rememberMe" options should work. I don't see any differences when I login with it or not.

I saw that there's a way to specify a cookieDomain for that, but same, I don't understand what is the goal.

If I set the rememberMe to true or not, I have the same behaviour:
 - A browser refresh send a "refresh token" request. If the token is expired, I receive a 401 error, my interceptor call logout(), and I'm logout(). 
 - For each request, as soon a 401 error is returned, the interceptor do a logout(), and I'm redirected to the login page.

So what is the goal exactly to set this option to true or false ?

Note: I'm using vue-resource, not axios.

In all case, thanks you for your work !

**Comment by websanova** [comment]
The remember me is just for keeping your token stored if you close your
browser. Of you are getting a 401 this is unrelated issue. Can you verify
if a too is being sent when you get the 401?

If so it's just some issue there.

**Comment by faistoiplaisir** [comment]
Ok ! I didn't realize that ... So, yes, it works fine, if I set "rememberMe" to false, the token is deleted when I close the browser. 

Maybe you can add that information in your documentation. Something like "if the rememberMe is set to false, the token will be deleted from local storage when the user close its browser. If set to true, the token will be kept in the local storage and a refresh will occurs on the next app boot". <=== It's the current behaviour, I'm right ?

About your question, "Can you verify if a too is being sent when you get the 401?", I'm not sure to understand what you want me to check. When the server send back a 401 request (when the token has expired), my interceptor do a logout().

Thanks for the clarification.

**Comment by faistoiplaisir** [comment]
I don't understand why, but actually, It works in my Firefox and not in Chrome. On Chrome, the token isn't deleted when I close the browser (with rememberMe set to false). Do you have an idea ? Maybe it's due to an extension I have ?

**Comment by websanova** [comment]
I will take a look at this, seems other people are reporting an issue here as well.

**Comment by stefanvanherwijnen** [comment]
Shouldn't the token be stored in sessionStorage if rememberMe is set to false? I believe localStorage is retained when the browser is closed, so if the token is always stored in localStorage then the value of rememberMe won't have any influence.

In the latest Firefox the token is still stored after a browser restart when rememberMe is set to false.

**Comment by websanova** [comment]
Hello, I know this is old thread, but there has been a release of version 3 with changes and fixes for how remember works. Please check the [Remember Me Vs. Stay Signed In Usage](https://websanova.com/docs/vue-auth/recipes/remember-me-vs-stay-signed-in) for more details.
