### ISSUE TITLE
Handle error on token refresh

### ISSUE THREAD

**Issue by AhmedAtef07** [websanova/vue-auth#262]
On refreshing the token only success response is being handled and no block for an `error`, is that on purpose? Or we are missing a error handler in this block:
https://github.com/websanova/vue-auth/blob/master/src/auth.js#L73-L77

### How to reproduce the problem the easy way
1- You can sign in normally and make sure you got the token saved.
2- Using chrome tools, get into the application tab, and damage the token by adding any characters in the access token. (Which is the same as the token was changed from the server side.)
3- Make any request now, and you will see a 401 printed in the console with no actions taken from $auth side. 

### Suggested fix
```
  if (this.options.refreshData.enabled && this.options.tokenExpired.call(this)) {
            this.options.refreshPerform.call(this, {
                success: function () {
                    this.options.checkAuthenticated.call(_this, cb);
                },
                error: function () {
                    // This needs to be handled
                    // Either by calling a different call back
                    // Or logout right away, to redirect to the redirect route
                    // and remove the token (which just gave an error)
                    // Logout using _this.logout({ makeRequest: false })
                }
            });

            return;
        }
```

The solution above fixes my problem, but my concern is, will it break anything? Or is this is the proper place to handle such thing?

**Comment by websanova** [comment]
are you actually using $auth.refresh() ? or some other method?

**Comment by AhmedAtef07** [comment]
On App loading, sometimes the token would be expired from the server side. What is expected that $auth should redirect us to the login page, but this doesn't happen, and we are left with a 401 error in the console.

![image](https://user-images.githubusercontent.com/4195363/30966090-f8b4084c-a457-11e7-9538-080019a4cd1f.png)

**Comment by websanova** [comment]
Just put your own interceptor.

**Comment by dbursztyn** [comment]
Having the same issue. It could be useful to be able to configure the behavior on refresh token error.

**Comment by websanova** [comment]
Just put an interceptor.

There is not really any standard default. I actually had one before to redirect but I got even more issues coming through because it was not doing or checking what someone wanted.

```
Vue.http.interceptors.push(function(request, next) {
        next(function (res) {

            // Unauthorized Access
            
            if (
                res.status === 401 &&
                ['UnauthorizedAccess', 'InvliadToken'].indexOf(res.data.code) > -1
            ) {
                Vue.auth.logout({
                    redirect: {name: 'auth-login'}
                });
            }
            
            // System Error

            else if (res.status === 500) {
                // Redirect to 500 page
            }
        });
    });
```
