### ISSUE TITLE
this.$auth is undefined when reseting init data component

### ISSUE THREAD

**Issue by dianjuar** [websanova/vue-auth#263]
Hi.
On my vue data component I have a complex object... One of its properties values contains part of the $auth element

```js
...,
digitalCode: {
  receipentNumber: this.$auth.user().phone,
  isRequired: false // NEW
},
...
```

I bind the `receipentNumber` property to an input, so by default is the phone number of the user but he can change it before make the submit...

When the user make the submit, I reset the complex object to its default value with line of code `Object.assign(this.$data, this.$options.data())` but it throws an error telling me that `TypeError: this.$auth is undefined`

Any suggestion ???

**Comment by tserkov** [comment]
This looks like a common Javascript scoping error -- you'll need to set the `data` function's context to Vue's, like so:
```javascript
Object.assign(this.$data, this.$options.data.call(this))
```

**Comment by websanova** [comment]
Not really sure what you're getting at

**Comment by websanova** [comment]
Doesn't seem like the right approach m you just want to update one field?
Not really sure why you would kill the whole object like this

**Comment by dianjuar** [comment]
@websanova I'm in a form with a lot of fields, when the user submit successfully, I reset all the fields of the forms with the default data... That is the why of the _complex object_

**Comment by websanova** [comment]
So why don't you just keep them in a separate object?

Like `$data.formFields`

Then just override that. Then you can just do `this.formFields`.

I don't think it's good idea to be overriding any `$` variables in Vue.

**Comment by websanova** [comment]
Anyway, $auth is giving you an error, probably just by coincidence, I would imagine lots of things will blow up if you do that.

**Comment by dianjuar** [comment]
@websanova I don't explain myself correctly or you are not paying attention...
I don't want to overwrite any $ variable, I want to reset the data of my component defined on `data () {}`.

@tserkov That solves my problem :)
