### ISSUE TITLE
Getting the headers

### ISSUE THREAD

**Issue by polderudo** [websanova/vue-auth#264]
Is there some way to get the headers i need to send for the current token?
I'm using element ui and for the upload i need to add the header manualy:
```
getHeaders () {      
      return {
        'Authorization': 'Bearer ' + this.$auth.token()
      }
    }
```

Would be nice to get this directly from the $auth

**Comment by websanova** [comment]
This is already done automatically

**Comment by polderudo** [comment]
ElementUI is using xhr.send for file upload. They are building the header manualy: https://github.com/ElemeFE/element/blob/dev/packages/upload/src/ajax.js

Therefor i need to pass in the headers on my own. Having something like GetAuthHeaders would be cool because right now, i have to build it on my own.

**Comment by websanova** [comment]
Depends on the driver, but if you only need the token you can get it with
$auth.token()

**Comment by polderudo** [comment]
Yes. Thats what i am using now. But having a function that returns the header name and driver form the lib would be more independent. Right now my code is coupled to the driver i am using in your lib. It's not a problem or so, wpuld just be noce to expose the header from the lib.
