### ISSUE TITLE
Remember me when logging in programmatically

### ISSUE THREAD

**Issue by alxppp** [websanova/vue-auth#266]
How can the token cookie be saved when logging in programmatically like in https://github.com/websanova/vue-auth/blob/master/docs/AdvancedGuide.md?

**Comment by websanova** [comment]
Not sure what you mean, it's just an argument on the $auth.login() function.

```
$auth.login({
    rememberMe: true
});
```

**Comment by razchen** [comment]
After refresh when logging in programmatically with setting the token the local storage is empty.
