### ISSUE TITLE
Make login/register/etc. return a Promise

### ISSUE THREAD

**Issue by archSeer** [websanova/vue-auth#267]
instead of
```js
      this.$auth.login({
        data: this.credentials
        success() { ... },
        error (res) {
          ...
        }
      })

```

```js
      this.$auth.login({
        data: this.credentials
      }).then(function () {
        // success
      }).catch(function () {
       // error
      })

```

**Comment by websanova** [comment]
Ya this can be done, it would just be forwarded to vue-resource/axio/etc

**Comment by loweoj** [comment]
Would I need to create/extend the axios driver some how? How might this work?

**Comment by websanova** [comment]
ok, this is in, should be working for both vue-resource and axios. It's in `v2.20.0-beta`. I've done a few other updates, but you can just check the change log.
