### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by gracewai** [websanova/vue-auth#268]
I wouldn't know where to look, but I can't sign in. 
This is the error I get for sign in 

Failed to load http://localhost:8000/auth/login: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
XHR finished loading: POST "http://localhost:8000/auth/login".

**Comment by websanova** [comment]
From your API?

**Comment by archSeer** [comment]
Is your API on a different domain and/or port? You need to enable ![CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS), just as the error message is telling you.

**Comment by tserkov** [comment]
This is possible related to the following bug, related to attempt XHR from localhost on Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=67743

**Comment by gracewai** [comment]
Thank you.
Already solve this problem by adding CORS mapping and appear "GET http://localhost:8000/auth/user 403 ()"
