### ISSUE TITLE
Best strategy to force login

### ISSUE THREAD

**Issue by alaindixon** [websanova/vue-auth#272]
First of all, thank you for your API.
Quick question, what is the best strategy to forbid a page, should I write everywhere:
`    if(!this.$auth.check()) {
      this.$router.push('Login') 
    } `
Or have you got a recommandation?

**Comment by websanova** [comment]
Did you check the docs at all?

**Comment by alaindixon** [comment]
Do you mean the solution is in the documentation?
I checked the step by step, beginner guide, advanced guide, FAQ, all the methods even the demo.
None of them explain the best strategy to check if a user is logged on all the pages.
Sorry to bother you.

**Comment by websanova** [comment]
Maybe this?

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md

**Comment by alaindixon** [comment]
My apologies, I saw it but I did not understand, because of all permissions (role=admin).
`auth: true` 
Thank you very much and sorry again.
