### ISSUE TITLE
I18n route

### ISSUE THREAD

**Issue by LuigiMigliardi93** [websanova/vue-auth#273]
Hi,

how can I pass parameters to the login path?
For example: `route: ': i18n / login'` pass it `params.i18n`.

Thanks,
Luigi

**Comment by websanova** [comment]
Same way you would with your http plugin/provider ;)

**Comment by LuigiMigliardi93** [comment]
But I can't pass the params.
Eg: `authRedirect = { path: '/signin', params: { lang: this.$route.params.lang }}`

**Comment by websanova** [comment]
Huh?

It's just vue-resource or axios running there. Just pass it in normally.

If you need to do it in each request it would be an interceptor.
