### ISSUE TITLE
$auth.login gets token, doesn't store in local storage

### ISSUE THREAD

**Issue by Surenapetrosyan** [websanova/vue-auth#277]
Hi, I'm having a weird issue I can't get around.

`$auth.login` makes the proper request, if the password is correct it gets the token but I'm stuck in login page because it doesn't store the token. 

If I manually do `localStorage.setItem('newreads_auth_token', response.body.access_token);` in the `$auth.login` success call it will redirect me to my application and seems to 'log in' fine. 

What are the implications of this workaround, and why isn't it just working? It was working up until I deleted all of my node_modules and reinstalled.

**Comment by websanova** [comment]
Can you verify with dev tools if any tokens are there?

**Comment by websanova** [comment]
What version if vue-auth are you using? Maybe try with the latest if you
are not already.

**Comment by Surenapetrosyan** [comment]
I'm on 2.18.3

**Comment by websanova** [comment]
I'm wondering if it's just not getting parsed properly.

Which driver are you using? And how are you sending the token?

**Comment by Cholowao** [comment]
@websanova I am using `axios` and latest vue-auth. But when the application logged successful, the token are stored as `default-auth-token` and I want it to store with different name.. Also when it logged in, it makes another request `/api/user` without sending authorization. How can I stop that behaviour 
![image](https://user-images.githubusercontent.com/11339750/34894522-daaff010-f7f2-11e7-8d6d-d56232160a9e.png)

**Comment by mgd722** [comment]
@Cholowao you can change default token name by [setting it in the options object](https://github.com/websanova/vue-auth/blob/master/docs/Options.md#tokendefaultname-default_auth_token).  if you don't want to automatically fetch a user after you've logged in, you can set `fetchUser: false`, also in the [options object](https://github.com/websanova/vue-auth/blob/master/docs/Options.md#logindata-url-authlogin-method-post-redirect--fetchuser-true).
