### ISSUE TITLE
Token issue using: VueAuth + VueResource + VueRouter + DeviseTokenAuth

### ISSUE THREAD

**Issue by fbove** [websanova/vue-auth#283]
Hello!
On my Vue App I'm using:
- vue-auth v2.18.3-beta
- vue-resource v1.3.4
- vue-router v2.7.0

And on Rails API:
- devise_token_auth v0.1.42

Had no problem doing a login/logout, token validation and updating content that requires auth. Though when an access-token is changed and then a new request is made, it is using an old token instead of the updated one. This is not happening always, meaning that it works great till it stops updating it.

Here is my configuration:

```javascript
import Vue from 'vue'
import router from './router'
import resource from './resource'
import App from './App'

Vue.http.options.root = process.env.API_URL
Vue.http.interceptors.push((request, next) => {
  next((response) => {
    // Unauthorized Access
    if (response.status === 401 && ['UnauthorizedAccess', 'InvalidToken'].indexOf(response.data.code) > -1) {
      Vue.auth.logout({
        redirect: { name: 'auth-login' }
      })
    }
    // System Error
    else if (response.status === 500) {
      Vue.router.push({name: 'error-500'})
    }
  })
})

Vue.router = router

Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'type',
  loginData: { url: process.env.API_URL + '/auth/sign_in', method: 'POST', redirect: '/' },
  logoutData: { url: process.env.API_URL + '/auth/sign_out', method: 'DELETE', redirect: '/login' },
  refreshData: { url: process.env.API_URL + '/auth/validate_token', method: 'GET', enabled: true, interval: 1 },
  fetchData: { url: process.env.API_URL + '/auth/validate_token', method: 'GET', enabled: true }
})

Quasar.start(() => {
  new Vue({
    el: '#q-app',
    router,
    resource,
    render: h => h(App)
  })
})
```
Would appreciate any given help.
Thanks!

**Comment by websanova** [comment]
Depends when the requests were fired. If the refresh comes back after a
bunch of calls it's too late.

I think with most implementations there is some short grace period for
expired requests.

**Comment by fbove** [comment]
I have devise_token_auth default configs set.

Debugging a little more, what is failing is automatic token validation.
The one done by refreshData. Configured in:
```javascript
...
 refreshData: { url: process.env.API_URL + '/auth/validate_token', method: 'GET', enabled: true, interval: 5 },
...
```
Check it here:
I have devise_token_auth default configs set.

Debugging a little more, what is failing is automatic token validation.
The one done by refreshData. Configured in:
```javascript
...
 refreshData: { url: process.env.API_URL + '/auth/validate_token', method: 'GET', enabled: true, interval: 5 },
...
```

Here login works great, it's also doing the token validation:

![vue-auth devise 1](https://user-images.githubusercontent.com/17007814/32458025-c4dc10ac-c309-11e7-8709-caeda001a394.png)

I can also update things without any problem. Though when automatico token validation is triggered it fails:

![vue-auth devise 2](https://user-images.githubusercontent.com/17007814/32458073-ece55108-c309-11e7-90a2-b8b74feaf508.png)

Any thoughts? I'll keep debugging anyways :man_technologist:

**Comment by fbove** [comment]
I'm answering myself :dancer: 

Headers working for token validation on login:
![token validation headers working](https://user-images.githubusercontent.com/17007814/32458556-8c325764-c30b-11e7-8a53-705bc0368688.png)

Headers not working for automatic token validation (refresh):
![token validation headers not working](https://user-images.githubusercontent.com/17007814/32458571-9502ccd4-c30b-11e7-9451-51d5516f8915.png)

I see the problem now ... It's a common "between chair and keyboard" issue I'm having.
