### ISSUE TITLE
Working example for Nuxt.js?

### ISSUE THREAD

**Issue by pvenableh** [websanova/vue-auth#284]
Is there a working example for Nuxt.js?  I see it is a work in progress and was wondering if a demo for this platform will be coming.  Thanks.

**Comment by websanova** [comment]
Not really,

I was trying, but didn't get too far. Ultimately I think I came to the
conclusion that it's just different problem set since Nuxt is more back-end
than front end solution.

It would be completely different auth from the back-end written for Nuxt as
far as I could understand.
