### ISSUE TITLE
OAuth2 flow

### ISSUE THREAD

**Issue by nbonamy** [websanova/vue-auth#285]
Hello,

I have successfully used vue-auth to implement user/password authentication.

Now I would like to add Facebook Connect functionality. I can go through the first step and successfully get a code. From what I understand from OAuth2, this authorization code must be exchanged with a an access token (and a refresh token). It seems that vue-auth does not perform this step.

If I copy/paste the code returned in https://developers.facebook.com/tools/debug/accesstoken/, I get a token malformed error which seems to indicate that the value is not a token.

I want then to connect to my passport-facebook-token provider which expects tokens and not auth code.

How can I fill the missing step?

Thanks,
Nicolas

**Comment by websanova** [comment]
Not sure,

But for me I get the code and ship it to my backend which then does all the
work.

As far as I understand/see it needs a private app key for this.

But I'm not expert on oauth2. I'm just using Laravel Socialite.

Do you not have any interaction with backend at all?

**Comment by nbonamy** [comment]
Yes I saw that in your sample.

I have a node/express backend that uses https://github.com/drudge/passport-facebook-token.

It returns the same error as https://developers.facebook.com/tools/debug/accesstoken/ : malformed token.

Thanks

**Comment by nbonamy** [comment]
Hello, I am back with a solution :)

Laravel Socialite indeed proceeds with the code/token exchange phase so this possibly could be implemented on the backend without much trouble.

But there is a faster way: Facebook allows to directly get an access_token on the first oauth call (not all oauth2 providers allow this; strava doesn't for instance).

For this, you need to set the `response_type` to `'token'` in your `facebookOauth2Data`.

Then the trick is that for some reason, when you ask for a token, Facebook puts back all the data in the callback URL behind a hashbang and not as query parameters :
```
code : http://callbackURL/?code=...
token : http://callbackURL/#?access_token=...
```

So instead of doing

```
code = this.$route.query.code
```

You have to do

```
let params = window.location.hash.substr(1).split('&')
params.forEach(function(d) {
  let pair = d.split('=')
  if (pair[0] === 'access_token') {
    code = pair[1]
    return false
  }
})
```

I guess this issue can be closed !

Nicolas

**Comment by Akopean** [comment]
I use a version with a token, can someone come in handy
`
**main.js**    
facebookOauth2Data: {
        clientId: '---',
        params: {
            redirect_uri: function () { return '---'; },
            response_type: 'token',
        }
     },
**oauth2.vue**
        mounted() {
            let params = window.location.hash.substr(1).split('&');
            params.forEach(param => {
                let pair = param.split('=');
                if (pair[0] === 'access_token') {
                    this.token = pair[1];
                    return false
                }
            });
            if (this.token) {
                console.log(this.token);
                this.$auth.login({
                    url: '../auth/facebook',
                    params: {
                        token: this.token,
                    },
                    success: function(res) {
                        console.log('success ' + this.context);
                    },
                    error: function (res) {
                        console.log('error ' + this.context);
                    }
                });
            }
        },

> backend facebook function -default

    /**
     * @param Request $request
     * @param $type
     * @param $cb
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws AuthorizationException
     * @throws CreateUserInvalidArgumentException
     */
    private function _social(Request $request, $type, $cb)
    {
        if ($request->has('token')) {

            $social_user = Socialite::with($type)->userFromToken($request->input('token'));
            $social_user = $cb($social_user);

            if (!@$social_user->id) {
                return response([
                    'status' => 'error',
                    'code' => 'ErrorGettingSocialUser',
                ], 400);
            }

            $user = $this->repository->findByField($type . '_id', $social_user->id)->first();

            if (!($user instanceof User)) {
                $user = $this->repository->findByField('email', $social_user->email)->first();

                if (!($user instanceof User)) {

                    event(new Registered($user = $this->create([
                        'name' => $social_user->name,
                        'email' => $social_user->email,
                        'facebook_id' => $social_user->id,
                        'type' => $type,
                    ])));

                    $this->autenticate($user);
                }
            }
            // Update info and save.
            if (empty($user[$type.'_id'])) {
                $user[$type.'_id'] = $social_user->id;
                $user->save();
            }

            if (!$token = JWTAuth::fromUser($user)) {
                throw new AuthorizationException;
            }

            return response([
                'status' => 'success',
                'token_type' => 'Bearer',
                'expires_in' => auth()->factory()->getTTL()
            ])->header('Authorization', $token);
        }
    }
`
