### ISSUE TITLE
Is it possible to have multiple configurations?

### ISSUE THREAD

**Issue by fbove** [websanova/vue-auth#288]
I'm currently implementing this [devise_token_auth using-multiple-models](https://github.com/lynndylanhurley/devise_token_auth#using-multiple-models) (Take a loot at first demo listed under "View Live Multi-User Demos" has a really good approach)

For example (just to show what I say), one configuration to login as a **user** and another one to login as an **admin**:

```javascript
Vue.use(VueAuth, [
  {
    default: {
      auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
      http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
      router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
      rolesVar: 'type',
      loginData: {
        url: `${apiEndpoint}/auth/sign_in`,
        method: 'POST',
        redirect: '/'
      },
      logoutData: {
        url: `${apiEndpoint}/auth/sign_out`,
        method: 'DELETE',
        redirect: '/login'
      },
      ...
    }
  },
  {
    admin: {
      auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
      http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
      router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
      rolesVar: 'type',
      loginData: {
        url: `${apiEndpoint}/admin_auth/sign_in`,
        method: 'POST',
        redirect: '/'
      },
      logoutData: {
        url: `${apiEndpoint}/admin_auth/sign_out`,
        method: 'DELETE',
        redirect: '/login'
      },
      ...
    }
  }
])
```
Could also share some common config, like auth, http, router and rolesVar.

Then login would be like:
```javascript
this.$auth.default.login(...)
//- or
this.$auth.admin.login(...)
```

Is this already doable by some way I couldn't find in the docs?

Thanks!

**Comment by websanova** [comment]
Did you look at the $auth.impersonate/unimpersonate/impersonating
methods/options?

**Comment by fbove** [comment]
Can't say I didn't, though I didn't suppose that this case applied.
The concept of impersonating requires me to be already signed in, right?.

What I meant on my previous description is that it's an alternative login for other kind of users (admins). So it's a completely different login for the same App.

Can the first login be an Impersonated one?

**Comment by websanova** [comment]
That would just be custom auth driver then, you should have the request and
response available there, so I assume you can just sniff out some parameter
or url to swap the schemes.

**Comment by fbove** [comment]
I've just checked it and the problem is that in the driver (devise.js in my case) is too late, because the request hook is being called for `/auth/validate_token` after sing_in.
The `/auth/sign_in` is being made on `function __duckPunch` in auth.js, using the options previously set.

**Comment by fbove** [comment]
Maybe a way to change options dinamically?

**Comment by websanova** [comment]
But in the end it's still sending some data back and forth, just in a
different format?

**Comment by fbove** [comment]
Same data with same format, but to a different endpoint.
For example: `/auth/...` or `/admin_auth/...`
And Vue App using unique components to login as a user or an admin.

devise_token_auth is mounted on both routes:
```ruby
mount_devise_token_auth_for 'User', at: 'auth'
mount_devise_token_auth_for 'Admin', at: 'admin_auth'
```

**Comment by websanova** [comment]
Everything is the same except the URL?

You can pass a url when you call $auth.login(). Not really sure im
following here.

**Comment by fbove** [comment]
However, every next auth request (`/validate_token`, `/logout`, etc..) has to be mounted on `/admin_auth` instead of `/auth` from that point on.

**Comment by websanova** [comment]
Hmm,

Well, how do you know when to swap, even if we coded something into the
plugin?

There has to be a trigger for determining which url to use. Like a role
parameter, or url, cookie, local storage, etc.

On Nov 15, 2017 00:09, "Facundo Bove" <notifications@github.com> wrote:

However, every next auth request (/validate_token, /logout, etc..) has to
be mounted on /admin_auth instead of /auth from that point on.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/288#issuecomment-344327968>,
or mute the thread

**Comment by fbove** [comment]
Two choices that may work:

**a**. Delay plugin configuration, so you can choose which API path to use (also every other config). I've tried to do something like this, but the plugin argues about http and router configs.
**b**. Make URL dynamic, in order to change it after the App has already booted. That URL parameter would be used among all requests (login, validate_token, logout, etc.).

I don't think choice _**a**_ could really work, but maybe choice _**b**_ could.

**Comment by websanova** [comment]
Ok, so say we use b and it's dynamic...what triggers the change?

**Comment by fbove** [comment]
The App itself. Suppose having two Login Components on separate routes in a our VueApp. Each component does it's own login against different API endpoints.

If you feel this is pointless, please do close the issue. I could always workaround it somehow.

**Comment by websanova** [comment]
I'm not saying it's pointless.

I'm just trying to point out that it's the app that ultimately determines
which login route to take (either user or admin).

So the plugin has no idea. In the there has to be some way to know whether
it's one or that one. A route, a cookie, local store or whatever.

So you can simply write a custom driver where this little check is done and
modify the url before it 's getting sent out.

Not sure why the plugin should bother to store multiple profiles.The check
needs to be done in the app either way.

**Comment by fbove** [comment]
I solved it by splitting concerns.
