### ISSUE TITLE
Redirect /404 to /login when logedin

### ISSUE THREAD

**Issue by kosanr1** [websanova/vue-auth#291]
I want to set different redirection then 404 to route '/login' when user is loged in. How can I do this?

`else if (routeAuth === false && this.check()) {
            __transitionRedirectType = 404;
            cb.call(this, notFoundRedirect);
        }`

vue-router
`
    {
      path: '/login',
      name: 'login',
      component: LoginPage,
      meta: {
        auth: false,
      },
    },`

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth/blob/master/docs/Options.md#authredirect-path-login

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md

**Comment by kosanr1** [comment]
I've seen this but it's not working.
I put it like this.

`Vue.use(VueAuth, {
  ...
  authRedirect: {path: '/'},
});`

**Comment by websanova** [comment]
Can I see more code?

**Comment by kosanr1** [comment]
main.js
```
Vue.use(VueAuth, {
  auth: {
    request: function (req, token) {
      token = token.split(';');
      token = req.url.indexOf('refresh') > -1 ? token[1] : token[0];
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
    },
    response: function (res) {
      if (res.data.access_token && res.data.refresh_token && res.data.expires_in) {
        return res.data.access_token + ';' + res.data.refresh_token+ ';' + res.data.expires_in;
      }
    }
  },
  http: WebsanovaAxios,
  router: VueRouter,
  rolesVar: 'roles',
  refreshData: {enabled: false},
  authRedirect: {path: '/'},
});
```
vue-router
```
export default new Router({
  hashbang: false,
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'home',
      component: HelloWorld,
    },
    {
      path: '/login',
      name: 'login',
      component: LoginPage,
      meta: {
        auth: false,
      },
    },
    {
      path: '/register',
      name: 'register',
      component: RegisterPage,
      meta: {
        auth: false,
      },
    },
    {
      path: '/secret',
      name: 'secret',
      meta: {
        auth: {
          roles: ['ROLE_USER'],
        },
      },
      component: SecretPage,
    },
  ],
});
```

**Comment by websanova** [comment]
Ah wait, just realized you said when user is logged in, and the route auth
is set to false, should use notFoundRedirect

**Comment by kosanr1** [comment]
Thanks :) It's working now :) Greeting from Poland
