### ISSUE TITLE
Vue-Auto should permit for extra / arbitrary parameters when constructing OAuth2 URL

### ISSUE THREAD

**Issue by k8n** [websanova/vue-auth#292]
Case in point: [```hd``` parameter for Google's OAuth2](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) for restricting login UI to particular hosted domain.

Code to revise:
https://github.com/websanova/vue-auth/blob/8375a51e47562133f6062dd54ec640aa46cbc67f/src/auth.js#L452

Current hack / workaround is to inject the extra parameter into the, e.g., scope variable:
```
googleOauth2Data: {
        clientId: 'NNNNNNNNNN-xxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
        scope: 'https://www.googleapis.com/auth/plus.me ' +
                     'https://www.googleapis.com/auth/plus.login ' + 
                     'https://www.googleapis.com/auth/plus.profile.emails.read' +
                     '&hd=example.com'
    },
```

**Comment by websanova** [comment]
ok, will fix this up over the weekend.

**Comment by websanova** [comment]
Ok, these changes are in  `v2.21.0-beta`.

Note it's a bit different format now to just use the `params` attribute.  However it's fully backward compatible so you should not have to make any existing changes in case you made some tweaks.

BUT, the defaults are different now:

https://github.com/websanova/vue-auth/blob/master/docs/Options.md#facebookoauth2data-url-httpswwwfacebookcomv25dialogoauth-params-redirect_uri-function---return-thisoptionsgeturl--loginfacebook--client_id--scope-email

And the `oauth2` method:

https://github.com/websanova/vue-auth/blob/master/docs/Methods.md#oauth2

There are some sensible defaults as well.

**Also:  note that some fields have changed to match oauth2 params. so `clientId` is now `client_id` and `redirect` is now `redirect_uri`. BUT only when used in `params`. For backwards compatible (outside of params) it remains the same**

**Comment by k8n** [comment]
Brilliant. Thanks!
