### ISSUE TITLE
Bearer.JS not intercepting response. 

### ISSUE THREAD

**Issue by dineshgupta630** [websanova/vue-auth#294]
Here is my Login.vue. I am doing a post request to my API Server which gives me a response in the JSON format  `{"token":"tokensample"}`. I am using Axios, Bearer.js and vue router. I get a valid,  status 200 response from the server and get the token in the response, however, I get the error,
```
TypeError: Cannot read property 'path' of null
    at Auth._processInvalidToken (auth.js?df86:220)
    at Auth._responseIntercept (auth.js?df86:148)
    at eval (axios.1.x.js?13ff:23)
    at <anonymous>
```
Why am I getting such an error? I tried editing the bearer.js but doesn't show any changes. This is for the first time thus I don't think I can set the authorization header.
```
export default {
  name: 'Login',
  data(){
    return {
      credentials: {
        email: '',
        password: ''
      },
      error: ''
    }
  },
  methods: {
    submit(){
        var credentials = {
          email: this.credentials.email,
          password: this.credentials.password
        }
        const ApiLogin = 'http://localhost:8000/';
        
        this.$auth.login({
            data: credentials, // data: {} in Axios
            url: ApiLogin + 'v1/login',
            success: function () {
              // var token = this.$auth.token();
              // console.log(token);
            },
            error: function (response) {
              console.log(response)
              // console.log(response)
            },
            // rememberMe: true,
            // redirect: '/account',
            // fetchUser: true,
      });
    }
  },
}
  </script>
```
Also how do I create Custom Auth as shown in the Documents? It is not very clear on where and how to implement them. It will be of great help thanks.

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth/blob/master/docs/Guide.md#authentication--drivers

**Comment by janein** [comment]
Hi I just came upon the same error.
I use the bearer-driver (which should be the correct one).
I also tried to debug the driver so I could write my own, but I it doesn't event jump into it.

```
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
```

Any progress on this? Or any idea whats going wrong?
