### ISSUE TITLE
$auth.login should receive body or data? 

### ISSUE THREAD

**Issue by ChauskinRodion** [websanova/vue-auth#295]
Hey Guys. I'm new in Vue and spend a lot time trying setup login method [using this tutorial](https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md#using-vue-auth)
Finally i realized that it does not work if i use `body: {}` parameter, but works with `data: {}`

so can somebody explain what i'm doing wrong or fix tutorial please?

**Comment by ChauskinRodion** [comment]
Okay, i think i found an answer.
```
                    body: this.data.body, // Vue-resource
                    data: this.data.body, // Axios
```

Documentation is poor.. :(

**Comment by websanova** [comment]
Or maybe you just didn't read it, it's in the first section of the guide in
bold ;)

**Comment by ChauskinRodion** [comment]
@websanova oh, sorry. looks like i'm wrong. Sorry for that. 
But can you please show me exact document where is is texted? Walked over documentation again..don't see it 😢
