### ISSUE TITLE
Content-Type not passed to login request in axios

### ISSUE THREAD

**Issue by tomaszchacuk** [websanova/vue-auth#299]
I configured axios to pass default header : Content-Type: application/json 
`var instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Content-Type': 'applicatipn/json'}
});`

But when performing login request (POST) by vue-auth the header is not passed ( no sign of in request params on Network tab in Chrome)

Am I doing sth wrong?

**Comment by websanova** [comment]
Yes, I think this is known issue now with headers being overridden, I will try to get to it in next couple days.

**Comment by websanova** [comment]
maybe you need to put this into `common`?

I just test this with my demo:

Vue.axios.defaults.headers.common['Test'] = 'text/html';

and it works fine.
