### ISSUE TITLE
Don't pass Authorization header when calling different API

### ISSUE THREAD

**Issue by igormatkovic** [websanova/vue-auth#302]
I ran into a little problem.

I'm using vue-auth with vue-resource for authentication.

This works great with the main API.

The problem I'm facing is when I try to interact with a different API. For example, AWS S3 for file upload.
The setup will attach the Authorization header to every call. Even if it has nothing to do with it. 

While most of the API's won't care if you have an extra header or not. 
Amazon does care because that's how it calculates the authentication signature for uploads.

Is there a way to exclude the Authorization header somehow for specific domains, or per call?

**Comment by jap1968** [comment]
Same problem here. I did some tests with axios and vue-axios with no success. Some documentation about this would be welcome.

**Comment by igormatkovic** [comment]
@jap1968 my workaround for this is that i created my own bearer.js file.

And there I just checked if the domain is not aws. And set the token then

```
module.exports = {
  request: function (req, token) {
    if (req.url.indexOf('amazonaws') == -1) {
        this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    }
    ........
```

**Comment by websanova** [comment]
Seems like good approach to me.
