### ISSUE TITLE
Question: Password Recovery

### ISSUE THREAD

**Issue by fbove** [websanova/vue-auth#305]
Is there a way to implement Password Recovery using vue-auth?
Does it exceeds the scope of the library?

For devise-token-auth, it's [explained here](https://github.com/lynndylanhurley/devise_token_auth/wiki/Reset-Password-Flow)

**Comment by websanova** [comment]
I thought about it before but I'm not sure. Really it's just another token,
the first of which is just a request for one. But the details are really
handled on the backend.

I kind of drew line there since it in now way really deals with
authentication tokens the way login, register or oAuth may.

**Comment by fbove** [comment]
Yes, I agree. It could just be a nice to have.

Thanks for answering :+1:
