### ISSUE TITLE
$auth.user(user) returns promise

### ISSUE THREAD

**Issue by steveops** [websanova/vue-auth#306]
I have a small issue. When you try to update the current user using `$auth.user(newUser)`, for a split second `$auth.user()` returns a promise. This is a problem because page elements that render user data e.g `<span>{{$auth.user().name}}</span>` fail at that moment. Wrapping in `$auth.ready()` doesn't help. I tried to use another variable `user_loaded` which I set to false just before calling `$auth.user(newUser)`  but it didn't help. Apparently, calling `$auth.user(newUser)` returns a promise, and by the time it resolves, calling `$auth.user()` still returns a promise. Check the code below:
```
/*inside a component*/

// I use this so I dont try to access $auth.user() when its a promise
this.user_loaded = false
this.$auth.user(newUser).then((u) => {
    // we should have an actual user here but the statement below still returns a promise
    let user = this.$auth.user() //still returns a promise
    // I expected it to return a user so I can set user_loaded = true
}) 
```
How can I handle this, or am I missing something?

**Comment by websanova** [comment]
huh?

https://github.com/websanova/vue-auth/blob/master/src/auth.js#L633

**Comment by steveops** [comment]
Apologies, one of my functions in the chain was returning a promise. Was authored by someone else and I wasn't aware of it.
