### ISSUE TITLE
Auth Token is not defined

### ISSUE THREAD

**Issue by mubasharbinafzal** [websanova/vue-auth#308]
app
.factory('Auth',function($http,AuthToken){
    var authFactory ={};
    
    authFactory.login =function(loginData){
        return $http.post('/api/authenticate',loginData).then(function(data){
            console.log(data.data.token);
        AuthToken.setToken(data.data.token);
            return data;
        });
        
       //Auth.isloggedIn();		
      //  authFactory.isLoggedIn = function(){
         //   if (AuthToken.getToken()){
         //       return true;    
        //    }
        //    else{
         //       return false;
         //   }
            
      //  };
    };
    return authFactory;
})

**Comment by websanova** [comment]
Huh???

**Comment by mubasharbinafzal** [comment]
solved

**Comment by mubasharbinafzal** [comment]
thanks for feedback

**Comment by mubasharbinafzal** [comment]
is not working
angular.module('userApp', [])

.config(function() {
    console.log("testing user application");
});

**Comment by websanova** [comment]
Are you even in the right place? This is for Vue Auth

**Comment by mubasharbinafzal** [comment]
yes
