### ISSUE TITLE
about denpendence vue-resource

### ISSUE THREAD

**Issue by hainuo** [websanova/vue-auth#31]
i found that  if  i cann't import vue-resource and use vue-resource by Vue.use(VueResource)  
i'll get error like  this  `this.options.http is undefinded`;
so i think in the readme or doc ,you shoude add someline about this.

**Comment by websanova** [comment]
How are you importing it?

**Comment by hainuo** [comment]
yes  i have  import

**Comment by hainuo** [comment]
@websanova     now i use 1.1.0-beta
there's a question about router and http;
i have a try 
```
import Vue from 'vue';
import VueRouter from 'vue-router';
import VueAuth from '@websanova/vue-auth';
import VueResource from 'vue-resource';

Vue.use(VueRouter);
Vue.use(VueResource);

const Foo = { template: '<div>Foo</div>' };
const Bar = { template: '<div>bar</div>' };
const routes = [
  { path: '/login', component: Foo },
  { path: '/bar', component: Bar },
];
const router = new VueRouter({
  routes, 
});
Vue.use(VueAuth, {
  router,  //if i didn't use router like this  will report error this.options.router  undefinded
  //http: VueResource,   //if use this   will report error  this.options.http undefinded
});
const app = new Vue({
  router,
}).$mount('#app');
console.log(app);
```

so  why must use router like 
```
Vue.use(VueRouter)
var router = new VueRouter({routes})
Vue.use(VueAuth, {
  router, 
});
new Vue({router}).$mount('#app')
``` 
can't like the vueresource just
```
Vue.use(VueResource)
```
and if i use http ，how and defind the http variable

**Comment by hainuo** [comment]
i read the doc of vue-resource  and found the usecase 
```
Vue.http.interceptors.push((request, next)  => {
  // modify request
  request.method = 'POST';
  // continue to next interceptor
  next((response) => {
    // modify response
    response.body = '...';
  });
});
```

so i  have try this
```
Vue.use(VueAuth, {
  router,
  http: Vue.http,
});
```
and it works not report errors;

so why  use the this.$http  if  this.$http was exist;

**Comment by hainuo** [comment]
sorry for the question, i know that  this's not the same scop. i want to know why not using exist the http to apply a http definded by user. It would be appreciated if you would like to share.

**Comment by websanova** [comment]
Not really sure what the issue you're having exactly but glad it's working. Btw, the plugin does not use $http instance, it uses http directly, so not sure about your second question either.
