### ISSUE TITLE
Unable to set redirect_uri for Oauth2

### ISSUE THREAD

**Issue by vamsiautomatad** [websanova/vue-auth#311]
Hi,

When I am trying to use Google OAuth2 Login,
I am getting an issue from Google:
 
Error: invalid_request
Invalid parameter value for redirect_uri: Missing scheme: [object Object]

client_id=456test31234-ltest53hi28nsna4e.apps.googleusercontent.com
redirect_uri=[object Object]
scope=https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read 
response_type=code
state={"rememberMe":false}

![screen shot 2018-01-03 at 5 57 14 pm](https://user-images.githubusercontent.com/34367328/34520667-a1d21a38-f0af-11e7-8b35-60c145642b13.png)

I have tried overriding the redirect_uri and set it to a hardcoded string, no matter what I set the value of redirect_uri to, it's still getting set to [object Object] .

How can I fix this issue  ?

Thanks

**Comment by websanova** [comment]
Can you show some code?

**Comment by vamsiautomatad** [comment]
thanks for the reply 
here's the code 

```main.js```
```
Vue.use(VueAxios, axios)
Vue.use(VueAuth, {
  auth: require('./components/modules/auth/Drivers/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  refreshData: {url: 'auth/refresh', method: 'GET', enabled: false, interval: 30},
  fetchData: {url: 'auth/user', method: 'GET', enabled: false},
  googleOauth2Data: {url: 'https://accounts.google.com/o/oauth2/auth', params: {redirect_uri: function () { return this.options.getUrl() + '/login/google'; }, client_id: 'egegef-fefefeffftret4tet4ete.apps.googleusercontent.com', scope: 'https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read '}}
})
```

and heres the code from component
  ```
  link_goog: function(){
      this.$auth.oauth2({
        provider: 'google',
        success: function(res) {},
        error: function(res) {
          console.log(res);
        },
        redirect: {path: '/account'}
      });
    }
```
```
<button class="btn btn-primary" @click="link_goog()">Link Google</button>
```

**Comment by websanova** [comment]
Hmm, redirect in this case should be a string I guess...sry not at my
computer. You can also try putting it into params object var.

**Comment by vamsiautomatad** [comment]
already tried putting a string value for redirect_uri in the params object. still it getting
 redirect_uri to [object Object]

**Comment by websanova** [comment]
Just copy and pasted your `googleOauthData` object in.

Seems ok to me:

```
https://accounts.google.com/o/oauth2/auth?&client_id=egegef-fefefeffftret4tet4ete.apps.googleusercontent.com&redirect_uri=https://hs.localhost.com:8002/login/google&scope=https://www.googleapis.com/auth/plus.me%20https://www.googleapis.com/auth/plus.login%20https://www.googleapis.com/auth/plus.profile.emails.read%20&response_type=code&state=%7B%22rememberMe%22%3Afalse%7D
```

Are you using latest version?
