### ISSUE TITLE
Error promise returns null

### ISSUE THREAD

**Issue by archSeer** [websanova/vue-auth#313]
It should return the response (and I can see it in the adapter), but it returns null.

**Comment by websanova** [comment]
Can you be a bit more descriptive?

Sample code, vue-auth version, axios, vue-resource

How I can test anything with what you give me?

**Comment by archSeer** [comment]
```js
        this.$auth.register({
          data: this.model,
          redirect: null,
        }).then((res) => {
          this.success = true;
        })
        .catch((res) => {
          console.log(res);
        });

```
catch block never gets called if the server returns 422.

**Comment by websanova** [comment]
Are you using latest version?

**Comment by websanova** [comment]
By the way this just returns vue-resource promise. So to catch this kind of error you will need to do

```
this.$auth.register({
          data: this.model,
          redirect: null,
        }).then((res) => {
          this.success = true;
        }, (res) => {
            console.log(res);
        });
```

But depends which driver/plugin you are using. MAybe axios is different, I'm not really sure.
