### ISSUE TITLE
vue-auth & framework7

### ISSUE THREAD

**Issue by Vincebe** [websanova/vue-auth#314]
Hi,

I'm working on a Vue / Framework7 based app.

F7 comes with a custom router : 
```javascript
import Routes from './routes.js'
new Vue({
  el: '#app',
  template: '<app/>',
  framework7: {
    ...
    routes: Routes
  },
})
```

routes.js
```javascript
export default [
  {
    path: '/about/',
    component: require('./assets/vue/pages/about.vue')
  }
]
```
Is it possible to make vue-auth work with a setup like this?

Thanks !

**Comment by websanova** [comment]
No idea about framework7 but should be fine. Only thing vue-auth checks for is the meta auth in a route.

**Comment by websanova** [comment]
Just try it ;)

**Comment by Vincebe** [comment]
I have no instance of vue-router so i can't set Vue.router...

**Comment by websanova** [comment]
What does framework7 use?

**Comment by websanova** [comment]
For this it's likely you would need to write a custom driver for the router.

You could take a look at the existing vue-router one:

https://github.com/websanova/vue-auth/blob/master/drivers/router/vue-router.2.x.js

You would then need to feed in the framework7 router in for the router driver.
