### ISSUE TITLE
Help Wanted: rolesVar as Object

### ISSUE THREAD

**Issue by fbove** [websanova/vue-auth#315]
I've got `rolesVar: 'role'` on my config, and role is an object.

`role_code` is one of it's properties and this works perfectly:
```
div(v-if="$auth.check({ role_code: [ roles.ADMIN, roles.PUBLIC ] })")
```

However I can't check role_code inside of router meta (I'ts always true)
```
{
   path: 'dashboard',
   component: Dashboard,
   meta: {
      auth: {
         roles: { role_code: [ roleCodes.ADMIN ] },
         redirect: { name: 'home' },
         forbiddenRedirect: { name: 'forbidden' }
      }
   }
}
```

Any thoughts?

**Comment by websanova** [comment]
Seems they are not matched in your example.

```
'role' !== 'roles'
```

```
rolesVar: 'role'
 roles: { role_code: [ roleCodes.ADMIN ] },
```

**Comment by fbove** [comment]
Tried it without luck.

```javascript
{
   path: 'dashboard',
   component: Dashboard,
   meta: {
      auth: {
         role: { role_code: [ roleCodes.ADMIN ] },
         redirect: { name: 'home' },
         forbiddenRedirect: { name: 'forbidden' }
      }
   }
}
```

I'm using `"@websanova/vue-auth": "^2.21.0-beta",` and this is my config:
```javascript
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  ......
}
```

`auth` property inside `meta` is specting the property which name is declared in `rolesVar`, right?

This is working if I use `role` as a string (and change my API to return a string) and compare it against a string or array of them.

**Comment by websanova** [comment]
Can you give sample of your user object

**Comment by fbove** [comment]
Sure, my user object has the following properties:

- uid
- name
- nickname
- email
- role
   - role_code
   - role_name
   - organization
- provider

**Comment by websanova** [comment]
Can you send sample of an actual json object

**Comment by fbove** [comment]
I have omitted sensible data, here it is:

```json
{
  "success": true,
  "data": {
    "uid": "user@email.com",
    "name": "User Name",
    "nickname": "User Nickname",
    "email": "user@email.com",
    "role": {
      "role_code": "admin",
      "role_name": "Administrator",
      "organization": {
        "name": "Organization Name",
        "alias": "org-alias"
      }
    },
    "provider": "email"
  }
}
```

**Comment by fbove** [comment]
I've been debugging and discovered this:

https://github.com/websanova/vue-auth/blob/dc456998fde6b64aa672688fb51e508c3224c6bc/src/auth.js#L92

In my case `routeAuth` is an Object. On the left part of the condition it evaluates to true, however on the right part it will never be true.

**Comment by websanova** [comment]
The line above should be converting it to an array though. Maybe try just
tossing it into an array. Could be some bug in the utilities.

I'm just flying now, will be out for a few days.

**Comment by fbove** [comment]
The previous has sense **if the property name is _roles_**:
https://github.com/websanova/vue-auth/blob/dc456998fde6b64aa672688fb51e508c3224c6bc/src/auth.js#L90

If that is true, which was not my case, then routeAuth will be:
```json
{
   "role_code": [
      "admin"
   ]
}
```
Which keeps being an Object, and `routeAuth.constructor === Array`  evaluates to false.

As a workaround I will be using it as an array somehow.

Thanks for feedback :)

**Comment by websanova** [comment]
@fbove ok, this should be good to go. It should be comparing the objects properly now. Make sure to grab the latest `v2.21.1-beta` for this fix.
