### ISSUE TITLE
user data loss when refresh page 

### ISSUE THREAD

**Issue by Juckky00** [websanova/vue-auth#317]
I set user data in success response
with this code
this.$auth.user({roles:['admin','user'],correntrole:'admin'})
then redirect to homepage in the first time $auth.user has data.
when I press F5 or go to other page and then console log this.$auth.user it empty.
how can i remember user data when i refresh.

**Comment by websanova** [comment]
Are you using auth.ready to make sure user is loaded first?

**Comment by Juckky00** [comment]
first I login to get Jwt token 
second when login  success I use this.$auth.fetch to get user data 
and check auth.ready if true set user data.

I don't know how to use auth.ready .

I can go to other page with have user data 

when I refresh browser user data always lost but not log out auth.check it has value true.

I don't know what happen.

T-T

```    javascript
login () {
      var redirect = this.$auth.redirect()
      this.$auth.login({
        headers: {
          'Content-Type': 'application/json',
          'user': this.data.body.user,
          'pass': this.data.body.pass
        },
        data: this.data.body,
        rememberMe: true,
        redirect: {name: redirect ? redirect.from.name : 'Home'},
        success (res) {
          if (res.data.status === true) {
            this.$auth.fetch({
              data: {
                'query': {
                  'user': 'bin',
                  'application': 'social'
                },
                'limit': 1
              },
              success: function (res) {
                if (this.$auth.ready()) {
                  this.$auth.user(res)
                }
              },
              error: function () {
              }
            })
          } else {
            console.log(res)
            this.$auth.logout({
              redirect: 'Login',
              makeRequest: false
            })
            openMessage({
              title: 'fail login',
              message: res.data.message,
              type: 'danger'
            })
          }
        },
        error (err) {
          if (err.response) {
            this.error = err.response.data
          } else {
          }
        }
      })
    }
```

**Comment by Juckky00** [comment]
ok I look demo when refresh browser demo will use refresh method and get user data again.
I can't do that I no have service for get user data with GET medthod.
I manual get user data form mongodb with POST method and set data parameter = mongo query.

I no have service support for refresh check token and get user data with token. 
how can i store user data until  logout. 
I will manual check every page manual token expire.

**Comment by websanova** [comment]
Use ready method not fefresh
