### ISSUE TITLE
localStorage item with default token name is always empty

### ISSUE THREAD

**Issue by DenzoNL** [websanova/vue-auth#318]
Today I have been implementing vue-auth in a new application and I've run into an issue where the `localStorage` item with the same name as the `tokenDefaultName` set in the options will always be non-existant.

E.g. if I set the tokenDefault name like this:

```
Vue.use(VueAuth, {
  ...
  tokenDefaultName: 'lorem_ipsum',
  ...
})
```

an item with the key lorem_ipsum never shows up. Even if I call

`localStorage.setItem("lorem_ipsum", "dolor sit amet");`

in my `$auth.login()` method the key-value pair never even shows up at all, whereas if I set `tokenDefaultName` to something else the value shows up fine.

I have looked into the code but I haven't been able to spot any obvious reason why it might be wiped. In either case, the package is broken for me as I can't store the auth token without it being wiped. My headers are correct and the token is being sent properly by the server (as I can login just fine), but the token is never persisted so as soon as I get a 401 I am booted out of the app.

Could you please look into this issue? Thanks in advance!

**Comment by websanova** [comment]
I don't understand the issue. Can you give more specific steps to reproduce.

**Comment by DenzoNL** [comment]
> I don't understand the issue. Can you give more specific steps to reproduce.

I'm not sure how else I can explain it. Any localStorage item with the same key as set in the `tokenDefaultName` in VueAuth is erased from localAuth whener vue-auth attempts to store the key there. Is there anything specific you would like me to explain in more detail?

Again, thanks in advance :)

**Comment by DenzoNL** [comment]
Just noticed that the template I'm using is using `vue-router@^3.0.1`, could this be the cause of my issues?

**Comment by websanova** [comment]
So it only doesn't work if you set the token to "lorem_ipsum" but anything else works?

**Comment by DenzoNL** [comment]
Tried it again after letting it settle for a few months, it seems to work now. I have to apply 

```php
header('Access-Control-Expose-Headers', 'Authorization');
```

in order for the token to actually be saved, though.
