### ISSUE TITLE
On login auth/user has no token

### ISSUE THREAD

**Issue by dobromir-hristov** [websanova/vue-auth#32]
I have a laravel API, pretty similar to the test one on your repo. On login I return an Authorization header with the token, your controller is pretty much the same.
On the APP part, when I call 
```js
login () {
        this.$auth.login({
          body: this.auth.body,
          rememberMe: this.auth.rememberMe,
          redirect: {name: 'account'},
          success () {
            Toast.create.positive({
              html: 'Login Successful'
            })
          },
          error (res) {
            Toast.create.negative({
              html: (typeof res.data.msg !== 'undefined') ? res.data.msg : 'Error'
            })
            this.error = res.data
          }
        })
      }
```
I get a successful login response in the console, but then the `auth/user` request which gets the user data is sent without the Authorization token that was just provided on the previous response.

Doing manual HTTP requests yields proper responses.  

Am I suppose to handle this, or is it done behind the scenes? I tried reading the code behind on auth.js, but I got pretty much lost with all those `__d*ckPunch()` calls :smile:

**Comment by websanova** [comment]
Don't be afraid of the duckies :-)

How are you sending the token from your server?

**Comment by dobromir-hristov** [comment]
Exactly as your controller does. 
```php
    public function login(Request $request)
    {
        $credentials = $request->only('username', 'password');
        if ( ! $token = JWTAuth::attempt($credentials)) {
            return response([
                'status' => 'error',
                'error' => 'invalid.credentials',
                'msg' => 'Invalid Credentials.'
            ], 400);
        }
        return response([
            'status' => 'success'
        ])
        ->header('Authorization', $token);
    }
```

**Comment by websanova** [comment]
What version of vue, vue-resource, vue-router vue-auth are you using?

**Comment by dobromir-hristov** [comment]
''''
"vue": "1.0.26",
    "vue-resource": "^0.9.3",
    "vue-router": "^0.7.13",
' ''

**Comment by websanova** [comment]
Make sure you have all the latest.

https://github.com/vuejs/vue-resource/releases

**Comment by dobromir-hristov** [comment]
OK, my bad there. I updated the resource, but still i get a Error 400 Token not provided. and here are the Request headers .
```
GET /api/v1/auth/user HTTP/1.1
Host: api.terrariums.eu
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/
Origin: http://localhost:8080
Connection: keep-alive
```
And the Response ones
```
HTTP/1.1 400 Bad Request
Date: Wed, 05 Oct 2016 10:07:14 GMT
Server: Apache
Cache-Control: no-cache
Access-Control-Allow-Origin: http://localhost:8080
Vary: Origin
phpdebugbar-id: 1368c01370f128cc59c3ec590f952a8c
Set-Cookie: XSRF-TOKEN=eyJpdiI6IjNLaFFoQkRWNWdrVGRJc3BITFZVb3c9PSIsInZhbHVlIjoiQnFrcTNheUZVVXFmdTl3NDdZSGpEMDRRem9YMUx0TXpTRW1lTWRmRGxsMmlQUTNodVhjaEV2ZXBWWVwvTzl2OVBOUlJTcFRBcnMwcWxIdDBTdW1qdGJnPT0iLCJtYWMiOiJhODg4MmM0OWNiZmE2OWViYzliOTU5NmFkYTA5ZWY2OWE0ZTM1MTUxNDViYmQ2YjRjZWFlMzgxZDYxMmFhZjRiIn0%3D; expires=Wed, 05-Oct-2016 12:07:14 GMT; Max-Age=7200; path=/
laravel_session=eyJpdiI6Im5KTXRFN3BUNCt1Tk1yc1NxRTgxWHc9PSIsInZhbHVlIjoieEZcL0U4XC9PZVwvMGlyZStZdElkTXQxWm5CQjFMOExUY2JOaVpDOEIyTkdOeW53MElqQXZpbDVlQTlVXC82S2ZWQ2V5NzY4S3dEYjNBVEhkeXZlZXArdEd3PT0iLCJtYWMiOiI0OTAxMWU3MzA4MzNjMzljMDFlODFhZTJiY2I3MjgxOGRmMWJkMTUwNzk3MDRkYzQ3ZjFlYmM3MDdmZWEyODQxIn0%3D; expires=Wed, 05-Oct-2016 12:07:14 GMT; Max-Age=7200; path=/; httponly
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
```

**Comment by dobromir-hristov** [comment]
My Exposed Headers did not include `Authorization` header ... stupid mistake ... it was a CORS issue all along.

**Comment by vesper8** [comment]
@dobromir-hristov an easy mistake to make :) you just saved me a lot of pain!

**Comment by zavgarr** [comment]
For all facing "token_not_provided" on fetch user request . After properly installing "barryvdh/laravel-cors" in laravel - check you have valid configuration in config/cors.php (you need to publish it before edit):
'allowedHeaders' => ['*']
'exposedHeaders' => ['Authorization'] - THIS WAS MISSING IN MY CASE!!
