### ISSUE TITLE
Params or Body?

### ISSUE THREAD

**Issue by komirad** [websanova/vue-auth#321]
Maybe I am not understanding this correctly but the example [here](https://github.com/websanova/vue-auth/blob/master/docs/StepByStepGuide.md#using-vue-auth) uses body
```
$auth.login({
    body: {email: 'test@example.com', password: 'secret'},
    rememberMe: true 
});
```
Whereas the example [here](https://github.com/websanova/vue-auth/blob/master/docs/Methods.md) uses param
```
this.$auth.register({
    params: {}, // data: {} in Axios
    success: function () {},
    error: function () {},
    autoLogin: true,
    rememberMe: true,
    redirect: {name: 'account'},
    // etc...
});
```

On top of that, when using params, it seems the param data is appended as URL strings instead of POST vars. Body doesn't seem to work altogether.

What am I missing?

**Comment by marvinworks** [comment]
why you closed that Isue, hw did you POST vars in body? I am facing the same situation ;)

**Comment by websanova** [comment]
Are you using axios?

**Comment by komirad** [comment]
@marvinworks Try using "data"

**Comment by marvinworks** [comment]
@websanova yes I am

@komirad i already tried

Thanks for the help :) 
Here is my detailed case: https://github.com/websanova/vue-auth/issues/324

**Comment by marvinworks** [comment]
It was a backend CORS Problem.

With the package 'cors' it works. The commented part is what I had before ...

```
// app.use(function(req, res, next) {
//   res.header('Access-Control-Allow-Origin', '*');
//   res.header('Access-Control-Allow-Methods', 'GET, PUT, POST, DELETE, OPTIONS');
//   res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');
//   next()
// });
app.use(cors());
```
