### ISSUE TITLE
[question]: Example for using cookies

### ISSUE THREAD

**Issue by renemarxis** [websanova/vue-auth#322]
Is there any working example on how to use the lib with cookies only (no localStorage)? I'm using axios for http.
Tried to set the tokenStore, tokenDefaultName and token.request/response and i do see the Set-Cookie Header in the response of the login call, but it does not get saved on the client.

One has to inplement a custom auth-driver right?

**Comment by websanova** [comment]
It's token based, there are no cookies. It uses local storage and optionally a cookie.

https://github.com/websanova/vue-auth/blob/master/docs/Options.md#tokenstore-localstorage-cookie
