### ISSUE TITLE
Force fetch of new user object if requests 403 or 401

### ISSUE THREAD

**Issue by pkraus109** [websanova/vue-auth#326]
So lets say a user logs into our SPA token is good for 1 day. The admin then marks the user as inactive on the backend or maybe just changes some roles. How can i force an update user object so the user thats logged in is always current against the last request against our api.

Obviously a refresh of the page causes a new fetch (i think caching might prevent that in production).

User is admin --> goes to admin page --> user roles remove the admin role --> user makes request and it 403's since the user is no longer valid to access those end points.

It would be cool if the user could refetch their details and then redirect in the case of a role change (vue router might just do this) or in the case of the user being inactive i think i can just revoke the token and that should logout the user?

Thanks just trying to get the authorizations nice and tight between client and server.

**Comment by websanova** [comment]
I'm not really sure what you're talking about.

If the token us expired, that's kind of the point, otherwise setup refresh
end point on an interval.

**Comment by websanova** [comment]
There is also a fetch call

**Comment by pkraus109** [comment]
I use fetch and that was really what i was driving at is there a way to force fetch to run.

I was thinking that i would use an axios interceptor to catch 403's and then when it does force fetch to run. I am just not sure how to trigger fetch.

**Comment by websanova** [comment]
Did you try the impersonating flag?

**Comment by pkraus109** [comment]
When the refreshdata function runs does it also call fetch afterwards?

Reading up on the impersonating stuff now.
