### ISSUE TITLE
Token not saved from response using axios

### ISSUE THREAD

**Issue by hannupaasonen** [websanova/vue-auth#327]
I can't get the token saved from response using axios.

Here's the code from main.js:

```
Vue.router = router
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: {url: 'auth/getToken', method: 'POST', redirect: '/', fetchUser: false},
  fetchData: {url: 'profile', method: 'GET', enabled: false}
})

App.router = router
App.store = store
App.template = '<App />'

new Vue(App).$mount('#app')
```

Here's the login-method from App.vue

```
methods: {
  login () {
    this.$auth.login({
      data: {
        username: 'username',
        password: 'password'
      },
      success: res => {
        console.log(res)
        console.log(this.$auth)
      }
    })
  }
}
```

The API returns the token in response body/data but it seems that it isn't saved anywhere:
```{"token":"this_is_a_token_from_server"}```

![screen shot 2018-02-23 at 12 31 39](https://user-images.githubusercontent.com/16918096/36589925-90042c02-1895-11e8-9ffc-914cf8cee2e3.png)

Will I need to save the token manually somehow or overdrive the token-setting in main.js?

**Comment by websanova** [comment]
Should be in the header or write a custom driver. Check the docs

**Comment by hannupaasonen** [comment]
Thank you. Here's my driver.

```
Vue.use(require('@websanova/vue-auth'), {
  auth: {
    request: function (req, token) {
      const refresh = req.url.indexOf('refreshToken') > -1
      token = token.split(';')
      if (!refresh) {
        token = token[0]
        req.headers['Authorization'] = 'Bearer ' + token
      } else {
        token = token[1]
        req.data = {'refresh_token': token}
      }
    },
    response: function (res) {
      if (res.data.token && res.data.refresh_token) {
        return res.data.token + ';' + res.data.refresh_token
      }
    }
  },
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'roles',
  loginData: {url: 'auth/getToken', method: 'POST', redirect: '/', fetchUser: true},
  refreshData: {url: 'auth/refreshToken', method: 'POST', enabled: true, interval: 30},
  fetchData: {url: 'profile', method: 'GET', enabled: true}
})

```

**Comment by stannyc** [comment]
@websanova can you please give me some enlightenment, as I also got similar issue like this  (I'm pretty new to vue so please bare with me). 
So my problem is when I log in,  the I got success response from my backend api (I"m using laravel for backend api, and my AuthController is  a copy-paste from your api demo. Also, I'm using  tymon/jwtauth package). However the fetchUser failed  due to absence of  token in my request header. I can check with dev tool that my response  during login contains Authorization and so the token, but somehow the plugin  seems doesn't save the token on localstorage. 

![screenshot from 2018-06-17 06-31-19](https://user-images.githubusercontent.com/9630523/41502967-a20a2cb8-71f9-11e8-8564-248d56981c54.png)

![screenshot from 2018-06-17 06-31-50](https://user-images.githubusercontent.com/9630523/41502971-a7b04666-71f9-11e8-964b-1bb0ee9b62ba.png)

![screenshot from 2018-06-17 06-31-59](https://user-images.githubusercontent.com/9630523/41502972-ac6454f4-71f9-11e8-8098-87ac13d02353.png)

Here's my login method

`    login(credentials){
      var that = this;
      this.$auth.login({
          data: credentials, // Axios
          rememberMe: true,
          redirect: {name: 'posmain'},
          fetchUser: true
      }).then(() => {
              //console.log('success');
          }, (res) => {
            that.$swal("Error: Wrong Password..!");
            
      });
    }`

I hope someone can help me on this, been spending hours googling around... :(

**Comment by Moppet12** [comment]
I have a very similar issue like @stannyc , same Laravel environment with JWT and vue-auth version. 
Did you find any fix?

**Comment by Jokerwin** [comment]
@stannyc @Moppet12 Seems you don't have the following headers in your responses:
```Access-Control-Allow-Headers: Authorization;
Access-Control-Expose-Headers: Authorization;```

Check out this [https://github.com/websanova/vue-auth/blob/master/docs/Faq.md#backend](https://github.com/websanova/vue-auth/blob/master/docs/Faq.md#backend)

**Comment by KylinWu** [comment]
@Jokerwin Thanks! You really saved the day for me.

**Comment by Jeanpdt** [comment]
> @websanova can you please give me some enlightenment, as I also got similar issue like this (I'm pretty new to vue so please bare with me).
> So my problem is when I log in, I got success response from my backend api (I"m using laravel for backend api, and my AuthController is a copy-paste from your api demo. Also, I'm using tymon/jwtauth package). However the fetchUser failed due to absence of token in my request header. I can check with dev tool that the response during login contains Authorization header and so the token, but somehow the plugin seems doesn't save the token on localstorage, thus no token sent with the fetchUser request, and my api responded the request as unauthorized
> 
> This is my login response header
> ![screenshot from 2018-06-17 06-31-19](https://user-images.githubusercontent.com/9630523/41502967-a20a2cb8-71f9-11e8-8564-248d56981c54.png)
> 
> this is my fetchUser request header
> ![screenshot from 2018-06-17 06-31-50](https://user-images.githubusercontent.com/9630523/41502971-a7b04666-71f9-11e8-964b-1bb0ee9b62ba.png)
> 
> no token in localstoreage
> ![screenshot from 2018-06-17 06-31-59](https://user-images.githubusercontent.com/9630523/41502972-ac6454f4-71f9-11e8-8098-87ac13d02353.png)
> 
> Here's my login method
> 
> ` login(credentials){
> var that = this;
> this.$auth.login({
> data: credentials, // Axios
> rememberMe: true,
> redirect: {name: 'posmain'},
> fetchUser: true
> }).then(() => {
> //console.log('success');
> }, (res) => {
> that.$swal("Error: Wrong Password..!");
> 
> ```
>   });
> }`
> ```
> 
> **versions I use:**
> vue-auth : "^2.21.11-beta",
> axios : "^0.16.1",
> vue : "^2.3.3",
> 
> I hope someone can help me on this, been spending hours googling around... :(

I'm having the same problem, anyone knows how to solve it?

**Comment by websanova** [comment]
@Jeanpdt what driver do you have set for auth? Are you using the "bearer" driver?

**Comment by Jeanpdt** [comment]
Yes.


This.is the post
```
this.$auth.login({
				data: {
					email: app.email,
					password: app.password
				},
				success: function() {
					app.success = true;
					const redirectTo = 'home';
					this.$router.push({name: redirectTo});
				},
				error: function(res) {
					app.has_error = true;
					app.error = res.response.data.error;
				},
				rememberMe: true,
				fetchUser: true
			});
		},
```

And this is the file auth.js

```
import bearer from '@websanova/vue-auth/drivers/auth/bearer';
import axios from '@websanova/vue-auth/drivers/http/axios.1.x';
import router from '@websanova/vue-auth/drivers/router/vue-router.2.x';
/**
 * Authentication configuration, some of the options can be override in method calls
 */
const config = {
	auth: bearer,
	http: axios,
	router: router,
	tokenDefaultName: 'laravel-jwt-auth',
	tokenStore: ['localStorage'],

	// API endpoints used in Vue Auth.
	registerData: {
		url: 'auth/register',
		method: 'POST',
		redirect: '/login'
	},
	loginData: {
		url: 'auth/login',
		method: 'POST',
		redirect: '',
		fetchUser: true
	},
	logoutData: {
		url: 'auth/logout',
		method: 'POST',
		redirect: '/',
		makeRequest: true
	},
	fetchData: {
		url: 'auth/user',
		method: 'GET',
		enabled: true
	},
	refreshData: {
		url: 'auth/refresh',
		method: 'GET',
		enabled: true,
		interval: 30
	}
};
export default config;

```

**Comment by websanova** [comment]
Is there anything in session storage?

**Comment by vovanchuk** [comment]
Had the same problem (with Laravel 7). Resolved by adding to the `bootstrap/app.php`
```
header('Access-Control-Allow-Headers: Authorization');
header('Access-Control-Expose-Headers: Authorization');
```

**Comment by Jeanpdt** [comment]
> Had the same problem (with Laravel 7). Resolved by adding to the `bootstrap/app.php`
> 
> ```
> header('Access-Control-Allow-Headers: Authorization');
> header('Access-Control-Expose-Headers: Authorization');
> ```

It worked, thank you!
