### ISSUE TITLE
Get token from response body

### ISSUE THREAD

**Issue by DenBeke** [websanova/vue-auth#328]
I have been searching for way too long, and trying many things, but I couldn't find anywhere how I can just extract the token from the response body of the login.

My login method looks like this:

```javascript
this.$auth.login({
            url: 'auth/token/',
            data: {
              username: app.email,
              password: app.password
            }, 
            rememberMe: true,
            redirect: '/',
            fetchUser: false
        });
```

General config looks like this:

```javascript
Vue.use(require('@websanova/vue-auth'), {
   auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
   http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
   router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
});
```

And this returns a valid JSON response:

```json
{"refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTUxOTUxMDg5OCwianRpIjoiNzY3M2JiMDZkYmMxNGE0M2FlZmQ3YjIwNDUyY2I2ZjUiLCJ1c2VyX2lkIjoyfQ.5h-SqvnnUvCr70aKmOm7qqgjVV77vjDAYpS1ehfUshA","access":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTE5NDI0Nzk4LCJqdGkiOiJmN2IyZTQzNWJmM2E0ZmYxOGJlMTc3NTlmNDliNjdhNyIsInVzZXJfaWQiOjJ9.86zCg-H8tobRlHYYV8XaF1brM3ksq2eSVtyTy0XIk6E"}
```

But I have no idea how to move from there...
I tried returning the token in the `success` function, tried setting it in the header, but nothing works.

How should I do this? Did miss something in the docs?

**Comment by meetmatt** [comment]
@DenBeke were you able to figure it out?

**Comment by achchu93** [comment]
@DenBeke @meetmatt Hey guys, I was too frustrated with the body based token. I spent 2 days on it and i couldnt find it. Even the doc is not good for a beginner to setup. Anyway finally could find the way how this plugin work and then only i realized the drivers matters on this.

The in built drivers are searching for the token in the Header. So using their any drivers doesnt gonna work. Just write your own one. It is super easy. Have a look at below code. I trust this would help for whoever search for body based toke.

`Vue.use(require("@websanova/vue-auth"), {
auth: {
		request: function (req, token) {
			this.http.setHeaders.call(this, req, {
				Authorization: 'Bearer ' + token
			});
		},

		response: function (res) {
			var body = this.http.httpData.call(this, res);

			if(body.data){
                               // handle the way how your response coming
				return body.data.access_token;
			}
		}
	},
	http: require("@websanova/vue-auth/drivers/http/axios.1.x"),
	router: require("@websanova/vue-auth/drivers/router/vue-router.2.x"),
	loginData: {
		url: '/login',
		method: 'POST',
		redirect: '',
		fetchUser: true,
		staySignedIn: true
	},
	logoutData: {
		url: '/logout',
		method: 'POST',
		redirect: '/login',
		makeRequest: true
	},
	fetchData: {
		url: '/user',
		method: 'GET',
	}
})`

Then play with the plugin!🙌🙌
