### ISSUE TITLE
Pass querystring data on login redirect

### ISSUE THREAD

**Issue by shaunie2fly** [websanova/vue-auth#329]
Hi
Excuse my ignorance if this is a dumb question (probably is) , but how would I pass querystring data on a redirect to login so once the user is logged in they are redirected back to their requested URL with the included querystring params?

Thanks :)

**Comment by websanova** [comment]
you can set an object for the login redirect parameter ;)

**Comment by shaunie2fly** [comment]
Thanks websanova,
I was nearly there.  Instead of modifying the redirect object in the `$auth.login() ` function i was trying to do it in the routes.
  ```
 this.$auth
        .login({
          data: this.credentials,
          rememberMe: this.rememberMe,
          redirect: {name: redirect ? redirect.from.name : "homeDash",  **query: redirect.from.query** },
          fetchUser: true
        })
```

Thanks for the response :)
