### ISSUE TITLE
token is not set

### ISSUE THREAD

**Issue by Rockatweb** [websanova/vue-auth#330]
Hi, i have the problem, that the login request does not set the token that it receives from the APIs Authorization Header.

So the request response from the api is this:

![bildschirmfoto 2018-03-05 um 20 08 58](https://user-images.githubusercontent.com/2091906/36994483-915ee262-20b1-11e8-8132-057a446d97ab.png)

And i put a console.log in the bearer.js but as you can see there is no Authorization Header. What am i doing wrong? oO

![bildschirmfoto 2018-03-05 um 20 09 18](https://user-images.githubusercontent.com/2091906/36994535-b37f5cf0-20b1-11e8-9fd0-395b6a601685.png)

The Login Code
```
<template>

    <div id="overlayBox">

        <div id="overlay">
            <div class="topBox">
                <img src="../../assets/images/logo_white.svg" class="logo" />
            </div>
            <div id="adminLogin">

                <form v-on:submit.prevent="doLogin()" method="post">

                    <label for="login">Name</label>
                    <input type="text" name="name" v-model="login.name" id="login" />

                    <label for="password">Passwort</label>
                    <input type="password" name="password" v-model="login.password" id="password" />

                    <div v-if="error !== ''">
                        {{error}}
                    </div>

                    {{$auth.check()}}

                    <input type="submit" value="Einloggen" />
                </form>

            </div>
        </div>
    </div>

</template>

<script>
    let qs = require('qs');

    export default {
        data() {
            return {
                login: {
                    name: '',
                    password: ''
                },
                error: ''
            }
        },
        methods: {
            doLogin() {
                this.$auth.login({
                    url: process.env.API_URL + 'data/login',
                    data: qs.stringify(this.login),
                    method: 'post',
                    success: (response) => {
                        console.log('ok', this.$auth);
                    },
                    error: (reject) => {
                        this.error = 'Login fehlerhaft'
                    },
                    redirect: '/admin',
                    fetchUser: false
                });
            }
        }
    }

</script>
```

and the app.js
```...

Vue.router = router;


Vue.use(VueLocalStorage);

Vue.config.productionTip = false;

Vue.use(VueAxios, axios);


Vue.axios.defaults.baseURL = process.env.API_URL;
Vue.axios.defaults.headers.common['Accept'] = 'application/json';
Vue.axios.defaults.headers.common['Content-Type'] = 'application/json;charset=UTF-8';
Vue.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';


Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    authRedirect: {
        path: '/admin-login'
    },
});
```

**Comment by websanova** [comment]
The header is not name correctly ;)

**Comment by websanova** [comment]
need to use basic auth if you don't include bearer

**Comment by Rockatweb** [comment]
wait, what is wrong with the name of the Header?

I tried the basic auth and there is also no Authorization header.

![bildschirmfoto 2018-03-06 um 08 52 06](https://user-images.githubusercontent.com/2091906/37020336-b58b29d8-211b-11e8-80b5-11bcc2506a68.png)

**Comment by hamdallah90** [comment]
+1

**Comment by websanova** [comment]
You need to return header in proper format for the driver.

**Comment by meliborn** [comment]
Have the same issue. In devise driver `response` method, `res` variable comes only with 2 headers.
![monosnap 2018-06-07 16-33-21](https://user-images.githubusercontent.com/735194/41102980-c13600de-6a70-11e8-89d7-786cb5946591.png)

But server response looks like:
![monosnap 2018-06-07 16-35-52](https://user-images.githubusercontent.com/735194/41103045-e408e2d4-6a70-11e8-8a77-a7c08d04e476.png)
Where're other headers?

**Comment by borie88** [comment]
That did it, thanks @meliborn . Anyone using Quasar Framework should have to do this on their dev server
