### ISSUE TITLE
this.$auth.token() returns null

### ISSUE THREAD

**Issue by lnufnu** [websanova/vue-auth#331]
$auth.token is unexpectedly returning null. I started with the Vue-CLI and added the demo application components to work with my server's endpoints.

In my main file, I require the driver:
```
Vue.use(require('@websanova/vue-auth'), {
  loginData: {url: 'login', method: 'POST', redirect: '/', fetchUser: true},
  fetchData: {url: 'users', method: 'GET', redirect: '/', enabled: true},
  refreshData: {url: 'refresh', method: 'GET', enabled: true, interval: 60},
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
})
```

I can see the bearer refresh tokens in the inspector, but in `Login.vue` I log `this.$auth.token()` and `localStorage.getItem('default-auth-token')`. They are both `null`.

Is there something I am doing wrong or may have failed to do? Thanks in advance for any suggestions.

<img width="929" alt="screen shot 2018-03-06 at 12 35 27 am" src="https://user-images.githubusercontent.com/11732163/37018361-b1e173ba-20d9-11e8-9b1e-3cc3511fa6bc.png">
<img width="920" alt="screen shot 2018-03-06 at 1 01 30 am" src="https://user-images.githubusercontent.com/11732163/37018442-005df5e0-20da-11e8-9846-0cfaa553ba95.png">

dependencies:
* "@websanova/vue-auth": "^2.21.3-beta",
* "axios": "^0.18.0",
* "vue": "^2.5.2",
* "vue-axios": "^2.0.2",
* "vue-router": "^3.0.1
Browser: Chrome Canary, Chrome (Stable), and Chromium

**Comment by websanova** [comment]
Should be fine, are you incognito mode or someting like that?

**Comment by lnufnu** [comment]
No. I just tried Safari, and it's the same.

**Comment by lnufnu** [comment]
Thank you for your quick response. I added `header('Access-Control-Expose-Headers', 'Authorization')` to the server code, and it worked.

It would be helpful if this was in the docs.

**Comment by steveops** [comment]
I almost hung myself trying to get auth to work. Everything was set up correctly on the client and server side but somehow it wasn't working. Was on it for a whole 12 hrs wondering what I was doing wrong, especially since I've used this package successfully before. Turns out I only needed `header('Access-Control-Expose-Headers', 'Authorization')` on my server! Jesus! @websanova maybe you can mention this somewhere in the `bearer` driver docs, just to help someone next time?

**Comment by websanova** [comment]
Feel free to submit a pull request ;)

**Comment by trmichaelmanlulu** [comment]
omfg. This solution finally worked!
@steveops same here bro same here!
