### ISSUE TITLE
fetching the user and checking roles

### ISSUE THREAD

**Issue by dgriego** [websanova/vue-auth#333]
it may be that I'm confused about the process, but I'm confused about what object `roles: 'admin'` is checking against?

so after I call `$auth.login()` which works fine, the token is set in local storage, which also works fine, but then this is where the confusion begins.  The JWT token contains the roles and necessary information about the user so is the fetchUser method decoding the token and checking for a property named roles? or is it expecting to make another request that returns this information?

sorry if this is confusing because I am confused myself.  I am happy to further clarify if this does not make sense, but basically I want to understand the idea of 'roles' and what vueAuth is trying to do with the token after the login process.  I want to utilize `$auth.user()`, but the information I need is already contained within the token and I don't need to make another request to get it.

Thanks for taking time to read this!

**Comment by websanova** [comment]
the user object should contain the necessary role parameter as per docs.
