### ISSUE TITLE
Integration with Quasar 0.15

### ISSUE THREAD

**Issue by sumpfgottheit** [websanova/vue-auth#334]
I've used vue-auth together with Quasar <= 0.14 for a few months.
I want to upgrade to 0.15. In this release, the configuration/integration of vue-router/axios has slightly changed and I am not able to come up with a solution.

Would it be possible to include a guide how to integrate vue-auth with Quasar 0.15?

**Comment by sustained** [comment]
I too am struggling to get this working with Quasar.

**Comment by websanova** [comment]
No idea about Quasar.

**Comment by wenmingpig** [comment]
add vue-auth at plugins\boot.js.

**Comment by arkhenstone** [comment]
@sumpfgottheit Look at neatpro's Quasar JWT repository on github, it's a starter kit embedding vue-auth see store (uses Vuex !)

**Comment by slegouffe** [comment]
Hi there ! 
neatpro's Quasar JWT is fine but not following the "App plugins" rules introduced in 0.15 as Vue-Auth and Axios are declared in Router and not in "plugins" folder. 
So here is my solution  : 
`npm quasar new plugin axios` then configure as needed
`npm quasar new plugin vueAuth` then configure as needed
And now the magic tricks : in `router/index` change `const Router` = ... by `Vue.router` and finally `export default Vue.router`
In `quasar.conf.js` set `plugins` array by calling "axios" before "vueAuth". 
```
module.exports = function (ctx) {
  return {
    // app plugins (/src/plugins)
    plugins: [
      'i18n',
      'axios',
      'vueAuth',
    ],
   ....
```

**Comment by nurikabe** [comment]
I've kind of got this working with Quasar.  I can authenticate and redirect to my target page, but it seems the token is not getting applied to subsequent requests, so I always get kicked back to login.  Any ideas?

**Comment by websanova** [comment]
Can you verify the token exists, and are you using "ready" to make sure
it's all loaded beforehand?

**Comment by onurkose** [comment]
check this:
https://github.com/websanova/vue-auth/issues/237#issuecomment-388009565

**Comment by onurkose** [comment]
check this out:
#237
