### ISSUE TITLE
Authentication Problem with JWT and Token Storage

### ISSUE THREAD

**Issue by sattlerio** [websanova/vue-auth#336]
Hi,

here is my Vue Object:

```
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x'),
  fetchData: {url: 'http://localhost:5000/auth/user', method: 'GET', enabled: true},
  tokenDefaultName: 'access_token',
  parseUserData: function (response) {
    console.log('found user')
    return response.data.user
  },
  tokenStore: ['localStorage']
})
```

Here is my login:

```
this.$auth.login({
                data: {
                  username: this.model.email,
                  password: this.model.password
                },
                success: function (response) {
                  alert(response)
                  console.log(response)
                  this.$auth.user = response.data
                },
                error: function (res) {
                  console.log(res.data)
                  console.log(res)
                  this.$notify({
                    component: {
                      template: `<span><strong>Oops, something went wrong... </strong><br>Not possible to login because of an internal server error</span>`
                    },
                    icon: 'fa fa-exclamation',
                    horizontalAlign: 'right', // right | center | left
                    verticalAlign: 'top', // top | bottom
                    type: 'danger'  // info | success | warning | danger
                  })
                  this.model.error_msg = 'Not possible to login'
                },
                rememberMe: true,
                url: 'http://localhost:5000/auth/login',
                redirect: '/dashboard',
                fetchUser: true
              })
```

The workflow should be 
* POST to /login the API returns the token (this works)
* Store the token (this doesnt work)
* Use the Token for the fetch user route (this doesnt work)

If vue posts to the /login route the API returns the following:

```
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjA5Mzg2MTcsIm5iZiI6MTUyMDkzODYxNywianRpIjoiZTZiNmViNTItMTI4NC00NzA5LWEwYTMtOTk5YTM4YmIyMTcwIiwiZXhwIjoxNTIwOTM5NTE3LCJpZGVudGl0eSI6eyJmaXJzdG5hbWUiOiJHZW9yZyIsImxhc3RuYW1lIjoiU2F0dGxlciIsImVtYWlsIjoiZ2VvcmdAc2F0dGxlci5pbyIsInV1aWQiOiI2ZTU1OGZjM2ExYjg0MTQ0YWQ1ODU1N2JlYWMxMjFkOCJ9LCJmcmVzaCI6dHJ1ZSwidHlwZSI6ImFjY2VzcyJ9.0EhkUXZpG4WTxhnDvQQp8i97GaNXoNyp24P7qLMRUPM", 
  "message": "successfully logged in - welcome", 
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjA5Mzg2MTcsIm5iZiI6MTUyMDkzODYxNywianRpIjoiNzAxNTAxYWYtODJjMC00YmQ5LTg1YjAtZjQ0ZTNjNzgzYmY1IiwiZXhwIjoxNTIzNTMwNjE3LCJpZGVudGl0eSI6eyJmaXJzdG5hbWUiOiJHZW9yZyIsImxhc3RuYW1lIjoiU2F0dGxlciIsImVtYWlsIjoiZ2VvcmdAc2F0dGxlci5pbyIsInV1aWQiOiI2ZTU1OGZjM2ExYjg0MTQ0YWQ1ODU1N2JlYWMxMjFkOCJ9LCJ0eXBlIjoicmVmcmVzaCJ9.gRH3nJQEaBc2_0iZ9E9fhGg-9i-fil8c5SOvh8Tvsbg", 
  "request_id": "037dd993-1c19-4c68-8e5a-e060e11d3ce8", 
  "status": "OK"
}
```
If i check the local storage in the dev tool it seems to be empty

How can I tell vue-auth to store the access token?
Thanks

**Comment by websanova** [comment]
You are using bearer driver but not sending a proper bearer token in Authentication header.

You will need to write a custom driver. Check the docs ;)

**Comment by erijonhson** [comment]
Hello,

In my case we use basic driver and all works fine in development. But, in production (after build, minification, etc), the token don't save on localStorage or cookie. See response example:

![image](https://user-images.githubusercontent.com/10831613/44227362-c515a180-a168-11e8-87f8-03327a1e4628.png)

Any ideas about that?

**Comment by websanova** [comment]
Seems like an issue with the build. No errors?

**Comment by erijonhson** [comment]
I've decided to remove vue-auth and do it myself, because it's a simple authentication. However, in the future, choosing vue-auth interests me. 

In addition, it follows the build configuration. No error occurred:

```js
'use strict'
const path = require('path')
const utils = require('./utils')
const webpack = require('webpack')
const config = require('../config')
const merge = require('webpack-merge')
const baseWebpackConfig = require('./webpack.base.conf')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')

const env = process.env.NODE_ENV === 'testing'
  ? require('../config/test.env')
  : require('../config/prod.env')

const webpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: true,
      usePostCSS: true
    })
  },
  devtool: config.build.productionSourceMap ? config.build.devtool : false,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
  },
  plugins: [
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new UglifyJsPlugin({
      uglifyOptions: {
        compress: {
          warnings: false
        }
      },
      sourceMap: config.build.productionSourceMap,
      parallel: true
    }),
    // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css'),
      // Setting the following option to `false` will not extract CSS from codesplit chunks.
      // Their CSS will instead be inserted dynamically with style-loader when the codesplit chunk has been loaded by webpack.
      // It's currently set to `true` because we are seeing that sourcemaps are included in the codesplit bundle as well when it's `false`, 
      // increasing file size: https://github.com/vuejs-templates/webpack/issues/1110
      allChunks: true,
    }),
    // Compress extracted CSS. We are using this plugin so that possible
    // duplicated CSS from different components can be deduped.
    new OptimizeCSSPlugin({
      cssProcessorOptions: config.build.productionSourceMap
        ? { safe: true, map: { inline: false } }
        : { safe: true }
    }),
    // generate dist index.html with correct asset hash for caching.
    // you can customize output by editing /index.html
    // see https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: process.env.NODE_ENV === 'testing'
        ? 'index.html'
        : config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency'
    }),
    // keep module.id stable when vendor modules does not change
    new webpack.HashedModuleIdsPlugin(),
    // enable scope hoisting
    new webpack.optimize.ModuleConcatenationPlugin(),
    // split vendor js into its own file
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks (module) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf(
            path.join(__dirname, '../node_modules')
          ) === 0
        )
      }
    }),
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      minChunks: Infinity
    }),
    // This instance extracts shared chunks from code splitted chunks and bundles them
    // in a separate chunk, similar to the vendor chunk
    // see: https://webpack.js.org/plugins/commons-chunk-plugin/#extra-async-commons-chunk
    new webpack.optimize.CommonsChunkPlugin({
      name: 'app',
      async: 'vendor-async',
      children: true,
      minChunks: 3
    }),

    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
  ]
})

if (config.build.productionGzip) {
  const CompressionWebpackPlugin = require('compression-webpack-plugin')

  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\\.(' +
        config.build.productionGzipExtensions.join('|') +
        ')$'
      ),
      threshold: 10240,
      minRatio: 0.8
    })
  )
}

if (config.build.bundleAnalyzerReport) {
  const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
  webpackConfig.plugins.push(new BundleAnalyzerPlugin())
}

module.exports = webpackConfig
```

Using, among others: 
- **vue ^2.5.2**
- **vue-resource ^1.5.1**
- **vue-router ^3.0.1**
- **vue-auth ^2.21.14-beta**
- **webpack ^3.6.0**

**Comment by KosratDAhmad** [comment]
I have the same issue with the latest version, even I have the Authorization header but still not saved 

<img width="607" alt="Screen Shot 2020-05-04 at 02 46 12" src="https://user-images.githubusercontent.com/10336475/80929027-88ad2d80-8db1-11ea-888c-b7cf20891e38.png">

**Comment by websanova** [comment]
Which auth driver are you using?

From the pic that should be basic driver

**Comment by KosratDAhmad** [comment]
I have tested it on `basic` and `bearer` but didn't work

**Comment by KosratDAhmad** [comment]
I have fixed it by adding the following headers:
```
header('Access-Control-Expose-Headers: Authorization');
header('Authorization: Bearer '.$token.'');
```
and I have a question why we should return the token from the response header as I have seen in the JWT website and all other websites will return the token from **body response** like that 
```
{
  "access_token":"MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3",
  "token_type":"bearer",
  "expires_in":3600,
  "refresh_token":"IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk"
}
```
is there any standards to be return in **header**??

**Comment by websanova** [comment]
Not sure what is the official or if it there is one. I think I just kind of started it that way because that was the default in Laravel JWT plugin that I used on the API side of things.

But in general doing it via headers seems a lot cleaner than muddying up the responses.

If you really want to do it in the response body though, it's easy enough to roll your own auth driver.

https://websanova.com/docs/vue-auth/guides/drivers

**Comment by KosratDAhmad** [comment]
I have another issue: Unauthorized (status code: 401) response will not redirect to login page.

**Comment by websanova** [comment]
Ok, well did you try any debugging? Any clues?

Can't help you much from just that.

**Comment by HenrijsS** [comment]
I'm still having an issue with this. I'm trying to store a bearer token in LocalStorage. 
As seen in a screenshot before, it still shows up in response headers but checking VueX in the devtools it doesn't store it. 
The $auth store at all isn't showing up even though it is implemented.

And also when trying to redirect from the login page, it shows a 401 when calling /api/user which is understandable as the token isn't being sent.
Login function: 
`this.$auth.login({
        params: {
          email: this.form.email,
          password: this.form.password
        },
        success: function(response) {
          // handle redirection
          this.$auth.user = response.data;
          const redirectTo = redirect
            ? redirect.from.name
            : this.$auth.user().role === "admin"
            ? "admin.dashboard"
            : "dashboard";
          this.$router.push({ name: redirectTo });
        },
        error: function() {
          this.has_error = true;
        },
        rememberMe: true,
        fetchUser: true
      });`
![image](https://user-images.githubusercontent.com/49265222/83337832-3b947c80-a2c7-11ea-9529-f8156ef7e8be.png)

`Vue.use(require('@websanova/vue-auth'),auth);`

Auth.js
`import bearer from '@websanova/vue-auth/drivers/auth/bearer'
import axios from '@websanova/vue-auth/drivers/http/axios.1.x'
import router from '@websanova/vue-auth/drivers/router/vue-router.2.x'

export default {
    auth: bearer,
    http: axios,
    router: router,
    tokenDefaultName: 'access_token',
    tokenStore: ['localStorage'],
    rolesKey: 'status',
    registerData: {
        url: 'auth/register',
        method: 'POST',
        redirect: '/'
    },
    loginData: {
        url: 'auth/login',
        method: 'POST',
        redirect: '/',
        fetchUser: true
    },
    logoutData: {
        url: 'auth/logout',
        method: 'POST',
        redirect: '/login',
        makeRquest: true
    },
    fetchData: {
        url: 'auth/user',
        method: 'GET',
        enabled: true
    },
    refreshData: {
        url: 'auth/refresh',
        method: 'GET',
        enabled: true,
        interval: 30
    }
}`

**Comment by websanova** [comment]
What's the format you are sending the token in?

**Comment by KosratDAhmad** [comment]
@websanova please get the login token from the **body response** instead from **header response**, it will be more general as I have searched, the backend developer should customize the header response for this library because by default the login token will not be returned from header response.

**Comment by websanova** [comment]
Ahh, well those are standard defaults for basic/bearer auth as far as I know, and you can set it any way you like otherwise.

https://websanova.com/docs/vue-auth/guides/drivers

**Comment by KosratDAhmad** [comment]
@websanova can you give us a resource that talks about these standards??

**Comment by websanova** [comment]
@kosratdev same as your searching, maybe not so official :-)

Anyway, the point is you can change the auth driver to whatever you like, just look at any existing one as an example.

https://github.com/websanova/vue-auth/blob/master/drivers/auth/basic.js
