### ISSUE TITLE
Is there any way to setup tokens without making ajax query

### ISSUE THREAD

**Issue by tpoxa** [websanova/vue-auth#337]
Hello. My access and refresh tokens are come from GET request during server side redirect.
So can I setup them into the vue-auth without doing ajax request of login method

For now I stopped with this:

```
export default {
  created: function () {
    this.$auth.login({
      data: {access_token: this.$route.query.access_token, refresh_token: this.$route.query.refresh_token}
    })
  }
}
```

Login response the same as requested. It works but I would like to drop this extra request.

Thank you.

**Comment by websanova** [comment]
Did you check the docs at all?

~~~
$auth.token('token');.
~~~

**Comment by tpoxa** [comment]
Yes, I tried but it doesn't work.

My auth response  is. Cause I use two types of tokens.
```
response: function (res) {
      if (res.data.access_token && res.data.refresh_token) {
        return res.data.access_token + ';' + res.data.refresh_token
      }
    }
```

So I tried:

```
created: function () {
    this.$auth.token(this.$route.query.access_token + ';' + this.$route.query.refresh_token)
// this.$auth.token('default', this.$route.query.access_token + ';' + this.$route.query.refresh_token)
// this.$auth.token('access_token', this.$route.query.access_token + ';' + this.$route.query.refresh_token)
    this.$router.push('/')
  }
```

But it doesn't work.

**Comment by websanova** [comment]
Huh? Seems you're using query in one but not the other.

**Comment by tpoxa** [comment]
@websanova
>you're using query in one but not the other.
 What you mean?
As I understood response is only for handling response from login method.
My goal is setup two tokens with help of $auth.token()  function

So entire code is next
`
Vue.use(auth, {
  auth: {
    request: function (req, token) {
      token = token.split(';')
      token = req.url.indexOf('refresh') > -1 || req.url.indexOf('logout') > -1 ? token[1] : token[0]
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    },
    response: function (res) {
      // console.log(res)
      if (res.data.access_token && res.data.refresh_token) {
        return res.data.access_token + ';' + res.data.refresh_token
      }
    }
  },
  rolesVar: 'role',
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: {url: 'auth/token', method: 'POST', redirect: '/', fetchUser: false},
  refreshData: {url: 'auth/refresh', method: 'POST', enabled: true, interval: 30},
  fetchData: {url: 'account', method: 'GET', enabled: true},
  logoutData: {url: 'auth/logout', method: 'POST', redirect: '/', makeRequest: false}
})
`
I need to setup my tokens from query params.

Currently I am doing next

`
<template>
  <div class="fixed fixed-center">Loading...</div>
</template>
<script>
export default {
  created: function () {
    this.$auth.login({
      data: {access_token: this.$route.query.access_token, refresh_token: this.$route.query.refresh_token},
      rememberMe: true
    })
  }
}
</script>

`

Can someone suggests solution?

**Comment by vesper8** [comment]
@tpoxa did you figure out how to login without doing the login post request? I need a way of mocking the login, I have the token stored locally and I want to end up with a logged-in state without making any api requests at all
