### ISSUE TITLE
How to override refresh token method?

### ISSUE THREAD

**Issue by rajagopalx** [websanova/vue-auth#338]
By default, To get refresh token, the existing token is passed in Header through GET method.

How to get refresh token by sending POST request with the existing token in the request body.

**Comment by websanova** [comment]
Are you kidding me?
https://github.com/websanova/vue-auth/blob/master/docs/Options.md#refreshdata-url-authrefresh-method-get-enabled-true-interval-30

**Comment by rajagopalx** [comment]
I saw tat. Even If I change method to POST token is send in request header. Is there any way to send token in body?

**Comment by websanova** [comment]
Just write your own driver.

https://github.com/websanova/vue-auth/tree/master/drivers
