### ISSUE TITLE
how to handle invalid username or password case?????

### ISSUE THREAD

**Issue by itdpong** [websanova/vue-auth#340]
what is the best practice to handle a wrong username or password case??
return a false value? return a error on request???
I found that only return error can stop the login redirect to other page.
the following script will always redirected nomatter your password is right or wrong 
```
  toLogin() {
      this.$auth.login({
        data: {
          username: this.username,
          password: this.password
        },
        rememberMe: true,
        url: process.env.API_URL + '/api/auth/login',
        redirect: '/home',
        fetchUser: false,
        success(response){
          if (response.data.success===true){
            this.$auth.user(response.data.user)
          } else {
            alert("invalid username");
            return false;
          }
        },
        error(err){
          console.log(err);
        }
      });
```

**Comment by websanova** [comment]
huh? Not really sure what you're saying. You said it always redirects but not on error. You are contradicting yourself.

**Comment by itdpong** [comment]
when user input a wrong password and validate by a backend server(node.js), what should the backend server should return to front end side??

**Comment by websanova** [comment]
I think you are confused. It's not really anything to do with the plugin.

Typically backend will send back a 4xx response for validation errors.
