### ISSUE TITLE
Inject JWT token to be used with different API endpoints

### ISSUE THREAD

**Issue by jap1968** [websanova/vue-auth#345]
We are developing a Vue application that gets data from different APIs

Currently `vue-auth` seems to be oriented to use just one API. Once the user gets authenticated, the JWT token is injected into subsequent calls to the same API endpoint used to perform the used authentication. So, `vue-auth` is assuming that just one API will be used, the process of user authentication as well as the application specific functions will be done by the same API.

Our context is a bit different, since we have an API endpoint specific for user authentication. Once the user gets authenticated, the application makes calls to different API endpoints (in fact, more than one) to manage application specific data. So, we need the JWT token obtained in the authentication step to be injected into any API calls.

One possible solution will be to have optional functions like `onUserAuthenticated` and `onTokenRefresh` so we could inject the new (or refreshed) token into the API calls. So far, we are using the `parseUserData` function, but this is not an optimal solution, and we can not update the token when it gets refreshed.

We have at least two endpoint URLs defined into our environment vars (`AUTH_ENDPOINT`, `HIS_ENDPOINT`) and we need both of them to have the JWT token injected into their calls.

```js
Vue.use(VueAxios, axios)
Vue.axios.defaults.baseURL = process.env.AUTH_ENDPOINT

...
export const HTTP_HIS = axios.create({
  baseURL: process.env.HIS_ENDPOINT,
  headers: {
  }
})
...

Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  parseUserData: function (response) {
    HTTP_HIS.defaults.headers.Authorization = 'Bearer ' + localStorage.getItem('default_auth_token')
    return response.data
  }
})
```
So, the question is this one: What should we do in order to inject the JWT token for the calls to other different APIs when the user gets authenticated as well as every time the token gets refreshed?

**Comment by websanova** [comment]
uhhh

This has nothing to do with vue-auth.

Just set the full path wherever you want.

~~~
$auth.login({
   url: 'some other url'.
});
~~~

You can also override any paths via config ;)
