### ISSUE TITLE
Can't get privileges (roles) working on routes (and checks)

### ISSUE THREAD

**Issue by cvgeldern** [websanova/vue-auth#347]
I'm afraid I'm annotating it wrong, but I tried everything to get roles working on routes (meta auth) and checks (auth check).

I have a VueJS 2.5.16 project with vue-auth 2.21.3-beta basically working (register, login, logout, user, etc.) against a Laravel backend with jwt-auth and permissions. The only issue I have is getting roles in vue-auth to work. Somehow it always returns false (forbidden).

These both don't work (I tried all sting, array and object values mentioned in the documentation):
```javascript
<div v-if="$auth.check([{'name': 'user', 'name': 'superadmin'}])">whoop whoop</div>
<div v-else>bummer...<br>{{ $auth.user().roles }}</div>`
```
and
```javascript
meta: { auth: [{'name': 'user'}] }
```
User object
```javascript
{
  id: 4,
  name: 'Example',
  email: 'example@example.com',
  roles: [{ 
    'id': 28,
    'name': 'user'
  },
  { 
    'id': 13,
    'name': 'support'
  }]
}
```

Other contructions do work (meta: {auth: true/false}; $auth.user(); etc.). I'm only unlucky matching roles.

**Comment by websanova** [comment]
Did you try:

```
meta: { auth: {'name': 'user'} } // or
meta: { auth: {'name':['user', 'manager']}
```

Something like that?

**Comment by cvgeldern** [comment]
@websanova 
Yes I did. And again with your examples (you have a typo in your 2nd meta line), roles still don't match. I tried, array[] within object{} notation and viceversa, with and without 'roles' key. 

It might have something to do with role objects in an roles array within the user object. I've seen it before where I had to handle the different responses from Laravel being an object {} (single model), array [] (simple data) or an array of objects [{}] (collection).

There must be a way of getting to match the role name, but I just can't get it right.

**Comment by websanova** [comment]
Ok yes.

Sry, I messed that up a bit. Also the docs had some typos.

I've updated it all. And added some comparison examples:

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md#comparing-roles

Let me know if that makes more sense.

**Comment by cvgeldern** [comment]
@websanova 
It does make more sense and it clarifies that my server side response, an array of role objects is not  suitable for matching. It either has to be a single object with one ore more role values or an flat array of role values.

My user object must be converted to somethin like this (if using multiple roles in the user object):
```javascript
{
  id: 4,
  name: 'Example',
  email: 'example@example.com',
  roles: { 
    'customers': 'support',
    'admin': 'user'
  }
}
```
or
{
  id: 4,
  name: 'Example',
  email: 'example@example.com',
  roles: [
    'support',
    'user'
  ]
}

**Comment by cvgeldern** [comment]
> I'll check it and update if that works.
It does, using the 2nd option:
`{
  id: 4,
  name: 'Example',
  email: 'example@example.com',
  roles: [
    'support',
    'user'
  ]
}`

**Comment by ojdgaf** [comment]
@websanova 
Yeah, it would be really nice to have an option for `array` of role `objects`. Anyway, thanks for the great library!

**Comment by JenteVH** [comment]
@websanova Is this being considered? If sent in a PR, would it be accepted?

**Comment by websanova** [comment]
@JenteVH, sure if you like :-)

I'm planning to rewrite a version of 3 of this very soon, so that would be nice to have to incorporate.
