### ISSUE TITLE
Set route for JWT token retrieval

### ISSUE THREAD

**Issue by fabiankaimer** [websanova/vue-auth#348]
Is there a possibility to change the route, where the JWT token is retrieved from? I know, that the login and the user route can be altered but I could not find an appropriate configuration solution for the token, so far.

**Comment by websanova** [comment]
Did you check the docs at all?

https://github.com/websanova/vue-auth/blob/master/docs/Options.md#refreshdata-url-authrefresh-method-get-enabled-true-interval-30

**Comment by fabiankaimer** [comment]
Yes, I have read them several times and I also had a look into your demo projects. I basically read everything available on the internet concerning your vue-auth project. I have set up everyting correctly and I can also send a login request to my Sails.js backend, using "Waterlock JWT authentication". My login state ($auth.check()) switches to true but neither a token, nor the user information are stored anywhere.

The problem - as I think - is, that vue-auth is searching for the token in the response from my "/login" route but waterlock returns the user data as a response, by default. Therefore, I would like vue-auth to retrieve the token in a second request from the "/user/jwt" route. I'm not sure, if this is even the actual problem, as no errors or feedbacks are being returned after executing the login function but it would explain why nothing is saved or retrieved when I try to access $auth.token() or $auth.user().

As I said, I have read the docs but I do not understand where I can configure vue-auth the way that it looks for the JWT at "/user/jwt" and I also do not understand where my problem might be coming from. A more detailed documentation for beginners or a Problem-FAQ would be very cool.

**Comment by websanova** [comment]
Did you look at refresh?
