### ISSUE TITLE
redirect hook?

### ISSUE THREAD

**Issue by renemendoza** [websanova/vue-auth#349]
I am able to determine weather I was redirected
inside a component i am able to do

``` javascript
       if ( this.$auth.redirect() ) {
       let message = 'El recurso solicitado requiere identificación';
         this.$toast.open({
           message: message,
           duration: 5000,
           type: 'is-danger',
           position: 'is-bottom-right'
         })
       }
```

and it works whenever i try to hit a route under /admin _and I am logged out_

```javascript
const routes = [
  path: '/admin', component: AdminDashboard, meta: {auth: true},
....

```

However i am unable to determine weather i have landed on /login  because the token has expired, 
`this.$auth.redirect()` always returns false when i have been redirected to /login

how can i accomplish this?
is there an option to **authRedirect** that can be used?

thanks!

**Comment by websanova** [comment]
are you sure you don't have other redirects client side?

**Comment by renemendoza** [comment]
hi @websanova I dont think i have any. 

**/login** redirects to **/admin/** when presented with the right credentials of course. and **/admin/** redirects to **/login** both when the user is unauthenticated and when the token has _expired_ and a **401** is received. The API will not say anything regarding token being expired unfortunately.

**Comment by websanova** [comment]
Why don't you just create another intercept and do some console log to see what is going on.

**Comment by renemendoza** [comment]
I have added some server logic to send a 'Token expired' error that i can catch in an interceptor.
This also logs the user out and send a proper message so that is a win. However if the user was visiting a component that made multiple API calls to the server, my code is being executed N times. i added a check in the interceptor my solution overall is not very clean but i got it working. thanks
