### ISSUE TITLE
login redirect object url exploding the uri

### ISSUE THREAD

**Issue by jkirkby91-2** [websanova/vue-auth#35]
After logging in im trying to redirect the app to a page called "/find"

but i keep getting redirected to the 404 page.

In the fetchPerform function if i console.log(data.redirect)

the object.redirect should contain the url "/find"

but the logged data is redirect
:
Object
0
:
"/"
1
:
"f"
2
:
"i"
3
:
"n"
4
:
"d"
name
:
"/account"

the loginData object in auth.js is set like 

```
    loginData:          {url: 'auth/login',        method: 'POST', redirect: '/find'},
```

can you explain why this is doing this?

**Comment by websanova** [comment]
Hmm, what version are you using?

I just tested it and it seems to work. Also as a fix for now you can try setting `redirect` to `{path: '/find'}`.

**Comment by jkirkby91-2** [comment]
im using the 1.0.0beta with a fresh install, im redirected to the account page but never the actual page set as a redirect in the auth.js

console logging the data object in the success callback of fetchperform shows this

{"url":"auth/login","method":"POST","redirect":{"0":"/","1":"f","2":"i","3":"n","4":"d","name":"account"},"body":{"email":"admin@admin.com","password":"admin"},"rememberMe":false,"query":{},"root":"http://api.dev"}

it looks like its redirecting to the name not the value of [0]

**Comment by websanova** [comment]
There is no 1.0.0-beta, do you mean 1.1.0-beta?

**Comment by websanova** [comment]
Also can you give me version of vue and vue-modules you are using.

**Comment by jkirkby91-2** [comment]
Sorry 1.0.0 version of vue 1.1.0-beta of your auth code, 

heres my package.json on gist
https://gist.github.com/jkirkby91-2/b5ee7f385972e61032b686caeb4e6196

**Comment by websanova** [comment]
Can I see some of your code.

How you are initializing it.

**Comment by jkirkby91-2** [comment]
literally standard app all ive added is two vue pages find and link list nothing elese modified, here is the app.js

https://gist.github.com/jkirkby91-2/7307347e407975a602c9d6d78db2662a

**Comment by websanova** [comment]
So where are you setting that loginData?

**Comment by jkirkby91-2** [comment]
in login.vue nothing changed apart from username to email

 export default {
        data() {
            return {
                context: 'login context',

                data: {
                    body: {
                        email: '',
                        password: ''
                    },
                    rememberMe: false
                },

                error: null
            };
        },

        methods: {
            login() {
                this.$auth.login({
                    body: this.data.body,
                    rememberMe: this.data.rememberMe,
                    redirect: {name: 'account'},
                    success() {
                        console.log('success ' + this.context);
                    },
                    error(res) {
                        console.log('error ' + this.context);

                        this.error = res.data;
                    }
                });
            }
        }
    }

**Comment by websanova** [comment]
Ok, so I see you are hacking the plugin directly? Can you make sure it's the latest version. Or send me your hacked version rob@websanova.com (also with the lib/*.js files).

**Comment by websanova** [comment]
One thing.... if you update the plugin manually, but only the main file and not the utils, that maybe an issue...

**Comment by websanova** [comment]
Ok, so this is working for you now?

**Comment by websanova** [comment]
Also, make sure you have the latest `1.3.0-beta`, there have been some fixes and updates (for vue2 suppport as well).

**Comment by jkirkby91-2** [comment]
i will update this and let you know

**Comment by websanova** [comment]
This should be well fixed in the latest 2.x stream as there are no longer any Vue objects being passed into the plugin.
