### ISSUE TITLE
is vue-router.2.x.js compatible with vue-router v3 ?

### ISSUE THREAD

**Issue by vesper8** [websanova/vue-auth#350]
Just wondering since there doesn't seem to be any mention of this. I'm using "vue-router": "^3.0.1" in my new vue-cli project. Does this work with websanova/vue-auth or do I need to downgrade?

**Comment by DanielsLuz** [comment]
@vesper8 Just had to upgrade a project that used vue-router 2.7 and vue-auth to vue-router 3.0.1.
No problem so far.

According to vue-router [changelogs](https://github.com/vuejs/vue-router/releases), there is no mention to breaking changes that would impact vue-auth router driver 2.x, so we should be just fine.
