### ISSUE TITLE
vue-auth deleting my token

### ISSUE THREAD

**Issue by DmitryNeposidjaka** [websanova/vue-auth#351]
Hi, I had made a lot of work with your module, thank you! But there is left one thing where i have had a problem and i couldn't resolve it by all week.
When server responses 401 Unathorized status, the plugin delete my token from store. then i can't refresh my token becouse I need old token but it deleted (server architecture and we live with it).
So like I see: my axios intercepts 401 status, and i send refresh token by method auth.refresh().
and it works fine when I am reload a page, or on my own do auth.refresh();
How can I make it not to delete token? or maybe you can  advice my how to refresh my token after 401 status?

**Comment by websanova** [comment]
Just add your own intercept for this ;)

intercept, request, refresh call next.

**Comment by DmitryNeposidjaka** [comment]
The problem is not solved.
Yesterday I observed strange behaviour of intercept, and today after your comment I tryed few times and get the same problem.
When i register intercept in my axios config, there are no problem with deleting token, but I can't do refresh( ) becouse the vue-axios is not registring yet (maybe). I have this error in my console:
![2018-04-12 10-59-10](https://user-images.githubusercontent.com/13102394/38665013-f83a2a8c-3e43-11e8-890f-2217936eae67.png)

In sources I see it:
![2018-04-12 11-04-09](https://user-images.githubusercontent.com/13102394/38665048-102831ca-3e44-11e8-9a63-714bf86452db.png)
If I will register intercept after registring vue-auth in my main.js file the refresh() work fine, but token had been already deleted, so I get an error from server in my refresh request.

**Comment by websanova** [comment]
Did you try Vue.auth in intercept? Or just console.log(Vue) and see what you get.

**Comment by DmitryNeposidjaka** [comment]
Yes. I try Vue.auth.
It is the second example. When I use intercepts after registring vue-auth
![2018-04-12 15-19-54](https://user-images.githubusercontent.com/13102394/38676923-4032f76c-3e65-11e8-8475-a54ec0a01b18.png)
And when token expired i see this in the console
![2018-04-12 15-20-28](https://user-images.githubusercontent.com/13102394/38676957-6047afb6-3e65-11e8-9eb1-87737697a276.png)
500 error becouse the server didn't fine a token in headers of the request, when vue-auth had deleted it.
And when I register Intercepts before vue-auth in axios config
![2018-04-12 15-45-45](https://user-images.githubusercontent.com/13102394/38678093-bfffc1ca-3e68-11e8-88c2-5130631d86da.png)
I have this error in console. The refresh mothod doesent work.
![2018-04-12 15-45-31](https://user-images.githubusercontent.com/13102394/38678140-dbfe25a6-3e68-11e8-93b0-eaa44d5845e7.png)

**Comment by DmitryNeposidjaka** [comment]
I don't get it. function next is underfined. I can't do like in your setByStepGuide.
I need retern next when interceptor after registring vue-auth?
When it before i get error when calling refresh.

**Comment by DmitryNeposidjaka** [comment]
**I solved the problem!**
the solution was easy: I deleted, maybe forgot to set up a ready() function.
