### ISSUE TITLE
check() function and route auth

### ISSUE THREAD

**Issue by alikhanz** [websanova/vue-auth#352]
I'm writed custom check() function for checking user roles, but checking roles in routes is difference.
My problem that is user object has role object, and default "rolesVar" isn't working.
User object example:
```json
{
  "id": 1001,
  "name": "Admin",
  "surname": null,
  "patronymic": null,
  "login": "admin",
  "email": "test@example.com",
  "created_at": 1523072337,
  "updated_at": 1523072337,
  "role": {
    "id": 1,
    "key": "admin"
  }
}
```

My check function:

```javascript
function(role) {
        if (this.watch.authenticated === true) {
            if (role) {
                let roles = [];

                if (typeof role === 'string') {
                    roles.push(role);
                } else if (role instanceof Array) {
                    roles = role;
                }

                return ~roles.indexOf(this.watch.data.role.key);
            }

            return true;
        }

        return false;
    }
```

And $auth.check() working perfect, but i can't write in routes something like:

```
meta: {
    auth: {
        roles: [
            'admin',
            'manager'
        ],
    }
}
```

Because route roles check working differently. 
Is there any workaround for my problem?

I think that check() function must be applied for routes too, but this change dangerous for other people

**Comment by websanova** [comment]
Not really sure what you're asking here. But the roles should match up for comparison, object to object or string to string.

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md

Your user role object should just be `"admin"` or `["admin"]` not 

```
"role": {
    "id": 1,
    "key": "admin"
  }
```

What's the point of dumping this id/key pair value?
