### ISSUE TITLE
rememberMe disappearing

### ISSUE THREAD

**Issue by DmitryNeposidjaka** [websanova/vue-auth#353]
I had solved the issue [#357](https://github.com/websanova/vue-auth/issues/351) and now get another problem: after refreshing token "rememberMe" disappearing and when I refresh page my token disappearing too (I know it, becouse  "rememberMe" has gone).
I set up rememberMe like this while refresh()
Vue.auth.refresh({
      rememberMe: true
    })
but it doesent work.
Any ideas how to fix it? Of course i can do it by my hands (set cookie "rememberMe" ), i just whant to use your plugin right. Thankyou

**Comment by websanova** [comment]
rememberMe is set during $auth.login() only.
