### ISSUE TITLE
Roles check does not work as it should.

### ISSUE THREAD

**Issue by ImArtur** [websanova/vue-auth#355]
Hallo, 
after a user is logged in he will be redirected to page
/dashboard/room
the page should be only accessible for users with role admin.
This is how my user object looks like in response:

`{
  "id": 1,
  "name": "Artur",
  "email": "1234@1234.com",
  "created_at": "2018-04-13 23:20:17",
  "updated_at": "2018-04-13 23:20:17",
  "roles": [
    {
      "id": 2,
      "name": "admin",
      "guard_name": "web",
      "created_at": "2018-04-14 00:18:43",
      "updated_at": "2018-04-14 00:18:43",
      "pivot": {
        "model_id": 1,
        "role_id": 2,
        "model_type": "App\\User"
      }
    }
  ]
}
`

As I said after succesful login i redirect user to /dashboard/room.
This is my route:
` {
            path: '/dashboard',
            name: 'dashboard',
            component: dashboard,
            children: [
                {
                    path: 'room',
                    component: Room,
                    name: 'room',
                    meta: {
                        auth: {
                            roles: 'admin',
                            forbiddenRedirect: '/admin/403'
                        }
                    },
                }
            ]
        },`

Why is script redirecting to /admin/403 if role admin exists in user object?

**Comment by websanova** [comment]
Check the privileges section in the docs on acceptable role formats.

**Comment by ImArtur** [comment]
I did read docs and use example of vue 2.x 
`
 meta: {
            auth: {
                roles: 'admin',
                redirect: {name: 'admin'},
                forbiddenRedirect: '/admin/403'
            }
        },
`

but is still do not work.

**Comment by websanova** [comment]
Well I can see you don't have it set right...

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md#comparing-roles

**Comment by ImArtur** [comment]
Yet thanks, i finally manage to fix it by returning array with all user roles. Still it will be really hard for some people to understand it.

**Comment by flowser** [comment]
> Yet thanks, i finally manage to fix it by returning array with all user roles. Still it will be really hard for some people to understand it. Great library tbh

share your solution am facing the same thing

**Comment by ffegu** [comment]
> > Yet thanks, i finally manage to fix it by returning array with all user roles. Still it will be really hard for some people to understand it. Great library tbh
> 
> share your solution am facing the same thing

just return the `$user` and `'roles` as array with a single data like 

`public function user(Request $request)
  {
    $user = User::where('id', \Auth::user()->id)->with('roles')->first();

    $data = [$user, 'roles'=>$user->getRoleNames()];
    
    return response([
      'status' => 'success',
      'data' => $data,
    ]);
  }`
