### ISSUE TITLE
But fetchData is still called

### ISSUE THREAD

**Issue by QylinFly** [websanova/vue-auth#363]
fetchData: {
    url: 'xxxxx',
    method: 'GET',
    enabled: false
}

But fetchData is still called，why?

**Comment by websanova** [comment]
can be more specific? No idea what you're doing here.

**Comment by jobsboris27** [comment]
I have same problem
` fetchData: {
    enabled: false
  }`

**Comment by websanova** [comment]
yea, need details, don't just tell me shit doesn't work.
