### ISSUE TITLE
Auto Redirect when token is expired

### ISSUE THREAD

**Issue by blalan** [websanova/vue-auth#364]
I understand that this question isn't exactly of this library, which is Awesome! Thank you, but I am wondering how you might approach this issue. 
User logs in and does stuff, walks away from computer and comes back later to page still up. Fills out a form and hits submit, but since he was gone too long, the token has now expired and the POST request returns a 401 which then causes the site to redirect to login form. Meaning they have to log back in and navigate to last page and then re-fill out form and re-submit. 
I have the token expiration date in my user data... is there a way to check it and when expired redirect automatically, so when user comes back, and token is expired, the user is already at the login page and Vue has the redirect info to take him back to last page?

**Comment by websanova** [comment]
Well, this really depends on the setup. the plugin automatically does a refresh behind the scenes every 30 minutes.

For this to fail it means you have some strict token setting without refresh? It's a bit strange to begin with. But if you know the token is gonna expire in x time, just put a timer and auto log them out I guess.

**Comment by blalan** [comment]
I think I missed that its doing a refresh... I'll look into that, so right now I have the token to expire in 5 minutes... which would be the reason for it to be failing.
Actually though, in this application, I want the user to be logged out, many users are using the same machine, and we want them to be logging in as their own user. I think I will send new token with each request, so they will always have 5 or 15 minutes since last interaction with server.
What is the best way to setup a timer in JS and Vue?
Thanks for the reply.

**Comment by blalan** [comment]
Now that I think about it, if this library is already making a request to the server with an expired token when looking to refreshData, then the server should be responding with a 401. Maybe I can just use that function (change the time to 15 mins) and redirect if response is 401. 
One issue I am/was having though is that the 401 redirect, doesn't contain any params or querys to redirect back to last page. 
It works fine when logged out and browsing to auth controlled page... but not when logged in and server responds with 401.
Thoughts?

**Comment by websanova** [comment]
For the first question....Google it

https://www.google.com/search?q=settimeout

For the second question... read the docs..

https://github.com/websanova/vue-auth/blob/master/docs/Methods.md#redirect
