### ISSUE TITLE
RolesVar as an Array

### ISSUE THREAD

**Issue by Sephen** [websanova/vue-auth#366]
I've got my permissions setup like:
```
{
  "type": "user",
  "id": "1",
  "attributes": {
      "username": "Sephen",
      "permissions": [
          "administrator",
          "user",
          "guest"
        ]
    }
}
```
In main.js: `  rolesVar: 'attributes.permissions',`

A user can have multiple roles but when i use  `$auth.check(['user'])"` it cannot find the role/permission. (If it is a single string it works but that is of no use to me)

```
<div v-if="$auth.check('user')">Yep!</div>
<div v-else>Nope</div>
{{ $auth.user().attributes.permissions }} <-- returns the array with permissions
```

I tried:
```
$auth.check('user')
$auth.check(['user'])
```

How can i make this work with arrays (or am i doing something wrong)?

**Comment by websanova** [comment]
Can you show some more code...

**Comment by websanova** [comment]
Also are you using latest version, etc, etc...

**Comment by Sephen** [comment]
Sorry, I updated the original post.
I'm using the latest version.

**Comment by websanova** [comment]
ok, I see now, it doesn't accept dot notation for parameters, so your `attributes.permissions` will not work.

I don't think I will bother to bloat the library with this extra feature.

Just use parseUserData to set it as a `roles` or whatever other var.

https://github.com/websanova/vue-auth/blob/master/docs/Options.md#parseuserdata-_parseuserdata

Should work.
