### ISSUE TITLE
[ASK] Add Path URL on Fetch user URL

### ISSUE THREAD

**Issue by argotri** [websanova/vue-auth#367]
hi , i want to ask about fetchingUser after login 
so the case is i want to get user details and save the role or in my case is in the field autorities 
 
my login script is like this 
```javascript
login () {
      this.$auth.login({
        data: this.data.body, // Axios
        rememberMe: this.data.body.rememberMe,
        fetchUser: {enable: true, url: '/users/' + this.data.body.username, methods: 'GET'},
        url: '/authenticate'
      })
```

backend url is _[some url]/users/[some username]_ which username is can be get from data.body.username , and using method gets
and after fetchUser from login  user how i can save the role ( in my case is authorities ) ? 

my data object is like this
```javascript
{
    "id": 3,
    "login": "admin",
    "firstName": "Administrator",
    "lastName": "Administrator",
    "email": "admin@localhost",
    "imageUrl": "",
    "activated": true,
    "langKey": "en",
    "createdBy": "system",
    "createdDate": "2018-04-23T13:54:19.186Z",
    "lastModifiedBy": "system",
    "lastModifiedDate": null,
    "authorities": [
        "ROLE_USER",
        "ROLE_ADMIN"
    ]
}
```

thanks before :)

**Comment by websanova** [comment]
the fetchUser field on login is just a flag. Check the other options for setting this in config.
