### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by blalan** [websanova/vue-auth#370]
I was able to get the refreshData to work in as much as when a request bounces back from the server with a 401 error code, I'm taken back to the login page. However, the $auth.redirect Method is null, even though I was "redirected" to the login page. 

Another point where there is unexpected behavior, I have a role locked route, declared as an array ['admin', 'office'], it works for someone with either 'admin' or 'office' in the "role" user prop, but for a user say with 'supervisor', I get redirected to /404. Per docs, I would think that I should be sent to the forbiddenRedirect, and not the notFoundRedirect... 

I'm also unsure how to use the invalidToken hook, is there an example somewhere I missed?

**Comment by websanova** [comment]
Do you have some examples of what you're trying?

Also, are you sure there are no other interceptors setup already?

**Comment by blalan** [comment]
main.js
`Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  authRedirect: {name: 'login'},
  forbiddenRedirect: {name: 'login'},
  loginData: {url: 'login', method: 'POST', fetchUser: true},
  fetchData: {url: 'user', method: 'GET', enabled: true},
  refreshData: {url: 'user', method: 'GET', enabled: true, interval: 3}
})`

router/index.js sample
`export default new Router({
  mode: 'history',
  routes: [
    {
      path: '',
      name: 'Hello',
      component: Hello,
      meta: { auth: true }
    }, {
      path: '/customers',
      component: customersIndex,
      children: [
        {
          path: '',
          name: 'customersDashboard',
          component: customersDashboard,
          meta: { auth: true }
        }, {
          path: 'view/:id/:sub',
          name: 'customersSingle',
          component: customersSingle,
          meta: { auth: true }
        }
      ]
    }, {
      path: '/settings',
      name: 'Settings',
      component: SettingsDashboard,
      meta: { auth: ['admin', 'office'] },
      children: [ ... ]
}]}`

user1 data sample
`{
  "id": 1,
  "username": "blandowski",
  "email": "blando.....",
  "permissions": [],
  "last_login": {
    "date": "2018-05-03 07:07:32.530877",
    "timezone_type": 3,
    "timezone": "America/Chicago"
  },
  "first_name": "Blaine",
  "last_name": "Landowski",
  "department_id": 13,
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjUzNDkyNTIsImV4cCI6MTUyNTM1MTA1MiwidG9rZW4iOiI2ZEJHZU4xMXdndXdSaGpibUxYZ0ZHIn0.tnMwwuAaIjRKgrwXg-fjvmvZ1Bqejyqe4PbIJYTYo4c",
  "token_expire_date": {
    "date": "2018-05-03 07:37:32.560126",
    "timezone_type": 3,
    "timezone": "America/Chicago"
  },
  "deleted": null,
  "created_at": "2018-04-03 18:32:55",
  "updated_at": "2018-05-03 07:07:32",
  "roles": [
    "admin"
  ],
  "tok_exp": 1525351052,
  "success": true
}`

user2 data sample
`{
  "id": 5,
  "username": "dbuchholz",
  "email": "dbuc ....",
  "permissions": [],
  "last_login": {
    "date": "2018-05-03 07:10:40.453701",
    "timezone_type": 3,
    "timezone": "America/Chicago"
  },
  "first_name": "Dallas",
  "last_name": "Buchholz",
  "department_id": 7,
  "token": "eyJ0eXAiOiJK ...,
  "token_expire_date": { ... },
  "deleted": null,
  "created_at": "2018-04-06 15:52:42",
  "updated_at": "2018-05-03 07:10:40",
  "roles": [
    "supervisor"
  ],
  "tok_exp": 1525351240,
  "success": true
}`

**Comment by blalan** [comment]
OK. I figured out the route issue (2); I have /login set to auth: false... so the route gets the forbidden call redirected to login which then gets redirected to the notFoundRedirect '404'. Duh! 

Still looking for help with the 401 interceptor redirect method...

**Comment by websanova** [comment]
ok, well I just tested 1, seems fine to me, and 3 I still don't know what you're talking about.
