### ISSUE TITLE
Any ideas why a logoutData = makeRequest: true might not work?

### ISSUE THREAD

**Issue by stratosgear** [websanova/vue-auth#372]
Sorry to bother but having configured as:

```
Vue.use(require("@websanova/vue-auth"), {
  auth: require("@websanova/vue-auth/drivers/auth/bearer.js"),
  http: require("@websanova/vue-auth/drivers/http/axios.1.x.js"),
  router: require("@websanova/vue-auth/drivers/router/vue-router.2.x.js"),
  //tokenStore: ['cookie', 'localStorage']
  logoutData: {redirect: '/login', makeRequest: true}
});
```

and performing a logout does **not** seem to make a request (checking chrome developer tools Network tab) to the logout url (the default `/auth/logout`).

The logout **does** indeed perform a logout though (visiting protected routes will trigger a login again).

I'm baffled!  Thanks...

**Comment by websanova** [comment]
Works fine for me (with vue-router). Maybe axios is doing something strange?

You don't get any bugs or anything? Should at least be firing a request.

**Comment by stratosgear** [comment]
I'm also using axios with vue-router...

Nothing is logged in console.  And as I said, i see no requests in the network tab.

BUUUT, I went to add some console.log messages on the `success` and `error` of the logout action and I saw this:

```
logout() {
      this.$auth.logout({
        makeRequest: false,
        success() {
          console.log("success " + this.context);
        },
        error() {
          console.log("error " + this.context);
        }
      });
    }
```

So this is one of these obvious Austin Power cases of  "That's not mine, baby"... Sorry!

Closing.
