### ISSUE TITLE
App logout when I change the route

### ISSUE THREAD

**Issue by Kuchiriel** [websanova/vue-auth#374]
Every time I change the route, the app simple logs outs, anynone knows why?

**Comment by websanova** [comment]
Do you have some examples, could be many reasons. Maybe show some config,
how you are logging in, some information about request, is there valid
token, do you have any auth setup on the routes....?

**Comment by Kuchiriel** [comment]
@websanova 
App.js https://pastebin.com/yHbgTaBV
Routes https://pastebin.com/qhQ2KfDi

**Comment by websanova** [comment]
Are you sure have a proper token coming back? No errors?

**Comment by Kuchiriel** [comment]
Yes, and I use the token with a jwt decoder to do dom auth. No problem.
