### ISSUE TITLE
Adding GET query string with Login request

### ISSUE THREAD

**Issue by williams-c** [websanova/vue-auth#376]
My backend application returns my token through a GET route. I have successfully changed the default auth login function to use the GET method. 

However, I want to send extra parameters through the query string. Something like:
`?code=efqwtqwtrewqrjkljhdbsafhsjkflqjwe`

How do I modify the `this.$auth.login()` function to make that happen?

**Comment by websanova** [comment]
Just do whatever you would do normally with axios, cue router, or whatever
you are using ;)

**Comment by williams-c** [comment]
Thank you. I got it to work using `params: {}`
