### ISSUE TITLE
Redirect issue after login

### ISSUE THREAD

**Issue by onurkose** [websanova/vue-auth#377]
Hi there,

There is a `this.authenticated = null` statement at the line 320 of auth.js
After that line, `fetchPerform` call happens no matter what `fetchUser` option is set.
In fetchPerform function, line 265, there is `(this.watch.authenticated !== true && !data.enabled)` condition checks the `authendicated` key of watch object. And that makes to call `__duckPunch` anyhow. If duckpunch fails during fetch user from server, even user is authenticated during login call, there will be no redirect at all.

So the problem here is `this.authenticated` in __loginProcess function. It should be `this.watch.authenticated` to `_fetchPerform` work properly.

**Comment by websanova** [comment]
Well you can submit a pull request or you can describe your issue.

I have a lot of complaints about this one, but it seems to always work out fine :-)

**Comment by onurkose** [comment]
They're probably using success/error endpoint of the login promise to redirect the user.
Successful fetchUser request doesn't make this issue to occur anyways.

**Comment by websanova** [comment]
ok, thx, merged, updated in v2.21.11-beta :-)
