### ISSUE TITLE
Can I use some features of this library without using login function

### ISSUE THREAD

**Issue by vicnoob** [websanova/vue-auth#379]
I want to use custom login function to call API myself, not using $auth.login, but I still want to use feature like $auth.ready(), $auth.user() especially authorization in router(check role, restrict access page). Can I achieve it?

**Comment by websanova** [comment]
Well, there is a lot of variations, depends on your setup.

If you are strictly talking about just the login, then you could simply call `$auth.fetch()` in your login success callback. But this depends a lot on your setup and if you have this end point and are sending back a token in the first place, etc.

**Comment by sieunhanvodich** [comment]
I did use $auth.fetch() in my own login and it worked , however, when I refresh the page, it seems to auto logout and redirect to login page. Are there any other configurations that I need to do?

**Comment by websanova** [comment]
Yes, you would still need to make an auth token is set (via login). The
plug-in will automatically pick it up.

**Comment by websanova** [comment]
If you are going fully manual you will need to set a couple flags as well.

this.$auth.watch.loaded = true;this.$auth.watch.authenticated = true;
