### ISSUE TITLE
The reason behind the removal of tokenVar option

### ISSUE THREAD

**Issue by HashemQolami** [websanova/vue-auth#38]
Hi Rob,
I was reading the latest commits and I was wondering why `tokenVar` has been removed and has been [merged with](https://github.com/websanova/vue-auth/commit/514c9a680d3fadbe42d21c951fd028e23b487f77#diff-3bbf637d3a6fe8e950d469c35444acdaR432) `tokenHeader`.

The new syntax of `token` option is cool, but it would be great if we could set two different names:
* one for the name of the token we receive from the server
* and one for the name of the header we set in requests.

Say it is needed to send an `Authorization: bearer ...` header but the server sends the token with something like: `id_token: ...`.

Any thoughts? I can send a PR if you don't mind.

**Comment by websanova** [comment]
I see... ok, I can make those two separate fields...

**Comment by websanova** [comment]
Ok, I've just update this (along with separate demo folders for vue 1 and 2). In the token option there is now an `request` and `response` field instead of the `name` field. I've update the README also.
