### ISSUE TITLE
how to save token in custom oauth2

### ISSUE THREAD

**Issue by Snapu** [websanova/vue-auth#382]
I have configured a custom oauth2 provider:

```
Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  myProviderOauth2Data: {
    url: 'https://dosent.matter.com/oauth/authorize',
    params: {
      client_id: 'my_client',
      redirect_uri: function () { return this.options.getUrl() + '/' },
      scope: 'my_scope'
    }
  }
})
```

and I have a method:
```
      login: async function () {
        await this.$auth.oauth2({
          provider: 'myProvider',
          response_type: 'token'
        })
        console.log('logged in')
      }
```

The login works and I come back with an access_token in the url but this is never saved in the storage and intercepted in my requests. What am I missing?

Can you please extend the documentation?

**Comment by websanova** [comment]
For oauth this token should be passed to your server. Not stored locally. Unless you are trying to do something else. But typically with oauth you send the token back to your server and use that to fetch some user data and create a user. Which can then be used to verify that user again across devices.
