### ISSUE TITLE
Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by meliborn** [websanova/vue-auth#384]
Here is my entry point:
```javascript
import Vue from 'vue'
import App from './App.vue'
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueRouter from 'vue-router';
import LoginForm from './components/LoginForm.vue';
import VueAuth from '@websanova/vue-auth';

Vue.use(VueRouter);
Vue.use(VueAxios, axios);
Vue.axios.defaults.baseURL = 'https://api-demo.websanova.com/api/v1';
Vue.config.productionTip = false;

Vue.router = new VueRouter({
  hashbang: false,
  linkActiveClass: 'active',
  mode: 'history',
  routes: [{
    path: '/',
    name: 'default',
    component: LoginForm
  }]
});
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
});

new Vue({
  render: h => h(App),
  data: {
    
  }
}).$mount('#app')
```

Here is my submit form handler:
```javascript
import Vue from 'vue';
export default {
  name: "LoginForm",
  data() {
    return {
        data: {
            body: {
                email: "",
                password: ""
            }
        }
      
    };
  },
  methods: {
    loginUser() {
      this.$auth.login({
        data: this.data.body,
        rememberMe: true
      });
    }
  }
};
```
On submit I'm getting `Cannot read property 'query' of undefined`. What's wrong?

**Comment by websanova** [comment]
Looks like to me

**Comment by websanova** [comment]
No idea what you're really asking here. I don't even see `query` in your code...

**Comment by meliborn** [comment]
`query`  wasn't in my code, it's from the core. The problem was that I've forgotten to pass `router` variable to the `Vue` constructor.

**Comment by Raggyman** [comment]
@meliborn  I have the problem.  What was it you did to fix the issue?

**Comment by Raggyman** [comment]
`12vue-router.2.x.js?832c:17 Uncaught TypeError: Cannot read property 'query' of undefined
    at Auth._bindData (vue-router.2.x.js?832c:17)
    at VueComponent.__bindContext (auth.js?9c12:31)
    at VueComponent.Auth.login (auth.js?9c12:676)
    at VueComponent.login (login_page.component.js?a46f:26)
    at submit (login_page.component.html?5678:19)
    at invoker (vue.esm.js?65d7:2027)
    at HTMLFormElement.fn._withTask.fn._withTask (vue.esm.js?65d7:1826)`

Is the actual error that is generated
