### ISSUE TITLE
Refresh token which calculated from the exp field

### ISSUE THREAD

**Issue by akaNightmare** [websanova/vue-auth#386]
Hello,

I wonder if possible calculate how often JWT token can be refreshed according to the iat and etc?
For example, a server returns JWT token with two fields iat and exp, and the difference between those two dates is 3hrs. It would be great to add some configuration field like `refresh_times: 3` or `refresh_frequency: 3` which will refresh the token every hour, because of 3hrs / 3(refresh_frequency value).

Thanks.

**Comment by websanova** [comment]
Yes, 

You can set an arbitrary interval
https://github.com/websanova/vue-auth/blob/master/docs/Options.md#refreshdata-url-authrefresh-method-get-enabled-true-interval-30

Or just disable refresh and do your own thing. You can use $auth.refresh() shortcut.

**Comment by akaNightmare** [comment]
@websanova that is not correct. I want to implement auto-refreshing according to the formula which I provided in the description.

**Comment by websanova** [comment]
Yes, so follow the second suggestion ;)

Disable refresh, and use auth ready
