### ISSUE TITLE
cannot access custom generated errors on error:

### ISSUE THREAD

**Issue by omenejoseph** [websanova/vue-auth#387]
my other_error is generated in my controller if a logic doesnt pass and I want to display the value of that error on my form. I get the value when i log it there inside error function but it does not set to the value of my variable as I expect it to... only custom form error that come with laravel request are being accessed. I dont know whay. Please help anyone... I need to feedback my client that the logic doesnt pass. this.error = true doesnt even happen even though I get error response    

  error: function (resp) {
                        this.error = true;
                        this.errors = resp.response.data.errors;
                        
                        this.other_error = resp.response.data.error;
                        console.log(this.other_error);
                        this.loading = false;
                        
                        
                    },

**Comment by websanova** [comment]
No idea what you're asking.
