### ISSUE TITLE
What are  different  Vue.http.options.root with  Vue.axios.defaults.baseURL ?

### ISSUE THREAD

**Issue by goodforever** [websanova/vue-auth#388]
What are  different  Vue.http.options.root with  Vue.axios.defaults.baseURL ?

**Comment by websanova** [comment]
Why don't you look it up in axios docs...

**Comment by goodforever** [comment]
I confuse that the install manual use vue-resource driver and axios driver at same time .
I think that  Vue.http.options.root is for vue-resource , Vue.axios.defaults.baseURL is  for axios.


Install 2.x
> npm install @websanova/vue-auth
The router and http drivers MUST be set. The drivers are quite small so can be replaced or overridden as necessary.

Note that the version in the driver file should denote the version it is compatible with. So router.2.x. means it's for router 2.x.

Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';

Vue.router = new VueRouter({
    ...
});

Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    ...
    rolesVar: 'type'
    ...
});


Install with Vue-Axios


import axios from 'axios'
import VueAxios from 'vue-axios'
import VueAuth from '@websanova/vue-auth'

Vue.use(VueAxios, axios)
Vue.use(VueAuth, {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
    ...
});

// access axios with Vue or use the 'this' reference in components
Vue.axios.post(...).then(res => {
    console.log('RES', res);
});

**Comment by goodforever** [comment]
Can I just use the part of "install with Vue-axios" ,ignore the following ?

Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';

Vue.router = new VueRouter({
...
});

Vue.use(require(''), {
auth: require('/drivers/auth/bearer.js'),
http: require('/drivers/http/vue-resource.1.x.js'),
router: require('/drivers/router/vue-router.2.x.js'),
...
rolesVar: 'type'
...
});

**Comment by goodforever** [comment]
I saw "Step By Step Guide", my question is closed
