### ISSUE TITLE
405 error breaking npm install

### ISSUE THREAD

**Issue by bwml** [websanova/vue-auth#390]
Hello,

I am getting the following error when running npm install, I believe related to this package.
> TypeError: Cannot read property 'latest' of undefined

Log file suggests it is a problem with retrieval:
> 482 silly lockFile 60352c60-popper-js-1-12 popper.js@^1.12
483 silly addNameRange { name: 'websanova/vue-auth',
483 silly addNameRange   range: '>=2.21.3-beta <3.0.0-0',
483 silly addNameRange   hasData: false }
484 verbose url raw websanova/vue-auth
485 verbose url resolving [ 'http://registry.npmjs.org/', './websanova/vue-auth' ]
486 verbose url resolved http://registry.npmjs.org/websanova/vue-auth
487 info trying registry request attempt 1 at 14:56:29
488 http GET http://registry.npmjs.org/websanova/vue-auth
489 http 405 http://registry.npmjs.org/websanova/vue-auth
490 silly registry.get cb [ 405,
490 silly registry.get   { date: 'Thu, 14 Jun 2018 14:56:29 GMT',
490 silly registry.get     'content-type': 'application/json',
490 silly registry.get     'content-length': '63',
490 silly registry.get     connection: 'keep-alive',
490 silly registry.get     'set-cookie': [ '__cfduid=d23b92f014fed97385690e6003a9432c81528988189; expires=Fri, 14-Jun-19 14:56:29 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
490 silly registry.get     allow: 'PUT',
490 silly registry.get     'cf-ray': '42ada4d606a39fc0-IAD',
490 silly registry.get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
490 silly registry.get     server: 'cloudflare' } ]
491 silly addNameRange number 2 { name: 'websanova/vue-auth',
491 silly addNameRange   range: '>=2.21.3-beta <3.0.0-0',
491 silly addNameRange   hasData: true }
492 silly addNameRange versions [ undefined, [] ]
493 error TypeError: Cannot read property 'latest' of undefined
493 error     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
493 error     at /usr/lib/node_modules/npm/lib/cache.js:675:5
493 error     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
493 error     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
493 error     at Object.oncomplete (fs.js:108:15)
494 error If you need help, you may report this log at:
494 error     <http://github.com/isaacs/npm/issues>
494 error or email it to:
494 error     <npm-@googlegroups.com>
495 error System Linux 4.14.33-51.37.amzn1.x86_64
496 error command "node" "/usr/bin/npm" "install"
497 error cwd /data/www/ubc-goal-settings/src
498 error node -v v0.10.48
499 error npm -v 1.3.6
500 error type non_object_property_load
501 verbose exit [ 1, true ]

Additionally when I follow the rabbit...
![image](https://user-images.githubusercontent.com/32103844/41420639-f4ebe234-6fc2-11e8-9af2-56089b068dda.png)

Can you advise?

Thanks.

**Comment by websanova** [comment]
Wrong package name, you could of course just try a search on npm ;)

https://www.npmjs.com/package/@websanova/vue-auth
