### ISSUE TITLE
$auth.user() on first login doesn't show up data, unless refreshed. Also, if a value on user model changes, it gets cached unless page is refreshed. How to solve this?

### ISSUE THREAD

**Issue by aligajani** [websanova/vue-auth#392]

**Comment by websanova** [comment]
No idea, do you have some code to show. did you disable refresh or user fetch or anything?

Also there is nothing cached for the user, you can can update it anytime using `$auth.user(<object>)` or simply change it's properties `$auth.user().blah = 'new value';`

**Comment by aligajani** [comment]
@websanova  Rob, I also have this function for token login, which seems to be the culprit?

Is `this.$auth.user(res.data);` right or should I do `this.$auth.user() = res.data`?

```
 // Manual login using token
              this.$auth.user(res.data);
              this.$auth.token(null, token);
              this.$auth.watch.authenticated = true;
              this.$auth.watch.loaded = true;

              // Manual cookie to prevent logout
              Cookies.set("rememberMe", true, { expires: 14 });
```

**Comment by aligajani** [comment]
Nevermind. the bug was `res.data.data` instead of `res.data`.
