### ISSUE TITLE
control how token is being refreshed

### ISSUE THREAD

**Issue by jerzyk** [websanova/vue-auth#397]
Have an issue with using 2 tokens - authentication and renewal, I've managed to override "auth" handler and store both of them in the storage, but then there are 2 and half issues:
- schedule token refresh - is there an option to schedule token refresh? (now I've overridden `tokenExpired` but this is reactive, not proactive)
- second is more important - I want to have control of what data is being sent in refresh token request and token invalidate (this is this remaining half-problem)

for the refresh/invalidate - there are different data that need to be sent, e.g. refresh token or client_id 

is there any mechanism to override this dynamically?

**Comment by websanova** [comment]
I don't see why a custom driver couldn't handle this. You're just modifying the request.

**Comment by jerzyk** [comment]
hmm.. which one? sorry, just trying to do this "properly"
`auth` has only 2 methods - just to manage tokens

`http` has only one method - token expired which may be helpful, but remaining one, even if used during a refresh, they do not have any contextual information that specific http request is belonging to refresh process

`router` - same as `http`..

overriding in main setup? something like:
```refreshPerform: function (data) {
    // return this._refreshPerform(data)
    return data
  },```

missing `_refreshPerform` anywhere... so no way to call original method with changed data

**Comment by websanova** [comment]
Just look at one of the driver files in the source code. It's just a few lines of code. You can write whatever you need there.
