### ISSUE TITLE
Login successfully but $auth.user() is empty

### ISSUE THREAD

**Issue by crossRT** [websanova/vue-auth#40]
I migrate my application from `vue-jwt-auth` to this new library.
Here's how I setup it:
```javascript
window.Auth = require('@websanova/vue-auth')
export var router = new VueRouter({
    history: true,
    hashbang: true,
    saveScrollPosition: true,
    linkActiveClass: 'active'
});

Vue.use(Auth, {
    router: router,
    http: Vue.http,
    fetchData: {
        url: '/api/check',
        method: 'get'
    },
    loginData: {
        url: '/api/login',
        method: 'post'
    },
    tokenName: 'token',
});
```

I can get the token via `this.$auth.token()`.
And I also check on chrome developer network tab, the `fetch()` has been called and returning the user object from server.
But if I call the user via `this.$auth.user()`, it's still an empty object.
What I expect is the `this.$auth.user()` will store the user object that I return for `fetch()` function like `vue-jwt-auth` did.

**Comment by websanova** [comment]
What version of kind are you using?

**Comment by crossRT** [comment]
Here's all the versions
vue: 1.0.28
vue-auth: 1.3.0-beta
vue-resource: 1.0.3
vue-router: 0.7.13,

**Comment by websanova** [comment]
Did you override any of the auth methods at all? Also can see your servers
response object for the user?

**Comment by crossRT** [comment]
I didn't override any auth methods.
Here's my server response object for the user.
```json
{
	"id": 1,
	"first_name": "First Name",
	"last_name": "Last Name",
	"email": "testing@example.com",
	"contact": "0123456789",
	"company_name": "Company Name",
	"verified": 1,
	"created_at": "2016-10-27 06:29:08",
	"updated_at": "2016-10-27 06:29:08"
}
```

**Comment by websanova** [comment]
What's the full response? is it just coming back like that one json object?
The auth plugin looks for something more structured. like {data: {id: 1,
name: 'blah', ....}}

**Comment by crossRT** [comment]
Finally solved, after I nested the user object in a wrapper like you show me.
here's the latest response:
```json
{
	"data": {
		"id": 1,
		"first_name": "First Name",
		"last_name": "Last Name",
		"email": "testing@example.com",
		"contact": "0123456789",
		"company_name": "Company Name",
		"verified": 1,
		"created_at": "2016-10-27 06:29:08",
		"updated_at": "2016-10-27 06:29:08"
	}
}
```

Thank you @websanova !
Do you have any documentation to show how's the JWT response should structure? Is there any specification for it? Because I have some problems during design the backend response when I first time using JWT.

**Comment by websanova** [comment]
Yes there are docs in the readme.
