### ISSUE TITLE
is there a way to intercept the process between $auth.oauth2 and fetchData ?

### ISSUE THREAD

**Issue by vesper8** [websanova/vue-auth#403]
I've been at this for over 2 hours and am really out of answers so any help is appreciated

I'm using this package in combination with Laravel and tymondesigns/jwt

Everything works great but now I have this special use case which is causing me major headaches.

My users can disable their accounts, in which case I soft delete their user models in Laravel. They can later restore their account. The way I did this previously (before migrating to jwt) is I would let them attempt to login (with facebook login as it happens) and if I detected they were soft-deleted, I would store their user in a session and send them to a 'account restore' page

I'm having a hell of a time reproducing the same flow with JWT

I am stuck. The facebook auth works fine, but it seems impossible to get pass the jwt.auth middleware with a soft deleted model.. thus the fetchData always fails.

What I am trying to do now is intercept a response during the oauth2 flow

```
      this.$auth.oauth2({
        code: true,
        provider: this.type,
        params: {
          code: this.code,
        },
        success(response) {
          console.log('success', response);
          ... do something here
        },
        error(response) {
          console.log('error', response);
          ... or do something here
        },
      });
```

On my Laravel side. I noticed if I try to return a valid jwt token.. 
```
            if ($user->trashed()) {
                return response([
                    'status' => 'error',
                    'error' => 'account.disabled',
                    'msg' => 'Account Disabled'
                ])
                ->header('Authorization', JWTAuth::fromUser($user));
            }
```

It does not enter the 'success' response above at all, instead it immediately tries to fetch the user (fetchData) which fails.. and I have no opportunity to do anything with my valid jwt token, I would like to be able to skip the fetchData.. send the user to an account restore page and use the valid jwt token to restore the account.

If I generate an error on the Laravel end (and here I can attach a valid JWT token along with the response if I want):

```
                return response([
                    'status' => 'error',
                    'error' => 'account.disabled',
                    'msg' => 'Account Disabled'
                ], 400)
                ->header('Authorization', JWTAuth::fromUser($user));
```

Then I noticed that the json response, which would help me determine what the error is about and whether I should send the user to the Account Restore page or maybe it's due to invalid credentials etc.. that json response is not at all available

I do enter the 
```
        error(response) {
          console.log('error', response);
        },
```

But the response itself does not contain my json response at all, instead it just contains a generic error:
```
error Error: Request failed with status code 400
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:18)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:77)
```

So this is my problem.. I can't get proper feedback from my backend.. I need to be able to read what the error is about. Ideally a scenario where I can read the error and retrieve the JWT token but skip the fetchData (since that will fail anyway), instead I can do something else with the token.

Any help would be much appreciated.. thanks

**Comment by vesper8** [comment]
Hrm.. ok so I was able to make some progress.. it's so odd that doing a console.log(response) was printing a generic message but if you do console.log(response.response) then you get the full json response including the token in the header and the message

with that I should be able to do something.. I'll close this for now since it seems I can't delete it

**Comment by websanova** [comment]
Hmm, yes, maybe over thinking it, I would just send back a failed auth with
a special code which can then be caught and redirected.
