### ISSUE TITLE
Can't get user roles to work

### ISSUE THREAD

**Issue by chrisribal** [websanova/vue-auth#405]
I'm using the latest version of vue-auth in the frontend and laravel in the backend, everything works fine - except the user roles. I created the "roles" parameter in the user model in laravel and filled it propery. So after the login, the server responds with the correct answer:

    {
        "id":3,
        "name": "John Doe",
        "email": "john.doe@gmail.com",
        "roles":["editor"],
        "created_at":"2018-06-25 14:02:47",
        "updated_at":"2018-06-25 14:02:47"
    }

In the initialization, i've also set:

    Vue.use(require("@websanova/vue-auth"), {
        auth: require("@websanova/vue-auth/drivers/auth/bearer.js"),
        http: require("@websanova/vue-auth/drivers/http/axios.1.x.js"),
        router: require("@websanova/vue-auth/drivers/router/vue-router.2.x.js"),
        rolesVar: 'roles'
    });

All the users can login, but every check like `this.$auth.check("editor")` returns false. Digging into your files i tried to debug the _check function in the auth.js. After many console outputs i realized, that the `this.watch.data` array is empty.

What am i doing wrong?

**Comment by websanova** [comment]
Are you using `$auth.ready()` at all ?

**Comment by pmoscicki** [comment]
Try return data as:
```
{
    "id":3,
    "name": "John Doe",
    "email": "john.doe@gmail.com",
    "data": {
      "roles":["editor"],
    },
    "created_at":"2018-06-25 14:02:47",
    "updated_at":"2018-06-25 14:02:47"
}
```

works for me ;)

**Comment by kulavvy** [comment]
Try return data as:
```
{
    "id":3,
    "name": "John Doe",
    "email": "john.doe@gmail.com",
    "data": {
      "roles":["editor"],
    },
    "created_at":"2018-06-25 14:02:47",
    "updated_at":"2018-06-25 14:02:47"
}
```

works for me ;)
