### ISSUE TITLE
Redirect after Refresh Failed

### ISSUE THREAD

**Issue by vanessa-joyce** [websanova/vue-auth#406]
Is there a simple way to remove the token if refresh failed and to forward the user to a defined url? Currently it tries several times to refresh the token and the user needs to reload the page until he gets redirected.

**Comment by websanova** [comment]
It should be doing this automatically depending on the return status code. Maybe chekx this and any intercept. Basically just need to capture a fail and call logout.

**Comment by vanessa-joyce** [comment]
Which status code should be returned if refresh failed to do this automatically? Will I need to capture the fail by myself or will this be done automatically if the return code fits?

**Comment by websanova** [comment]
It's in the http drivers, vue-router for example:

https://github.com/websanova/vue-auth/blob/master/drivers/http/vue-resource.1.x.js#L21

That's the default and you can just override it.

**Comment by vanessa-joyce** [comment]
Perfect, thank you! One question left: Which status code should be returned if the token is expired and needs to be refreshed? We changed our backend to return 401 if the token in invalid and now need to know which status code to return if the token needs a refresh. 

Thank you in advance.
