### ISSUE TITLE
Implement role hierarchy

### ISSUE THREAD

**Issue by pabloraissiguier** [websanova/vue-auth#407]
Hi!
How could I implement role hierarchy? I have a symfony backend that has role hierarchy like:
ADMIN
     USER

ADMIN role can do anything USER can and some more.

But when I try to make it work with vue-auth I have some trouble.
For example, in my routes file, a page that can be accessed by both type of users:

`
meta: {auth: ['admin', 'user']},
`

It redirects me to login, because my user only have 'admin' privileges (the backend assumes it contains user permissions) but no 'user'.

Should I modify my backend, to retrieve all roles, regarding of the hierarchy or can I make it work with vue-auth?

(sorry for my english.. please let me know if there's anything unclear :) )

Thanks!

**Comment by websanova** [comment]
It should be working fine, like that. It's not checking all roles exists, just that one of them in the array hits.

Probably just something simple with the roles vars not matching up.
