### ISSUE TITLE
Getting roles properly from JWT custom claims

### ISSUE THREAD

**Issue by gileneusz** [websanova/vue-auth#408]
Hi,

I've got an issue with the roles. I used to send roles via my jwt token.

It was taken from users table from 'role' column. That was done via standard $token from laravel:

`$token = JWTAuth::attempt($credentials)`

and my vue showed on: `console.log(vm.$auth.user())` correct user - I was able to use roles natively without any problems.

Now I installed laravel voyager and I had to change name of 'role' column, because of naming conflict

So I decided to use JWT customClaims to make this work:

`$token = JWTAuth::customClaims(['role' => $user->new_role_column])->attempt($credentials);`

and this is not working, on: `console.log(vm.$auth.user())` I've got standard user table values, without 'role'.

I'm not sure if this is because of JWT or vue-auth, but I don't know what to do now to make this work.

jwt: 1.0.0-rc.2, vue-auth: 2.21.1-beta

**Comment by websanova** [comment]
Sounds like a Laravel issue.

This plugin will require some kind of role value/bit.

**Comment by gileneusz** [comment]
Sorry, I can't make this work. I tried almost all options as described there:
https://github.com/tymondesigns/jwt-auth/issues/1636

on console.log(this.$auth.user() I can't get `role: 'user'`, I can only get `app_role: 'user' `
Is it possible to give role from 'app_role' instead of 'role' ?

**Comment by gileneusz** [comment]
This is still unsolved...

**Comment by websanova** [comment]
Did you try setting rolesVar option?

**Comment by shingsoso** [comment]
I have the similar situation here ... 
Do you guys come up any idea or solution to this issue ?

**Comment by purplenimbus** [comment]
Lol i believe `getJWTCustomClaims` will only work for static variables. Any data beyond the user model seems to always gets stripped out
