### ISSUE TITLE
Unable to get headers (axios + vue http)

### ISSUE THREAD

**Issue by oligus** [websanova/vue-auth#409]
I'm having problems getting the correct headers from the http driver and thus auth doesn't set the token. I'm probably doing something wrong but I just can't figure out what it is.

The server response to the login request is correct and does return the correct headers ( I have double checked through other means aswell):

![screen shot 2018-08-02 at 11 07 14](https://user-images.githubusercontent.com/2466591/43574380-5677c868-9644-11e8-9e29-e96e9afa2e91.png)

When making `console.log(res)`in the `response`function in `bearer.js` there is clearly just one header available (content-type), this is true for both the axios and the http driver.

![screen shot 2018-08-02 at 11 17 52](https://user-images.githubusercontent.com/2466591/43574936-bc68400c-9645-11e8-9237-070c4666fa7c.png)

My setup:

![screen shot 2018-08-02 at 11 19 41](https://user-images.githubusercontent.com/2466591/43575025-fe6c1320-9645-11e8-8607-4314792e798d.png)

![screen shot 2018-08-02 at 11 22 44](https://user-images.githubusercontent.com/2466591/43575151-667fa652-9646-11e8-95be-2d23f870bf1e.png)

If anybody has any idea I would be interested to hear it, thank you!

**Comment by clsechi** [comment]
Hello,
Try add the line bellow in the the headers of the response send by php.
`'Access-Control-Expose-Headers': 'Authorization'`

**Comment by websanova** [comment]
I think should have something like this more or less

~~~
->header('Access-Control-Allow-Origin', '*')
->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS')
>header('Access-Control-Allow-Headers', 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With')
->header('Access-Control-Expose-Headers', 'Authorization')
->header('Content-Type', 'application/json; charset=utf-8');
~~~

**Comment by oligus** [comment]
Thanks guys, adding the `Access-Control-Expose-Headers` did the trick. How did I not know about this? :-)

Works beautifully after adding that header, thanks!
