### ISSUE TITLE
Super user?

### ISSUE THREAD

**Issue by DeanWard** [websanova/vue-auth#413]
Thanks for the great plugin! 

I've just started using a permissions library server side that has a super user concept built in. Super user's list of permissions becomes ['*']. Is it possible to make vue-auth take asterisk as 'can do anything'?

Cheers

**Comment by websanova** [comment]
Well it's just comparing strings so you could use whatever string you like. You can also override the default check method.

https://github.com/websanova/vue-auth/blob/master/docs/Options.md#check-_check

**Comment by DeanWard** [comment]
I have added a custom check function to the config that accepts role as parameter. It's been called but nothing is being passed in and even if I hard card a `true` response vue-auth still denies entry to the route.

Have I misunderstood?

`var config = {
    auth: require('../authdrivers/bearer-2fa.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    registerData: {
        url: 'api/auth/register',
        method: 'POST',
        redirect: '/auth/login'
    },
    loginData: {
        url: 'api/auth/login',
        method: 'POST',
        redirect: '/'
    },
    logoutData: {
        url: 'api/auth/logout',
        method: 'POST',
        redirect: '/auth/login',
        makeRequest: false
    },
    oauth1Data: {
        url: 'api/auth/login',
        method: 'POST'
    },
    fetchData: {
        url: 'api/auth/user',
        method: 'GET'
    },
    refreshData: {
        url: 'api/auth/refresh',
        method: 'GET'
    },
    authRedirect: {
        path: '/auth/login'
    },
    rolesVar: "roles",
    check: function(role) {
        console.log('checking ', role);
        return true;
    }
}`

**Comment by websanova** [comment]
Are you using auth.ready properly?

**Comment by websanova** [comment]
And you are using all your auth checks within that router view?

Also, maybe the routes are not setup correctly. If you console log arguments do you see anything?
