### ISSUE TITLE
Refresh method not triggered on axios call

### ISSUE THREAD

**Issue by Pochwar** [websanova/vue-auth#414]
Hi,

When the token is expired, if a reload the page, the `$auth.refresh()` method is triggered and make an api call to refresh the token.

But if the token is expired and I navigate on my app, if some component make an api call to fetch some data, `$auth.refresh()` is not triggered and I get redirect to the login page.

Is it the normal behaviour or am I missing something?

Thanks!

**Comment by websanova** [comment]
Yes, this is intended behavior. It's quite standard I believe.
