### ISSUE TITLE
how are triggered redirections ?

### ISSUE THREAD

**Issue by Pochwar** [websanova/vue-auth#418]
Hi,

I'm trying to display some message for the user in the login page depending on how he reaches this page: 
- case 1: error message if he got redirected after trying to access a page he can't reach if he's not logged
- case 2: information message if he got redirect after a successful registration
- case 3: no message if he reach this page on his own

My intention was to check the `$auth.redirect` object:
- if he's null -> case 3
- if not null and `from.name` is `register` -> case 2
- if not null and `from.name` is not `register` -> case 1

But I realized that `redirect` option in `$auth.register` doesn't trigger a redirection that I can get with `$auth.redirect()`. I guess it uses the vue-router push() method instead.

So, is there a way to trigger a redirection ?

Thanks

**Comment by Pochwar** [comment]
Hi, thanks for your answer.

I understood that `$auth.redirect()` is to catch redirections, and that redirections are triggered by auth when trying to reach a protected page.

But as `$auth.login()` and `$auth.register()` have a `redirect` option, I thought this one triggers a redirection too, that I could catch with `$auth.redirect()`
Example :
```
this.$auth.register({
    data: {},
    success: function () {},
    error: function () {},
    redirect: {name: 'login'}
})
```
But as you say, those redirect are picked up bay $router.

So my question was : is it possible to manually trigger redirections that I can catch with `$auth.redirect()`?
Something like`$auth.redirectTo({name: 'login'})`

btw, I found a way to achieve my goal with the `$router`, but if it's possible, it would help me having a cleaner code :)

**Comment by websanova** [comment]
Not directly that really makes much sense as in the login it's not a real
redirect. And maybe the wording is confusing things.

Similarly having a redirectTo is NOT a redirect and would simply be a
wrapper for $router.push.

If you login and send the user to an account page for example, I think it
makes sense just to use router directly.

Why would you specifically need $auth here? I'm just thinking why would you
direct it to the wrong place? And if there are some internal app level
redirects than this is nothing to do with $auth at that point.

**Comment by Pochwar** [comment]
I'm discovering Vue (and vue-auth) and maybe I don't have a full understatement of how doing things.

My intention was just to detect from where and how users reach the login page.
As I discovered that auth.redirect can tell me from where users come from, I first tried this:
// Login.vue

    <div v-if="$auth.redirect() && $auth().redirect().from.name == 'register'">
        You have successfully registered. You can login below
    </div>
    <div v-if="$auth.redirect() && $auth().redirect().from.name != 'register'">
        You are not authorized to reach this page, please, login below
    </div>

But it didn't work as register's redirect uses the router :p 

So, I tried with the router: 
// router.js

    const router = new VueRouter({
      history: true,
      mode: 'history',
      routes,
      previousRoute: null,
    })
    
    router.beforeEach(async (to, from, next) => {
      this.a.options.previousRoute = from.name
      return next()
    })

// Login.vue

    <div v-if="$router.options.previousRoute == 'register'">
        You have successfully registered. You can login below
    </div>
    <div v-if="$auth.redirect()">
        You are not authorized to reach this page, please, login below
    </div>

but with this, the message displays everytime when navigating from register page to login page without registering...

So I end up with this: 
// Register.vue

    this.$auth.register({
          data: {
            email: app.email,
            password: app.password,
          },
          success: function () {
            app.success = true
            this.$router.push({name: 'login', params: {successRegistrationRedirect: true}})
          },

// router.js

    const router = new VueRouter({
      history: true,
      mode: 'history',
      routes,
      successRegistrationRedirect: false,
    })
    
    router.beforeEach(async (to, from, next) => {
      this.a.options.successRegistrationRedirect = to.params.successRegistrationRedirect || false
      return next()
    })

// Login.vue

    <div v-if="$router.options.successRegistrationRedirect">
        You have successfully registered. You can login below
    </div>
    <div v-if="$auth.redirect()">
        You are not authorized to reach this page, please, login below
    </div>

This works, but it would have been easier if I could handle this with $auth.redirect() ;)

btw, thanks for your answers and your package!

**Comment by Pochwar** [comment]
hum... I think we didn't understand each other, maybe cause of my unperfect english (sorry about that :/ ), my lack of knowledge on Vue and the confusing "redirect" property of $auth.register() that is not a redirection catched by $auth.redirect() ^^

So nevermind, I managed to do what I wanted with the last code snipper I share, and sadly, I don't have much time for now to keep looking of a better way to do this.

But again, thank you for taking the time to answer my questions :)

**Comment by renaudham** [comment]
Hi Pochwar

Did you succed ? 

For me it was easy to do..

on my login vue I add this

` data () {
      return {
...
        **initialPageSource**: '',`
        form: {
          **redirect**: '/admin/dashboard',

checking the status on mounted

`  mounted () {
      console.log('mounted')
      if (this.$auth.redirect() != null) {
        this.testInitialPage()
      }
      /* $auth().redirect().from.name */
    },`

then a simple method, where I have added a Snotify alert layer
`
 methods: {
      testInitialPage () {
        this.initialPageSource = this.$auth.redirect().from.fullPath
        console.log(this.initialPageSource)
        this.form.redirect = this.initialPageSource
        this.$snotify.error(this.$t('access_limited_txt'), this.$t('access_limited_ttl'), // 'Error', // $i18n $t()
          {
            timeout: 3000,
            showProgressBar: true,
            closeOnClick: true,
            bodyMaxLength: 1000,
            position: 'rightTop'
          })
      },

`

and last using this variable for redirection on login

`
          this.$auth.login({
...
            redirect: **this.form.redirect**
          })
`
