### ISSUE TITLE
Add method for manual authentication

### ISSUE THREAD

**Issue by martynasS** [websanova/vue-auth#420]
Manual authentication would make easy adding plugins for something like 2FA. I know its possible to just write your own `_loginProcess`, but it would be a lot better to have it out of the box.

**Comment by websanova** [comment]
Yea, I need a wrapper for it, but you can just do this for now.

https://github.com/websanova/vue-auth/blob/master/docs/Guide.md#static-pages

I will add some simple wrapper this week, gonna leave this open for now.
