### ISSUE TITLE
$auth.ready() - always true

### ISSUE THREAD

**Issue by kostya-r** [websanova/vue-auth#421]
Hello, 

$auth.ready() - always return true. I use with $auth.check(), but I think what this problem to save user and route roles. This my code: 
**app.js**

    Vue.router = router;
    Vue.store = store;

    Vue.use(require('@websanova/vue-auth'), {
        auth: {
            request: function(request, token) {
                 this.options.http._setHeaders.call(this, request, {Authorization: 'Bearer ' + token});
            },
            response: function(response) {
                return response.data.access_token;
           }
    },
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    authRedirect: { path: '/auth/login' },
    refreshData: { url: 'auth/refresh', method: 'POST', enabled: true, interval: 30 },
    fetchData: { url: 'auth/user', method: 'POST', enabled: false },
    tokenDefaultName: 'token',
    parseUserData: function(response) {
        store.commit('saveUser', response.data);

        return response.data;
    },
    check: function() {
        const token = window.localStorage.getItem('token');

        if (token) {
            return true;
        } else {
            window.localStorage.clear();
            store.dispatch('user');

            return false;
        }
    }
    });

    App.router = Vue.router;

    new Vue({
        router: Vue.router,
        store: store,
        render: h => h(App)
    }).$mount('#app');

**Home.vue**

`
   <template></template>

    <script>
        export default {
        computed: {},
        data: () => ({}),
        mounted () {
            console.log("READY: ", this.$auth.ready());
            console.log("CHECK: ", this.$auth.check());
        }
    };
    </script>
`

What my problem, why I can't use this ready()?

**Comment by dgriego** [comment]
@websanova,
I'm also having issues with this, from doing a little bit of sleuthing, I was able find that in
`_checkAuthenticated`:

```js
function _checkAuthenticated(cb) {
        // this looks to be an if to trigger a logout process?
        // if so, shouldn't we be looking for a false evaluation on __token.get.call(this)?
        if (this.watch.authenticated === null && __token.get.call(this)) {
            if ( ! __cookie.exists.call(this)) {
                this.options.logoutProcess.call(this, null, {});

                this.watch.loaded = true;

                return cb.call(this);
            }

            this.watch.authenticated = false;

            if (this.options.fetchData.enabled) {
                this.options.fetchPerform.call(this, {
                    success: cb,
                    error: cb,
                    enabled: true
                });
            }
            else {
                this.options.fetchProcess.call(this, {}, {});
                return cb.call(this);
            }
        } else {
            console.log('this is always called before logging in');
            this.watch.loaded = true;
            return cb.call(this);
        }
    }
```

It looks like, I may be wrong, but the check here:
`if (this.watch.authenticated === null && __token.get.call(this)) {`
is checking if they are not authenticated?  It looks to me like that is the case, but wanted to confirm, 

if that is true, then this could fix it:
`if (this.watch.authenticated && !__token.get.call(this)) {`

in addition to that though, there is a check for a cookie, but there isn't a check in that same spot for if they are even using cookie as the tokenStore and if a cookie didn't exist, it is still setting
`this.watch.loaded = true`

**Comment by websanova** [comment]
$auth.ready() is just a toggle and yes will always be true once the app boots, it should be used for pre-load otherwise use $auth.check().

**Comment by krysalead** [comment]
In the documentation $auth.ready() is defined as a toggle that will be true once the fetchUser is done if activated. In my case I have the flag true once the user is authenticated.

**Comment by websanova** [comment]
Which version are you using?
