### ISSUE TITLE
this.$auth.check() gives false on $auth.login response 

### ISSUE THREAD

**Issue by gileneusz** [websanova/vue-auth#424]
I'm logging via $auth:

```
this.$auth.login({
	params: this.data.body,
	rememberMe: this.data.rememberMe,
	 redirect: {name: null},
	fetchUser: this.data.fetchUser            
})
.then((response) => {
console.log('success ' + this.context);
console.log(response)
console.log('test of login:')
console.log(this.$auth.check('company'))
})
```
this gives me false, when logging is success, I tied also:
```
.then((response) => {
console.log('success ' + this.context);
console.log(response)
console.log('test of login:')
console.log(this.$auth.check('company'))
this.$auth.ready(function () {
	if (this.$auth.check('company')) {
	console.log('user authenticated')
	} else {
	console.log('user not authenticated')
	}
})
})
```
and $auth.ready function is not giving any response at all
I've managed to check auth by:
```
let vm = this;
setTimeout(function(){console.log(vm.$auth.check('company'))}, 1500);
```
but relating this to setTimeout is a bad practice...
May I ask how should I correct my code, to make this work?

**Comment by websanova** [comment]
Yes, this is an issue.

So it's logged in, but it's still fetching the user data. So technically
it's not "ready".

Still not sure how to deal with it, I've used a combination of computed
property and watch on $auth.check() which works but is not ideal.

All the methods just return the promise from Vue router, or axios, so don't
really wanna mess with that, especially if we want to inject some events in
as well. Wondering if should just have a onFetch optional method on
register and login.

Probably will add that as a quick fix for now (this weekend).

**Comment by websanova** [comment]
Here is a sample of what I mean for computed check.

~~~
computed: {
    _check() {
        return this.$auth.check();
    }
},

watch: {
    _check() {
        console.log(this.auth.user());
    }
}
~~~

**Comment by gileneusz** [comment]
Thank you, I'll try your fix, it's much better than timeout function. Can you please consider adding this to documentation to show other users how to deal with this issue?

**Comment by websanova** [comment]
Huh? What do you mean, the watch will only trigger if there is a change. Not sure why you think it's gonna trigger for a password update?
