### ISSUE TITLE
Role Login routing not working

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#43]
When a user logins successfully i get the following returned data. 
```
{"token":"TOKENKEY","roles":"2"}
```
My Auth Options
Login Data returns both token and roles

```
var options = {
    token: [{name: 'token', authType: 'bearer', foundIn: 'response'}],
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/acnt', method: 'GET'},
    rolesVar: 'roles'
};
```

In My routing i have the following routes

```
Vue.router.map({
    '/auth/login': {
        component: (resolve) => { require(['./components/views/login.vue'], resolve); }
},

'dashboard': {
    auth: ["1"],
    name:"dashboard",
        component: (resolve) => { require(['./components/views/dashboard.vue'], resolve); }
});
```

It Doesn't Route to the dashboard.  If I remove auth: ["1"]  to auth:true.  It works.  I am getting the following error

```
TypeError: this.watch.data is undefined
[Learn More]app.js:15062:58
[vue-router] Uncaught error during transition: 
```

here is a list of vue resources i am using

```
"@websanova/vue-auth": "^1.4.0-beta",
    "vue": "^1.0.26",
    "vue-hot-reload-api": "^2.0.6",
    "vue-html-loader": "1.2.3",
    "vue-loader": "8.5.4",
    "vue-mdl": "^0.9.4",
    "vue-resource": "^1.0.3",
    "vue-router": "^0.7.13",
    "vue-strap": "^1.0.11",
    "vue-style-loader": "^1.0.0",
    "vuex": "^1.0.0-rc.2",
```

**Comment by websanova** [comment]
What version of.vue auth are you using?

**Comment by websanova** [comment]
Ah yes, ok, I see, because the plugin expects any data to be return in a
"data" object. So {token: 'tokrn', data: {roles:...}}

**Comment by websanova** [comment]
You can override the _userData function to change this behavior, but
generally not a good idea otherwise you would store the token and other
data along with user.

Also good to have convention like status and errors for consistent format.
Just my two cents though.

**Comment by kyoukhana** [comment]
Should it be something like this proper JSON? 

```
{"token":"DSXRREIEI","data":[{"userid":1,"roles":2,"name":"Joe","lastname":"Smith"}]}

```

I tired with this format but didn't work

**Comment by websanova** [comment]
why did you put it in an array?

**Comment by kyoukhana** [comment]
So I changed it out of a array still doesn't work

```
{"token":"DASXEERE","data":{"roles":1,"name":"Joe","lastname":"Smith"}}
```

Here is what the router configuration looks like
```
Vue.router.map({
    '/auth/login': {
        component: (resolve) => { require(['./components/views/login.vue'], resolve); }
},

'dashboard': {
    auth: [1,3],
    name:"dashboard",
        component: (resolve) => { require(['./components/views/dashboard.vue'], resolve); }
});

```

Here is the AuthController in Laravel
```
   public function authenticate(Request $request){
        $credentials=$request->only('email','password');

        try{
            if(! $token = JWTAuth::attempt($credentials)){
                return response()->json(['error'=>'invalid_credentials'], 401);
            }
        } catch(JWTException $e){
            return response()->json(['error'=>'couldnt_not_create_token'], 500);
        }
        $dta= User::where(['email' => $request->get('email')])->select('role_id as roles','name','lastname','email')->get();
        $data=$dta[0];
        return response()->json(compact('token', 'data'));
    }
```

**Comment by websanova** [comment]
Note it's also doing an === check and you have an int and a string for the
roke. Maybe sort that out as well first.

**Comment by websanova** [comment]
Probably why the true is working since.its doing 1 === true, but 1 === "1"
will fail.

**Comment by websanova** [comment]
Can also try overriding this function in the options and see what data
gives you.

_parseUserData: function(data) {
        console.log(data.data);
        return data.data;
}

**Comment by kyoukhana** [comment]
Should I put this.  In my main application file

```
_parseUserData: function(data) { console.log(data.data); return data.data; }

```

**Comment by kyoukhana** [comment]
I put it in the options like this

```
/*vue-jwt-auth options */
var options = {
    token: [{name: 'token', authType: 'bearer', foundIn: 'response'}],
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/acnt', method: 'GET'},
    rolesVar: 'roles',
    _parseUserData: function(data) { console.log(data.data); return data.data; }
};
```

**Comment by websanova** [comment]
As a vue auth option

**Comment by websanova** [comment]
Ya what's the output there in the console?

**Comment by websanova** [comment]
What version of the vue-auth plugin you are using?

**Comment by kyoukhana** [comment]
I am using @websanova/vue-auth": "^1.4.0-beta"

**Comment by kyoukhana** [comment]
I edited _parseUserData function in the module to output the values and it said undefined.  So I changed the database so it outputs the following results.  Notice how the roles is a string.

Here is what the router configuration looks like
```
Vue.router.map({
    '/auth/login': {
        component: (resolve) => { require(['./components/views/login.vue'], resolve); }
},

'dashboard': {
    auth: [1,3],
    name:"dashboard",
        component: (resolve) => { require(['./components/views/dashboard.vue'], resolve); }
});
```

```
{
  "token": "XRDF134",
  "data": {
    "roles": "2",
    "name": "Joe",
    "lastname": "Smith",
    "email": "jsmith@gmail.com"
  }
}
```

**Comment by kyoukhana** [comment]
I think the problem is with fetchData.  fetchData is the area where it will get the roles.  My question is how do you pass the returned token to fetchData?

```
/*vue-jwt-auth options */
var options = {
    token: [{name: 'token', authType: 'bearer', foundIn: 'response'}],
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/account', method: 'GET'},
    rolesVar: 'roles',
    _parseUserData: function(data) { console.log(data.data); return data.data; }
};

```

**Comment by websanova** [comment]
Wait a sec. The issue may just be the token. The plugin is using the `Authorization` header by default. If you are getting undefined in that parseUserData function then something else is wrong.

Can we take a step back just cut the front end out of the equation for a second. What do your api requests look like for login and fetching user. Meaning the url, data (body or query params) and method used. Also where does your server expect the token? body, auth, what are the parameters it's looking for, etc. Let's see what a successful response looks like for both of these.

**Comment by websanova** [comment]
Just realized something, you're also using v1.4.0-beta, and there have been some auth changes there, you will likely need to create a simple custom auth driver. I've updated the docs about this.

But basically because token in body is a bit non standard (I think more official way is using Authorization header), I've eliminated this to simplify the auth. There were just too many different formats.

https://github.com/websanova/vue-auth#authentication

In your case it would probably look like this:

~~~
authType: 'custom1',

custom1Auth: {
    request: function (req, token) {
        req.headers.set('Authorization', token);
    },
    response: function (res) {
        return (res.data.data || {}).token;
    }
}
~~~

**Comment by websanova** [comment]
I also see you are using Laravel (JWTAuth) so if you wanted to keep it standard you could just add the header in your responses as well..

~~~
return response(['status' => 'success'])->header('Authorization', $token);
~~~

**Comment by kyoukhana** [comment]
With the JWT auth here is the code for the response.  Token isn't inside of data

```
public function authenticate(Request $request){
        $credentials=$request->only('email','password');

        try{
            if(! $token = JWTAuth::attempt($credentials)){
                return response()->json(['error'=>'invalid_credentials'], 401);
            }
        } catch(JWTException $e){
            return response()->json(['error'=>'couldnt_not_create_token'], 500);
        }
        $dta= User::where(['email' => $request->get('email')])->select('role_id as roles','name','lastname','email')->get();

        $data=$dta[0];
        $status="success";

        return response()->json(compact('token', 'data','status'));
    }
}

```

In Your example 
```
return response(['status' => 'success'])->header('Authorization', $token);
```
It only returns success without token and no data attributes of the user such as role.

I added the custom auth like so  but this assumes that token is inside data.  How do we make it so that its outside of data.  The other concern is **fetchData** in this area is it for getting the roles or we include this in the l**oginData**.  l**oginData** should grab the token and the roles.  

```
/*vue-jwt-auth options */
var options = {
    token: [{name: 'token', authType: 'bearer', foundIn: 'response'}],
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/account', method: 'GET'},
    rolesVar: 'roles',
    authType: 'custom1',

    custom1Auth: {
        request: function (req, token) {
            req.headers.set('Authorization', token);
        },
        response: function (res) {
            return (res.data.data || {}).token;
        }
    }
};
```

With this code above I belive it assumes that the format is like so.  
```
{data: {token: 'abcd1234'}}
```

The response in my data is like so.   This is for auth
```
{
  "token": "XRDF134",
  "data": {
    "roles": "2",
    "name": "Joe",
    "lastname": "Smith",
    "email": "jsmith@gmail.com"
  },
"status": "success"
}
```

**Comment by websanova** [comment]
It was just example of how to put the token in header. And again would be
nice to see your api calls and responses first.

**Comment by kyoukhana** [comment]
Ah ok so I am at a loss as to what I need to fix on my end.  Please advise.  I have been struggling with this now for a while.

In VueJs I have it now **returning the token**,  But at what point does jwt-auth get the roles. is it in
fetchData?  Is there a custom function for that to define.  Because my return data format is different.  


```
/*vue-jwt-auth options */
var options = {
    token: [{name: 'token', authType: 'bearer', foundIn: 'response'}],
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/account', method: 'GET'},
    rolesVar: 'roles',
    authType: 'custom1',

    custom1Auth: {
        request: function (req, token) {
            req.headers.set('SomeHeader', token);
        },
        response: function (res) {

            **return (res.data.token || {});**  //This was changed to return just the token.  In the response roles are here as well but just getting the token
        }
    }
};
``

Again here is the JWT Auth in Laravel
```
public function authenticate(Request $request){
        $credentials=$request->only('email','password');

        try{
            if(! $token = JWTAuth::attempt($credentials)){
                return response()->json(['error'=>'invalid_credentials'], 401);
            }
        } catch(JWTException $e){
            return response()->json(['error'=>'couldnt_not_create_token'], 500);
        }
        $dta= User::where(['email' => $request->get('email')])->select('role_id as roles','name','lastname','email')->get();

        $data=$dta[0];
        $status="success";
        return response()->json(compact('token', 'data','status'));
    }
```

Here is the response **FORMAT** from the server
```
{
  "token": "XRDF134",
  "data": {
    "roles": "2",
    "name": "Joe",
    "lastname": "Smith",
    "email": "jsmith@gmail.com"
  },
"status": "success"
}
```

**Comment by kyoukhana** [comment]
So I think the issue is here.  The problem is that **fetchData**  as far as i can understand returns the roles.  But in my API you need the token to return the auth user.  

```
/*vue-jwt-auth options */
var options = {
    token: [{name: 'token', authType: 'bearer', foundIn: 'response'}],
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/acnt', method: 'GET'},
    rolesVar: 'roles',
    authType: 'custom1',
    custom1Auth: {
        request: function (req, token) {
            req.headers.set('SomeHeader', token);
        },
        response: function (res) {

            return (res.data.token || {});
        }
    }
};

Here is the laravel portion of it.

Controller
```
 public function show()
    {
        return "data:".Auth::user();
    }
```

Route
```
Route::get('account',[
        'middleware' => [
            'jwt.auth'
        ],
        'roles' => ['administrator'],
        'as'=>'account.show',
        'uses' => 'AccountController@show'
    ]);
```

**Comment by websanova** [comment]
ok, if you are sending back this: `return "data:".Auth::user();` we definitely have some issues.

Here is what mine looks like.

~~~
    public function login(Request $request)
    {
        $user = User::where('email', $request->get('email'))->first();

        if ( ! $token = JWTAuth::attempt($request->only('email', 'password'))) {
            return response([
                'status' => 'error',
                'msg' => 'Invalid credentials.',
                'errors' => [
                    ['field' => 'email', 'rule' => 'auth', 'message' => 'Invalid credentials.'],
                    ['field' => 'password', 'rule' => 'auth', 'message' => 'Invalid credentials.']
                ]
            ], 400);
        }

        return response([
            'status' => 'success'
        ])
        ->header('Authorization', $token);
    }

    public function user(Request $request)
    {
        $user = User::with('avatar')->find(Auth::user()->id);

        return response([
            'status' => 'success',
            'data' => $user
        ]);
    }

Again, I feel there are issues with your api, would be nice to see the exact request and response your api call are giving (not your code).

**Comment by kyoukhana** [comment]
Here is the API Code.  Probably will shed some light. 

**Authenticate**

```
public function authenticate(Request $request){
        $credentials=$request->only('email','password');

        try{
            if(! $token = JWTAuth::attempt($credentials)){
                return response()->json(['error'=>'invalid_credentials'], 401);
            }
        } catch(JWTException $e){
            return response()->json(['error'=>'couldnt_not_create_token'], 500);
        }
        $dta= User::where(['email' => $request->get('email')])->select('role_id as roles','name','lastname','email')->get();

        $data=$dta[0];


        return response()->json(compact('token', 'data','status'));
    }
```

**Return user Account information**
```
  public function show()
    {
        return "data:".Auth::user();
    }
```

To get the user credentials here is the route.  You basically pass the token and it will return the user account information.  Before I had it as post not get.

```
Route::get('account',[
        'middleware' => [
            'jwt.auth'
        ],
        'roles' => ['administrator'],
        'as'=>'account.show',
        'uses' => 'AccountController@show'
    ]);
```

**Comment by websanova** [comment]
Yes, you've sent this code already. But I'm more interested in the api request/response.

Also, as I've mentioned this: `return "data:".Auth::user();` is definitely not right. Please look at the sample code I gave you.

**Comment by kyoukhana** [comment]
So here is my code to get the user account.  Because with vue-auth I don't think it passes the token in POST or get to get the user account information. 

## Controller

```
 public function show()
    {
        $user=Auth::user();
        return response([
            'status' => 'success',
            'data' => $user
        ]);

    }
```

## Route Request
```
 Route::get('account',[
        'middleware' => [
            'jwt.auth'
        ],
        'roles' => ['administrator'],
        'as'=>'account.show',
        'uses' => 'AccountController@show'
    ]);
```

To get the results of the user you need to pass the token and it will return the user  information.
http://www.devapp.com/api/account

When passed the token using postman it will return the following.
```
{
  "status": "success",
  "data": {
    "id": 1,
    "role_id": "2",
    "name": "Joe",
    "lastname": "Smith",
    "email": "jsmith@gmail.com",
    "lang": "en",
    "referral_code": "0",
    "created_at": "2016-10-11 19:26:09",
    "updated_at": "2016-10-11 19:26:09"
  }
}
```

**Comment by websanova** [comment]
~~~
authType: 'custom1',
    custom1Auth: {
        request: function (req, token) {
            req.headers.set('SomeHeader', token);
        },
        response: function (res) {

            return (res.data.token || {});
        }
    }
~~~

Did you actually leave it as "SomeHeader"? It "should" be `Authorization`, but depends what you have setup.

**Comment by kyoukhana** [comment]
Sorry I didn't leave it at SomeHeader.  

My Question is that with 

```
 fetchData: {url: 'api/account', method: 'GET'},
```

How do I pass a token to it to return the user data?  Once the user is authorized the fetchData should have the ability to grab the token.  Therefore the response from the API would be the users roles and basic information. 

You can see my API above that it needs a token to return the user information.

**Comment by websanova** [comment]
It automatically sends it in header of every request.

**Comment by kyoukhana** [comment]
I have isolated the problem. The issue is that with the API needs the request as bearer.  What is coming back as the header request is. 

```
Acceptapplication/json, text/plain, */*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5Authorization[object Object]Connectionkeep-aliveCookierememberMe=true; XSRF-TOKEN=eyJpdiI6ImMzbWhadmowNUdJMFNXMFwvNld4bWlnPT0iLCJ2YWx1ZSI6IlJcL2FlSEFDYkZpYVBUMnN0V0NPeTJVaTJuWXJ4TFduQkZkOFBJbDlGQ3RkMXFHd2RZSkFnaDZGYUtyRlQrbU9GNjBibHRcL2JwS1wvT3BBOVZCUzZMNXZBPT0iLCJtYWMiOiJiYzhkNTUyYzcwZjgzYTJkMjJkOTBlNjU1ZGI0Y2NiNDZkN2RhM2UyYTE2ZjMwYzI2MjlkZGQ1OTUzYjNhMjFkIn0%3D; laravel_session=eyJpdiI6IjZrZDVMQzhzcURsQ3B6Rm1lczhPamc9PSIsInZhbHVlIjoiUFU5MW1OOXcyWjNoa1h1VHk0NjlGMVNsalBGUFJWRmNYbktqNHNBeHpTS250XC9IZWFcL1JMeHc3Y3RySHlqYktrUTUwZ09YcmVUalwvdmx5SzRSTHhRTFE9PSIsIm1hYyI6IjkzYTY1ZWNhNGExMjk4MDg4NTAzYjFmYmNkNzZhNjUyYWU1MDQyOGRiN2RlZmU3NWViZTc1YjQwN2RhYWE1OGMifQ%3D%3DHostwww.devqi.comRefererhttp://www.devqi.com/User-AgentMozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0X-CSRF-TOKENfnHnmhQ3nfpfcAhwZfRe6zCbSuvmyU3BqxPc5pNwX-Requested-WithXMLHttpRequest
```

```
fetchData: {url: 'api/account', method: 'GET'}
```

**Comment by websanova** [comment]
Right.

**Comment by kyoukhana** [comment]
So how do we fix this so that the Authorization header is bearer:?

**Comment by websanova** [comment]
Not sure, that's question for Laravel/jwt auth guys. That should be working
out of the box.

**Comment by websanova** [comment]
Not sure why you ha e object there, seems strange.

**Comment by kyoukhana** [comment]
Here is what the request looks like in postman.  It works



![alt text](http://www.kyoukhana.com/images/_troubleshoot/resquest.png "Troubleshoot")

**Comment by kyoukhana** [comment]
Ok So I finally got it working.

needed to change the options to this
```
/*vue-jwt-auth options */
var options = {
    token: [{request: 'token', response: 'token', authType: 'bearer', foundIn: 'header'}],
    tokenName:'token',
    loginData: {url: 'api/auth', method: 'POST', redirect: 'dashboard'},
    fetchData: {url: 'api/account', method: 'GET' , authType: 'bearer'},
    rolesVar: 'role_id'
};
```


## Laravel Stuff

Here is the login auth code

```
   public function login(Request $request)
    {
        if ( ! $token = JWTAuth::attempt($request->only('email', 'password'))) {
            return response([
                'status' => 'error',
                'msg' => 'Invalid credentials.',
                'errors' => [
                    ['field' => 'email', 'rule' => 'auth', 'message' => 'Invalid credentials.'],
                    ['field' => 'password', 'rule' => 'auth', 'message' => 'Invalid credentials.']
                ]
            ], 400);
        }

        return response([
            'status' => 'success'
        ])
            ->header('Authorization', $token);
    }
```

Account Controller

```
public function show()
    {
        $user=Auth::user();
        return response([
            'status' => 'success',
            'data' => $user
        ]);

    } 
```

## Routes

```
  Route::get('account',[
        'middleware' => [
            'jwt.auth'
        ],
        'roles' => ['administrator'],
        'as'=>'account.show',
        'uses' => 'AccountController@show'
    ]);


Route::post('auth',[
        'as'=>'auth.authenticate',
        'uses'=>'AuthController@login',
    ]);

```

**Comment by websanova** [comment]
Ok
