### ISSUE TITLE
persisting $auth.user between page refreshes

### ISSUE THREAD

**Issue by renemendoza** [websanova/vue-auth#434]
Hello, 
After a succesful login,
I am able to  set up $auth.user() properly 
( it is done manually at the moment because I cant make parseUserData do anything)
Then i am able to navigate to the proper componet using  router.go('my-component') and vue-auth will honor my $auth.user().roles. However if try to navigate to any component by clicking on a router-link element or by manually refreshing the browser $auth.user will be wiped

 and more importantly my roles are wiped out, which sends me back to the login screen

My question is, how to persist $auth.user between page refreshes?

**Comment by renemendoza** [comment]
```
  module.exports = {

      request: function (req, token) {
        this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
      },
      response: function (res) {
        return res.body.jwt
      }
  };
```

**Comment by renemendoza** [comment]
When i visit a new page, that is secured with 
i get

```
TypeError: Cannot read property 'roles' of undefined
    at Auth._transitionEach (auth.js:97)
    at Auth.<anonymous> (vue-router.2.x.js:34)
    at Auth._checkAuthenticated (auth.js:57)
    at Auth._routerBeforeEach (auth.js:82)
    at vue-router.2.x.js:31
    at iterator (vue-router.esm.js:1943)
    at step (vue-router.esm.js:1717)
    at runQueue (vue-router.esm.js:1725)
    at HTML5History.confirmTransition (vue-router.esm.js:1972)
    at HTML5History.transitionTo (vue-router.esm.js:1874)
```

**Comment by websanova** [comment]
Are you using $auth.ready ?

**Comment by renemendoza** [comment]
@websanova yes Rob, i am using it, actually  `` {{ $auth.watch.authenticated }} `` and `` this.$auth.check()`` keeps working across page visits. if i change the above Customers router config into 
```
path: 'customers',
          component: Customers,
          name: 'customers',   
         meta: { auth:  true }

```

by removing the roles configuration i no longer get the error
 however $auth.user().roles and any other user data do get wiped out.

**Comment by renemendoza** [comment]
btw i am using Rails based webpacker SSR.

**Comment by websanova** [comment]
Could be many things. Do you see any requests to fetch the user or refresh
going out at all?

**Comment by renemendoza** [comment]
I also need to mention that I am running vue from inside a server side app (Rails /webpacker) in case somebody later runs into this. Not sure if this is what is called a SSR scenario

**Comment by renemendoza** [comment]
I am closing this now unless you have any other comment @websanova  thanks!

**Comment by jongbonga** [comment]
Hi there

I'm getting the same issue with manual auth.
so I basically `$auth.user(**userObject**)` then navigate to Dashboard where `$auth.user()` displays my **userObject**. but as soon as I refresh the page, **userObject** becomes an empty object `{}`

**Comment by adrianpearl** [comment]
Hi, I was having similar issues and was able to fix them by wrapping anything auth-related in a `<div v-if="!auth.loading">`. Inside that div, I have full access to `$auth` and all of its properties.

**Comment by websanova** [comment]
@adrianpearl that's what `$auth.ready()` and `$auth.load()` are for.
