### ISSUE TITLE
How to catch automatic refresh data request error (Http 500 error)?

### ISSUE THREAD

**Issue by bhusalb** [websanova/vue-auth#436]
I am getting uncaught response for refresh data request.

`Uncaught (in promise) Response {url: "auth/refresh", ok: false, status: 500, statusText: "Internal Server Error", headers: Headers, …}`

I don't want to use global interceptor for catching this exception. There is any way to pass callback for such error case. I haven't called the `this.$auth.refresh` manually.

**Comment by websanova** [comment]
Did you try setting success method on ferchData option in settings?
