### ISSUE TITLE
Issue Redirecting

### ISSUE THREAD

**Issue by go4cas** [websanova/vue-auth#439]
Thanks for the great plugin!

I have worked through the docs and the demo code, and have managed to configure most correctly. My main issue is that after successful login, the redirect does not follow.

Here's my login method:
```javascript
this.$auth.login({
  data: this.loginForm,
  rememberMe: true,
  redirect: { name: 'console.desktop' },
  fetchUser: true
})
```
My route definition:
```javascript
{
  path: '/console',
  name: 'console.desktop',
  component: () => import('@/views/Home/Index.vue'),
  meta: {auth: true},
},
```
I can confirm that the login API call responds successfully, and that the user is correctly fetched.

If I set meta: `{auth: false}` or `meta: {auth: undefined}` then the redirect works correctly.

Any ideas?

**Comment by go4cas** [comment]
Never mind. I had weird redirect logic inside my router.

**Comment by aldozumaran** [comment]
Hi @go4cas , I have the same problem

```
[
    {
        path: '/login',
        name: 'login',
        component: () => import('pages/login')
    },
    {
        path: '/',
        component: () => import('layouts/default'),
        meta: { auth: true },
        children: [
            { path: '', name: 'dashboard', component: () => import('pages/Index') },
            { path: 'home', name: 'home', component: () => import('pages/home') }
        ]
    },

    { // Always leave this as last one
        path: '*',
        component: () => import('pages/Error404')
    }
]
```

this is my routes file, where is the problem?

**Comment by go4cas** [comment]
@aldozumaran, check that you don't have an redirect logic in `router.beforeEach` somewhere. Also ensure that `vue-router` is loaded before `vue-auth`.

Can you share your `this.$auth.login` config?

**Comment by aldozumaran** [comment]
this is my config, i'm using quasar 0.17 as frontend and laravel 5.7 as backend
[config.txt](https://github.com/websanova/vue-auth/files/2490572/config.txt)

**Comment by go4cas** [comment]
@aldozumaran, when you check the "Console" and "Network" tabs in Dev Tools in your browser, do you see successful API response?

If you see a success response, you could try to add `redirect` to your `login` call, e.g:
```javascript
redirect: { path: '/' }
```

**Comment by aldozumaran** [comment]
I did it, but it doesn't work.

 /auth/login response
```
access_token: "eyJ0eXAiOiJKV1QiLCJh..."
expires_in: 3600
token_type: "bearer"
```

**Comment by aldozumaran** [comment]
if i comment meta object, it works

[routes.txt](https://github.com/websanova/vue-auth/files/2490699/routes.txt)

**Comment by go4cas** [comment]
It might have something to do with the nested routes. Can you try to redirect it to a route without any children, to test?

**Comment by aldozumaran** [comment]
No, doesn't work with auth:true, login not create rememberMe cookie

**Comment by go4cas** [comment]
Can you check your code base for `Router.beforeEach`? This was my original problem.

**Comment by aldozumaran** [comment]
i don't have beforeEach on my code base, there is one on vue-router.2.x.js
```

_beforeEach: function (routerBeforeEach, transitionEach) {
        var _this = this;

        this.options.Vue.router.beforeEach(function (transition, location, next) {
            _this.options.setTransitions.call(this, transition);
            
            routerBeforeEach.call(_this, function () {
                var auth = _this.options.getAuthMeta(transition);

                transitionEach.call(_this, transition, auth, function (redirect) {
                    if (!redirect) {
                        (next || transition.next)();
                        return;
                    }

                    // router v2.x
                    if (next) {
                        next(redirect);
                    } else {
                        this.options.router._routerReplace.call(this, redirect);
                    }
                });
            });
        })
    },
```

**Comment by go4cas** [comment]
I see that you send the `access_token` in the body of your response. By default, `vue-auth` expects the token to be in the `Authorization` header of your response. Can you try that?

**Comment by aldozumaran** [comment]
Ohhhhhh thanks, it works
