### ISSUE TITLE
vue-resource alternatives?

### ISSUE THREAD

**Issue by dgrubelic** [websanova/vue-auth#44]
So, vue team just announced that they will retire `vue-resource` as official lib for request handling. From what they are saying, no more development or support will be put into this lib. Any thoughts on replacing this lib (or making it request lib agnostic) in near future? For example, official suggestion is `axios` (https://github.com/mzabriskie/axios), but i don't think it will work `out-of-the-box` because of different request/response interceptor registration.  Lib itself looks good and i plan to use it in my new project. I guess i'm just not comfortable using lib that has limited support or no future development plans.

I'm just starting a new project using `vue.js` and this basically means that i will abandon `vue-resource` and use `axios` instead.

https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.fepyvnwbo

**Comment by websanova** [comment]
Hmm, well, the plugin is far more dependent on vue-router than on
vue-resource. Actually the http part of it is non critical and just a small
piece.

It sux they would stop supporting it but right now the plugin is already
designed to handle this as there is a driver file. So would not be hard to
forward http calls into whatever plugin is being used for http.

I really wouldn't want to hard code all this logic into the plugin as it
would likely be duplicate bloat. Will have too see how this unravels.

**Comment by websanova** [comment]
I will test out axios soon, and see how compatible it is.

**Comment by dgrubelic** [comment]
Well, current driver architecture is not so good since you would have to rewrite entire driver just to support some other request handling lib. Maybe a parameter based driver factory would be more appropriate solution. Another one would be to remove driver concept entirely and implement everything as `options` concept. That way you could replace only `http`or `interceptor` module. 

Imho, current driver implements both `router` and `http` modules which makes it difficult to replace only one module since you would end up having to reimplement module that doesn't change at all. This is what i can see from `vue.1.0.0.js` driver.

**Comment by ghprod** [comment]
:+1: for axios

**Comment by dgrubelic** [comment]
Hi @websanova Any progress on this one?

**Comment by websanova** [comment]
Hey, yes, I'm looking into this one today. Thinking to remove this dependency all together.

* http://stackoverflow.com/questions/25335648/how-to-intercept-all-ajax-requests-made-by-different-js-libraries
* http://stackoverflow.com/questions/5202296/add-a-hook-to-all-ajax-requests-on-a-page

It's a small override for the interceptors, and then use Vanilla js for the ajax calls. Probably the best way to go since don't really need anything fancy for the plugin. The only thing is the base url would need to be set like the `http.options.root` but that's not such a big deal I think.

**Comment by websanova** [comment]
Hey, so decided to make a more direct driver centric approach for now. The README has been updated ad it will now be in a `v2.x` line. I didn't add support for axios yet, but it should be be easy enough to add.

Just take a look in the drivers folder and you can pretty much follow the `vue-resource` file. I will probably not get around to looking at axios myself for another week or two. But I'm hoping with the new setup driver files can be contributed much easier for different packages and versions.

**Comment by ghprod** [comment]
Sound cool Rob.. Thanks
