### ISSUE TITLE
Auto login user after registration

### ISSUE THREAD

**Issue by ddzobov** [websanova/vue-auth#442]
My code returning token after registration - but user after it redirecting to login page. 

autoLogin option for me bad idea - this sending second query to server.

**Comment by go4cas** [comment]
@ddzobov ... you should be able to set your rediect on the [`registerData`](https://github.com/websanova/vue-auth/blob/master/docs/Options.md#registerdata-url-authregister-method-post-redirect-login) property.

**Comment by ddzobov** [comment]
> @ddzobov ... you should be able to set your rediect on the [`registerData`](https://github.com/websanova/vue-auth/blob/master/docs/Options.md#registerdata-url-authregister-method-post-redirect-login) property.

My register method returning Authorization header - i dont need redirect after login

**Comment by capaci** [comment]
I was having the same problem, but with a reset password function. What I did to solve this was setting token manually using the method `token()` described in the [docs](https://github.com/websanova/vue-auth/blob/master/docs/Methods.md#token).

```javascript
    async reset () {
          let { data: { jwt, user } } = await this.axios.post('/auth/reset-password', {
            token: this.token,
            password: this.form.password,
            passwordConfirmation: this.form.passwordConfirmation
          })
          this.$auth.token(null, jwt)
          this.$auth.user(user)
          this.$router.push({ name: 'dashboard' })
    }
```

I think this may work, but now I'm having another problem, the token saved to localStorage is deleted after the `router.push`. I'm trying to figure out why this is happening, I think this is not related to vue-auth.

**Comment by capaci** [comment]
I figured out what happened. The vue-auth data wasn't set correctly. I followed [this recommendations](https://github.com/websanova/vue-auth/blob/master/docs/Guide.md#static-pages).

My final code:
```javascript
async reset () {
      let { data: { jwt, user } } = await this.axios.post('/auth/reset-password', {
        token: this.token,
        password: this.form.password,
        passwordConfirmation: this.form.passwordConfirmation
      })
      this.$auth.token(null, jwt)
      this.$auth.watch.data = user
      this.$auth.watch.loaded = true
      this.$auth.watch.authenticated = true
      this.$router.push({ name: 'dashboard' })
}
```

**Comment by websanova** [comment]
You could also just call $auth.login() her with email password set (since we have the new password already).
