### ISSUE TITLE
tokenStore  isn't  working with   ['sessionStorage', 'cookie'], but token stored in localStorage

### ISSUE THREAD

**Issue by skortabeast** [websanova/vue-auth#449]
when I use option with "tokenStore"  isn't working , websanova vesrion - "^2.21.14-beta"
![image](https://user-images.githubusercontent.com/10978770/48185143-0e225f80-e32c-11e8-9393-aaf78f0c112c.png)
![image](https://user-images.githubusercontent.com/10978770/48185191-30b47880-e32c-11e8-967d-5452af4762bd.png)
![image](https://user-images.githubusercontent.com/10978770/48185393-ba644600-e32c-11e8-9fb2-5257edc838ab.png)

**Comment by skortabeast** [comment]
this problem can resolve by changing code at token.js 

```
function isSessionStorageSupported()  {
        try {
            if (!window.sessionStorage) {
                throw 'exception';
            }
            sessionStorage.setItem('storage_test', 1);
            sessionStorage.removeItem('storage_test');
            return true;
        } catch (e) {
            return false;
        }
}
```
but I don't know how make functional for  clear  sessionStorage  after browser was closed, maybe have other solutions?

**Comment by IljaN** [comment]
Had the same issue with brave-browser which blocked local-storage in incognito mode thus forcing vue-auth to fallback to cookie

**Comment by websanova** [comment]
Hello, bit late, but this has been updated with version 3 release. Please check [Tokens Guide](https://websanova.com/docs/vue-auth/guides/tokens) for more details.
