### ISSUE TITLE
Lost redirect when token is expired

### ISSUE THREAD

**Issue by tuanlc** [websanova/vue-auth#454]
Hello,
I'm encountering an issue that the redirect link is lost when the token is expired. It is the invalid token case.

Context:
- User logged in and is in `/currentpage/url`
- User closes the tab
- User come back (re-open tab for example) after token expire time
- Vue auth redirect user to login page without redirect to origin page (`/currentpage/url`)
- User logged in but not in `/currentpage/url` page

As I saw on lines:
- https://github.com/websanova/vue-auth/blob/706b151a337a27b99c86516cbf42dfcd865450d0/src/auth.js#L247
and 
- https://github.com/websanova/vue-auth/blob/706b151a337a27b99c86516cbf42dfcd865450d0/src/auth.js#L360

That the redirect link will be overridden to login page, but it totally lost the origin redirect when user logged in again.

There is a solution that we refresh token to avoid expiration. But it does not work if user closes the Vue tab and come back after.

Is there any solution for this case?

**Comment by gorbunovav** [comment]
@websanova Hi! Could you comment on this?

**Comment by gorbunovav** [comment]
@websanova, maybe the explicit redirect to the login page is not required during the invalid token processing? I mean this block from the `_processInvalidToken` method:

https://github.com/websanova/vue-auth/blob/706b151a337a27b99c86516cbf42dfcd865450d0/src/auth.js#L246-L250

this method logouts the user, and if the target page requires authentication, the login process will be handled by the general logic with the correct redirect after the login.

**Comment by websanova** [comment]
This was updated a while ago actually with a `$auth.redirect()` function that will give the previous route if there was some redierct.

Also, please note the plugin has been updated to version 3, so grab the latest if you're still using the old one.

https://websanova.com/docs/vue-auth/upgrades/2x-3x

**Comment by tuanlc** [comment]
Thank you!
