### ISSUE TITLE
The documentation isn't clear about the authType option

### ISSUE THREAD

**Issue by guillaumekpomda** [websanova/vue-auth#455]
I'm trying to override the authType option:

Here are my config:

```
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: {
    url: 'auth/local'
  },
  authType: 'custom1',
  custom1Auth: {
    request: function (req, token) {
      console.log(req)
      this.options.http._setHeaders.call(this, req, { Authorization: 'Bearer ' + token });
    },
    response: function (res) {
      console.log(res)
      return res.data.jwt
    }
  }
});
```

My problem is that the custom1Auth option seems to be ignored (that's why I added the console.logs). I don't see anything being logged in the console so it seems that my options are just ignored...

Also, When you look at the Options page in the docs: https://github.com/websanova/vue-auth/blob/master/docs/Options.md

It looks like 'authType' is not to be declared at the root of the config variable, like I did, but has to be nested inside the 'token' property:

`token: [{request: 'Authorization', response: 'Authorization', authType: 'bearer', foundIn: 'header'}, {request: 'token', response: 'token', authType: 'bearer', foundIn: 'response'}]`

The documentation lacks clarity about that option... Can anyone please help?
Thanks in advance

**Comment by capaci** [comment]
Hi @sikko . I was having the same problem. What I did was just to ignore authType and customAuth and set my driver in `auth` property

Something like this:
```
Vue.use(VueAuth, {
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: {
    url: 'auth/local'
  },
  auth: {
    request: function (req, token) {
      this.options.http._setHeaders.call(this, req, { Authorization: 'Bearer ' + token });
    },
    response: function (res) {
      return res.data.jwt
    }
  }
})
```

This worked for me
