### ISSUE TITLE
Logout  after fetchUser  not  working

### ISSUE THREAD

**Issue by Akopean** [websanova/vue-auth#457]
Version: "@websanova/vue-auth": "^2.21.14-beta"
![image](https://user-images.githubusercontent.com/13051822/51991713-575df780-24b4-11e9-984f-a01364578f9f.png)
```
  axios.interceptors.response.use(response => {
    return response
    }, error => {
        if (error.response.status === 401 || error.response.status === 403) {
            Vue.auth.logout({
                redirect: 'login',
                makeRequest: false,
            });
        }
        else if (error.response.status === 500) {
            window.toastr.error(error.response.data.message, 'Error');
            Vue.router.push('error-500');
        }
        return Promise.reject(error)
    });
```

Vue.auth.logout - does not clear the token and does not redirect the user.
if I refresh the page it will again make a request fetchUser

if you change the code Vue.auth.logout to Vue.router.push ('login'); then it redirects and the repeated request for verification of the token does not go.

Why does not work Vue.auth.logout and does not do its job

**Comment by yoyTeam** [comment]
Hi!, I have the same problem you can fix that?, maybe you can help me, I tried with axios interceptors and nothing happend, Regards!

**Comment by websanova** [comment]
Nothing to special with the logout method, perhaps make sure it's even being called and also test calling it manually.

Also new version 3 is released, so potentially some bugs fixed there.

https://websanova.com/docs/vue-auth
