### ISSUE TITLE
this.$auth.user() returns an empty object

### ISSUE THREAD

**Issue by murum** [websanova/vue-auth#46]
HI!

I'm using an external golang API created with labstack/echo and using HS256 as the crypt algoritm.

If I try to decode the token throught jwt.io I get the following response:
```
{
  "name": "text@example.com",
  "admin": true,
  "exp": 1478820041
}
```

but whatever I try to write in the vue.js application the `this.$auth.user()` just return an empty object.

```
    {{ $auth.user() }}
    <b>Email:</b> {{ $auth.user().name }}
```

I've also tried to console.log it on the Account component created method like this:
```
    created () {
      console.log(this.$auth.user().name)
    },
```

Any ideas of what could be wrong?

**Comment by websanova** [comment]
The plugin works on the basis that the user data will be like so:

~~~
"data": {
    {
       "name": "text@example.com",
       "admin": true,
       "exp": 1478820041
     }
}
~~~

This can be overridden with `_parseUserData` function.

**Comment by websanova** [comment]
I've just updated docs about this:

https://github.com/websanova/vue-auth#user-data
