### ISSUE TITLE
How can I pass $auth.user() to component

### ISSUE THREAD

**Issue by KuzmenkoArtem** [websanova/vue-auth#461]
Hello!
I'm trying to do something like this
`<my-component :user="$auth.user()"></my-component>`

But in the component 'user' prop is always empty.

Thank you!

**Comment by skortabeast** [comment]
use $auth.user() in component without props,  return in  computed or set local var when component  mounted

**Comment by KuzmenkoArtem** [comment]
> use $auth.user() in component without props, return in computed or set local var when component mounted

Thanks for advice.
Yes, I understand that I can do that. I just wanted to make the component more reusable and be able to work not only with authored user but with the others too.

But you pushed me to another idea. Maybe I can put $auth.user() in computed and pass the results to props. But I'm not sure whether it will work

**Comment by skortabeast** [comment]
@KuzmenkoArtem  
give your code

**Comment by KuzmenkoArtem** [comment]
> @KuzmenkoArtem
> give your code

`<my-component :user="$auth.user()"></my-component>`

And component
`<template>
    <span>{{user.name}}</span>
</template>

<script>
    export default {
       props: ['user'];
       
    }
</script>`

It works if I put simple object to props like this
`<my-component :user="someUserObj"></my-component>`

**Comment by aligajani** [comment]
Why do you need to pass it? It is available globally using `this.$auth.user()` ..

**Comment by skortabeast** [comment]
@KuzmenkoArtem 
```
<template>
<span v-if="userAuthComputed">{{ user.name }}</span>
</template>

```
<script>
export default {
 props: { 
     userAuth: {
           type: Object,
          required: true,
          default: null
       }
}
compoted: {
    userAuthComputed() {
        return this.userAuth;
   }
}
</script>
```

in component 
`<my-component :user="someUserObj"></my-component>
`
but it's  question doesn't treat to websanova, websanova

**Comment by jongbonga** [comment]
my `$auth.user()` return `{}` after refresh

**Comment by websanova** [comment]
@jongbonga no need to pepper your issue all over the comments when it's not related.
