### ISSUE TITLE
Google Oauth2 redirect_uri_mismatch/redirect_uri

### ISSUE THREAD

**Issue by Sephen** [websanova/vue-auth#463]
I'm trying to get the google Oauth2 singin to work but I'm running into some problems.

Email/password login is working fine. so i added the following googleOauth2Data variables

```
googleOauth2Data: {
  url: 'https://accounts.google.com/o/oauth2/auth',
  params: {
    redirect_uri: function () {
      return this.options.getUrl() + '/login/google'
    },
    client_id: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    scope: 'email'
  }
},
googleData: {
  url: 'auth/google',
  method: 'POST',
  redirect: '/'
},
```

But whenever i run this method:

```
social (type) {
  if (this.$route.query.code) {
    this.$auth.oauth2({
      code: true,
      provider: type,
      params: {
        code: this.code
      },
      success: function(res) {
        console.log(res)
      },
      error: function (res) {
        console.log(res)
      },
      redirect: {path: '/'},
      })
  } else {
      this.$auth.oauth2({
        provider: type,
        rememberMe: true,
        params: {}
      })
  }
}
```

I get redirected to a 400/Error: redirect_uri_mismatch page of Google. When i remove the '/login/google' from the redirect_uri it sends me to the correct account page but after selecting a Google account it redirects back to the wrong url.

**Comment by vabreuvarela** [comment]
Having the same problem. any solution so far?

**Comment by websanova** [comment]
This has been updated, with version 3 release. Please check the [OAuth2 Guide](https://websanova.com/docs/vue-auth/guides/oauth2) for more details.
