### ISSUE TITLE
Is any purpose of path depended rememberMe cookie for localhost?

### ISSUE THREAD

**Issue by tpoxa** [websanova/vue-auth#469]
Hello. Thank you for great auth lib!

But this behavior doesn't make my life easier. What it's for?
```
if (domain !== 'localhost') {
            cookie += ' Path=/; Domain=' + domain + ';';
        }
```
Can we just set cookie for **/** even on localhost?

**Comment by websanova** [comment]
This has been updated in version 3.

Please check:

https://websanova.com/docs/vue-auth/guides/cookies
https://websanova.com/docs/vue-auth/recipes/remember-me-vs-stay-signed-in
