### ISSUE TITLE
Credentials visible in POST request

### ISSUE THREAD

**Issue by patsa** [websanova/vue-auth#471]
I implemented vue-auth in a vue frontend combined with jwt-auth in the laravel backend.
When I use the login function, which is configured to use POST, the credentials are concatenated to the post url in plain text. 
Is that supposed to be like that or am I doing something wrong?

**Comment by rusenask** [comment]
ensure that you are using HTTPS, then it's fine. If you are not using HTTPS then there's no point in authentication :)

**Comment by vovawed** [comment]
Change `parameters` to `body` or `data`  if you're using axios.
