### ISSUE TITLE
Does vue-auth store refresh token?

### ISSUE THREAD

**Issue by vovawed** [websanova/vue-auth#474]
My backend API returns 2 tokens: access and refresh. How can I get refresh token?

**Comment by akeebismail** [comment]
> My backend API returns 2 tokens: access and refresh. How can I get refresh token?

the same way you get the access token
`response: function(res) {
            let token = this.options.http._httpData(res).refresh;
            if (token) {
                return token;
            }
            console.log(res);
            return res.data.refresh;
        }`

**Comment by zorn-v** [comment]
You can do it like me https://github.com/websanova/vue-auth/issues/489
