### ISSUE TITLE
Authenticated but still access to login page

### ISSUE THREAD

**Issue by nhoxbin** [websanova/vue-auth#478]
Hello, i'm from Vietnam and i have some questions. sorry if i write english not good :-)

i'm install your package to use laravel-jwt and vue-auth from client, everythings is OK but when i change url to login page, it's still access, i don't know why it not redirect to dashboard as i expected... it still fetch the user and access to the login page

My config
`const AUTH_CONFIG = {

	auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
	http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
	router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
	tokenDefaultName: 'AuthToken',
	tokenStore: ['localStorage'],
	rolesVar: 'role_id',
	rememberMe: true,
	authRedirect: {
		path: '/session/login'
	}
        .......
`}

anyone help me solve this problem??
Tks everyone!

**Comment by bisserof** [comment]
add `meta: { auth: false }` property in router config:

```
{
    path: '/session/login',
    meta: { auth: false },
    name: 'login',
    component: LoginView
}
```

https://github.com/websanova/vue-auth/blob/master/docs/Privileges.md#routing

**Comment by nhoxbin** [comment]
> property in router config

thanks you... my bad... i didn't read the docs clearly
