### ISSUE TITLE
By default, where does vue-auth expect to find a token from a server's login response?

### ISSUE THREAD

**Issue by k00k** [websanova/vue-auth#48]
It isn't clear to me as to how my server should respond with a token (jwt in my case) to my vue app at login. Is it supposed to supply the token in the response body, or a response header? If the body, in what property? If a header, what should that header look like?

One of these?
`Authorization: Bearer myTokenContents`

`Authorization: myTokenContents`

**Comment by websanova** [comment]
Yes, that is default:

`Authorization: Bearer myTokenContents`

**Comment by k00k** [comment]
Ok, cool, thanks. Might be worth adding to the README

**Comment by k00k** [comment]
A follow-up question to this:

Should the automatic request of `GET /auth/user` provide the Authorization header with Bearer token automatically to that endpoint? I'm not seeing that header presented to the server. Wondering if I missed something in configuring.

I've tried the 2 following ways and don't see an Authorization header with a bearer token being presented to my API server with either config.

```
import Auth from '@websanova/vue-auth'
Vue.use(Auth, {
  router: router,
  http: Vue.http
})
```

and

```
import Auth from '@websanova/vue-auth'
Vue.use(Auth, {
  router: router,
  http: Vue.http,
  fetchData: { url: 'auth/user', method: 'GET', authType: 'bearer' }
})
```

**Comment by dobromir-hristov** [comment]
It should provide the token, because without it, the server would return an Unauthorized response status.

**Comment by websanova** [comment]
What version of the plugin are you using?

Also `authType` should not be in `user Data`. Actually should not need to
set it at all since bearer is the default. Where did you get that from?

On Nov 18, 2016 04:54, "Dobromir Hristov" <notifications@github.com> wrote:

It should provide the token, because without it, the server would return an
Unauthorized response status.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/48#issuecomment-261366413>,
or mute the thread

**Comment by k00k** [comment]
I'm using 1.5.1-beta, tried 1.5.0-beta as well.

Right, I didn't think I needed to set `authType` as bearer is the default, I've since removed it. I was just trying a few different things to get it going. In any case, it's not presenting the Authorization bearer header to my server for the `GET /auth/user` request. Any ideas why that might not occur? 

Here are the only headers in the request to `GET /auth/user`:

```
{ host: 'local.xyz.com',
  connection: 'keep-alive',
  accept: 'application/json, text/plain, */*',
  origin: 'http://local.xyz.com:8080',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
  referer: 'http://local.xyz.com:8080/login',
  'accept-encoding': 'gzip, deflate, sdch, br',
  'accept-language': 'en-US,en;q=0.8' }
```

**Comment by dobromir-hristov** [comment]
Is the token getting saved in your local storage?
If your server is not returning the token in the format the plugin expects it to, it might not be able to save it.

**Comment by k00k** [comment]
@dobromir-hristov Thanks for that pointer. All I see in local storage is `id_token:undefined`. So I guess that's likely what's occurring?

I can see in the login response that the authorization header is there though, I guess it's just not making it to storage. 

`authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Mzc1MTE1ZjAwMjBhN2ZmY2MwMDAwMDIiLCJpYXQiOjE0Nzk0Nzc0NjQsImV4cCI6MTQ4MDY4NzA2NH0.rMmQ5cLdLCpwcy617SHjMRvDv9bDMDb7jdyNioZGkPU`

**Comment by k00k** [comment]
I should note that I've tested this directly with the server via Postman and everything works perfectly. `/auth/login` responds with the header, and `/auth/user` accepts the header and responds with details about the user.

So it's definitely something in my vue app and not server-side.

**Comment by dobromir-hristov** [comment]
Are you doing a CORS request? When doing a CORS AJAX you have to supply additional headers.

**Comment by k00k** [comment]
@dobromir-hristov Yes, CORS. Can you elaborate on the additional headers?

**Comment by k00k** [comment]
I do have CORS stuff setup in my app, here's the snippet from my Glue manifest:

```
      routes: {
        cors: {
          origin: ['*'],
          headers: ['Origin', 'Accept', 'Authorization', 'Content-Type', 'If-None-Match', 'Accept-language'],
          additionalHeaders: ['cache-control', 'x-requested-with']
        }
      },
```

**Comment by dobromir-hristov** [comment]
I use laravel, but these are mine:
```php
 return $next($request)
            ->header('Access-Control-Allow-Origin', '*')
            ->header('Access-Control-Allow-Headers', 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With')
            ->header('Access-Control-Expose-Headers', 'Authorization')
            ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
```

**Comment by k00k** [comment]
@dobromir-hristov Thanks, I added the Access-Control-Expose-Headers of Authorization like you had as well.

I tried it with a curl CORS simulation and it worked fine and I also just tried it with a simple html/jquery page on the same origin (url), and it works. So I know my server-side CORS is working ok. I'm really stumped.

**Comment by k00k** [comment]
@websanova I think I found the problem! Even though I am setting my header on my server to use an uppercase **A** in **A**uthorization, when it comes through to Chrome/Vue and eventually to the `_getHeaders` function in the form of [`res.headers.map`](https://github.com/websanova/vue-auth/blob/master/src/drivers/vue.1.0.0.js#L28), for whatever reason it's been changed to lowercase: `authorization`. So when you try to [access it on this line via **.Authorization**](https://github.com/websanova/vue-auth/blob/master/src/auth.js#L408), it can't find it. I proved it by changing that line to: `var token = this.options._getHeaders.call(this, res).Authorization || this.options._getHeaders.call(this, res).authorization` and it works.

As HTTP headers are case-insensitive, seems this needs to be fixed. Probably also makes sense to allow for 'bearer' or 'Bearer' when you do: `token = token.split('Bearer ')`

**Comment by websanova** [comment]
Hmm, that's a bit strange. Where in your Laravel code are you actually
setting the header. The CORS part is just for what headers are available.

I see from the sample you provided below its lowercase. So perhaps your
server is sending it this way.

"authorization:Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Mzc1MTE1ZjAwMjBhN2ZmY2MwMDAwMDIiLCJpYXQiOjE0Nzk0Nzc0NjQsImV4cCI6MTQ4MDY4NzA2NH0.rMmQ5cLdLCpwcy617SHjMRvDv9bDMDb7jdyNioZGkPU"

As far as adding an support for upper/lower (and many other schemes people
have been asking for). The bearer method is quite standardized as
Authorization and Bearer. The plugin allows you to very easily add custom
authentication patterns. It's in the docs.

On Nov 19, 2016 22:28, "Steve Babigian" <notifications@github.com> wrote:

@websanova <https://github.com/websanova> I think I found the problem! Even
though I am setting my header on my server to use an uppercase *A* in
*A*uthorization,
when it comes through to Chrome/Vue and eventually to the _getHeaders
function in the form of res.headers.map
<https://github.com/websanova/vue-auth/blob/master/src/drivers/vue.1.0.0.js#L28>,
for whatever reason it's been changed to lowercase: authorization. So when
you try to access it on this line via *.Authorization*
<https://github.com/websanova/vue-auth/blob/master/src/auth.js#L408>, it
can't find it. I proved it by changing that line to: var token =
this.options._getHeaders.call(this, res).Authorization ||
this.options._getHeaders.call(this, res).authorization and it works.

As HTTP headers are case-insensitive, seems this needs to be fixed.
Probably also makes sense to allow for 'bearer' or 'Bearer' when you do: token
= token.split('Bearer ')

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/48#issuecomment-261716905>,
or mute the thread

**Comment by k00k** [comment]
I'm not using Laravel, I'm using Hapi.js (node.js) for my API. I've learned that node's http module (which Hapi uses) automatically lowercases all outbound headers. So that's what's causing this. Obviously up to you whether or not you want to handle that on the consumption side of things.

I think Node's official take is that as the HTTP spec is that headers should be case-INsensitive, the least offensive thing for consistency is lowercase. Not sure I agree when most people capitalize, but it is what it is. 

[Here's some discussion on node's lowercasing of the headers](https://github.com/nodejs/node-v0.x-archive/issues/1954)

**Comment by websanova** [comment]
ok, fair enough. I'll add it in next week, I'm on holiday at the moment :p
You can add a custom driver for now.

Also now I'm thinking bearer also might as well support upper/lower and
with and without the colon as well.

**Comment by k00k** [comment]
That colon was just from copying/pasting from Chrome's inspector, it wasn't really part of the header.

If you didn't want to have to hard code the cases in the driver, one way to handle it might be as a user definable option with obvious defaults, something like:

```
{
  headerName: "Authorization",
  headerSeparator: " ",
  headerValuePrefix: "Bearer"
}
```

Not sure that's much easier than just doing the custom driver, and might be overkill.

**Comment by websanova** [comment]
Actually had that before, but it doesn't address the variety of cases that
were coming up. So I just did the custom request/response which allows
pretty much anything you want to do.

**Comment by k00k** [comment]
Yeah, I think the custom req/res is a much better overall solution, and could understand if you wanted to just leave it at that with some notes in the docs to watch out for case-sensitivity. However, the case-insensitivity is probably a worthwhile addition as Vue seems to be gaining decent traction and this project should do as well. No doubt others using node for their APIs will run into the same problem I did.

As a side note, I would have greatly benefited from a couple lines in the README outlining what actually happens from a flow perspective with vue-auth. Something outlining the default flow: that you make an initial login request, then automatically a GET to /auth/user happens with the Bearer token that was received on successful login, then a redirect. If you'd like some help with that, I'd be happy to.

**Comment by websanova** [comment]
Yes, you're not the first one to ask. I will add some docs for that next
week. :-)

**Comment by websanova** [comment]
Ok, I've added this in. Also note that this is in the new 2.x stream. Make sure you get the latest as I'm making a lot of updates today. Also note the new driver centric model. Please check docs and change log for more info.

**Comment by websanova** [comment]
Ok, I guess this is good now. closing off, thx for help :-)

**Comment by Imboga** [comment]
> @websanova I think I found the problem! Even though I am setting my header on my server to use an uppercase **A** in **A**uthorization, when it comes through to Chrome/Vue and eventually to the `_getHeaders` function in the form of [`res.headers.map`](https://github.com/websanova/vue-auth/blob/master/src/drivers/vue.1.0.0.js#L28), for whatever reason it's been changed to lowercase: `authorization`. So when you try to [access it on this line via **.Authorization**](https://github.com/websanova/vue-auth/blob/master/src/auth.js#L408), it can't find it. I proved it by changing that line to: `var token = this.options._getHeaders.call(this, res).Authorization || this.options._getHeaders.call(this, res).authorization` and it works.
> 
> As HTTP headers are case-insensitive, seems this needs to be fixed. Probably also makes sense to allow for 'bearer' or 'Bearer' when you do: `token = token.split('Bearer ')`

Thanks a LOT!!!! Many hours struggling whit this until I saw your comment. You've made my day!
