### ISSUE TITLE
Make rememberMe path an option

### ISSUE THREAD

**Issue by LukasCornille** [websanova/vue-auth#481]
My authentication routes are nested (/authentication/login and /authentication/register). If I use the rememberMe option it sets it for path /authentication, however the rest of my site is located from "/". Is there a way for me to choose the path? (even when setting it to false it creates a cookie false so creating my own doesn't help).

I see as in #469 this is only disabled for localhost but that greatly hinders my development.

**Comment by websanova** [comment]
This has been updated in version 3. Please check [rememberKey Option](https://websanova.com/docs/vue-auth/options/examples/#rememberkey) for more details.
