### ISSUE TITLE
Error when edit request driver

### ISSUE THREAD

**Issue by morfair** [websanova/vue-auth#482]
On this page https://github.com/websanova/vue-auth/blob/master/docs/Authentication.md in section "Example 2: Token with multiple parts" is written:

token = token.split(';');

When I add this line in default request: (), I get error:

Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by alex-eri** [comment]
Works with:
```

├── @babel/polyfill@7.2.5
├── @vue/cli-plugin-babel@3.2.2
├── @vue/cli-plugin-eslint@3.2.2
├── @vue/cli-service@3.2.3
├── @websanova/vue-auth@2.21.14-beta
├── axios@0.18.0
├── chart.js@2.7.3
├── js-beautify@1.8.9
├── material-design-icons-iconfont@4.0.3
├── style-resources-loader@1.2.1
├── stylus@0.54.5
├── stylus-loader@3.0.2
├── vue@2.5.21
├── vue-axios@2.1.4
├── vue-chartjs@3.4.0
├── vue-cli-plugin-axios@0.0.4
├── vue-cli-plugin-style-resources-loader@0.1.3
├── vue-cli-plugin-vuetify@0.2.1
├── vue-router@3.0.2
├── vue-template-compiler@2.5.21
├── vuetify@1.4.0
└── vuetify-loader@1.1.0

```

**Comment by websanova** [comment]
@morfair bit late, but version 3 released with much more stable demo and code.

https://websanova.com/docs/vue-auth
