### ISSUE TITLE
custom token to allow guest access to specific route

### ISSUE THREAD

**Issue by justijndepover** [websanova/vue-auth#484]
Hi

First of all great plugin!
I'm building a SPA with the vue-auth plugin to manage all my routes / permissions.

What i would like to achieve is a page that is accessible to anyone if they have the correct url, if not you should be authenticated.
for example: `/project/1` is a protected route inside my routes file
```
routes: [
    {
        path: '/project/:id',
        component: ProjectComponent,
        meta: {
            auth: true
        }
    },
]
```

but `/project/1?token=2ZYEetUkBHxexMUxNAwWC0cdhP7N3DCU` should be accessible to anyone that has the link and where the token is not expired (database check).

How can i achieve this?

**Comment by aligajani** [comment]
Then make the project auth:false and do API checks on token itself.
