### ISSUE TITLE
Method to change rememberMe

### ISSUE THREAD

**Issue by Mapteg34** [websanova/vue-auth#485]
Now we haven't method to change rememberMe.
But we need it in some cases:
If we use manual token set: auth lost after refresh.

Can you add method to manual change rememberMe?

Example:
```
    Auth.prototype.setRememberMe = function (val) {
        __cookie.remember.call(this, val ? true : false);
    };
```

**Comment by websanova** [comment]
This has been added in version 3 and now supports "stay signed in" and "remember" please check docs for more details.

https://websanova.com/docs/vue-auth
