### ISSUE TITLE
refresh+fetch

### ISSUE THREAD

**Issue by matro-skin** [websanova/vue-auth#486]
Is it possible to always `fetch` user when `refresh` fired?

**Comment by zorn-v** [comment]
Why you need this ? On refresh, auth token also should be refreshed (and pass via auth.response function)

**Comment by websanova** [comment]
For things like that the refresh is on a timer, so just write another timer if it's really necessary.

```
setTimeout(() => {
    this.$auth.fetch();
}, 1000 * 60 * 30);
```
