### ISSUE TITLE
setCookie path is set to current path in localhost

### ISSUE THREAD

**Issue by tonila** [websanova/vue-auth#487]
I'm implemeting oauth in backend and backend redirects to vue-application with token in url. 
`localhost/oauth/callback`

There was not way to set rememberMe=true, when setting token, so best I could came up with was:

```
Cookie.remember.call(this.$auth, true);
this.$auth.token(null, token);
```

But this did not work in localhost, since cookie path was set to '/oauth/callback'. I found out that it is because cookie.js ->

https://github.com/websanova/vue-auth/blob/master/src/lib/cookie.js#L9

I suppose "Expires" is left out to create session cookie, but should "Path" part be set in localhost?

**Comment by websanova** [comment]
This has been updated in version 3 with support for a cookie option that can be set with whatever cookie parameters necessary.

Check the cookies guide for more details.

https://websanova.com/docs/vue-auth/guides/cookies
