### ISSUE TITLE
Persisting user data between refreshes

### ISSUE THREAD

**Issue by cenotaph** [websanova/vue-auth#488]
Hi,

There are quite a few issues about the $auth.user not being persisted after page refreshes, but no explanations on how to make this function work out of the box. Could this be explained better in the docs?

I am using a Rails backend with devise authentication, and auth.check() works fine after a login, but then on a hard page refresh, even when 'rememberMe' is true, it's lost. I would think this should persist as default behaviour when using rememberMe, but it seems that lots of manual setting of the user object and token has to be done at the start of the app?

**Comment by websanova** [comment]
It's in the docs `$auth.ready()`

otherwise you can show some examples of what you tried...
