### ISSUE TITLE
Refresh token delete on logout

### ISSUE THREAD

**Issue by zorn-v** [websanova/vue-auth#489]
Currently I use config like this
```js
  auth: {
    request: function (req, token) {
      if (req.url === this.options.refreshData.url) {
        req.data = {refresh_token: this.token(this.options.refreshTokenName)}
      }
      this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    },
    response: function (res) {
      const resData = res.data || {}
      this.token(this.options.refreshTokenName, resData.refresh_token);
      return resData.token
    }
  },
  refreshTokenName: 'refresh_token',
  refreshData: {url: '/auth/refresh', method: 'POST', interval: 25},
  logoutData: {success: function () {this.token(this.options.refreshTokenName, 'INVALID')}}
```
It's fine, but I don't want to leave garbage after me )

Maybe some new method like `deleteToken` or new "standard" option `refreshTokenName` and remove it automatically on logout as impersonate token ?

**Comment by websanova** [comment]
Well logout will delete everything already.

**Comment by zorn-v** [comment]
You did not notice that I use additional token - "refresh_token", and I set it to "INVALID" on logout. It will be better to delete it, but there is not (or was not) public method for this.

**Comment by websanova** [comment]
I would just unset it on logout and have logout method in vuex.

```
Vue.auth
    .logout()
    .then(() => {
        Vue.auth.token(Vue.auth.options.refreshTokenName, null);
    });
```

**Comment by zorn-v** [comment]
This will not work because `null`, and `token` method will work just as getter. That's why I set it to "INVALID"
https://github.com/websanova/vue-auth/blob/810469e7a15c8515424263f7974b118d96848259/src/auth.js#L504-L512

**Comment by websanova** [comment]
ah damn, ok see what you mean. Was plowing through the tickets a bit too fast.

I've updated this in the latest to accept any value other than `undefined` now to pass through. so this will apply to `user()` and `token()` method calls.

Also in the case of `token()` if a `null` value is set it will do a `remove` instead of a `set`. Hopefully nobody needs a null value there.

latest at `3.1.2-beta`
