### ISSUE TITLE
token refresh

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#49]
Just was wondering what does the API look like for token refresh.  Lets say if you refresh the browser page a new token will be produced.  This needs to be secure as well.

**Comment by websanova** [comment]
The API? Well that's pretty broad question and many different
implementations for back end.

**Comment by kyoukhana** [comment]
Was wondering if you had a sample of your API for a token refresh.

**Comment by websanova** [comment]
Yes, check the docs. There is link to a sample server in my GH account ;)
