### ISSUE TITLE
is there any way to mock this connection, to speed up local testing?

### ISSUE THREAD

**Issue by vesper8** [websanova/vue-auth#490]
I use this library to authenticate my vue pwa, but lately I've been writing a lot of tests using Cypress and they all require me to be authenticated, I've somewhat mocked the login so I don't have to fill out a form every time, but I still have to do a bit of back and forth with the server to obtain the jwt token and get the logged-in state, and I was wondering if I can speed this up faster by storing a logged-in state and starting fresh from this at the beginning of every test instead of having to authenticate every time which adds a few precious seconds to each of my dozens of tests

**Comment by websanova** [comment]
Well you can set a token manually, quite a lot of options for that actaully.

Please check options and methods for more details.

https://websanova.com/docs/vue-auth/methods
https://websanova.com/docs/vue-auth/options

**Comment by aislanmaia** [comment]
I have the same problem. 
And with my actual config with Vue and vue-auth, I dont know how the correct way to export that config to use inside my cypress spec file, so that I will able to use the method `token()` to set manually my auth.

Please helpe me!

**Comment by websanova** [comment]
Maybe just override the token method?

Vue.auth token = ...
