### ISSUE TITLE
How to set other login url ? 

### ISSUE THREAD

**Issue by Aarbel** [websanova/vue-auth#491]
vue-auth seems to send post request to `auth/login` routes.

I'm building a magic link feature, so need to provide an other route for login, like 
`/magic/login`, this route returns the user JWT.
Do you have any idea how can i manage that ? 

Thanks a lot for your help ! 

My code for the moment : 
```JS
this.$http.post('auth/magic/login', { 
          email: this.email,
          loginToken: this.login_token,
        }).then(function (response) {
          console.log('MAGIC LOGIN RESPONSE :', response)
          this.redirectRoute();
        }, function (error) {
          this.error = true;
          console.log('MAGIC LOGIN ERROR :', error)
        })
```

**Comment by TheGlenn88** [comment]
Try something like `  methods: {
    login() {
      this.$auth.login({
        params: {
          email: this.email,
          password: this.password,
        },
        success() {
          console.log('success');
        },
        error() {
          console.log('fail');
        },
        url: '/auth/magic/login',
        rememberMe: true,
      });
    },
  },`

**Comment by Aarbel** [comment]
works perfectly, thanks a lot !
