### ISSUE TITLE
Token not refreshing

### ISSUE THREAD

**Issue by Jakuboslav** [websanova/vue-auth#497]
Hello,
I can not find solution to make authentification token refresh. I red documentation, but I couldn’t find info that would help me. I have got VueAuth options specified like this:

```
Vue.use(VueAuth, {
  tokenStore: "localStorage",
  loginData: {
    url: configuration.baseURL + "/staff/login",
    method: "POST",
    redirect: "/",
    fetchUser: false
  },
  authRedirect: "/login",
  authMeta: "auth",
  rolesVar: "roles",
  tokenDefaultName: "vue_auth_token",
  userDefaultName: "vue_auth_user",
  headerTokenReplace: "{auth_token}",
  tokenType: "",
  refreshData: {
    url: configuration.baseURL + "/staff/login/renew",
    method: "GET",
    interval: 55
  },
  logoutData: {
    redirect: "/login"
  }
});
```

I tried any interval, but `/staff/login/renew` is not triggered. Am I missing something?

Thanks in advance.

**Comment by eyaylagul** [comment]
+1

**Comment by rbrouwer** [comment]
Can you try with: 
```
  refreshData: {
    url: configuration.baseURL + "/staff/login/renew",
    method: "GET",
    enabled: true,
    interval: 55
  },
```
So adding enabled: true to refreshData?

**Comment by websanova** [comment]
@Jakuboslav sorry for late reply, but yes, it's as @rbrouwer states, the `refreshData` has been overridden which set `enabled` to `undefined` hence false.

Also note the plugin has been updated to version 3 with a lot of changes and big improvement in docs.

https://websanova.com/docs/vue-auth/home
