### ISSUE TITLE
Modify 'Bearer:' lexem

### ISSUE THREAD

**Issue by dubov94** [websanova/vue-auth#5]
Could you add an option that would allow to customize the 'Bearer:' part in authorization headers?

For example [express-jwt](https://www.npmjs.com/package/express-jwt) expects it to be 'Bearer' (without  a colon).

**Comment by websanova** [comment]
Will add an option for this soon.

**Comment by websanova** [comment]
This is resolved in `v1.0.4-dev`.

By default it is now passed without the "colon". Also the `bearerAuth.request` and `bearerAuth.response` functions can be overridden for any other customization.
