### ISSUE TITLE
Is it possible to get token from response data?

### ISSUE THREAD

**Issue by zetdotpi** [websanova/vue-auth#50]
Is there some kind of settings I should pass, when I instantiate Auth? Or should I override some method to get token from reponse data?

Response body looks like this:
`{ token: 'TOKEN_BODY' }`
and of course header `Content-Type:'application/json'` is present.

**Comment by websanova** [comment]
Yes, this question had been asked a lot. Please check the docs for adding a
custom driver. There is exact example for your situation.
