### ISSUE TITLE
Not working login facebook. hepl me!

### ISSUE THREAD

**Issue by genkifsoft** [websanova/vue-auth#501]
Hi Everyone!
I problem about login facebook. I read all document of vue-auth. But working with it not success.
Error: ID invalid

`loginFacebook() {
            if (this.$route.query.code) {
            this.$auth.oauth2({
                code: true,
                provider: 'facebook',
                params: {
                    code:this.$route.query.code
                },
                success: function(res) {},
                error: function (err) {},
                redirect: {path: '/account'},
            });
        }
        else {
            this.$auth.oauth2({
                provider: 'facebook'
            });
        }
    }`
**Route api**
`Route::get('/auth/redirect/{social}', 'SocialAuthController@redirect');
Route::get('/auth/callback/{social}', 'SocialAuthController@callback');`
Nice to meet you. Thanks

**Comment by websanova** [comment]
Please note this has been updated and (hopefully) simplified in version 3.

Please check the following guides:

https://websanova.com/docs/vue-auth/upgrades/2x-3x
https://websanova.com/docs/vue-auth/guides/oauth2
