### ISSUE TITLE
NavigationDuplicated

### ISSUE THREAD

**Issue by mhluska** [websanova/vue-auth#503]
When I try to log in with an incorrect password, the library redirects me to the login page. Except I'm already on the login page so modern verions of Vue throw a "NavigationDuplicated" error. Could this library avoid navigating to login if already on the login route?

Here's part of the NavigationDuplicated stack trace:

```
eval | @ | vue-router.esm.js?8c4f:2051
-- | -- | --
  | abort | @ | vue-router.esm.js?8c4f:2082
  | confirmTransition | @ | vue-router.esm.js?8c4f:2090
  | transitionTo | @ | vue-router.esm.js?8c4f:2034
  | push | @ | vue-router.esm.js?8c4f:2365
  | eval | @ | vue-router.esm.js?8c4f:2779
  | push | @ | vue-router.esm.js?8c4f:2778
  | _routerGo | @ | vue-router.2.x.js?4ae6:60
  | _logoutProcess | @ | auth.js?771d:372
  | _processInvalidToken | @ | auth.js?771d:262
  | _responseIntercept | @ | auth.js?771d:160
```

You can see that it tries to logout because of missing auth tokens. Then logout tries to go back to the login route because of our logout redirect config.

Would it make sense for this library to not logout on missing auth tokens when the request is a 401 for login?

**Comment by mhluska** [comment]
I wish this library was not abandoned 😂

**Comment by armelus** [comment]
To solve the problem,
Just override the file `@websanova/vue-auth/drivers/router/vue-router.2.x.js` by your own file that you'll create `(Exemple: vue-router.js)` and import it.  

Into your created file, override the function `_routerGo` by this code:
 ``` javascript
_routerGo: function (data) {
    var router = this.options.Vue.router;

    (router.push || router.go).call(router, data).catch((err) => {});
  }
```

**Comment by mhluska** [comment]
@armelus I don't want to silence the error though. I want to ideally patch the library to not cause navigation to the current route.

**Comment by websanova** [comment]
hey all, sorry, not abandoned yet, just super busy this year with work. Unfortunately open source doesn't pay :-P

I'm planning to rewrite a v3, probably over the holidays. So many patches with this one already. And want to get proper promises and cleaner code in.

**Comment by fussraider** [comment]
I will Supplement @armelus answer:

Create file `vue-auth-router-fix.js` (or your some custom name) and paste:

```js
const vue_router_driver = require('@websanova/vue-auth/drivers/router/vue-router.2.x.js');
vue_router_driver._routerGo =  function (data) {
    let router = this.options.Vue.router;
    (router.push || router.go).call(router, data).catch((err) => {});
}

module.exports = vue_router_driver;
```

And in your `app.js` find:
```js
Vue.use(VueAuth, {
// ... 
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
// ...
})
```

replace it with:

```js
Vue.use(VueAuth, {
// ... 
    router: require('./vue-auth-router-fix'),
// ...
})
```

**Comment by tpoxa** [comment]
I have same error during logout

**Comment by websanova** [comment]
Hey all, fyi, huge update with the library in version 3.

The NavigationDuplicated I've seen also. The issue in relation with the library is that there are default `redirect` values for login, register, etc. So if the app is doing some custom stuff outside the lib that `redirect` should be set to `null`.

I've also added some notes on that to the docs.

https://websanova.com/docs/vue-auth/recipes/duplicate-navigation-error
