### ISSUE TITLE
Refresh will always fire on boot.

### ISSUE THREAD

**Issue by rbrouwer** [websanova/vue-auth#505]
According to the [Methods page](https://github.com/websanova/vue-auth/blob/master/docs/Methods.md)

> The refresh will always fire on boot, to disable this override the tokenExpired option method.

However tokenExpired does not seem to effect the refresh on boot, but only the refresh called on interval. How can I prevent the refreshing during boot?

**Comment by websanova** [comment]
This is fixed in version 3, so setting `refreshData.enabled` to `false` has expected behavior now.

Please check the upgrade guide for more details.

https://websanova.com/docs/vue-auth/upgrades/2x-3x
