### ISSUE TITLE
Authorization header not found

### ISSUE THREAD

**Issue by alxetd** [websanova/vue-auth#510]
Hello,

I'm trying to implement an authentification for a vuejs frontend with a laravel aplication. I followed the steps for using this package but I still have an issue.
From the backend I get this:
![image](https://user-images.githubusercontent.com/33486449/70623217-4a5a7a80-1c26-11ea-8a53-1a43b0da2902.png)
![image](https://user-images.githubusercontent.com/33486449/70623255-63632b80-1c26-11ea-8164-284c13240a1b.png)
When testing with postman it seems ok.

My code for the login is this:
![image](https://user-images.githubusercontent.com/33486449/70623532-061baa00-1c27-11ea-8978-7fb170afd3ab.png)
I added some logs here:
![image](https://user-images.githubusercontent.com/33486449/70623731-64e12380-1c27-11ea-9dee-3cf19787eef3.png)
But here there is no Authorization header.
![image](https://user-images.githubusercontent.com/33486449/70624059-154f2780-1c28-11ea-8189-da486b552104.png)
Although in the network tab I see it:
![image](https://user-images.githubusercontent.com/33486449/70624112-3f084e80-1c28-11ea-8f87-ff276538e135.png)

Maybe it is something I don't see. Any ideas?
Sorry if this is not the right place to ask.

Thanks,

**Comment by treeleaf** [comment]
I have a similar question, using Symfony backend with regular json login. Also no authentication header, although it is allowed by CORS

**Comment by kfelix** [comment]
@alxetd you need to add "Authorization" to the exposed_headers array in the Laravel file config/cors.php
