### ISSUE TITLE
Need to edit refresh function / expiration error

### ISSUE THREAD

**Issue by vlahde** [websanova/vue-auth#514]
Hi. I need to perform a bunch actions when token is expired. I tried looking the guide and issues but I did not manage to get the response I need. I need to do something like this:

> Vue.use(VueAuth, {
auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    error: function () {
        console.log('auth refresh expired')
    },
});

How can I achieve it?

**Comment by websanova** [comment]
well if you're looking for a global error handler on requests you should add a interceptor before the vue-auth pluign in axios.
