### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by emanuellimabr** [websanova/vue-auth#515]
Hi, I am new using VueJs and this library. I've been trying to handle errors when the token expires but no success. Where do I have put my code to handle errors? I have followed the tip on the StepByStepGuide but it is not working, I'm getting the error `Uncaught TypeError: Cannot read property 'interceptors' of undefined`. 

My app.js file is as follow:

`import VueAuth from '@websanova/vue-auth';`
`import auth from './api/auth';`

`Vue.http.interceptors.push(function(request, next) {
    next(function (res) {
        // Unauthorized Access
        
        if (
            res.status === 401 &&
            ['UnauthorizedAccess', 'InvalidToken'].indexOf(res.data.code) > -1
        ) {
            Vue.auth.logout({
                redirect: {name: 'auth-login'}
            });
        }
        
        // System Error

        else if (res.status === 500) {
            Vue.router.push({name: 'error-500'});
        }
    });});`

Any help?

**Comment by iomariani** [comment]
@emanuellimabr Were you able to find out what was the issue? I'm having the same error...

It's as if the instance of axios/http was not found in Vue, even thought it has been loaded prior to this plugin...

**Comment by birdman00** [comment]
![image](https://user-images.githubusercontent.com/63040114/80046561-8d661c00-853d-11ea-8af3-1dfb31185d7a.png)
Sample code to handle token expire. Hope it help

**Comment by websanova** [comment]
not sure, potentially some issue with axios, I normally use vue-resource.

But likely just something off with the http interceptors.

Otheriwse ya, something like the above screenshot should work. Or setting up a global interceptor should work as well. Just note that with a global interceptor order will matter, so if you wanna capture before vue-auth does to do your own thing, make sure you include that interceptor before vue-auth plugin.

**Comment by iomariani** [comment]
I've packed a new vue app with basically how I'm loading the plugin:
[vue-auth-test@github](https://github.com/iomariani/vue-auth-test)

If that's any help to debug this error...
I tried with axios and vue-resource and I get the same error on both, I'm new to Vue so I am not sure if I am doing something wrong loading them up either...

**Comment by websanova** [comment]
this is quiet likely an issue with your http plugin or perhaps driver. It's undefined...why don't you just try some `console.log` and try to find out where it's undefined and why.
