### ISSUE TITLE
Plugin not setting token on Chrome

### ISSUE THREAD

**Issue by GMolini** [websanova/vue-auth#517]
Ive been having this weird error (and only in production, development mode seems to work fine) in Chrome, where the plugin doesnt set the correct token. I use this code to perform the login, then automatically fetch and save the user.

    this.$auth.login({
        data: formData,
        fetchUser: true,
        success: (response) => {
        },
       error: () => {
        },
        redirect: {name: 'dashboard'}
    });

In development, and in production in some browsers it works, but it has stopped working (for unknown reasons) in chrome. Using the network tab, I can see that the login works, and it returns a token and client id, but the fetch requests doesnt use that new token, so it gets rejected by the backend.

Any ideas why this is happening?

**Comment by jseitel** [comment]
@GMolini I just started playing with the library, but ran into similar issues.  The default bearer driver attempts to parse the access token from the Authorization header.  Perhaps that header is being successfully sent to the client in your development environment but not production?

**Comment by GMolini** [comment]
But Im using devise.   
auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),

Its very weird, because it sends a token, but an incorrect one when doing the fetch. I dont know where does this token come from, since it uses it even after ive cleared the cache and cookies from the browser.

Even more weird is that, if I use an incognito window, it works!

**Comment by GMolini** [comment]
Closed the issue as I finally found what was causing it, and nothing to do with the plugin. It was another plugin i had that was interfering with the token.

**Comment by agoalofalife** [comment]
@GMolini  Hi, I met same problem, can you remember which plugin was?
