### ISSUE TITLE
Authorization header is not set with subdomain API url

### ISSUE THREAD

**Issue by dimitribocquet** [websanova/vue-auth#519]
Hello,

I have a Laravel Application, with 2 urls: one for my frontend (front.app.test), and another one for my API (api.app.test). When I'm trying to login with "api.app.test" and fetching the user, the Authorization header is never set. With "front.app.test", everything is working fine.

CORS are enabled :

```
public function handle($request, Closure $next)
    {
        $response = $next($request);

        $response->headers->set('Access-Control-Allow-Origin' , '*');
        $response->headers->set('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
        $response->headers->set('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Requested-With, Application, Access-Token, Uid, NGX-Cache, X-App-Version, X-CSRF-TOKEN');

        return $response;
    }
```

Why does it work with one and not the other?

Thank you !

**Comment by ishapkin** [comment]
Same problem!

**Comment by mauricoder** [comment]
Have you managed to fix it? I'm having the same problem.

Thanks!

**Comment by dimitribocquet** [comment]
@mauricoder Currently I use the same sub domain for both frontend and my API, because they are on the same project.
I am still in development, so it's okay like that. I think I will make a fork/PR and fix this issue when I will have to go in production, if it's not fixed at this moment.

**Comment by dimitribocquet** [comment]
Found my mistake, I have also to set **Access-Control-Expose-Headers: Authorization**.

See [FAQ: Backend section](https://github.com/websanova/vue-auth/blob/master/docs/Faq.md#backend)
