### ISSUE TITLE
Log user by token

### ISSUE THREAD

**Issue by lucavizzi** [websanova/vue-auth#522]
Hi websanova,
It would be possible to log-in a user avoiding "$auth.login()" function?

In my scenario I got an email address and I can safely retrieve a valid token from my back-end.

With this code:
```
this.$auth.token(null, res.data.token);
this.$auth.watch.loaded = true;
this.$auth.watch.authenticated = true;
this.$auth.user(res.data.user);
```
I already can log-in user but it doesn't work as a normal login. 
User can navigate through SPA pages but get disconnected on page refresh.

Any hint to get user logged permanently?
Thanks in advance

**Comment by mauricoder** [comment]
Hi,

I'm facing the same issue. Did you managed to fix it?

Thanks!

**Comment by mauricoder** [comment]
For future readers, this was the solution for me: https://github.com/websanova/vue-auth/issues/492
