### ISSUE TITLE
Devise Error

### ISSUE THREAD

**Issue by diegolinhares** [websanova/vue-auth#524]
I have this configuration on my main.js

import Vue from 'vue'
import App from './App.vue'
import router from './router'
import axios from 'axios';
import VueAxios from 'vue-axios';

Vue.use(VueAxios, axios)
Vue.axios.defaults.baseURL = 'http://localhost:3000'; // Rails Api

Vue.router=router

Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  loginData: {
    url: "/auth/sign_in",
    method: "POST",
    redirect: "/",
    fetchUser: true
  },
  logoutData: { redirect: "/" },
  refreshData: { url: '/auth/validate_token', method: 'GET', enabled: true },
  fetchData: { url: '/auth/validate_token', method: 'GET', enabled: true, interval: 30 }
})

new Vue({
  router,
  render: h => h(App),
}).$mount('#app')

Why, when I'm doing login, my I get an error 401 from validate_token?

post sign_in 200 ok
after
get validate_token 401

When i go sign in, works

**Comment by thelastinuit** [comment]
@diegolinhares which version of Devise are you using?

**Comment by diegolinhares** [comment]
> 
> 
> @diegolinhares which version of Devise are you using?

Hi, I solved it. I had to expose the fours headers from devise-token-auth gem in my Rails cors file. After I did that, it works normally. Thanks for your time.

**Comment by lucasfrdgs** [comment]
@websanova 
i am using latest version of vue-auth, 
is devise driver working?  I am using its reference but the Token-type is defined as 'Bearer'

**Comment by websanova** [comment]
@lucasfrdgs not really sure what you mean, but did you check the new docs?

https://websanova.com/docs/vue-auth/guides/drivers
