### ISSUE TITLE
Check if user has one role from array of roles in router.js

### ISSUE THREAD

**Issue by hadalaba** [websanova/vue-auth#526]
I wanted to check, if user has role by at least one coincidence in assigned array of strings.

So, I have a User model with field, where we can know a user's role:

```   
{
    ... ,    
    role_code: 'admin', // can be 'moderator' or other role
    ...
}
```

I did assign rolesVar in auth.js by:

`rolesVar: 'role_code'`

In vue components the checking is working fine, however in router.js it doesn't. There's my router.js:
```  
...
{ 
    path: "/admin",
    component: AdminComponent,
    meta: {
        auth: {
            role_code: ["admin", "moderator"],
            redirect: { name: "login" },
            forbiddenRedirect: { path: "/403" }
        }
    },
    children: [ ... ]
},
...
```

Also i tried to replace 'role_code' code property to 'roles' (like in docs >.>) and it didn't work.

**Comment by websanova** [comment]
The `rolesVar` is just the var to use on the user object. This doesn't change in the auth meta and shold remain as "roles" there in your example.
