### ISSUE TITLE
$auth.login succeeds, but user is not logged in?

### ISSUE THREAD

**Issue by paddelboot** [websanova/vue-auth#529]
My `login` component:

            methods: {
            login() {
                const app = this;

                this.$auth.login( {
                    params: {
                        email: app.email,
                        password: app.password
                    },
                    success: function () {
                        console.log( 'Logged in' );
                    },
                    error: function () {
                        console.log( 'Could not log in' );
                    },
                    rememberMe: true,
                    redirect: '/dashboard',
                    fetchUser: true,
                } );
            },
        }

This works as expected, also throws the error when wrong credentials are being used. But `$auth.check()` always returns `false`.

The redirect to `/dashboard` never triggers, because this page requires authentication.

    const routes = [
    {
        path: '/',
        name: 'home',
        component: Login
    },
    {
        path: '/register',
        name: 'register',
        component: Register,
        meta: {
            auth: false
        }
    },
    {
        path: '/login',
        name: 'login',
        component: Login,
        meta: {
            auth: false
        }
    },
    {
        path: '/dashboard',
        name: 'dashboard',
        component: Dashboard,
        meta: {
            auth: true
        }
    },
    {
        path: '*',
        component: PageNotFound
    },
    ];

I also checked my api endpoints with Postman and they all seem to work fine. 

Not sure where to start looking? Thanks.

**Comment by paddelboot** [comment]
Problem was that I didn't add the proper `Authorization` header in my response.

**Comment by lawrence615** [comment]
@paddelboot kindly share what you changed on the Authorization header response to fix the issue. Thanks.
