### ISSUE TITLE
Seperate user login from admin

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#53]
So I am just wondering lets say if you have a login called /admin/login.  How can we define a different login like /users/login.  Because lets say if you have admin rights you want to redirect to a dashboard.  If you have normal user rights you get redirected to a totally different path.  Does loginOther and logoutOther take care of this?

**Comment by websanova** [comment]
Well, not sure about details of your project but it seems a bit overkill
for a small app to have separate api logins.

Probably best to funnel everything into one login point like
`api/v1/auth/login` or something like that. If you want to have different
interfaces for user and admin login, that's nothing to do with the plugin
and just a design thing which is fine. The api should probably return some
kind of "role" identifier in the front end which you could then redirect
accordingly in the `success` function`. But at that point there are many
ways to handle it.

**Comment by kyoukhana** [comment]
Thanks for the help and insight.  What I want to do is this

What I  have my /admin/login working perfectly

What I want to do is have a 
/users/login 

Different design then the admin.  When the user logs in it will have different redirects then the admin.    Just puzzled on how to do this.

**Comment by websanova** [comment]
Are these paths from api or front end? can you be a bit more specific....

**Comment by kyoukhana** [comment]
These paths are all in front end not back end at all.  Using vue-router 1.x

**Comment by websanova** [comment]
ok, so if it's front end, then not sure what it has to do with the
vue-auth. You just need to redirect to whatever you want on success.
`$auth.login({success: function() {}.....})` etc..

**Comment by kyoukhana** [comment]
Ah so but the confusion is in here the vue-auth options.  The LoginData and the LogoutData.  Should I leave that blank?  Or does the $auth.login({success: function() {}.....}) I can take care of this in there. 
```
var options = {
    token: [{request: 'token', response: 'token', authType: 'bearer', foundIn: 'header'}],
    tokenName:'token',
    loginData: {url: 'api/auth', method: 'POST'},
    logoutData: {url: 'api/logout', method: 'POST', redirect: '/admin/login', makeRequest: false},
    authRedirect: {path: '/admin/login'},
    fetchData: {url: 'api/account', method: 'GET' , authType: 'bearer'},
    rolesVar: 'role_id'
};

```

**Comment by websanova** [comment]
Those are just defaults ;)  when you can call any of the functions it maps
accordingly and overrides anything you pass in through the call.

**Comment by websanova** [comment]
Any luck here?
