### ISSUE TITLE
3.0.5-beta staySignedIn bug ?

### ISSUE THREAD

**Issue by birdman00** [websanova/vue-auth#532]
![image](https://user-images.githubusercontent.com/63040114/78919836-148aad00-7ac5-11ea-9625-df31f4337d40.png)

When staySignedIn is true, it using sessionStorage. if staySignedIn is false, it using localStorage. Not same as per documentation.

**Comment by websanova** [comment]
Not sure what you mean...can you be more descriptive, or provide some code sample...

**Comment by birdman00** [comment]
My configuration

loginData: { url: 'auth/login', method: 'POST', redirect: null, fetchUser: true, staySignedIn: false }

After login success, it suppose to use session storage. But when i check browser, it does not work as expected. The JWT token is storing in local storage

**Comment by birdman00** [comment]
https://github.com/websanova/vue-auth/blob/master/src/auth.js

![image](https://user-images.githubusercontent.com/63040114/78925127-7d762300-7acd-11ea-967e-1947acd90dd3.png)

Line 183, it suppose be

__token.set.call(this, null, token, (__auth.options.loginData.staySignedIn === true ? false : true));

**Comment by lim116** [comment]
https://websanova.com/docs/vue-auth/upgrades/2x-3x#the-codelocalstoragecode-option-for-codetokenstorecode-has-been-renamed-to-codestoragecode

@websanova according to the upgrade to 3.x user guide, there was written

> With staySignedIn set to true it would use localStorage while with a false value, it will use sessionStorage.

https://github.com/websanova/vue-auth/blob/master/src/lib/storage.js

but in the src/lib/storage.js file, the code was written differently from the user guide provided where the output/process will be different

![image](https://user-images.githubusercontent.com/45387123/78930501-d1d1d080-7ad6-11ea-8e74-7d10f026b8f6.png)

**Comment by birdman00** [comment]
Another issue again, once at login page, uncheck Stay Signed In checkbox, staySignedIn will become false value. After login, refresh the page, staySignedIn value will become default value based on default configuration or src/auth.js config.

![image](https://user-images.githubusercontent.com/63040114/78939363-90e1b800-7ae6-11ea-9bdb-c5a7aff85b8d.png)

**Comment by websanova** [comment]
ok, updated the initial issue in 3.0.6-beta.

With the latter, I will need to fix that. It will need to store the `staySignedIn` value locally as well for the refresh. Will update shortly.

Thx

**Comment by websanova** [comment]
Ok, the latter is now fixed as well in 3.0.7-beta.

Actually this works much better since it uses the specified storage to remember the selection and behaves more globally which makes a lot more sense.

Thx, for reporting :-)
