### ISSUE TITLE
Is there is a way to return {} for empty user in 3.x

### ISSUE THREAD

**Issue by zorn-v** [websanova/vue-auth#533]
I have app with all routes protected with auth except login. In that pages I often use user object fields like `{{ $auth.user().field1 }} {{ $auth.user().field2 }}` etc.
If I reload page after login and then do logout I'm get `[Vue warn]: Error in render: "TypeError: _vm.user is null"` in console.

It is possibly to return 2.x behavior for `$auth.user()` function somehow ? I don't want to do something like `<span v-if-"$auth.user()">{{ $auth.user().field1 }} {{ $auth.user().field2 }}</span>` everywhere

**Comment by websanova** [comment]
Don't need an if, just use a computed property and `return $auth.user() || {}` or just do `($auth.user() || {}).field

**Comment by zorn-v** [comment]
I think I'm create plugin to populate `$user()` function to components
