### ISSUE TITLE
I get an errror after upgrade: Error (@websanova/vue-auth): "auth" driver must be set.

### ISSUE THREAD

**Issue by laurnicolae** [websanova/vue-auth#539]
I've upgraded websanova to v3 on my vuejs app and I get the following errors:

Error (@websanova/vue-auth): "auth" driver must be set.
TypeError: __auth.http is undefined

Before this I had the following code:
`Vue.use(require('@websanova/vue-auth'), {
   auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
   http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
   router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
   loginData: { redirect: '' }
});`

and after I upgraded I have this:

`import auth from '@websanova/vue-auth';
import authBasic from '@websanova/vue-auth/drivers/auth/basic.js';
import httpVueResource from '@websanova/vue-auth/drivers/http/vue-resource.1.x.js';
import routerVueRouter from '@websanova/vue-auth/drivers/router/vue-router.2.x.js';
import oauth2Google from '@websanova/vue-auth/drivers/oauth2/google.js';
import oauth2Facebook from '@websanova/vue-auth/drivers/oauth2/facebook.js';

oauth2Google.params.client_id = 'GOOGLE-OAUTH2-CLIENT-ID';
oauth2Facebook.params.client_id = 'FACEBOOK-CLIENT-ID';

Vue.use(auth, {
  auth: authBasic,
  http: httpVueResource,
  router: routerVueRouter,
  oauth2: {
    google: oauth2Google,
    facebook: oauth2Facebook,
  }
});`

(ignore the oauth2 part, I'm not using it for now).

I had 2.21.14-beta and upgraded to 3.1.2-beta.

Where am I wrong?

**Comment by websanova** [comment]
Looks ok, not sure.

But it's clearly showing undefined errors, perhaps investigating with a few simple console.log statements will help before posting an issue.
