### ISSUE TITLE
the expire cookie is not set

### ISSUE THREAD

**Issue by heartbeatLV** [websanova/vue-auth#540]
Hi I'm trying to set a default for the expire cookie but no value is updated. this is my configuration:

```js
"@websanova/vue-auth": "^3.1.2-beta"
```

```js
import VueAuth from '@websanova/vue-auth'
import auth from '@websanova/vue-auth/drivers/auth/bearer.js'
import http from '@websanova/vue-auth/drivers/http/axios.1.x.js'
import router from '@websanova/vue-auth/drivers/router/vue-router.2.x.js'

export default ({ router: appRouter, Vue }) => {
  Vue.router = appRouter
  Vue.use(VueAuth, {
    auth,
    http,
    router,
    stores: ['cookie'],
    cookie: {
      Path: '/',
      Domain: 'custom.domain.x',
      Secure: false,
      Expires: any number, <--
      SameSite: 'None'
    }
  })
}

```

**Comment by lexusburn** [comment]
Works for me if i set a valid number in milliseconds.

I had a problem if Domain is set. I use a different approach:
```
var getMyAuthCookieDomain = function() {
	return 'custom.domain.x;
};
...
	getCookieDomain: getMyAuthCookieDomain, // variable 
	cookie: {
		Path: '/',
		Secure: true,
		Expires: 129600 * 60000, // 3 months
		SameSite: 'None'
	},

```

**Comment by heartbeatLV** [comment]
> 
> 
> Works for me if i set a valid number in milliseconds.
> 
> I had a problem if Domain is set. I use a different approach:
> 
> ```
> var getMyAuthCookieDomain = function() {
> 	return 'custom.domain.x;
> };
> ...
> 	getCookieDomain: getMyAuthCookieDomain, // variable 
> 	cookie: {
> 		Path: '/',
> 		Secure: true,
> 		Expires: 129600 * 60000, // 3 months
> 		SameSite: 'None'
> 	},
> ```

I used your configuration but the error persists

**Comment by websanova** [comment]
seems fine to me in the demo.

I think you have to double check if it's http/s and the domain matches.

From testing if I set the domain to one that is not the actual domain it gets wonky. Normally I would just leave this as null and let it auto fetch the domain.

Also if you have some previous cookies stored I would suggest removing them. For instance when i let it save automatically it went to my localhost.com domain. If I changed it to localhost.x it seemed to just get ignored and keep using the cookie there. So basically the cookie does not get set if it doesn't match the actual domain (which make sense I guess).

**Comment by heartbeatLV** [comment]
> seems fine to me in the demo.
> 
> I think you have to double check if it's http/s and the domain matches.
> 
> From testing if I set the domain to one that is not the actual domain it gets wonky. Normally I would just leave this as null and let it auto fetch the domain.
> 
> Also if you have some previous cookies stored I would suggest removing them. For instance when i let it save automatically it went to my localhost.com domain. If I changed it to localhost.x it seemed to just get ignored and keep using the cookie there. So basically the cookie does not get set if it doesn't match the actual domain (which make sense I guess).

i've tryed this configuration:
```js
stores: ['cookie'],
cookie: {
  Path: '/',
  Secure: false,
  Expires: 129600 * 60000, // 12096e5,
  SameSite: 'None'
}
```

and this:
```js
stores: ['cookie'],
cookie: {
  Path: '/',
  Secure: false,
  Expires: 129600 * 60000, // 12096e5
}
```
result: 
![immagine](https://user-images.githubusercontent.com/33943143/80488632-f0511c00-895e-11ea-80aa-78f0fc6119db.png)

---

the only thing i can't try is on secure connection

**Comment by websanova** [comment]
Did you try to console.log document.cookie? Or doing it manually outside the plugin to isolate the issue?

**Comment by websanova** [comment]
Do you still have getCookieDomain function set? What happens if you go full default?

**Comment by websanova** [comment]
Otherwise only thing I can think of is put a console.log in the package in the cookie lib. There is a spot where it sets document.cookie. log that and we'll have a better idea of what's actually getting set.

**Comment by heartbeatLV** [comment]
> Do you still have getCookieDomain function set? What happens if you go full default?

no, it's not set [configuration](https://github.com/websanova/vue-auth/issues/540#issuecomment-620584559)

> Otherwise only thing I can think of is put a console.log in the package in the cookie lib. There is a spot where it sets document.cookie. log that and we'll have a better idea of what's actually getting set.
> 
> Meaning log the string before the cookie is set...

lib/cookie.js:
```js
console.log(cookie)
document.cookie = cookie;
```

console:
```
auth_token_default=token; Path=/; Domain=demo.crm-client.x; Expires=; SameSite=None;
```

**Comment by websanova** [comment]
Right, and console params above....a little debugging would help...

**Comment by websanova** [comment]
And just realized, do you have staySignedIn set to true or false?

**Comment by heartbeatLV** [comment]
> And just realized, do you have staySignedIn set to true or false?

```js
async login () {
  await this.$auth.login({
    data: this.form
  })
}
```

I left it as default: true

however even setting it to false doesn't change anything

I also noticed that using cookies rather than the local storage `auth_stay_signed_in` is never set

**Comment by websanova** [comment]
I dunno dude, I can't recreate it and can't debug from here.

Everything happens in this `setCookie` function.

https://github.com/websanova/vue-auth/blob/master/src/lib/cookie.js#L1

How about just putting some console.log there. You've already shown that the Expires value is not set so maybe check the params at the top and pepper some console statements around. I'm sure it's something simple ;-)
