### ISSUE TITLE
How can i get notified after user is fetched (previously with watch in v2)

### ISSUE THREAD

**Issue by lexusburn** [websanova/vue-auth#541]
i've used watch to get notified when authenticated was fetched.
User will be fetched after refresh if a token is saved in a cookie (remember me) or after login.

```	
watch: {
  '$auth.watch.data': function(val) {
    try {
      // save authenticated user in vuex
      this.setUser(val);
    } catch (e) {
      console.log('something went wrong: ', e);
    }
  }
},
```

At v3 it seems that i can't handle both cases.
I can use this to get the user if a cookie was set:
```
mounted() {
  this.$auth.load().then(() => {
    if (this.$auth.check()) {
      if (this.$auth.user() !== null) {
        const user = this.$auth.user();
        this.setUser(user);
      }
    }
  });
},
```

But how can i use a promise to handle the automatic fetch after a login?

**Comment by websanova** [comment]
Maybe overthinking it.

Just use `this.$auth.user()` directly, no watch required.

Normally the way I may do it is just to wrap my `router-view` or some other block with `$auth.check()` or if that doesn't suit the situation, just use a computed property.

```
   computed: {
       _user() {
           return this.$auth.user() || {};
       }
   }
```

Or even better just do it via Vuex (I have an example in my demo for that already, just check in there).
