### ISSUE TITLE
this.$auth is undefined - "TypeError: Cannot read property 'login' of undefined"

### ISSUE THREAD

**Issue by lucasfrdgs** [websanova/vue-auth#544]
@websanova even after install the plugin and require it in main.js file,  "this.$auth" is undefined in vue components and i cannot access any methods

Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/devise.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  tokenStore: ['localStorage', 'cookie'],
  rolesVar: 'role',
}

for each require statement i have warnings about 'could not find declaration file for module'

**Comment by lucasfrdgs** [comment]
![image](https://user-images.githubusercontent.com/34378185/80492963-1a90e280-893b-11ea-9d40-0ef8eba5ac4f.png)

**Comment by websanova** [comment]
Did you follow the upgrade guide?

**Comment by lucasfrdgs** [comment]
Sorry, this is the first time i am working on auth.
I checked the upgrade guide and it still doesnt work for me.
now, with syntaxe below the axios driver breaks

import VueAuth from "@websanova/vue-auth";
import authDevise from "@websanova/vue-auth/drivers/auth/devise.js";
import authHttp from "@websanova/vue-auth/drivers/http/axios.1.x.js";
import authRouter from "@websanova/vue-auth/drivers/router/vue-router.2.x.js";

Vue.use(VueAuth, {
  auth: authDevise,
  http: authHttp,
  router: authRouter,
  stores: ["storage"],
  rolesKey: "role",
  cookie: {
    Path: "/",
    Domain: null,
    Secure: true,
    Expires: 12096e5,
    SameSite: "None"
  }
});

![image](https://user-images.githubusercontent.com/34378185/80513857-10c8a880-8956-11ea-9958-808a2131d2f0.png)

and I have axios installed

**Comment by lucasfrdgs** [comment]
> Sorry, this is the first time i am working on auth.
> I checked the upgrade guide and it still doesnt work for me.
> now, with syntaxe below the axios driver breaks
> 
> import VueAuth from "@websanova/vue-auth";
> import authDevise from "@websanova/vue-auth/drivers/auth/devise.js";
> import authHttp from "@websanova/vue-auth/drivers/http/axios.1.x.js";
> import authRouter from "@websanova/vue-auth/drivers/router/vue-router.2.x.js";
> 
> Vue.use(VueAuth, {
> auth: authDevise,
> http: authHttp,
> router: authRouter,
> stores: ["storage"],
> rolesKey: "role",
> cookie: {
> Path: "/",
> Domain: null,
> Secure: true,
> Expires: 12096e5,
> SameSite: "None"
> }
> });
> 
> ![image](https://user-images.githubusercontent.com/34378185/80513857-10c8a880-8956-11ea-9958-808a2131d2f0.png)
> 
> and I have axios installed

i have fixed it importing axios before VueAuth.. ok.
but again i have the same first issue, about i am unable to access $auth in components.
