### ISSUE TITLE
Check Method return false in role check

### ISSUE THREAD

**Issue by zaamx** [websanova/vue-auth#547]
The check method returns false using the example of check role with object

`
<pre>
      {{$auth.user().role}}
    </pre>
`
returns 
`
{
  "id": 1,
  "name": "Authenticated",
  "description": "Default role given to authenticated user.",
  "type": "authenticated"
}
`
and 

`
 <pre>
      {{$auth.check({ type: 'authenticated' })}}
    </pre>
`

returns **false**

The issue reflects in the router.

Any advice? Tnks

**Comment by websanova** [comment]
Did you update your roles key in the config?

https://websanova.com/docs/vue-auth/options/examples/#roleskey

**Comment by zaamx** [comment]
Yep, where 'role' its a object in the @me response of my strapi api

`export default async ({ app, router, Vue }) => {
  // something to do
  Vue.router = router
  Vue.use(auth, {
    auth: {
      request: function (req, token) {
        if (token) {
          // this.options.http._setHeaders.call(this, req, { Authorization: 'Bearer ' + token })
          this.options.http.setHeaders(req, { Authorization: 'Bearer ' + token })
        }
      },
      response: function (res) {
        if (res.data.jwt) {
          return (res.data || {}).jwt
        }
      }
    },
    http: httpAxios,
    router: routerVueRouter,
    loginData: { url: process.env.API + 'auth/local', method: 'POST', redirect: '/', fetchUser: true },
    tokenDefaultKey: 'jwt',
    tokenName: 'token',
    stores: ['storage', 'cookie'],
    authRedirect: { path: '/login' },
    roleskey: 'role',
    fetchData: {
      url: process.env.API + 'users/me',
      method: 'GET',
      enabled: true
    },
    parseUserData (data) {
      console.log('user', data)
      return data || {}
    },
    refreshData: { url: process.env.API + 'auth/refresh', method: 'GET', enabled: false, interval: 30 },
    tokenExpired: () => {
      return false
    }
  })
}
`

**Comment by websanova** [comment]
Is that a typo on `roleskey`?  Should be `rolesKey` maybe?

**Comment by zaamx** [comment]
Yeah it was the typo, tnks for the inconvenience. Your lib its great for wp and strapi!
