### ISSUE TITLE
redirect() in 3.x

### ISSUE THREAD

**Issue by Al10s** [websanova/vue-auth#549]
Hey there

I'm trying to migrate from 2.22.1 to 3.x, and I am wondering if `this.$auth.redirect()` still works.

In 2.22.1-beta, it returned either `null`, or an object containing the type of the redirect, and route descriptions in `from` and `to`.

In 3.0.0-beta (and until 3.1.2-beta), it appears that `from` and `to` are always `null` when it returns the object.

I double-checked and I don't think I missed any change from the migration manual, so I wanted to know if it was a bug in 3.x versions or if I should keep digging on my side.

Thanks

**Comment by websanova** [comment]
Ok, found some typos there.

Fixed in `3.1.3-beta`
