### ISSUE TITLE
Incorrect expiry when impersonating

### ISSUE THREAD

**Issue by kukicola** [websanova/vue-auth#553]
Hi!
I noticed that my impersonation tokens are kept in localStorage instead of sessionStorage even if I have `staySignedIn: false`. I looked a bit at the code and there is something wrong:

In login action:
https://github.com/websanova/vue-auth/blob/master/src/auth.js#L192
Expiry param (4th argument) is set to `false` when this staySignedInKey is present in localStorage (and it makes sense) but it's opposite in impersonate:
https://github.com/websanova/vue-auth/blob/master/src/auth.js#L354
Expiry param is set to `true` here if key is present. So when `staySignedIn: false` (key is missing so expiry param is set to `false`) this tokens are stored in localStorage instead of sessionStorage.

Same bug in `token` method:
https://github.com/websanova/vue-auth/blob/master/src/auth.js#L510
If a expiry param is missing and staySignedIn key is present it will be set to `true` instead of `false`.

**Comment by websanova** [comment]
Nice catch.

Fixed in `3.1.5-beta`.
