### ISSUE TITLE
Redirect on unsuccessfully login - beta 3

### ISSUE THREAD

**Issue by larscmagnusson** [websanova/vue-auth#554]
Hi!

I love vue-auth, but when I upgraded from v2 to v3 Im having problems with the login method.

What I want to do is to catch the 401 error, and display a message to the user, but instead a redirect is made to / .

The error is cauth, but the errormessage dont get display since the user is not on the same route anymore.  

```

const response = await this.$auth.login({
          url: '/login',
          data: {
            userName: this.username.replace('-', ''),
            password: this.password,
            timeToLive: 0
          },
          remember: true
          // redirect: null
});
```

Any idées?

**Comment by websanova** [comment]
where is the 401 error coming from actually? Like on the login response or maybe on fetch user? some other redirects occurring ? 

Do you have an existing interceptor for that 401?

**Comment by larscmagnusson** [comment]
Yes, its from the login responsen. I do have another interceptor for 401!

**Comment by websanova** [comment]
Ok, well bit strange to get a 401 on login. Sounds like something not setup quite right.

Otherwise you could also try passing in `null` for the redirect option

**Comment by larscmagnusson** [comment]
401 happens on unsuccessful attempt to logIn, not so very strange I think? https://stackoverflow.com/questions/11714485/restful-login-failure-return-401-or-custom-response

I tried pass null, I also tried to remove redirect entirely, but same results :(

**Comment by websanova** [comment]
Well regardless, you mentioned you have an interceptor for the 401, this is not the cause of the issue?

**Comment by larscmagnusson** [comment]
I’ll try to remove it and see what happens, but this was not a problem in the previous version of the package

**Comment by websanova** [comment]
Well, it is a major version bump, so some different behavior would be expected. Especially since you have an interceptor there, that would be the first thing to check.

**Comment by larscmagnusson** [comment]
I Will definitely try to remove the interceptor to see what happens. I’ll let you know 👍

**Comment by larscmagnusson** [comment]
I had a interceptor watching for 401 request, and if one occurred, logout the user (session expired). I guess the a new default is to redirect on logout. So the actual problem wasnt redirect on login, but on logout. 

I solved it by settings the `logotData.redirect` in the default options to `null`.

Thanks!
