### ISSUE TITLE
this.Vue.router is undefined

### ISSUE THREAD

**Issue by BlackoutGG** [websanova/vue-auth#555]
Versions:
Vue: 2.6.11
Vue-router: 3.1.6
Vuetify: 2.2.11
Vue-auth: 3.1.3-beta

I'm trying to setup vue-auth as explained in the guides, however I encounter a problem.

My setup:
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import vuetify from "./plugins/vuetify";
import axios from "axios";
import VueAxios from "vue-axios";

import auth from "@websanova/vue-auth";
import authBearer from "@websanova/vue-auth/drivers/auth/bearer.js";
import httpAxios from "@websanova/vue-auth/drivers/http/axios.1.x.js";
import routerVueRouter from "@websanova/vue-auth/drivers/router/vue-router.2.x.js";

axios.defaults.baseURL = "http://localhost:3000/api/v1";

Vue.use(VueAxios, axios);

Vue.config.productionTip = false;

Vue.use(auth, {
  auth: authBearer,
  http: httpAxios,
  router: routerVueRouter,
});

new Vue({
  router,
  store,
  vuetify,
  render: (h) => h(App),
}).$mount("#app");
```
I import the router from ./router/index.js

Everything seems to be correct, however when I launch the dev server I get a white screen with the following error:
`TypeError: this.Vue.router is undefined`

Upon further investigation it seems Vue is not loading:
`window.Vue
undefined
`

What did I do wrong?

**Comment by websanova** [comment]
Maybe check the demo sample code

**Comment by BlackoutGG** [comment]
Checked the demo, besides using axios and vuetify, I don't see where the issue could be, Unfortunately not using vuetify isn't an option.

**Comment by websanova** [comment]
Note the router is setup before the plugin calls in the config. 

https://github.com/websanova/vue-auth/blob/master/demos/2.x/src/main.js

Are you setting up the vue router after the auth plugin?

Otherwise should not have anything to do with vuetify or axios, since it's complaining about router.

**Comment by BlackoutGG** [comment]
simple fix. Changed the router file, had to be Vue.router and exported it accordingly.

**Comment by newfylox** [comment]
@BlackoutGG can you tell me how you get this fixed? Not really sure to understand your solution.

What's weird is that is passes the `init` function that tests `this.Vue.router` but after I have the error that it can't call `beforeEach` of undefined on `this.Vue.router` that already passed the test.

**Comment by newfylox** [comment]
Ok, I think I got your solution. I had to put `Vue.router = router;` before the `vue-auth` plugin and it worked. But it seems kind of weird for me. Any idea?
