### ISSUE TITLE
Unit testing issue

### ISSUE THREAD

**Issue by YankeeMan2012** [websanova/vue-auth#556]
I am trying to run test:unit in app

# appjs.spec.js

```javascript
import vm, { render } from '@/app';
import Vue from 'vue';

jest.mock('@websanova/vue-auth');

describe('app', () => {
  it('should call render handler with App', () => {
    const h = jest.fn();
    render(h);
    expect(h).toHaveBeenCalledWith({
      render: expect.anything(),
      created: expect.anything(),
      name: 'app',
      staticRenderFns: [],
    });
  });
});
```

# app.js

```javascript
import Vue from 'vue';
import VueAxios from 'vue-axios';
import VueAuth from '@websanova/vue-auth';
import websanovaAuth from '@/services/auth';
import websanovaRouter from '@websanova/vue-auth/drivers/http/axios.1.x';
import websanovaHttp from '@websanova/vue-auth/drivers/router/vue-router.2.x';
import api from '@/services/api';
import App from './App.vue';
import router from './router';
import store from './store';
import './filters';

Vue.config.productionTip = false;
Vue.router = router;

Vue.use(VueAxios, api);
Vue.axios.defaults.baseURL = 'http://localhost:3000'; // TODO: temp

Vue.use(VueAuth, {
  auth: websanovaAuth,
  http: websanovaRouter,
  router: websanovaHttp,
});

export const render = (h) => h(App);

const vm = new Vue({
  router,
  store,
  render,
});

export default vm;
```

and I get an error 

# error

>  tests/unit/appjs.spec.js
> Test suite failed to run
>
>    /******/node_modules/@websanova/vue-auth/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Auth from './auth.js';
                                                                                                    ^^^^
>
>    SyntaxError: Unexpected identifier
>
>       5 | import VTooltip from 'v-tooltip';
>       6 | import VueAxios from 'vue-axios';
>    >  7 | import VueAuth from '@websanova/vue-auth';
>         | ^

I am trying to mock vue-auth but it didn't help. Any suggestions or thinks?
Thanks!

**Comment by websanova** [comment]
Hmm, doesn't seem like the error there is with the library.

I mean it's showing syntax error right...

Your app supports es6 import/export syntax?

**Comment by YankeeMan2012** [comment]
Yes, I use es6 syntax with many modules. Maybe my test runner doesn't support it. I'll review it. Thanks for your feedback!

**Comment by YankeeMan2012** [comment]
Problem with my test runner. Thank you @websanova for your feedback!

**Comment by aislanmaia** [comment]
@YankeeMan2012 how you fixed it ? I'm having the same problem to import vue-auth related things to my jest tests..
