### ISSUE TITLE
"body" not working in login method

### ISSUE THREAD

**Issue by darkylmnx** [websanova/vue-auth#557]
In the docs, you show examples of `$auth.login()` and `$auth.register` with a body parameter, I've been trying for almost an hour now and nothing worked with that. I then realized that maybe the doc is wrong, I checked your code, you seem to pass the params to the HTTP driver **as is** and that meant that, **body** was passed to axios (in my case), but in axios there's no such thing as **body**, the name of the parameter is **data**.

The docs should be clear about that, IMO, all drivers should have examples specific to theme if you do not normalize anything internally.

**Comment by websanova** [comment]
Good point, actually this is common issue.

Added bunch of references for this to the docs.

* https://websanova.com/docs/vue-auth/guides/drivers
* https://websanova.com/docs/vue-auth/recipes/body-param-is-not-working

Also added references to the recipe in the method reference where it applies. Hopefully this will stop coming up.
