### ISSUE TITLE
TypeError: this.Vue.axios is undefined when using axios HTTP driver

### ISSUE THREAD

**Issue by straurob** [websanova/vue-auth#558]
This is how I configure `vue-auth` to use the Axios HTTP driver.

```
import axiosDriver from "@websanova/vue-auth/drivers/http/axios.1.x";

Vue.use(vueAuth, {
  auth: bearer,
  http: axiosDriver,
  router: vueRouter,
  authRedirect: { path: "/login" },
  // ...
});
```

When loading my page the following is printed to the console:

`TypeError: this.Vue.axios is undefined`

It seems as if the `axios.1.x` driver tries accessing axios via `this.Vue.axios`.

What am I missing here?

**Comment by websanova** [comment]
Not sure exactly, but do you have axios installed before the vue-auth plugin.

Otherwise it's not gonna find it.

**Comment by straurob** [comment]
Indeed it was a wrong order of imports. I had another library importing and setting up axios, so that vue-auth could not find it.

**Comment by straurob** [comment]
Think I need to reopen this issue as it's not a hundred percent clear to me...

**main.js**

```
import Vue from "vue";
import App from "./App.vue";
import axios from "axios";
import "./libs/vue-auth";
```

**./libs/vue-auth**

```
import Vue from "vue";
import vueAuth from "@websanova/vue-auth";
import bearer from "@websanova/vue-auth/drivers/auth/bearer";
import axiosHttp from "@websanova/vue-auth/drivers/http/axios.1.x";
import vueRouter from "@websanova/vue-auth/drivers/router/vue-router.2.x";

// Vue.axios = axios;

// https://github.com/websanova/vue-auth/blob/master/docs/Options.md
Vue.use(vueAuth, {
  auth: bearer,
  http: axiosHttp,
  router: vueRouter
  // ...
});
```

This way I get `this.Vue.axios is undefined` error. When removing the comment for `Vue.axios = axios;` it seems to work at first glance.

So I thought moving `Vue.axios = axios;` to the `main.js` but then again it's not working.

**Comment by websanova** [comment]
Don't see any line like that in the main.js file...

and maybe just do some console.log(Vue.axios) to see where it's getting lost.

**Comment by straurob** [comment]
https://stackoverflow.com/a/61908041/478406 solved my issue.

**Comment by websanova** [comment]
I've updated the docs, adding link here for reference:

https://websanova.com/docs/vue-auth/recipes/common-axios-issues
