### ISSUE TITLE
An "auth driver must be set" error occurred when Vue was referenced externally

### ISSUE THREAD

**Issue by wenner** [websanova/vue-auth#559]
I found that the version was upgraded to 3. X a few days ago, which is great

There are some inconveniences in the previous version. For example, if you need to obtain some data after logging in successfully, you can only modify the fetchprocess method (or I don't know how to modify other places)

---

Well, I upgraded to 3. X in the first place, checked the new documents and made changes, and it worked well

However, after I build , the following error occurred:
```
auth.js:396 Error (@websanova/vue-auth): "auth" driver must be set.
auth.js:430 Uncaught TypeError: Cannot read property 'interceptor' of undefined
```

Unlike previous projects, which have always used Vue auth, I have placed Vue as an external reference
```js
configureWebpack: smp.wrap( {
    externals: isProduction ? {
        'vue': 'Vue',
    }: {},
})
```

Then, I checked the source code. I think the error is that no options are passed in the Vue.use method, so the above error will appear

```
if (typeof window !== 'undefined' && window.Vue) {
    window.Vue.use(plugin);
}
```
At present, I don't know how to solve this problem gracefully. I've looked at Vue-resource and other libraries using  "function plugin (Vue)",  These libraries do not pass in parameters, so they can be used directly window.Vue.use (xxx)

I can only roughly annotate that sentence at present :(

I hope it can be solved. Thank you

**Comment by websanova** [comment]
Hmm, seems like just ordering of plugin initialization.

Maybe similar to this issue?

https://github.com/websanova/vue-auth/issues/558

**Comment by websanova** [comment]
Update docs as well, this may help if using axios.

https://websanova.com/docs/vue-auth/recipes/common-axios-issues

**Comment by wenner** [comment]
No, I don't think it's the reason you said ...
Because Window.Vue.use (plugin) is directly executed, there is no second parameter options, so it will report an error

You can simply build the vue-auth example and try
Before buid, you need to modify vue.config.js to set the vue to no external reference.
```
	configureWebpack: {
		externals: isProduction ? {
		  'vue': 'Vue'
		} : {},
	},
```

At the same time, add the reference of vue.js to the successful dist / index.html
```

<div id=app></div>
<!--add vue.js-->
<script src="https://unpkg.com/vue@2.6.11/dist/vue.js"></script>

<script src=/js/chunk-vendors.22327a86.js></script>
<script src=/js/app.cbf0c106.js></script>

</body></html>
```
Then, you can see this error

---
In addition, there are too many ES6 arrow functions in the new version of the code, and then if it runs in IE, there will be an error ... (Is it only me who still needs to be compatible with IE)

I think, is it possible to generate code suitable for ES5 through babel when it is released?
Thank you!!

**Comment by websanova** [comment]
ok, so I guess you are install via scripts, so may have been the issue.

I've actually updated the build just yesterday using the exact same build file from vue-resource.

It does output common, es6 and it seems just a vanilla js version for web install.

https://github.com/websanova/vue-auth/tree/master/dist

Maybe see if this one works (there is min version as well).

https://github.com/websanova/vue-auth/blob/master/dist/vue-auth.js

**Comment by wenner** [comment]
Hi, friend

Recently, a project used @websanova/vue-auth 4.1.1, and then encountered this problem again. It only occurs in build, but not in dev

The error message is as follows:

```
chunk-vendors.c4ad78d6.js:403 Uncaught TypeError: Cannot read property 'auth' of undefined
    at chunk-vendors.c4ad78d6.js:403
    at new k (chunk-vendors.c4ad78d6.js:403)
    at L (chunk-vendors.c4ad78d6.js:403)
    at Function.e.use (vue.min.js:6)
    at chunk-vendors.c4ad78d6.js:403
    at Object.287c (chunk-vendors.c4ad78d6.js:403)
    at s (app.6e3204af.js:1)
    at Module.e1f5 (app.6e3204af.js:589)
    at s (app.6e3204af.js:1)
    at Module.1112 (app.6e3204af.js:41)
```

I found that the problem is the code in issue above

```
//at @websanova/vue-auth/dist/v2/vue-auth.esm.js
//source at @websanova/vue-auth/src/v2.js

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(plugin);
}

```

The problem is that I refer to Vue directly in the script, so I execute the above code automatically
```
<div id=app></div>
<!--add vue.js-->
<script src="https://unpkg.com/vue@2.6.11/dist/vue.js"></script>

<script src=/js/chunk-vendors.22327a86.js></script>
<script src=/js/app.cbf0c106.js></script>

</body></html>
```

Excuse me, how to solve this problem（ I remember that the last time I encountered this problem, I ended up returning to version 2. X

**Comment by websanova** [comment]
Hard to say from what you've shown.

"Cannot read property 'auth' of undefined" where is the code trying to run that?

Perhaps you are trying to use `Vue.auth` somewhere before `Vue` is available.

Probably best to start with a search for instances of `.auth` in your code.
