### ISSUE TITLE
clearing browser cache default login page

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#56]
Lets say you clear the browser cache and hit refresh again.  Is possible to override the default login page on refresh?

**Comment by websanova** [comment]
Not sure what you mean. There are options for authRedirect,
notFoundRedirect and forbiddenRedirect.

Did you mean one of those?

**Comment by websanova** [comment]
Did you try authRedirect option???

**Comment by kyoukhana** [comment]
let's say you have two different login pages one for users that looks different then admins how would authRedirect work

**Comment by websanova** [comment]
Well in that case you will need to write your own intercept and you can use
the $auth.check() function

**Comment by websanova** [comment]
Just realized something here, if the cache is cleared then you would not know whether the user was a regular use or an admin anyways. Even if you stored some additional info to keep track of this it would also be cleared.

Probably the only way to check would be the current route. And in this case you would just write your own interceptor I think.
