### ISSUE TITLE
vue-router.esm.js:2051 Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by desdevol** [websanova/vue-auth#562]
Version: "^3.2.1-beta"
Got this when successfully login with `this.$auth.login`. This is my code if you need it for reference:
```
login: function () {
            // get the redirect object
            let vm = this;
            this.$auth.login({
                params: {
                    email: vm.loginForm.username,
                    password: vm.loginForm.password
                },
                success: function () {
                    // handle redirection
                    vm.$router.push({ name: "home" })
                },
                error: function () {
                    vm.$q.notify({
                        message: 'Wrong email or password.',
                        color: 'red'
                    });
                },
                rememberMe: true,
                fetchUser: true
            })
        },
```
Only the first time I login would be an error. The second time has no problem with the redirection. I've tried to use $nextTick on `login()` function but does not solve the issue.

**Comment by websanova** [comment]
That's too ambiguous of an error to be posting for any debug.

You say it logs in, so maybe some redirect conflicts. Maybe try setting `redirect: null` as login option.

Also seems you need to take a look at the upgrade guide, since you are still using `error`, `success` options which are no longer supported in version 3 as that uses promises all the way.

https://websanova.com/docs/vue-auth/upgrades/2x-3x

**Comment by desdevol** [comment]
@websanova Thanks for the speedy reply. My bad, been following a Medium tutorial with 2.x versions usage. It works now with the promises method. However I had to pass the form data as `params` Object instead of `body` Object, which is showed in the example https://websanova.com/docs/vue-auth/methods/examples#login

**Comment by websanova** [comment]
Depends on the http driver, can be data for axios, body for cue resource
