### ISSUE TITLE
[HELP] Need to programatically login

### ISSUE THREAD

**Issue by krysalead** [websanova/vue-auth#563]
Hi,

I am running end 2 end test in Cypress.io and I need to bypass the login page using only $auth API.
I tried doing the following where app is the root DOM element of the app
```
const auth = app.__vue__.$auth;
  auth.user(user);
  auth.token(null, token);
  auth.watch.authenticated = true;
  auth.watch.loaded = true;
  app.__vue__.$user(user);
```
But it crashes on __ auth.watch__ which is undefined.
I have checked older issue and it seems that (in 2017) it was the way to go.
In the Previous API there was the login function that was having a flag (makeRequest:false if I remember correctly) to skip the request
Do you have an idea?

**Comment by websanova** [comment]
Not quite sure, but you could just console.log(auth) or console.log(auth.watch) and see what is there.
