### ISSUE TITLE
I Can't successfully login

### ISSUE THREAD

**Issue by Msangi21** [websanova/vue-auth#564]
I'm using "@websanova/vue-auth": "^2.21.17-beta", I get the unauthorized error when I attempted to log in. What I note is the login request is successful but when the websanova/vue-auth try to fetch the user is where it getting an unauthorized response and after check-in network tab in browser I saw the request does not have authorization bear token. Check the image attached. Please I need a help coz it takes me 2 days now.
![error2](https://user-images.githubusercontent.com/29815436/83941068-fef9e100-a7f0-11ea-938b-371642573395.PNG)
The below image show the successfully login request
![error1](https://user-images.githubusercontent.com/29815436/83941143-aa0a9a80-a7f1-11ea-874b-318233fbccef.PNG)

**Comment by websanova** [comment]
Did you check the `ready` and `check` method usage?

Also note the documentation is for v3 which I would recommend switching to.

**Comment by Msangi21** [comment]
After update to 3.2.1-beta. I still getting the same error plus.
![error3](https://user-images.githubusercontent.com/29815436/83942156-b2ff6a00-a7f9-11ea-8ae0-080a6044e088.PNG)
The bellow is my login function
`login(){
                this.loading = true
                let app = this
                this.$auth.login({
                    params: {
                        email:app.email,
                        password:app.password
                    },
                    success: function(){
                        app.loading = false
                        if (app.$auth.user().role === 1) {

                            this.$router.push({path:'/staff/dashboard'})
                        }else{
                            this.$router.push({path:'/customer/dashboard'})
                        }
                    },
                    error: function(){
                        app.loading = false
                        app.has_error = true
                    },
                    rememberMe: true,
                    fetchUser: true
                })
            }`

**Comment by websanova** [comment]
I think you need to check the upgrade guide.

You should be using "then" there as the login method returns a promise rather than the success callback there.

**Comment by Msangi21** [comment]
Thanks for your feedback.
Let me try ur suggestion

**Comment by Msangi21** [comment]
Hello @websanova ,
I have been trying to check documentation per your suggestion but I didn't find the sample which you implement login using "then", So please can you try to show/give me a sample of it?.

**Comment by Msangi21** [comment]
And this is my auth.js 
`import bearer from '@websanova/vue-auth/drivers/auth/bearer'
import axios from '@websanova/vue-auth/drivers/http/axios.1.x'
import router from '@websanova/vue-auth/drivers/router/vue-router.2.x'

const config = {
    auth: bearer,
    http: axios,
    router: router,
    tokenDefaultName: 'laravel-vue-spa',
    tokenStore: ['localStorage'],
    rolesVar: 'role',
    loginData: {url: 'login', method: 'POST', redirect: '', fetchUser: true},
    logoutData: {url: 'logout', method: 'POST', redirect: '/', makeRequest: true},
    fetchData: {url: 'user', method: 'GET', enabled: true},
    refreshData: {url: 'refresh', method: 'GET', enabled: true, interval: 30}
  }

  export default config`

**Comment by Msangi21** [comment]
And also I have try to install a fresh vue project but still I getting the same error

**Comment by Msangi21** [comment]
Alse this is my main.js

`import Vue from 'vue'
import App from './App.vue'
import 'es6-promise/auto'
import axios from 'axios'
import VueAuth from '@websanova/vue-auth'
import VueAxios from 'vue-axios'
import auth from './auth'
import router from './router'
import VueRouter from 'vue-router'

import 'jquery'
import jQuery from 'jquery'

let $ = jQuery

import 'jquery/src/jquery.js'
import 'bootstrap/dist/js/bootstrap.min.js'


Vue.router = router;
Vue.use(VueRouter);
Vue.use(VueAxios, axios);
axios.defaults.baseURL = "http://localhost:8000/v1"
Vue.use(VueAuth, auth);
Vue.config.productionTip = false

new Vue({
  render: h => h(App),
  router
}).$mount('#app')`

**Comment by websanova** [comment]
Well, it's just a standard Promise so maybe read up on that. Will be something like `this.$auth.login().then()`

And as I mentioned before did you check the `check` and `ready` usage?

**Comment by Msangi21** [comment]
Getting the same error

`loginI(){
                this.loading = true
                let app = this
                this.$auth.login(
                { params:{
                        email:app.email,
                        password:app.password
                    } },
            ).then(response => {
                    app.loading = false
                    console.log(response)
                    if (app.$auth.user().role === 1) {

                        this.$router.push({path:'/staff/dashboard'})
                    }else{
                        this.$router.push({path:'/customer/dashboard'})
                    }
                }).catch(error => {
                    console.log(error)
                    app.loading = false
                    app.has_error = true
                })
            }`

**Comment by websanova** [comment]
Not really sure I'm following this, you're getting unauthorized error from api?

Are you using vue-resource or axios? Maybe just need to send `data` instead of `body` for axios?

**Comment by Msangi21** [comment]
I got it from my endpoint because the fetch user request is sent without an authorization token to the backend. I try many ways but I getting the same problem

**Comment by Msangi21** [comment]
Why the request does not have an authorization token? 
![error4](https://user-images.githubusercontent.com/29815436/84568933-86b09400-ad8b-11ea-90e2-a47f0fe3bc55.PNG)

**Comment by Msangi21** [comment]
Sorry I was not answer this question "Are you using vue-resource or axios?",
I user axios

**Comment by websanova** [comment]
https://websanova.com/docs/vue-auth/options/examples/#parseuserdata

Maybe not to change how your response data is parsed

**Comment by Msangi21** [comment]
When I console in bearer.js I getting undefined value means hearder does not contain data

`export default {

    request: function (req, token) {
        this.http.setHeaders.call(this, req, {
            Authorization: 'Bearer ' + token
        });
    },

    response: function (res) {
        var headers = this.http.getHeaders.call(this, res),
            // token   = headers.Authorization || headers.authorization;
            // token   = res.data.token || headers.Authorization; This line is work but I don't think if is right way
        console.log(token)
        if (token) {
            token = token.split(/Bearer:?\s?/i);

            return token[token.length > 1 ? 1 : 0].trim();
        }
    }
};`

**Comment by Msangi21** [comment]
And this is how I return my token after success login

`return response()->json([
            'status' => 'success',
            'token' => $token,
        ],200)->header('Authorization', $token);`

**Comment by websanova** [comment]
Not sure man,

Seems like you just have some simple parsing issues with your token and user. I'm a bit busy to play with this for you. You just need to make sure the api/app match up in terms of where they are looking for things. It's not magically know.

The plugin comes with some defaults/drivers. If it doesn't match that you just need to tweak the params.

**Comment by Msangi21** [comment]
Okay

**Comment by lawrence615** [comment]
Hello @Msangi21 , did you get a solution to this?

**Comment by Msangi21** [comment]
Yeah by editing some line in bearer.js

**Comment by lawrence615** [comment]
@Msangi21 what change did you make?

**Comment by Msangi21** [comment]
`export default {

request: function (req, token) {
    this.http.setHeaders.call(this, req, {
        Authorization: 'Bearer ' + token
    });
},

response: function (res) {
    var headers = this.http.getHeaders.call(this, res),
        // token   = headers.Authorization || headers.authorization;
         token   = res.data.token // I use this one instead of above one
    console.log(token)
    if (token) {
        token = token.split(/Bearer:?\s?/i);

        return token[token.length > 1 ? 1 : 0].trim();
    }
}`

**Comment by AndreasElia** [comment]
@Msangi21 you have to expose the Authorization header in Laravel too. For example:

```
        return response(['user' => $user])
            ->withHeaders([
                'Access-Control-Expose-Headers' => 'Authorization',
                'Authorization' => $token,
            ]);
```

**Comment by Msangi21** [comment]
Thanks, it works
