### ISSUE TITLE
Cookies are not stored when i logged in.

### ISSUE THREAD

**Issue by vignesh164** [websanova/vue-auth#565]
Please Help me to save a cookie.

I have configured the auth and login but the cookie was not stored.
I have attached my code below.

![vue auth file](https://user-images.githubusercontent.com/38978461/83963289-6764c300-a8c2-11ea-8bae-4874a7e3aafe.jpg)

main.js
![main js file](https://user-images.githubusercontent.com/38978461/83963295-79466600-a8c2-11ea-9d76-d321a64b99ee.jpg)

my login component login function code

![login code](https://user-images.githubusercontent.com/38978461/83963298-8b280900-a8c2-11ea-8fc2-bd60ca10fe00.jpg)

I got successful login with a cookie but cookies are not stored
network tab in chrome:

![login request cookie](https://user-images.githubusercontent.com/38978461/83963024-56b34d80-a8c0-11ea-9f67-d733b18d3224.JPG)

cookies are empty after login
![empty cookie](https://user-images.githubusercontent.com/38978461/83963067-99752580-a8c0-11ea-9457-c01725cf0414.JPG)

**Comment by zorn-v** [comment]
You should configure `stores` option for vue-auth
https://websanova.com/docs/vue-auth/options/examples/#stores

By default it save auth info in storage if it avail. Check local/session storage

**Comment by vignesh164** [comment]
I already checked in all storage. there was no key are stored.

**Comment by websanova** [comment]
If they are all empty then you need to check the auth driver you are using to pass the token along and make sure the format matches what the API is sending.

**Comment by vignesh164** [comment]
I changed to bearer. but still is not store.

**Comment by websanova** [comment]
The driver is just client side.

What is your api sending?

**Comment by vignesh164** [comment]
this is my API sending
![api response](https://user-images.githubusercontent.com/38978461/83966443-e44e6780-a8d7-11ea-9f89-e6bfd6aa1035.JPG)
 
![api login data](https://user-images.githubusercontent.com/38978461/83966454-f3351a00-a8d7-11ea-86c2-6864c6c29964.JPG)

**Comment by zorn-v** [comment]
You should use something like
```js
      auth: {
        request: function (req, token) {
          this.http.setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
        },
        response: function (res) {
          const resData = res.data || {}
          return resData.token
        }
      },
```

**Comment by websanova** [comment]
Rights so your api doesn't match the drivers available. I would suggest you read up a bit more on auth tokens, bearer, basic, etc.

You can so check the drivers section in the docs.

**Comment by vignesh164** [comment]
> ```js
> auth: {
>         request: function (req, token) {
>           this.http.setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
>         },
>         response: function (res) {
>           const resData = res.data || {}
>           return resData.token
>         }
>       },
> ```

changed but I got a console error.
![console error](https://user-images.githubusercontent.com/38978461/83966756-d0a40080-a8d9-11ea-9016-fe4a8a86656b.JPG)

**Comment by vignesh164** [comment]
> > ```js
> > auth: {
> >         request: function (req, token) {
> >           this.http.setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
> >         },
> >         response: function (res) {
> >           const resData = res.data || {}
> >           return resData.token
> >         }
> >       },
> > ```
> 
> changed but I got a console error.
> ![console error](https://user-images.githubusercontent.com/38978461/83966756-d0a40080-a8d9-11ea-9016-fe4a8a86656b.JPG)

it' s work fine. problems are fixed. Thank you very much.

**Comment by vignesh164** [comment]
Thank you guys
