### ISSUE TITLE
$auth.user() is empty. returned {}. after i logged and fetch user

### ISSUE THREAD

**Issue by vignesh164** [websanova/vue-auth#567]
Hi,
I have logged successfully, and my fetch request was a success.

after I call $auth.user() it gives {} data

![image](https://user-images.githubusercontent.com/38978461/84022431-debe5380-a9a3-11ea-944b-ac07d0eacee3.png)

this is my login data
![image](https://user-images.githubusercontent.com/38978461/84022564-1b8a4a80-a9a4-11ea-8a80-ebadfb1b1634.png)

and it's my user fetch API data
![image](https://user-images.githubusercontent.com/38978461/84022657-407ebd80-a9a4-11ea-8cfb-2f3e8d7fc1e6.png)

please help me to get $auth.user()

**Comment by websanova** [comment]
Check the parse option

**Comment by vignesh164** [comment]
please share a link to check.

**Comment by websanova** [comment]
You could just check the docs yourself.

https://websanova.com/docs/vue-auth/options/index

**Comment by vignesh164** [comment]
I don't know. how to do.  please check my code. please tell where I change code for saving $auth.user().


![image](https://user-images.githubusercontent.com/38978461/84028650-b9831280-a9ae-11ea-96ec-307fbf0de78f.png)
