### ISSUE TITLE
role based and auth based router

### ISSUE THREAD

**Issue by vignesh164** [websanova/vue-auth#568]
Hi websanova,

I want sample code for role base route and also auth is true in vue router. please help me.

I tried this way but it fails. 
![image](https://user-images.githubusercontent.com/38978461/84127095-68c9f300-aa5c-11ea-9f2c-3e239c16c562.png)

please share sample code

**Comment by websanova** [comment]
Did you check the demo?

It's full of sample code and examples...

**Comment by vignesh164** [comment]
Thanks, it's worked.

![image](https://user-images.githubusercontent.com/38978461/84131546-505cd700-aa62-11ea-8422-911ad0c866ba.png)
