### ISSUE TITLE
Uncaught TypeError: Cannot read property 'interceptor' of undefined when deployed to Nginx

### ISSUE THREAD

**Issue by houzw** [websanova/vue-auth#569]
The program works fine when I execute `npm run dev`.  But when I build and deploy it to Nginx, I get an error
```
Uncaught TypeError: Cannot read property 'interceptor' of undefined
    at Z (vue-auth.esm.js:691)
    at new Q (vue-auth.esm.js:715)
    at tt (vue-auth.esm.js:962)
    at Function.$n.use (vue.min.js:6)
    at Object.<anonymous> (vue-auth.esm.js:973)
    at n (bootstrap 910d6cef2f8b186b4393:54)
    at Object.112 (app.6ebea90a0af4423c665c.js:92)
    at n (bootstrap 910d6cef2f8b186b4393:54)
    at window.webpackJsonp (bootstrap 910d6cef2f8b186b4393:25)
    at app.6ebea90a0af4423c665c.js:11
```

Version of vue-auth is "^3.2.1-beta", version of axios is "^0.19.2",

My configuration

```javascript
import Vue from "vue";
import axios from "axios";
import VueAxios from "vue-axios";
import VueAuth from "@websanova/vue-auth";
import authBearer from '@websanova/vue-auth/drivers/auth/bearer';
import httpAxios  from '@websanova/vue-auth/drivers/http/axios.1.x';
import routerVueRouter from '@websanova/vue-auth/drivers/router/vue-router.2.x';

Vue.use(VueAxios, axios);
Vue.use(VueAuth, {
  auth: authBearer,
  http: httpAxios,
  router: routerVueRouter,
  stores:['storage'],
  refreshData:{
    interval: 30
  }
});
```

**Comment by elreco** [comment]
I got the same error

**Comment by websanova** [comment]
Well, I don't think nginx would have anything to do with it.

Likely some discrepancy with the packages, you sure they are no aliases or anything like that?

What happens when you build locally?

**Comment by houzw** [comment]
I'm sure there are no aliases or anything like that. 
I have tried vue-auth 2.x and 3.x respectively with the same webpack and Nginx configurations, and the same versions of other packages. 
Vue-auth 2.22.1 works just fine in nginx.  
Both the building processes of 2.x and 3.x throws no exceptions. 

related packages currently used
```
    "axios": "^0.19.2",
    "vue": "^2.5.16",
    "vue-axios": "^2.1.5",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
```

**Comment by websanova** [comment]
Well if we look at the line error it shows issue with auth driver not installed correctly.

https://github.com/websanova/vue-auth/blob/master/dist/vue-auth.esm.js#L691

Possibly just need to use the esm package for proper module syntax, can try that...

https://websanova.com/docs/vue-auth/guides/startup#setup

Which is strange you don't get the error locally, likely means different build setup for dev/release potentially.

**Comment by houzw** [comment]
I finally found that the problem might be the Vue CDN in `index.html`.

```html

<!DOCTYPE html>
<html >
<body>
<div id="app"></div>
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuex@3.0.1/dist/vuex.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-router@3.0.1/dist/vue-router.min.js"></script>
</body>
</html>
```
When I comment out these lines and deploy the program to nginx, it works.

No problem with these CDNs when I use vue-auth 2.x.

**Comment by websanova** [comment]
Well, ya, you need Vue.router installed before vue-auth
