### ISSUE TITLE
Roles Check seems to be broken with arrays?

### ISSUE THREAD

**Issue by murum** [websanova/vue-auth#57]
Hi.

I've been wondering around and I can't really understand why the h*ll I get false when I run `$auth.check(4)` in my component. It doesn't matter if I do it with a string `$auth.check('4')`
if I do `$auth.user()` I get the following output
```
{
  "businessUnits": [
    {
      "Id": 99,
      "Name": "Example Ltd"
    }
  ],
  "detailedRoles": [
    {
      "Id": 4,
      "Name": "user"
    }
  ],
  "exp": 1480883709,
  "name": "firstname.lastname",
  "roles": [
    4
  ]
}
```

My init of VueAuth looks like this, I guess the rolesVar isn't necessary since I use the standard.
```
Vue.use(VueAuth, {
  router: router,
  authRedirect: {path: '/'},
  loginData: {'method': 'GET'},
  rolesVar: 'roles',
  tokenExpired: () => {
    return false
  }
})
```
Any clues why the heck I can't do `$auth.check(4)` and get true

**Comment by websanova** [comment]
Hmm, did you set auth on your routes?

**Comment by murum** [comment]
This is how my Routes looks
```
  { path: '/', name: 'login', component: Login },
  { path: '/auth/:next/:uid/:hash', name: 'login', component: Login },
  { path: '/account', name: 'account', meta: {auth: true}, component: Account },
  { path: '/invoice/index', name: 'invoice', meta: {auth: true}, component: Invoice },
```

**Comment by websanova** [comment]
Can you send your package.json depends for viruses plugins.

**Comment by murum** [comment]
```
{
  "name": "dt-frontend",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "Christoffer Rydberg <christoffer.rydberg@ganillagrace.se>",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "lint": "eslint --ext .js,.vue src"
  },
  "dependencies": {
    "@websanova/vue-auth": "^1.3.0-beta",
    "jquery": "^3.1.1",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.0",
    "babel-core": "^6.0.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.0.0",
    "connect-history-api-fallback": "^1.1.0",
    "css-loader": "^0.25.0",
    "eslint": "^3.7.1",
    "eslint-config-standard": "^6.1.0",
    "eslint-friendly-formatter": "^2.0.5",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-html": "^1.3.0",
    "eslint-plugin-promise": "^2.0.1",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.8.1",
    "http-proxy-middleware": "^0.17.2",
    "json-loader": "^0.5.4",
    "node-sass": "^3.11.2",
    "opn": "^4.0.2",
    "ora": "^0.3.0",
    "sass-loader": "^4.0.2",
    "shelljs": "^0.7.4",
    "url-loader": "^0.5.7",
    "vue-loader": "^9.4.0",
    "vue-style-loader": "^1.0.0",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"
  }
}
```

**Comment by murum** [comment]
Which is the stable version of vue-auth, I tried to change it to use 2.1.0.
But that resulted in:
`utils.js?92c3:3 Uncaught RangeError: Maximum call stack size exceeded(…)`

**Comment by websanova** [comment]
Ya, you are using quite old version of vue-auth. You should use the latest
1.x or try the latest 2.x which is quite new.

**Comment by murum** [comment]
@websanova When I try to use the latest 2.1.0-beta I get the error I added
`utils.js?92c3:3 Uncaught RangeError: Maximum call stack size exceeded(…)`

That is referring to in the `utils.js` file
```
    function isObject(val) {
        if (val !== null && typeof val === 'object' && val.constructor !== Array ) {
            return true;
        }

        return false;
    }
```

**Comment by oleg-nogin** [comment]
@websanova hey, the same error in console

**Comment by websanova** [comment]
Hmm, there is 2.2.0-beta already. Seems I just forgot to push to GH (just
pushed it now). But it's in npm already.

Also note there are major changes with 2.x. If you haven't already, please
check the Change Log. It no longer accepts the `Router` object as it's a
more driver centric approach in the 2.x stream. The `router`, `http` and
`auth` are driver files now, not the objects themselves.

There are also some install docs for 2.x. in the README. Let me know if
that works out or if anything doesn't make sense.

**Comment by murum** [comment]
Thanks for that knowledge.

Still it seems not to be working but right now I guess there's problem with my integration instead of the code and help is needed.

This is my code now, I guess it should be working with imports instead of the require methods.

```
import VueAuth from '@websanova/vue-auth'
import VueAuthAuth from '@websanova/vue-auth/drivers/auth/bearer.js'
import VueAuthHttp from '@websanova/vue-auth/drivers/http/vue-resource.1.x.js'
import VueAuthRouter from '@websanova/vue-auth/drivers/router/vue-router.2.x.js'
Vue.use(VueAuth, {
  auth: VueAuthAuth,
  http: VueAuthHttp,
  router: VueAuthRouter,
  authRedirect: {path: '/'},
  loginData: {'method': 'GET'}
})
```

I get this error
`vue-router.2.x.js?832c:22 Uncaught TypeError: Cannot read property 'beforeEach' of undefined`

**Comment by murum** [comment]
I found out what were missing
`Vue.router = router` was not set so the Vue had no variable router.

I'm not that good with pull requests etc. I just want to mention out that you should probably from some kind of warning 
in the `vue-router.2.x.js` if the option `this.options.Vue.router` is undefined, then you could probably error out that you might have been missing to define the Vue.router variable on the base vue element.

**Comment by websanova** [comment]
Yea, all the drivers will need that I guess. But I'm glad it's working for
you now.

**Comment by murum** [comment]
I just got into the next problem now, the Authorization header is not set as it did before with vue-auth 1.3. Researching it now, any ideas?

**Comment by oleg-nogin** [comment]
@murum can u show code with vue-auth pls?
`import Vue from 'vue'
import Auth from '@websanova/vue-auth'
import VueAuth from '@websanova/vue-auth/drivers/auth/basic.js'
import VueAuthHttp from '@websanova/vue-auth/drivers/http/vue-resource.1.x.js'
import VueAuthRouter from '@websanova/vue-auth/drivers/router/vue-router.2.x.js'
import VueResource from 'vue-resource'
import router from '../router'

Vue.use(VueResource)

Vue.http.options.root = 'https://api-demo.websanova.com/api/v1'

Vue.router = router

Vue.use(Auth, {
  auth: VueAuth,
  http: VueAuthHttp,
  router: VueAuthRouter
})`

and router 
`import Vue from 'vue'
import VueRouter from 'vue-router'
import menuModule from 'vuex-store/modules/menu'
import { TOGGLE_SIDEBAR } from 'vuex-store/mutation-types'
import store from '../store'

Vue.use(VueRouter)

const { state } = store

let router = new VueRouter({
  mode: 'history',
  linkActiveClass: 'is-active',
  scrollBehavior: () => ({ y: 0 }),
  routes: [
    ...generateRoutesFromMenu(menuModule.state.items),
    {
      path: '*',
      redirect: '/',
      meta: {
        auth: false
      }
    }
  ]
})

router.beforeEach((route, redirect, next) => {
  if (state.app.device.isMobile && state.app.sidebar.opened) {
    store.commit(TOGGLE_SIDEBAR, false)
  }
  next()
})

export default router

function generateRoutesFromMenu (menu = [], routes = []) {
  for (let i = 0, l = menu.length; i < l; i++) {
    let item = menu[i]
    if (item.path) {
      routes.push(item)
    }
    if (!item.component) {
      generateRoutesFromMenu(item.children, routes)
    }
  }
  return routes
}
`

**Comment by oleg-nogin** [comment]
Ooook

mistake was in 

```
{
   path: '*',
   redirect: '/',
   meta: {
      auth: false
   }
}
```

**Comment by websanova** [comment]
You are using basic driver or bearer?

**Comment by murum** [comment]
@websanova I'm using the bearer auth. How does the token be set and what's defining if it should be sent?

The response from my login route

```
{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVdassa.eyJuYW1lIjoiYWxleGFuZGVyLmxpbmRhaGwiLCJyb2xlcyI6WzRdLCJkZXRhaWxlZFJvbGVzIjpbeyJJZCI6NCwiTmFtZSI6IkFrdGllw6RnYXJlIn1dLCJidXNpbmVzc1VuaXRzIjpbeyJJZCI6OTksIk5hbWUiOiJHZXR0ZXLDpSBEw6RjayBBQidasdasddas.p5UrnXs4Oe2jbZ1AwNmoWbrICdLWXowWUjy7RQGEyEdsadas","data":{"name":"firstname.lastname","roles":[4],"detailedRoles":[{"Id":4,"Name":"User"}],"businessUnits":[{"Id":99,"Name":"Blaha Blaha B"}],"exp":1481182699}}
```

I've changed the tokens value so it isn't a valid token but the real token is a valid token etc.

**Comment by murum** [comment]
I'll close this issue and open a new that the token is not being set correct.
