### ISSUE TITLE
Redirect handler doesn't work

### ISSUE THREAD

**Issue by Nemes1sX** [websanova/vue-auth#570]
I'm using websanova 2.21.14 version. When I successfully logined in, I get Error:  Redirected from "/login" to "/dashboard" via a navigation guard. Because when I successfully logined in, this.$auth.user().role get null value. Hence, redirect handler doesn't work. P.S. login worked fine. I don't understand why this.$auth.user().role gets null value.
```
export default {
    data() {
      return {
        email: null,
        password: null,
        has_error: false
      }
    },
    mounted() {
      //
    },
    methods: {
      login() {
        // get the redirect object
        var redirect = this.$auth.redirect()
        var app = this
        this.$auth.login({
          params: {
            email: app.email,
            password: app.password
          },
          success: function() {
            // handle redirection
            const redirectTo = redirect ? redirect.from.name : this.$auth.user().role === 2 ? 'admin.dashboard' : 'dashboard'
            this.$router.push({name: redirectTo})
          },
          error: function() {
            app.has_error = true
          },
          rememberMe: true,
          fetchUser: true
        })
      }
    }
  }
```

**Comment by websanova** [comment]
Seems like issue with API response

**Comment by Nemes1sX** [comment]
I forget to mention, that I get 200 response because authentication was successfull.

**Comment by Al10s** [comment]
It may has something to do with the update of `vue-router` (at least in my case).
It worked fine with `vue-router@3.1.6`, but returns `null` with the latest version (`vue-router@3.3.4`)

**Comment by websanova** [comment]
But you said `this.$auth.user().role` is `null`.

So if you `console.log(this.$auth.user())` and there is no value for role, then something is off there.

**Comment by Nemes1sX** [comment]
Yeah i use ``` console.log(this.$auth.user()) ``` I get some object of values. But for role I get null. @Al10s @websanova I use ```vue-router: ^3.3.2, ``` maybe why redirect handler doesn't work

**Comment by websanova** [comment]
Right, so where is your user data coming from?

**Comment by Nemes1sX** [comment]
For my user data API on PHP (Laravel). https://medium.com/@ripoche.b/create-a-spa-with-role-based-authentication-with-laravel-and-vue-js-ac4b260b882f I'm using this approach

**Comment by Nemes1sX** [comment]
Also, I downgrading vue-router to 3.1.6 version, I get uncaught: promise
