### ISSUE TITLE
Questions about redirect() and logout()

### ISSUE THREAD

**Issue by Al10s** [websanova/vue-auth#574]
Hey there, I have a few questions about how `this.$auth.redirect()` is supposed to work.

1. If I try to go to a route that requires authentication, I get redirected according to `authRedirect`.
`this.$auth.redirect()` is holds the route data in its `from` parameter.

2. If I want to log out, I call `this.$auth.logout()`, that can make a request to the server. I can get redirected according to `logoutData.redirect`.
What is `this.$auth.redirect()` supposed to hold ? It seems always `null`, but there has been a redirection.

3. If I set up an axios interceptor in order to log out when i receive a 401 error from the server, this interceptor is supposed to call `Vue.auth.logout({ makeRequest: false })`. In this case I get redirected according to `logoutData.redirect`.
From my point of view, `this.$auth.redirect()` is supposed to hold the route where I was when the 401 error occurred in its `from` parameter, but it appears to be always `null`.
Is there a way to retrieve this data ?

In my case, I just want to redirect the user where he was before he gets disconnected because of the expiration of his token.

Is there a way to do that ?

**Comment by websanova** [comment]
Don't over think it, it's just meant for login requires redirects as a quick shortcut to keep you from having to code that in since it's gonna be the most common scenario.

Everything else just use your router or http plugin

**Comment by Al10s** [comment]
Ok then, thanks :)
