### ISSUE TITLE
$auth views do not load sometimes

### ISSUE THREAD

**Issue by tradebrse** [websanova/vue-auth#575]
When I try to load my views, that use this.$auth.user() , on some occasions the view will simply not load. 
I get a blank page without any errors. 
Workaround: Pressing F5 / reloading the page manually.
This only happens in my views that have $auth.user() in mounted() , so I think vue-auth is the cause of this problem.
Did anyone experience something similar or has a solution for this?
Thank you so much in advance!

**Comment by websanova** [comment]
Do you get any errors?

Are you using it anywhere else with check or ready?

**Comment by tradebrse** [comment]
Hi Rob,
Thank you for your response.
No I don't use it somewhere else with check or ready.
I only use  $auth.user() in a couple of views and when I use it, only once in a view.

**Comment by websanova** [comment]
Well for the page to go blank I would imagine there must be some error or somewhere where $auth is being used on a router view or something. Not really giving a lot of info to go on here.

**Comment by tradebrse** [comment]
I have checked my code again and found out that I use check(). I will provide some insight:
template:
`            <h4 class="uk-margin-remove">Welcome, {{ user.first_name }} {{ user.last_name }} <span
                class="uk-label uk-label-success" v-if="$auth.check(2)">Admin</span></h4>`
method:
`getUser(address) {
                axios
                    .get( 'users/' + this.$auth.user().id)
                    .then(response => {

                        this.successful = true;
                        this.error = false;
                        this.errors = [];

                        this.user = response.data.user;
                        this.user.created_at = moment(this.user.created_at).format('DD.MM.YYYY - HH:mm');
                        this.user.updated_at = moment(this.user.updated_at).format('DD.MM.YYYY - HH:mm');
                        this.user.birthday = moment(this.user.birthday).format('DD.MM.YYYY');
                        this.address = response.data.address;
                        this.address.created_at = moment(this.address.created_at).format('DD.MM.YYYY - HH:mm');
                        this.address.updated_at = moment(this.address.updated_at).format('DD.MM.YYYY - HH:mm');
                        this.loading = false;

                    })
                    .catch(error => {
                        if (!_.isEmpty(error.response)) {
                            if ((error.response.status = 422)) {
                                this.errors = error.response.data.errors;
                                this.successful = false;
                                this.error = true;
                            }
                        }
                    });
            },`

**Comment by websanova** [comment]
maybe you can describe this part a bit better:

"When I try to load my views, that use this.$auth.user() , on some occasions the view will simply not load.
I get a blank page without any errors."

And would be best if you could provide an isolated example.

**Comment by websanova** [comment]
You may also want to look into using `$auth.ready()`:

https://websanova.com/docs/vue-auth/methods/examples#ready
