### ISSUE TITLE
Cannot read property 'beforeEach' of undefined  (doesn't reach routes)

### ISSUE THREAD

**Issue by shqnks** [websanova/vue-auth#576]
Hello,

I've followed the documentation and the demo here : https://github.com/websanova/vue-auth/tree/master/demos/2.x/src

When I declare my vue-auth configuration :

```
import Vue from 'vue';
import auth from '@websanova/vue-auth';
import authBearer from '@websanova/vue-auth/drivers/auth/bearer.js';
import httpAxios from '@websanova/vue-auth/drivers/http/axios.1.x.js';
import routerVueRouter from '@websanova/vue-auth/dist/drivers/router/vue-router.2.x.js';

Vue.use(auth, {
    auth: authBearer,
    http: httpAxios,
    router: routerVueRouter,
    rolesKey: 'role'
});
```

I have this error in console : 

```
Uncaught TypeError: Cannot read property 'beforeEach' of undefined
at Auth.beforeEach
at _initInterceptors
at new Auth
```

I think the plugin can't reach my routes, but I followed the same code from the demo. Do you know how to solve this ?

**Comment by websanova** [comment]
Need to have `Vue.router` set before.

I'll add that to the docs actually.

**Comment by websanova** [comment]
Updated docs here.

https://websanova.com/docs/vue-auth/guides/startup#dependencies

**Comment by shqnks** [comment]
Thanks a lot for your answer, but I can't figure out what exactly I have to change.

In my main.js, I have this :

```
import router from './_services/router'
import config from './_services/config'
```

So the router is set before vue-auth, no ?

**Comment by websanova** [comment]
Well, what's in your router service file?

**Comment by shqnks** [comment]
```
import Vue from 'vue';
import Router from 'vue-router';

Vue.use(Router);

function loadView(view) {
    return () => import(`../../components/${view}.vue`);
}

function loadLayout(view) {
    return () => import(`../../components/_layouts/${view}.vue`);
}

const routes = [
    // USER ROUTES
    {
        path: '/tableau-de-bord',
        component: loadView('user/Dashboard'),
        meta: {
            layout: loadLayout('user/Layout'),
            auth: "user"
        },
        name: 'user'
    },
    // SUPPLIER ROUTES
    {
        path: '/prestataire',
        component: loadView('supplier/Dashboard'),
        meta: {
            layout: loadLayout('supplier/Layout'),
            auth: "supplier"
        },
        name: 'supplier'
    },
    // ADMIN ROUTES
    {
        path: '/admin',
        component: loadView('admin/Dashboard'),
        meta: {
            layout: loadLayout('admin/Layout'),
            auth: "admin"
        },
        name: 'admin'
    },
    // DEFAULT ROUTES
    {
        path: '/inscription',
        component: loadView('auth/Register'),
        meta: {
            layout: loadLayout('home/Layout'),
            auth: false
        },
        name: 'register'
    },
    {
        path: '/connexion',
        name: 'login',
        component: loadView('auth/Login'),
        meta: {
            layout: loadLayout('home/Layout'),
            auth: false
        }
    },
    {
        path: '/',
        component: loadView('home/Home'),
        meta: {
            layout: loadLayout('home/Layout'),
            auth: undefined
        },
        name: 'home'
    },
    // otherwise redirect to home
    {
        path: '*',
        redirect: '/'
    }

];

Vue.Router = new Router({
    hashbang: false,
    mode: 'history',
    routes
});

console.log(Vue.Router)

export default Vue.Router;
```

**Comment by websanova** [comment]
Should be fine.

Of you console.log(Vue.router) in your config file do you get anything?

**Comment by shqnks** [comment]
No, undefined

**Comment by websanova** [comment]
Also, how do you have Axios installed? actually that may be issue with http plugin not router.

**Comment by shqnks** [comment]
I did 
```npm install vue-axios ```

**Comment by websanova** [comment]
I mean how did you instantiate the plugin on your code

**Comment by shqnks** [comment]
I import it in my config (showed in my first post) and that's all

**Comment by websanova** [comment]
Well seems you're missing axios install, you can check the link I sent and docs again for that.

**Comment by websanova** [comment]
Also demo has a full example on how to setup axios plugin with Vue.

**Comment by shqnks** [comment]
Oh you mean my http/index.js file ?
```
import Vue from 'vue';

// Axios
import axios from 'axios';
import VueAxios from 'vue-axios';

var appUrl = "http://localhost/api"

axios.defaults.baseURL = appUrl;
Vue.use(VueAxios, axios);

export default {
    root: appUrl
};

```

**Comment by shqnks** [comment]
Yes I've followed the demo file by file to implement your plugin, but I'm stuck with this issue

**Comment by websanova** [comment]
ah wait, your imports are out of whack, you need to point to es6 files for import syntax.

https://websanova.com/docs/vue-auth/guides/startup#setup

Try adding the .esm ones.

```
import authBearer from '@websanova/vue-auth/drivers/auth/bearer.esm.js';
import httpAxios from '@websanova/vue-auth/drivers/http/axios.1.x.esm.js';
import routerVueRouter from '@websanova/vue-auth/dist/drivers/router/vue-router.2.x.esm.js';
```

**Comment by shqnks** [comment]
I have these npm errors when I `npm run dev`
```
ERROR in ./resources/js/_services/config/plugins.js
Module not found: Error: Can't resolve '@websanova/vue-auth/drivers/auth/bearer.esm.js' in 'C:\Projets\weddingproject\resources\js\_services\config'
 @ ./resources/js/_services/config/plugins.js 3:0-72 8:8-18
 @ ./resources/js/_services/config/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/_services/config/plugins.js
Module not found: Error: Can't resolve '@websanova/vue-auth/drivers/http/axios.1.x.esm.js' in 'C:\Projets\weddingproject\resources\js\_services\config'
 @ ./resources/js/_services/config/plugins.js 4:0-74 9:8-17
 @ ./resources/js/_services/config/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

**Comment by shqnks** [comment]
Ok it's because you forgot the /dist directory in Axios and Bearer paths.

Now I have no npm error, but the initial problem is still the same

**Comment by shqnks** [comment]
FIXED ! My all issue was a case problem.

I didn't uderstood that in the whole plugin, Vue.router is needed and it was impossible to use Vue.Router as I usually did

I'm sorry for the time you lost with me

**Comment by amanpatel** [comment]
I had the same issue. I was using this import,
```javascript
//import VueAuth from '@websanova/vue-auth';
```

but the correct import is this:

```javascript
import VueAuth         from '@websanova/vue-auth/src/index.js';
```

Worked like a charm!

**Comment by shqnks** [comment]
> I had the same issue. I was using this import,
> 
> ```js
> //import VueAuth from '@websanova/vue-auth';
> Vue.use(VueAuth, {
>   auth: ...,
>   http: ...,
>   router: ...
> });
> ```
> 
> but the correct import is this:
> 
> ```js
> import VueAuth         from '@websanova/vue-auth/src/index.js';
> Vue.use(VueAuth, {
>   auth: ...,
>   http: ...,
>   router: ...
> });
> ```
> 
> Worked like a charm!

My problem is hat I was used to write Vue.Router and the plugin expects Vue.router x)
Thanks for your reply tho, mayble it would help people who have the same issue as you had
