### ISSUE TITLE
Expected Bearer Token, but sending X-XSRF-TOKEN

### ISSUE THREAD

**Issue by shqnks** [websanova/vue-auth#577]
Hi,

I'm trying to use the default login method

My credentials work, I have my access_token inside my local_storage in browser, it's cool.

Now it's the second API automatic call that fails:

```
GET [my_api]/api/auth/user 401 (Unauthorized)
```

And when I use my Api from Postman, if I put the User's token as a Bearer header, it works.

I've inspected my Request headers and I've found a "X-XSRF-TOKEN" key where the token is. I think it's not sending a Bearer token (i'm not an expert at all, I try to understand the whole knowledge package).

Do you have a solution ? I can't figure out on the documentation how I can send my token as a Bearer token

**Comment by websanova** [comment]
Check your CORS headers

**Comment by shqnks** [comment]
I can access to my API since the logging is successfull

https://stackoverflow.com/questions/51426683/how-to-test-cors-header#:~:text=You%20can%20test%20it%20with,can%20check%20request%20and%20response.

According to the answer to this post, I would have a javascript error that would tell me if I can't reach the API, right ?
(And my font-end and back-end are on the same domain)

**Comment by websanova** [comment]
Well, can you send some examples of what your headers look like went sent with the plugin, when you're doing it manually in postman.
