### ISSUE TITLE
refresh tokens

### ISSUE THREAD

**Issue by narwy** [websanova/vue-auth#578]
Hi,

I've creating a JWT auth driver atm, my response would be:

```
{
    "token_type":"Bearer",
    "access_token":"JWT_HERE",
    "expires_in": 20,
    "refresh_token":"fdb8fdbecf1d03ce5e6125c067733c0d51de209c"
}
```

How can I tie the refresh token into the driver, is there any support for this at all?

So if you've got a refresh_token set and the response is a certain 401 and then you can invoke a new token request using the refresh token? TIA

**Comment by websanova** [comment]
Did you check the drivers guide?

https://websanova.com/docs/vue-auth/guides/drivers

**Comment by AndreasElia** [comment]
Refresh tokens via refresh:

https://websanova.com/docs/vue-auth/methods/examples#refresh

**Comment by narwy** [comment]
@websanova What am I looking at because I can't see anything in the docs on how to build a driver to support refreshing? I know it's a method but how do you even set a refresh token then? 

![where](https://user-images.githubusercontent.com/32820112/88460319-49afe500-ce93-11ea-8a1e-6b5558927d8c.PNG)

**Comment by AndreasElia** [comment]
@websanova In this case, I think an auth driver example would be beneficial for Auth0 to show how you can overwrite the refresh method or whatnot in a driver to utilise a returned refresh token.

**Comment by narwy** [comment]
@AndreasElia I agree, Laravel passport for example, returns `refresh_token` as a response, how can I set that in a driver, so if the token expires I can use this refresh token to generate another JWT for example. Any guidance would be grateful @websanova thanks in advance.

**Comment by websanova** [comment]
Is your app sending back two tokens on login?

**Comment by websanova** [comment]
You really should be able to just write your own driver and look at one of the examples listed in the guide linked above.

You can store/parse whatever you like and just put some logic around it. For instance if it's two tokens just return them with a pipe between and parse accordingly.

And of course in a request you can put conditions on which token to use of there are more than one based on request url.

@narwy  you are welcome to submit a pull request for any other drivers you feel are common enough ;-)

**Comment by narwy** [comment]
Hi @websanova,

I can get the login working it's just when a token expires and gets a response I want to use the refresh_token to generate a new access token. I've no idea how to build a driver around that refresh method. Any advice on this would be grateful. Thanks

**Comment by websanova** [comment]
Ok, well I would

1) setup custom driver to store/parse both tokens.
2) setup an http intercept in your app to check for that refresh response, assuming the API is giving some proper error code for that.

Otherwise, I wouldn't wait for the app to send an error, I would just auto refresh the token in some time interval, which the plugin already handles.

**Comment by AndreasElia** [comment]
Hey @websanova, just been following this issue out of curiosity.

An auth driver example would be great of something like Auth0 where when you login you are returned both an `access_token` and `refresh_token` as from what I'm understanding here you are suggesting putting two tokens together and then splitting them in a custom drivers request function? Then I think you're saying to store the tokens together and then access the one you need from storage in the response function. On top of that, the refresh function would be overwritten and this would append the refresh token.

I'm not sure I'm totally following this correctly?

**Comment by AndreasElia** [comment]
I see a similar issue has been discussed before with no real outcome for this sort of situation #440

**Comment by narwy** [comment]
@websanova Can you explain where in the plugin the auto refresh is handled? Is this just recalling a endpoint with the token expecting a new token being returned and not using any form of `refresh_token` I'm a bit lost with the documentation I find it a bit hard to navigate and read. Do you have any working concept, before vue-auth I would use a axios interceptor before each request and if I got back a token expired I would renew that token using a `refresh_token` (oauth2 RFC) and invoke a new `access_token` to be generated from that (JWT)

**Comment by websanova** [comment]
So, you're over thinking it a bit, the plugin is just a wrapper around vue-router and vue-resource/axios/etc, nothing special going on there really.

So step 1 is you simply need to store the tokens right:

https://github.com/websanova/vue-auth/blob/master/drivers/auth/basic.js

So if you take a look at the existing driver and simply rewrite it:

```
export default {
    
    request: function (req, token) {
        var token = (token || '').split('|');

         // send back your token in the req however you like....

         // I would imagine here you could also put an if condition that would not require any token parsing on the intercept.

         if (/// uri for refresh)
            // use token1
         else
            // use token2
    },
    
    response: function (res) {
        
        // get token from res however you like
        
        return token1 + '|' + token2;
    }
};
```

2) As for the intercept, you can use axios, or whatever you normally use, just write some normal intercept logic that checks for your specific error condition and simple initiates another request. The plugin "should" handle the rest. If you need access to the token simply use `$auth.token()` and parse out whichever you need.

Not sure it needs to get more complicated than that.

**Comment by AndreasElia** [comment]
Thank you for clearing that up @websanova!

**Comment by narwy** [comment]
Yeh thanks @websanova I was getting confused with `this.$auth.refresh()` appreciate it

**Comment by narwy** [comment]
Just a quick one when writing drivers is there a way to detect in the driver what request driver vue-auth is using at the time, i.e axios, vue-resource etc, because if we write interceptors they will vary

**Comment by websanova** [comment]
@narwy huh?

You have both axios and vue-resource installed?

I mean....it's using whichever driver you set during the plugin install

**Comment by narwy** [comment]
@websanova I'm thinking if we start uploading plugins to this repo, is there a way we can detect the request drivers, axios, vue-resource etc when making drivers for people to use.

**Comment by websanova** [comment]
@narwy not really sure what you're asking.

As for the drivers, they are set manually during the pluign install, no need to auto-detect anything.
