### ISSUE TITLE
Vue auth not working after calling login method programmatically inside success of another method.

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [websanova/vue-auth#581]
I have an option for admin, which create user account, system send a verification email,  and once user clicked, he is redirected to set his password. Now after password is set i want to automatically login the user.  Every thing works except redirection after login to the dashboard or any where else, removed the token, and auth middleware redirect back to the login page.

` 

     async setPasswordAndLogin() {
      this.isLoggingIn = true;
      this.errors = [];
      this.isloading = true;
      let data = {
        email: this.email,
        password: this.password,
        password_confirmation: this.confirmPassword
      };
      await axios
        .put(config.BASE_URL+"auth/set-password", data)
        .then(res => {
          this.otp = false;
          this.login();
        })
        .catch(err => err)
    },
    login() {
      this.isLoggingIn = true;
      this.errors = [];
      this.isloading = true;

      this.$auth.login({
        data: {
          email: this.email,
          password: this.password
        },
        rememberMe: true,
        fetchUser: true,
        redirect: null,
        remember: "Rob",
        staySignedIn: this.rememberMe,
        success() {
          this.isLoggingIn = false;
          this.isloading = false;

          let authUser = this.$auth.user();
          console.log(authUser, "Auth");
          Vue.store.dispatch("setUser", { ...authUser });
       
          this.redirectUser();
        },
        error(error) {
         
        }
      });
    },
    redirectUser() {
      let uri = "admin";
      if (this.isBusiness || this.isBusinessMember) {
        let isProfileNotCompleted = this.isBusiness
          ? !this.$auth.user().business.profile_completed
          : !this.$auth.user().colleague_business.profile_completed;
        uri = isProfileNotCompleted ? "bra/application" : "my-posts";
        if (this.$route.query.redirect_url) {
          uri = this.$route.query.redirect_url;
        }
      } else if (this.$auth.user().perms.includes("Freelancer")) {
        uri = !this.$auth.user().profile_completed
          ? "fra/application"
          : "my-posts";
        if (this.$route.query.redirect_url) {
          uri = this.$route.query.redirect_url;
        }
      }
      window.location.href = window.location.origin + "/" + uri;
    },
`

**Comment by websanova** [comment]
Well your `redirect` is set to `null` and you're not showing your `redirectUser` function so can't really comment much there.

**Comment by Mobasher-NetLinks** [comment]
Updated the issue, that redirect routes have `meta: {auth: true}`

**Comment by websanova** [comment]
ah ya, no idea what you're doing there.

Maybe try a `$router.push` instead of href redirect like that...bit strange.

**Comment by Mobasher-NetLinks** [comment]
Yeah this `window.location.href` was the reason, but why it works in login page ?

**Comment by websanova** [comment]
Not really sure, I mean who knows what you got going on there with that redirect...

Why are you using a `window.location.href` instead of a regular `router.push`? Is the url changing or something?

**Comment by Mobasher-NetLinks** [comment]
Because I have different panels for users based on rule, an admin panel design is different from normal user,  to avoid any css conflict when user switching to another account, I tried to reload the whole page to avoid design conflict issues.

**Comment by websanova** [comment]
Sure, so it's a different url?

**Comment by Mobasher-NetLinks** [comment]
Yeah based on user role it will redirect user to their dashboard page

**Comment by websanova** [comment]
Right, so if it's a different url, the token won't exist there.

You would need to redirect with the token as a param and then store it again manually, which you could do with `$auth.token()`.

**Comment by websanova** [comment]
clsoing due to inactivity.
