### ISSUE TITLE
Login with 401 response status results in "Uncaught (in promise) Error"

### ISSUE THREAD

**Issue by straurob** [websanova/vue-auth#582]
### Version
vue-auth@^3.2.0-beta with axios as http driver

### Sample code
```
this.$auth.login({ data: body, redirect: false }).then(
async () => {
    // Do success stuff...
},
(e) => {
    this.error = true
    if (e.response.status === HttpStatus.UNAUTHORIZED) {
      this.loginFailed++;
    }
});
```

If the user provides invalid credentials, the server responds with a 401 and an error message is shown. This is working as it should.

When inspecting the console though, then I see the following error message. It does not seem to have any "functional consequence" but I'm wondering why this error is thrown.

```
Uncaught (in promise) Error: Request failed with status code 401
    createError createError.js:16
    settle settle.js:17
    handleLoad xhr.js:61
    dispatchXhrRequest xhr.js:36
    xhrAdapter xhr.js:12
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    wrap bind.js:9
    node_modules axios.1.x.js:51
    node_modules vue-auth.esm.js:819
    node_modules vue-auth.esm.js:818
    node_modules Login.vue?vue&type=script&lang=js&:149
    VueJS 4
    method backend.js:1793
    node_modules UAForm.vue?vue&type=script&lang=js&:12
    submit UAForm.vue:13
    VueJS 33
createError.js:16

```

**Comment by websanova** [comment]
Why do you have `async` in front of your success callback?

**Comment by straurob** [comment]
Sorry, I commented out too much from the code. The success callback triggers several REST calls to the backend like this:

```
await Promise.all([
  this.loadUserConfig(),
  this.checkCart()
]);
```

**Comment by websanova** [comment]
Can you isolate it at all, really no idea from what you're posting here.... it's quite random code.

**Comment by straurob** [comment]
The problem is that I can't share too much of the surrounding code. I'll try to provide a minimal reproducible example...

**Comment by websanova** [comment]
are you returning some promise to a component event?

I think I seen some errors like that doing `@change="myfunc"` where my func returns a promise and is otherwise behaving normally.

**Comment by straurob** [comment]
As far as I can tell, no but I'll further have a look into that direction.

I found an older issue (#552) for the v2 but it has been closed. From what the reporter described, the "symptoms" were pretty similar.

**Comment by lik-alive** [comment]
Encountered this issue with the axios.1.x driver (the same for frisbee.1.x):
```
http: function (data) {
    var http = this.Vue.axios(data);
    http.then(data.success, data.error);    // the first branch
    return http;                            // the second branch
},
```
Here we have two branches of Promises. The complication is that we have to handle one exception (server response with error status code) two times:

```
Vue.auth.login({
    ...
    error: () => {...},   // the first handler
    ...
}.catch(() => {...}).     // the second handler
```

Both handlers are mandatory to prevent the error appearance in console (but the first one may be left empty `() => {}`).

P.S. The demo example suffers from the same problem, so... may be one handler is enough (e.g. `return http.then(...)` in drivers)?

**Comment by websanova** [comment]
Hmm, would have to test a bit, but the drivers are not meant to handle any logic, they just use as is and return, so if that's a thing with axios then it should be handled accordingly.

**Comment by websanova** [comment]
I just did some tests with 401 and 403 response in the demo, I don't see the issue you're describing at all anywhere with any of the drivers.

**Comment by lik-alive** [comment]
I've checked the last version 3.2.2-beta: Then, Redirect and Default methods work great now, the problem with 401 and 403 responses is solved.

P.S. Vuex method also works, but only after a small fix in "store/auth.js":
```
login(ctx, data) {
...
    body: this.form.body, // VueResource
    data: this.form.body, // Axios
...
}
register(ctx, data) {
...
    body: this.form.body, // VueResource
    data: this.form.body, // Axios
...
}
```
In both functions `this.form.body` should be replaced with `data.body`.

**Comment by websanova** [comment]
ok, great!
