### ISSUE TITLE
$auth.user() returns {} after refresh

### ISSUE THREAD

**Issue by jongbonga** [websanova/vue-auth#583]
Hi @websanova 

I've investigated most of the issues with the same problem without success.

I am using Auth0 to retrieve my access token, then manually store it using `$auth.token(null, accessToken, false)` **(works 100%)** 
Then I manually sett the user data with `$auth.user(userObject)` then I navigate to the main page and display user data with `$auth.user()` , also working fine until I refresh the page ... then I get `{}`.

I noticed you asked everybody if they were using `$auth.ready()` before setting the user data... I do!
```
<div id="app" v-if="$auth.ready()">
    <router-view />
</div>
```

but still experiencing the same behavior... :(

**Comment by websanova** [comment]
Well, you refreshed the page, so the data is gone and needs to be set again...

The only thing that gets stored locally is the token, not the user data, so seeing as you're taking a more manual approach you would need to fetch your user data on load in your app.

**Comment by jongbonga** [comment]
I was under the impression that user data was also stored in an internal state management or so.

Thank you for clarifying.
