### ISSUE TITLE
Vue auth login method's success is not working even server returning 200

### ISSUE THREAD

**Issue by saadkamaal** [websanova/vue-auth#588]
`login() {
        // get the redirect object
        var redirect = this.$auth.redirect()
        var app = this
        this.$auth.login({
          data: {
            UserName: app.email,
            Password: app.password
          },
          success: function() {
            
            const redirectTo = redirect ? redirect.from.name : this.$auth.user().role == 1 ? 'admin.dashboard' : 'dashboard';
            this.$router.push({name: redirectTo})
         
          },
          error: function() {
            app.has_error = true
            console.log('error')
          },
        
          staySignedIn: true,
          fetchUser: true
        })
      }`

**Comment by websanova** [comment]
What version are you using?

Since v3 it switched to promise so `success` callback won't do anything.

**Comment by saadkamaal** [comment]
Thanks alot i was using v3 or greater, working now
