### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by diegolinhares** [websanova/vue-auth#591]
When I sign out and I try to sign in again with correct credentials, sometimes I'm getting a devise error saying that my email or password is wrong. But, they are correct. So, I saw my browser session's storage with the token information. I suppose this is responsible for my error, but I don't understand why. Could you help me to solve that? I'm using version 3 and sending my plugin configurations:

```
export default Vue.use(auth, {
  auth: authBasic,
  http: httpAxios,
  router: routerVueRouter,

  registerData: {
    url: RESOURCE_URL,
    method: 'POST',
    fetchUser: true,
    staySignedIn: true,
    redirect: '/finishedSignUp'
  },

  loginData: {
    url: `${RESOURCE_URL}/sign_in`,
    method: 'POST',
    redirect: '/home',
    fetchUser: true,
    staySignedIn: true
  },
  logoutData: {
    url: `${RESOURCE_URL}/sign_out`,
    method: 'DELETE',
    redirect: '/',
    makeRequest: true
  },

  refreshData: {
    url: `${RESOURCE_URL}/validate_token`,
    method: 'GET',
    enabled: true,
    interval: 30
  },

  fetchData: {
    url: `${RESOURCE_URL}/validate_token`,
    method: 'GET',
    enabled: true,
    interval: 30
  }
}
```
Thanks.

**Comment by websanova** [comment]
Well if the apo is having issues with the login I think it's best to isolate that issue first and test with postman/insomnia directly to the API.

**Comment by diegolinhares** [comment]
Hi, thanks for answering me.

I think this is my problem https://websanova.com/docs/vue-auth/recipes/setting-stay-signed-in-to-false-is-broken.

The problem is: if I'm logged in when I sign out and try to register a new user using my sign up form, in the end, I have to be redirected and logged in to a view. This isn't working because I think I already have the token information from the first user in session storage, I think there's a conflict.

When I close the browser and try to register another user again, it works perfectly. But, if I try to register another it doesn't work.

Do you have a suggestion for work with this approach?

Thanks for your time.

**Comment by websanova** [comment]
Not really sure, but did you check the options on login and register such as `fetchUser` and `autoLogin`?

**Comment by diegolinhares** [comment]
I'm not using the autoLogin option for register. I made a test and set it to true.

After, I get some problems with my parameters, because I don't have a field password and password confirmation in my sign up form. The password is generated by the backend and sent by e-mail. So, I think this is the problem, to use autoLogin.

Besides, after I register someone, I redirect it to a page that uses a dashboard with the check() and user()methods to retrieve some data from user as his name, for example.

Do you have any suggestions?

Thanks

**Comment by websanova** [comment]
autoLogin is already true by default, did you try setting it to false?

**Comment by diegolinhares** [comment]
Yes, I set to false. It works perfectly.

This app has the following case of use: I have to let a user sign up, but in the signup form, I don't have fields to ask for a password or password confirmation. After the user provides all information in the form and submits If all it's okay I have to auto-login him and redirect to a view.

The problem is: password is generated by the backend and sent by email. To use the autoLogin option from the plugin, I need to have the password field in the signup form, I think. Because the autoLogin option uses the same params to send a second request after the user signs up, correct me if I'm wrong, please. But, for my use case, I think this isn't possible.

May, you have suggestions?

Thanks.

**Comment by websanova** [comment]
You're over thinking it. The plugin just preforms http requests so you can send whatever you want as long as you send back a token.

So you can send a request with no paramus for all it cares. In your case just take an email and send back a token on login.

They will get a session and next time they will use the password that's emailed.

**Comment by diegolinhares** [comment]
So, after I logout, I'm being redirected to the same page. I have some requests on this page. When I print their response headers, the devise headers are present. So, I think this is the problem. Besides, my session storage have the tokens too.

I'm using the option for make request as true to logout method.

Do you have any suggestion?

**Comment by websanova** [comment]
You did `$auth.logout()`?

**Comment by diegolinhares** [comment]
> 
> 
> You did `$auth.logout()`?

Yes. I'm using the devise-token-auth gem in my back end. 

I set the log out to make the request. After I logout, the session storage doesn't have the tokens. When I refresh the page, the tokens are in the session storage. Some request to validate token on refresh is done.

My stay signed in is set to true.

**Comment by websanova** [comment]
can you show your logout code?

**Comment by diegolinhares** [comment]
> 
> 
> can you show your logout code?

Sure.

`      this.$auth.logout({makeRequest: true}).then(() => {
        console.log('success')
      }, () => {
        console.log('error')
      })`

**Comment by websanova** [comment]
And can you confirm a request is being sent?

**Comment by diegolinhares** [comment]
Yes. I logout and after the second refresh I did, this message was present in the console

XHRGEThttp://localhost:3000/user_auth/validate_token
[HTTP/1.1 401 Unauthorized 35ms]

Uncaught (in promise) Error: Request failed with status code 401

**Comment by websanova** [comment]
Well, I have no idea about your application.

But you should see something in the console with the request actually being sent successfully, it will only then clear out the token.

What your're showing me some output from the server side I guess, and does seem to show a 401 error.

**Comment by diegolinhares** [comment]
So, after two weeks. I found the problem. It was an endpoint problem in my API with the gem Cancancan.

Thank you for your help. You give me so many clarifications about your plugin.

Your plugin is awesome! :))

**Comment by diegolinhares** [comment]
So, I have one more doubt. After I sign up, using autoLogin, why I'm getting some token at the storage?

`      this.$auth
        .register({
          data: { user: this.user },
          fetchUser: true,
          staySignedIn: true,
          autoLogin: true,
          redirect: "/",
        })
        .then(..`

**Comment by websanova** [comment]
https://websanova.com/docs/vue-auth/guides/tokens
