### ISSUE TITLE
Is it possible to add Changelog  for version 3.3.x

### ISSUE THREAD

**Issue by service-paradis** [websanova/vue-auth#593]
Currently, there are no changelog for version 3.3.x. It would be great to have an idea about changes that were made before updating.

Thanks!

**Comment by websanova** [comment]
Hmm, maybe because there was nothing to note ;-)

Just some updates in the demo and packages, perhaps doesn't warrant a minor version change. Anyway you can always check the commit log

https://github.com/websanova/vue-auth/commits

**Comment by service-paradis** [comment]
Thanks for the reply :). I checked the commit log and did not see any relevant changes. But I wanted to be sure that I did not miss something since there were minor releases.
