### ISSUE TITLE
"auth" driver not set, but it is.

### ISSUE THREAD

**Issue by giekus** [websanova/vue-auth#594]
Hi, I have used this package in various projects and it works perfectly, but today I have faced an issue. The following code throws me an error that auth driver is not set:

```
import auth from '@websanova/vue-auth'
import bearerDriver from '@websanova/vue-auth/drivers/auth/bearer.js'
import httpDriver from '@websanova/vue-auth/drivers/http/axios.1.x.js'
import routerDriver from '@websanova/vue-auth/drivers/router/vue-router.2.x.js'

Vue.use(auth, {
  auth: bearerDriver,
  http: httpDriver,
  router: routerDriver
})
```

I've tried to install earlier version "2.x-beta" and it is working with the same exact code, what is wrong here? I have looked through the information provided but did not see any changes in the setup recently.

Thank you.

**Comment by websanova** [comment]
Version 3 has a bit different setup, check the startup guide.

https://websanova.com/docs/vue-auth/guides/startup#setup
