### ISSUE TITLE
Provided devise driver doesn't work with cookies

### ISSUE THREAD

**Issue by mammuth** [websanova/vue-auth#595]
The [devise driver uses `;` as a delimiter ](https://github.com/websanova/vue-auth/blob/master/drivers/auth/devise.js#L10)between the different token parts. This works perfectly fine when storing the resulting string in `localStorage`, but cookie values aren't allowed to contain the `;` character (at least on Chrome).

As a result, the provided devise auth isn't correctly storing the received token in the cookie.

For anyone experiencing this issue, copy out the devise driver, use another delimiter when splitting/joining the token, and then use your custom driver with VueAuth.

**Comment by websanova** [comment]
Alright, this has been updated to use a pipe instead, version `3.3.4`.
