### ISSUE TITLE
Redirect Back To Page After Login Doesn't Change URL

### ISSUE THREAD

**Issue by nimashoghi0** [websanova/vue-auth#597]
Hey there,

First off I'd like to thank you for such an awesome JWT plugin.

I'm facing one issue though, I have a route with a router url parameter like so: website/3/view. When I hit this url without being logged in, I am redirected to the login page as expected. When I log in, I get redirected back to the page, but it fails as the URL doesn't get changed. If I hit a page that doesn't have a url parameter, it works as expected, however the URL still doesn't get changed.

Is this a bug or done this way on purpose ? I hope this can be resolved easily, as this is a showstopper for my application. (People are given links outside the app with url parameters set).

I look forward to hearing back from you with your thoughts,

Thanks heaps
Alex

**Comment by websanova** [comment]
Not really sure I fully understand the issue, would be better to provide some fuller examples of the urls, what's happening and expected outcome.

Otherwise, did you check the `$auth.redirect()` function?

**Comment by nimashoghi0** [comment]
Let's say you hit a url on your app that requires authentication, for example: www.app.com/website/:id/
User is not logged in so you're redirected to the login page www.app.com/login
After you have logged in vue-auth attempts to redirect you back to www.app.com/website/:id, however, the URL doesn't get updated so router.js can't see the paramater.

If I test this using a url that doesn't have a url parameter, the correct route view shows, but the url is in the urlbar is not updated, but rather shows www.app.com/ not www.app.com/**page**

I hope this makes it a little more clear.

**Comment by websanova** [comment]
Right, so did you try `$auth.redirect()` method?

"After you have logged in vue-auth attempts to redirect you back to"

So, vue-auth doesn't attempt to do anything, it just sends you to whatever the "redirect" parameter is set to which by default is just "/", you can see that in the src [here](https://github.com/websanova/vue-auth/blob/master/src/auth.js#L35). So you just need to set the redirect to that previous path/route.

As a little bonus, vue-auth does include a `$auth.redirect()` shortcut method exactly for this, which gives you the `to/from` params from vue-router which you can use if you like for the redirect after login.

Also, if you're getting an "error out" on your router, then something else is up with your app, not the plugin, you should definitely have a catch all for a 404 in those kind of scenarios.

Seems more of an issue with your routing than vue-auth. All vue auth does after a successful login is a `$router.push()` if redirect is not set to `null`.

**Comment by nimashoghi0** [comment]
Hey Rob,

I implemented the authentication quite a while ago that I forgot how the redirect mechanism worked. Sorry, I thought it redirected out of the box but I see the redirect line in both my code and also in your example. $auth.redirect() is exactly what I need.

Truly sorry to occupy your time with a silly query, but thank you so much for guiding me in the right direction 👍 

Have a great day, and thanks for getting back to me so quickly,

All the best,

**Comment by nimashoghi0** [comment]
You know what the strangest thing is - the router push (this.$router.push(redirectTo);) is working as expected everywhere on my project, however, when used in the login success handler, the url isn't updating, however the correct view is shown.

Very strange, any idea's on why this may be happening ? Does it usually work with the url updating ?

**Comment by websanova** [comment]
All good :-)
