### ISSUE TITLE
RefreshToken is not working on the first login

### ISSUE THREAD

**Issue by dubov94** [websanova/vue-auth#6]
If user has never logged in before then the condition on the line 143 is falsey. Since fetch() is the only external place where _refreshToken() is called an updating timer will never be set.

By the way, do you have any plans on covering the library with tests? The codebase is fairly large and complicated already.

**Comment by websanova** [comment]
It needs quite a bit of stuff, testing definitely one of them, no time for now though.

**Comment by websanova** [comment]
Should be all good in new `v1.0.x-dev` version.
