### ISSUE TITLE
set watcher on $auth

### ISSUE THREAD

**Issue by oleg-nogin** [websanova/vue-auth#60]
Hello again :)

How can I implement watcher on $auth to call methods only when auth.ready()

like this
```
watch: {
   '$auth': {
      handler() {
         this.method.from.anywhere
      },
      deep: true
   }
}
```
i have tried:
1. 'window.vue.$auth' (where vue is mounted application)
2. 'this.$auth'
3. '$auth.ready'
and nothing =(

**Comment by websanova** [comment]
you can just do it in the component <div v-if="$auth.ready()"></div>

**Comment by oleg-nogin** [comment]
@websanova 
it's not the correct way to set watch elements
for example, i can write 
```
watch: {
   '$route': {
      handler() {
         this.method.from.anywhere
      },
      deep: true
   }
}
```
and every time when route will change component will launch this.method.from.anywhere

**Comment by oleg-nogin** [comment]
@websanova 
do you have any ideas about this problem? :)

**Comment by websanova** [comment]
Well in this case the ready is a one off. As a watch you would need to
access the data directly. Just console out $auth. I think it should be
$auth.loaded.

**Comment by websanova** [comment]
Sry, should be in `$auth.watch.loaded`.

Any luck with this?

**Comment by oleg-nogin** [comment]
@websanova 

nice hook, it works now. thx =)
