### ISSUE TITLE
TypeError: Cannot read property 'beforeEach' of undefined

### ISSUE THREAD

**Issue by Msangi21** [websanova/vue-auth#600]
Hello @websanova , I have installed a fresh "@websanova/vue-auth": "^3.3.8" on my vue project after follow the docs I getting the above error "TypeError: Cannot read property 'beforeEach' of undefined", which found in this file "vue-router.2.x.esm.js"

**Comment by websanova** [comment]
Did you install Vue.router befor vue auth?

**Comment by Msangi21** [comment]
Yes

**Comment by Msangi21** [comment]
@websanova now I run like this 
npm i @websanova/vue-auth vue-router vue-axios axios es6-promise

**Comment by websanova** [comment]
Ah no the package order doesn't matter. I mean installation of the plugin in the app.

Did you check the docs or demo app at all?

**Comment by Msangi21** [comment]
I was miss `Vue.router = router;`
