### ISSUE TITLE
What a simple flow for token auth

### ISSUE THREAD

**Issue by igorbelikov** [websanova/vue-auth#601]
Hi, can you describe please a simple flow for token auth?

I have endpoint which return access token `access_token` after success pair login/password and what I should do next? I try to call a login method and check promise `then`, but as I see — in promise I see result of `fetchUser` without Authorization header. 😭 

Maybe I should set `fetchUser: false`, call login method, after set `token(null, token_from_response)` and next check `fetchUser: this.$auth.token() !== null`?

**Comment by websanova** [comment]
Well depends

1. What auth driver are you using?
2. How is the token being sent back from your api on login success?

**Comment by igorbelikov** [comment]
Thank you for quick response.

1. Bearer;
2. Json response, like this:
```
{
  ...
  "data": {
    "access_token": "..."
  },
  ...
}
```

**Comment by websanova** [comment]
The token would need to be in authorization header for that driver to work. Or create a custom driver to handle it in body.

**Comment by igorbelikov** [comment]
@websanova that is, I have to add it token in the response in the header and then it will be automatically recorded?

**Comment by igorbelikov** [comment]
@websanova great, I did it, thanks! 😄

**Comment by handhikadj** [comment]
@igorbelikov can you share the snippet of how you fixed it?
