### ISSUE TITLE
Success on fetchData and refreshData not being called

### ISSUE THREAD

**Issue by GMolini** [websanova/vue-auth#602]
Ive upgraded from 3.1.5 beta to 3.3.8 and and the success and error callbacks defined in main.js are not being called

```
    fetchData: {
      url: '${apiEndpoint}/auth/fetch',
      method: 'GET',
      enabled: true,
      success: (response) => {
        // Do Some things
      },
      error: () => {
        // Handle fetch errors
      },
    },
```

If this isnt a bug but a new design feature, how are we supposed to define the generic callbacks of this functions?  Thanks.

**Comment by websanova** [comment]
Hmm, ya that was removed a while ago, Perhaps it needs to be added back...

I guess the only scenario where does happens automagically is with login/register though...

So really, you could just set fetchUser to false and then call it manually after login...

```
this.$auth.login({
    fetchUser: false,
})
.then(() => {
    this.$auth.fetch().then(/* logic here */);
})
```

Probably cleaner that way anyway rather than hiding it in the plugin config somewhere...

**Comment by GMolini** [comment]
But it isnt the only scenario, is it? If I reload the page, only fetch will be called, isnt it?

**Comment by websanova** [comment]
Are you just trying to parse the user data?

**Comment by GMolini** [comment]
yes, but i want to be able to watch for changes. thats why i was doing it on the callback

**Comment by websanova** [comment]
Well there is a parse function provided for that.

As for a watch did you try watching the user object?


computed: {
    auth: { return this.$auth(); }
},

watch: {
    auth {
         // Do some.stuff
    }
}

**Comment by GMolini** [comment]
Ok, so, ive tried that, and it should work... but im not sure why the user object is not being set. I see in the network panel the request being made and the response, but the user object is empty

**Comment by websanova** [comment]
Well, what do you mean by empty, null, undefined...?

Also, can you show what you're doing and perhaps do a bit of your own digging with some console log(this.$auth). It's just a single instance in there, not hard to poke around ;-)

**Comment by GMolini** [comment]
I mean empty,

If I do this after logging in

```
      console.log(this.$auth);
      console.log(this.$auth.user());
      console.log({ ...this.$auth.user() });
      console.log(this.$auth.check());
```

This is what gets printed in the console:

![image](https://user-images.githubusercontent.com/1327783/97699168-fc529d80-1aa9-11eb-9802-3dd4f86b38f9.png)


I dont understand why $auth.check returns true but theres no user object.

**Comment by websanova** [comment]
Well, how are you sending back your user data? Maybe have to parse it if it's not using the default

**Comment by GMolini** [comment]
Its a json with the form:

```
{
  "user": {
      "company": "blabla",
      "name": 'blabla"
}
```

and so on, but Ive tried returning it without the "user" tag, and it didnt work either
```
{
   "company": "blabla",
    "name": 'blabla"
}
```

**Comment by GMolini** [comment]
Well, yeah, it is something in the parsing. But im not sure why its giving problems. If I add the following option to the initializer:

```
  parseUserData(data) {
    return data;
  },
```
It works perfectly

**Comment by websanova** [comment]
A quick look at the source will show what parseData method is doing...

https://github.com/websanova/vue-auth/blob/master/src/auth.js#L138

So either put your user data in the expected data object or override parse to return your user object.

**Comment by GMolini** [comment]
Ok, thank you very much
