### ISSUE TITLE
"auth" driver must be set + Cannot read property 'interceptor' of undefined

### ISSUE THREAD

**Issue by gacekm** [websanova/vue-auth#604]
Hi, sorry, new by in your lib, i thx for your works.

I use vuejs + quasarjs and i try to implement your lib for auth.

i implement in route/index.js
import Vue from 'vue'
import VueRouter from 'vue-router'
import store from './../store/index'
import { sync } from 'vuex-router-sync'
import routes from './routes'

Vue.use(VueRouter)

Vue.router = new VueRouter({
  /*
   * NOTE! Change Vue Router mode from quasar.conf.js -> build.env.VUE_ROUTER_MODE
   *
   * If you decide to go with "history" mode, please also set "build.publicPath"
   * to something other than an empty string.
   * Example: '/' instead of ''
   */

  // Leave as is and change from quasar.conf.js instead!
  mode: process.env.VUE_ROUTER_MODE,
  base: process.env.VUE_ROUTER_BASE,
  scrollBehavior: () => ({ y: 0 }),
  routes
})

// Sync Vuex and vue-router;
sync(store, Vue.router)

import axios from 'axios'
import VueAxios from 'vue-axios'

axios.defaults.baseURL = 'http://...'

Vue.use(VueAxios, axios)

import auth from '@websanova/vue-auth'
import authBasic from '@websanova/vue-auth/dist/drivers/auth/basic.esm.js'
import httpVueResource from '@websanova/vue-auth/dist/drivers/http/vue-resource.1.x.esm.js'
import routerVueRouter from '@websanova/vue-auth/dist/drivers/router/vue-router.2.x.esm.js'
import oauth2Google from '@websanova/vue-auth/dist/drivers/oauth2/google.esm.js'
import oauth2Facebook from '@websanova/vue-auth/dist/drivers/oauth2/facebook.esm.js'

oauth2Google.params.client_id = 'GOOGLE-OAUTH2-CLIENT-ID'
oauth2Facebook.params.client_id = 'FACEBOOK-CLIENT-ID'

Vue.use(auth, {
  auth: authBasic,
  http: httpVueResource,
  router: routerVueRouter,
  oauth2: {
    google: oauth2Google,
    facebook: oauth2Facebook
  },
  rolesKey: 'role'
})

export default Vue.router
 i get erro
![image](https://user-images.githubusercontent.com/5834314/97585679-b5a56a80-19f9-11eb-8f8d-10b1bef1544f.png)
 I use version 

  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "@websanova/vue-auth": "^3.3.8",
    "axios": "^0.18.1",
    "core-js": "^3.6.5",
    "quasar": "^1.0.0",
    "vue-axios": "^3.1.3",
    "vue-i18n": "^8.0.0",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "@quasar/app": "^2.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.1.2"
  },
  "browserslist": [
    "ie >= 11",
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }

**Comment by websanova** [comment]
Vue.router needs to exist before, check install guide

**Comment by gacekm** [comment]
I see definition VueRouter before @websanova/vue-auth.
I can't see the issue. Could you help me please?
