### ISSUE TITLE
Vue 3 compatibility

### ISSUE THREAD

**Issue by zorn-v** [websanova/vue-auth#606]
First of all there is no global Vue export (`"export 'default' (imported as 'Vue') was not found in 'vue'`), so we can not set `Vue.router` and `Vue.axios`
Next, even if we do something like
```js
const app = createApp(App).use(router)
app.axios = axios
app.router = router
app.use(VueAuth, {...})
```
we get `Uncaught TypeError: __auth.Vue is not a constructor` in `_initVm` function.

Check the docs how to write plugin for v3 https://v3.vuejs.org/guide/plugins.html
Use `app.config.globalProperties` for global instance proerties like `$auth` for example etc.
Also maybe pass router and axios as config options on `use`

PS. Instead of `new Vue` you can use `ref` (`import { ref } from 'vue'`) or `reactive` for objects from composition api 
https://v3.vuejs.org/guide/composition-api-introduction.html#reactive-variables-with-ref
https://v3.vuejs.org/guide/reactivity-fundamentals.html

**Comment by websanova** [comment]
As mentioned in pull request comments, I'll be working on it this week. I've already updated my vue-upload plugin to support v3 so just a matter of porting those changes over. There will be a v3 demo and doc updates as well, so I'll do that all in one batch.

Will keep this thread posted.

**Comment by websanova** [comment]
This should be good to go.

https://websanova.com/docs/vue-auth/upgrades/3x-4x

Not really much change other than the options format.
