### ISSUE TITLE
{auth:false} change behavior

### ISSUE THREAD

**Issue by biglanggwapoventures** [websanova/vue-auth#61]
As of the moment if you do something like
```js

{ 
      path: '/', 
      component: require('./components/LoginForm.vue'),
      name: 'login',
      meta: {auth: false},
},
```

on a route, the authenticated user trying to access this route will be redirected to a 404. Is there a way to change this behavior? I can't seem to find a solution based on the docs.

Help is greatly appreciated. Thanks!

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth#notfoundredirect-path-404

**Comment by biglanggwapoventures** [comment]
Thanks @websanova  for the quick reply.

What I wanted to do is make a redirect to /home if an authenticated user tries to access /login.
The 404 seems to be overkill for me.

**Comment by websanova** [comment]
You just wanna do it strictly for /login or pages like /register as well?

**Comment by websanova** [comment]
And did you try setting notFoundRedirect: '/home' ?

**Comment by biglanggwapoventures** [comment]
I just want the `/login` route to redirect to `/home` if the user is already authenticated. If I set `notFoundRedirect: '/home' ` then all 404s will go to `/home``and I do not want that behavior.

**Comment by websanova** [comment]
Ok, so in that case it's quite specialized behaviour, probably you will
need to write your own intercept and just place it before the auth plugin.
I believe you can still use this.$auth.ready() in the intercept.

**Comment by websanova** [comment]
Set, should be in $auth.watch.loaded.

**Comment by websanova** [comment]
Any luck with this?

Btw it's not redirecting all 404, just the cases where auth: false is trying to be hit will go to some default page. Again, if you want some specific case here for only "/login" to "/home" but everything else to the default "404", you would need to add your own intercept.
