### ISSUE TITLE
Token Refresh request

### ISSUE THREAD

**Issue by 5knnbdwm** [websanova/vue-auth#615]
Hey, 
I have the situation that in my login method I receive an `access_token` and a `refresh_token`. The `access_token` is valid for several minutes and the `refresh_token` is valid for several days. After the `access_token` is expired I need to request a new `access_token` with the `refresh_token`.

How would I do/manage that? At what step would I have to intercept calls and for what would I have to listen in the responses?

**Comment by websanova** [comment]
So you will likely need to setup a custom auth driver, probably similar to the devise driver.

https://github.com/websanova/vue-auth/blob/master/src/drivers/auth/devise.js

As with the expiry, the plugins doesn't have a way to check any explicit expiry. It just does a fresh on restart or on a timer to keep perpetuating the token expiry forward.

If you really wanted to get detailed you could maybe also store a timestamp in the token store, but probably not necessary.

**Comment by 5knnbdwm** [comment]
Ok thanks for the info. Don't know whether auth/devise.js will help me a lot. But it's good to know that there isn't a preferred way in the framework.

Will probably add the token expiry timestamp to the token, so that I don't have to check whether a request failed with a status code but just request a new `access_token` when the old one is expired and set and use that then to continue with the original request.
