### ISSUE TITLE
Make Google Auth in a new window?

### ISSUE THREAD

**Issue by kami4ka** [websanova/vue-auth#616]
Is it possible to open google auth in a new small window (like, I guess, google makes it via its own library)?

**Comment by websanova** [comment]
hmm, you mean open the oauth login on separate popup window rather than redirect?

**Comment by kami4ka** [comment]
@websanova yep, exactly
In the case of the current flow, Google Analytics shows google as a referrer when using Google Auth.

**Comment by websanova** [comment]
Ok, this has been updated in 4.1.0,

so you can now pass an optional window parameter like so...

```
this.$auth
    .oauth2({
        params: {
            client_id: 'FACEBOOK_CLIENT_ID'
            ...
        },
        remember: 'Rob',
        staySignedIn: true,
        fetchUser: true,
        window: {
            name: '_blank',
            specs: {},
            replace: false
        }
    });
```

**Comment by kami4ka** [comment]
@websanova oh, cool, thanks! I'll check it out!

**Comment by kami4ka** [comment]
I've checked it out - thanks for the feature! 
But looks like that redirect happens in the new window as well.
I think it will be more convenient to pass the redirect inside the parent window, so all the flow related to my site will proceed in the main window, and the oauth2 flow (google, Facebook) will be in the new window.

Or can you, please, suggest how it would be better to implement the same behavior as for most of the sites?
For example: https://rapidapi.com/login

**Comment by websanova** [comment]
Ahh, so I'm not really sure what you mean by redirect then.

With the new window option you should be able to open the Google/facebook/etc login in a new window. Is that not working for you?

From there you either need to redirect back to some pafe and run a close, or perhaps have some flag that google or FB accepts to fire off the close.

Is there some other process flow you are trying to work out?

**Comment by kami4ka** [comment]
Thanks for the response :-)
I'm thinking that it would be nice to have the same log-in behavior as we have, for example, here: https://rapidapi.com/login

So the user opens the Google/FB auth in a new window (the new window contains only the Google/FB content) and then the result comes back to the main (parent) window (probably, we can catch the redirect).

Currently, when I'm using a new window, it shows with a Google/FB content and then, after the successful login, the redirect URL also shows in the same window as Google/FB, so we have 2 windows with the site content.

As from my understanding of the process, this behavior is a part of Google/FB/etc. JS library, but I haven't look into them deeply.

What do you think about it?  Would it be a good improvement for the library to catch the redirect from the child popup window and make this redirect inside the parent window? (that's only my suggestion, I'm not very experienced frontend developer :-) )

**Comment by websanova** [comment]
Ah, ya, I think the idea is in those cases that you redirect to like a
dummy close page and just have some JS in there to close.

Not really sure there is a redirect like that, and you can always pass a
state param for some specific flag as well.

**Comment by kami4ka** [comment]
Do you have plans to enhance and implement this functionality inside the library or it'll better to do it inside the code of my app?

**Comment by websanova** [comment]
Not sure that is really for the library to handle, seems more like the apps responsibility.

**Comment by truongnmt** [comment]
@websanova 
Maybe not relevant but after I doing like this

```
this.$auth
    .oauth2({
        params: {
            client_id: 'FACEBOOK_CLIENT_ID'
            ...
        },
        remember: 'Rob',
        staySignedIn: true,
        fetchUser: true,
        window: {
            name: '_blank',
            specs: {},
            replace: false
        }
    });
```

Let's say I'm in AuthLogin controller, click login with facebook button and a new window pop up and after I got the authorization code from facebook, how can I redirect to AuthLogin controller and continue the flow (exchange code to token...), currently the authorization code is redirected in the new pop up window. 🤔

**Comment by websanova** [comment]
You have a monorepo or separate api and spa?

**Comment by truongnmt** [comment]
Mine is separate backend API and SPA

**Comment by websanova** [comment]
So it should redirect from you app/spa and back to it again, then fire off a request to your api with the code you just received.

Also, did you check the guide at all?

https://websanova.com/docs/vue-auth/guides/oauth2

**Comment by truongnmt** [comment]
Thanks for clearing out! Yes, I'm doing exactly as you suggest. However, by doing redirect I'm losing all states in store. If only we could pop up a new window, then user login, then the result is returned to the original window, no full page refresh, so states are not being deleted 🤔 

Anyway I'm saving to local storage as a workaround, never mind though...

**Comment by websanova** [comment]
Yes, you can keep state, it's part of oauth2 spec, bunjsing state parameters.

You can also open it in a separate window of that works better by passing the window argument.

https://github.com/websanova/vue-auth/blob/master/src/auth.js#L746
