### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jporter-dev** [websanova/vue-auth#619]
There are some broken links in the docs due to the `drivers` folder being moved into `/src`. 

The broken links can be found [here](https://websanova.com/docs/vue-auth/guides/drivers). Links for pretty much anything within the `drivers` folder needs updating. 

I didn't see any docs in this repo and couldn't find a repo for the documentation, as I would have made these changes myself.

**Comment by websanova** [comment]
thx, for the heads up, fixed :-)
