### ISSUE TITLE
not able to send a number to $auth.check()

### ISSUE THREAD

**Issue by murum** [websanova/vue-auth#62]
I'm using role id's on my auth check. But when only sending a single number to the function I got `check()` Then I do get the response of `false` whatever roles I've in the user.roles.

The function toArray only take care of strings. Not Numbers.

**Comment by websanova** [comment]
OK, will check it tmr (you can do toString() for now I guess :p)

**Comment by murum** [comment]
See my PR and it'll be fixed.

**Comment by websanova** [comment]
up in `v2.2.1-beta`.
