### ISSUE TITLE
Specs to handle refresh tokens

### ISSUE THREAD

**Issue by philippeluickx** [websanova/vue-auth#620]
Hi!

I have some challenges trying to figure out how to write my own driver to deal with refresh tokens.
1. I get the refresh_token in an object as response when I log in. I can access it from the response, but how do I return it _together with_ the access_token? An array? Piped together or with a semicolon?
2. I can use the refresh method on my API with a POST expecting  `{refresh: <token>}` payload. Where can I define this? I can set the method in refreshData option to "POST" but can't define payload...

```
    auth: {
      request(req, token) {
        this.drivers.http.setHeaders.call(this, req, {
          Authorization: `Bearer  ${token}`,
        });
      },
      response(res) {
        if (res.data.access_token && res.data.refresh_token) {
          return `${res.data.access_token};${res.data.refresh_token}`; # ????
        }
        return res.data.access_token;
      },
```

Thanks!

**Comment by websanova** [comment]
Don't over think it :-)

It's just storing and parsing a string.

So you can actually do whatever you like. So in the "response" it's looking for the token and in the "request" it's sending it back out. With the string format you can do whatever you like, pipe, colon, etc. It would just be a matter of storing/parsing it accordingly between resonse/request.

Something like that...

```
    auth: {
      request(req, token) {
          token = token.split(';');

          if (token.length > 1) // do a
          else // do b
      },
      response(res) {
        if (res.data.access_token && res.data.refresh_token) {
          return `${res.data.access_token};${res.data.refresh_token}`; # ????
        }
        return res.data.access_token;
      },
```

**Comment by philippeluickx** [comment]
I had no idea... good to know!
Seems like you have to check on "undefined" though, otherwise things get ugly.

I still do not understand though how you can define the payload for the refresh call? My API expects a POST request with a body containing "refresh: '123'"... Any suggestions for that part?

**Comment by websanova** [comment]
look at the options ;-) you can configure any request.

**Comment by philippeluickx** [comment]
I'm still confused with this. Sorry but I'm just not seeing it.
So now I got both access and refresh token in the request of the driver.

```
    auth: {
      request(req, token) {
        const tokens = (token || '').split(';');
        // TODO:
        // This part? What triggers refresh?
        if (req.uri === 'refresh') {
          this.$auth.refresh({ refresh: tokens[1] });
        } else {
          this.drivers.http.setHeaders.call(this, req, {
            Authorization: `Bearer  ${tokens[0]}`,
          });
        }
      },
      response(res) {
        if (res.data.access_token && res.data.refresh_token) {
          return `${res.data.access_token};${res.data.refresh_token}`;
        }
        return '';
        // const headers = this.drivers.http.getHeaders.call(this, res);
        // const token = headers.Authorization || headers.authorization;
        // return res.data.access_token;
      },
    },
```
But how exactly do I use that refresh token? My guess is that something should happen whenever the API returns 40x - access token expired (or something like that)?
You mention the options for defining the request, but I still can't see how you define the payload?

```
    @default {
        url: 'auth/refresh',
        method: 'GET',
        enabled: true,
        interval: 30
    }
```

I searched the code and it seems that there's some logic at https://github.com/websanova/vue-auth/blob/master/src/auth.js#L232 where user should get logged out if token has expired and on https://github.com/websanova/vue-auth/blob/master/src/auth.js#L415 there is an interval where tokens get refreshed.
The actual function is called on https://github.com/websanova/vue-auth/blob/65c3245a63831af29c93bef73f365b537874fd29/src/auth.js#L539 which has a data parameter, which is using the refreshData options we defined. But options are still not the same as actual payload?

Probably something obvious and simple, but at least it's not simple for me...

**Comment by websanova** [comment]
Hard to say without knowing your code and what you're trying to achieve exactly.

Best I can tell you is that don't think vue-auth is some magic box.

When you make a call like "$auth.login" or "$auth.refresh", etc, it's just piping those calls to your http plugin, such as axios. That's pretty much all. There is an included interceptor which are called the "auth" drivers. So every request is your app will go through those intereceptors. And that's just your normal axios interceptor so you can do whatever you like there. I mean the "req" and "res" objects are right there, so do whatever you need.

So typically the driver adds some header like "Authorization: $token" but you can manipulate that request in whatever way makes sense or even sniff out specific routes, etc.

Now note that the auth plugin does have some things built in but there may be special cases to intercept some 401 and do a refresh or something. So you can just write your own interceptor for those kinds of scenarios.

**Comment by zorn-v** [comment]
I do it like this
```js
//...
  refreshTokenName: 'refresh_token', //my own option
  refreshData: {url: '/api/auth/refresh', method: 'POST', interval: 25},
  auth: {
    request: function (req, token) {
      if (req.url === this.options.refreshData.url) {
        req.data = {refresh_token: this.token(this.options.refreshTokenName)}
      }
      this.drivers.http.setHeaders.call(this, req, {Authorization: 'Bearer ' + token})
    },
    response: function (res) {
      const resData = res.data || {}
      this.token(this.options.refreshTokenName, resData.refresh_token);
      return resData.token
    }
  },
  logoutData: {redirect: '/', success() {this.token(this.options.refreshTokenName, null)}}, //cleanup
//...
```

**Comment by philippeluickx** [comment]
Ok, that's helping a lot! Thanks for clarifying @websanova and for the example @zorn-v . So this code makes sense, now I just need to write my own interceptor that deals with a 401 when the access_token expires and needs a refresh. I think I was expecting this library to handle it, makes sense though that it doesn't!

Thanks again!

**Comment by zorn-v** [comment]
> need to write my own interceptor that deals with a 401 when the access_token expires and needs a refresh

I think `refreshData` is enough because tokens updated on each page load. vue-auth make auto request (interval in minutes) with params in this option.

**Comment by philippeluickx** [comment]
Right, I was just realizing that when browsing the code. So https://github.com/websanova/vue-auth/blob/master/src/auth.js#L232 refreshes the token on every page load and then https://github.com/websanova/vue-auth/blob/master/src/auth.js#L415 on an interval if the user is staying on the same page.
That logic completely escaped me... makes sense now.

**Comment by philippeluickx** [comment]
@zorn-v  I still did not get this to work... When I log in I get an access_token and refresh_token. However, when I do a refresh, I only get a new access_token.
This makes me lose the refresh token, so the next time I do a refresh it fails.
How should I handle that?

**Comment by zorn-v** [comment]
Well you should change you refresh route (in backend) to update refresh token and send it also I think.

I used this symfony bundle for refresh tokens https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle

**Comment by philippeluickx** [comment]
I managed to get this working with the following response:
```
      response(res) {
        // On login you get both access and refresh token
        const accessToken = res.data.access_token || res.data.access;
        if (accessToken) {
          const refreshToken = res.data.refresh_token || Vue.auth.token().split(';')[1];
          return `${accessToken};${refreshToken}`;
        }
        return undefined;
      },
```
So glad this is done. Authentication is difficult... Thanks @zorn-v  and @websanova for the support!

**Comment by zorn-v** [comment]
> Vue.auth.token()

Better use `this.token()` - it will be vue 3 compatible

**Comment by lucianobosco** [comment]
For those wondering how to do this in v4, this is my solution by using Vue 2 and Laravel 8 Passport. This is based on @zorn-v solution.

**LARAVEL SIDE**
Set exposed headers in `cors.php` config file so it can be read by `vue-auth`
```
'exposed_headers' => ['Authorization', 'Refresh'],
```

Return `access_token` and `refresh_token` from your controller. Please note that you may do this also in refresh token function. This is my login function:
```
public function login(Request $request) {
    $http = new Client;
    try {
        $response = $http->post(config('services.passport.login_endpoint'), [
            'form_params' => [
                'grant_type' => 'password',
                'client_id' => config('services.passport.client_id'),
                'client_secret' => config('services.passport.client_secret'),
                'username' => $request->username,
                'password' => $request->password,
            ],
            'http_errors' => false
        ]);

        // Attach headers to response
        if ($response->getStatusCode() == 200) {
            $result = $response->getBody()->getContents();
            header("Authorization: Bearer ".json_decode($result)->access_token);
            header("Refresh: ".json_decode($result)->refresh_token);
        }
    } catch (\GuzzleHttp\Exception\BadResponseException $e) {
        if ($e->getCode() === 400) {
            return response()->json('Invalid Request. Please enter a username or a password.', $response->getStatusCode());
        } else if ($e->getCode() === 401) {
            return response()->json('Your credentials are incorrect. Please try again', $response->getStatusCode());
        }
        return response()->json('Something went wrong on the server.', $response->getStatusCode());
    }
}
```

**VUE JS SIDE**
Define a custom key for `refresh_token` under `vue-auth` options
```
refreshTokenKey: 'auth_refresh_token',
```
Define a custom auth driver and attach the Refresh header on request:
```
this.drivers.http.setHeaders.call(this, req, {
      Refresh: this.token(this.options.refreshTokenKey)
})
```
and set Refresh token on response:
```
var refresh_token = headers.Refresh || headers.refresh
if (refresh_token) this.token(this.options.refreshTokenKey, refresh_token)
```

So the full code for `vue-auth` init is:
```
Vue.use(auth, {
    plugins: {
        http: Vue.axios, // Axios
        router: Vue.router
    },
    drivers: {
        auth: {
            request: function (req, token) {
                this.drivers.http.setHeaders.call(this, req, {
                    Authorization: 'Bearer ' + token
                })
                // Set auth_refresh_token on every request
                this.drivers.http.setHeaders.call(this, req, {
                    Refresh: this.token(this.options.refreshTokenKey)
                })
            },

            response: function (res) {
                var headers = this.drivers.http.getHeaders.call(this, res)
                var token = headers.Authorization || headers.authorization

                // Set auth_refresh_token if available
                var refresh_token = headers.Refresh || headers.refresh
                if (refresh_token) this.token(this.options.refreshTokenKey, refresh_token)

                if (token) {
                    token = token.split(/Bearer:?\s?/i)
                    return token[token.length > 1 ? 1 : 0].trim()
                }
            }
        },
        http: driverHttpAxios,
        router: driverRouterVueRouter,
        oauth2: {
            google: driverOAuth2Google,
            facebook: driverOAuth2Facebook
        }
    },
    options: {
        rememberkey: 'auth_remember',
        tokenDefaultKey: 'auth_token_default',
        tokenImpersonateKey: 'auth_token_impersonate',
        refreshTokenKey: 'auth_refresh_token',
        stores: ['storage', 'cookie'],

        loginData: {
            url: '/login',
            method: 'POST',
            redirect: '/dashboard',
            fetchUser: false
        },

        logoutData: {
            url: '/logout',
            method: 'POST',
            redirect: '/',
            makeRequest: false
        },

        refreshData: {
            url: '/refresh',
            method: 'POST',
            enabled: true,
            interval: 15
        },

        fetchData: {
            url: '/user',
            method: 'GET',
            enabled: false
        },

        authRedirect: { name: 'login' },
        forbiddenRedirect: { name: '401' },
        notFoundRedirect: { name: 'dashboard' }
    }
})
```
Of course, you can also return your tokens within the response body and handle them in another way, but this will give you an idea.

Not sure if this the best way to do this, but is working fine so far.
Hope it helps!

**Comment by websanova** [comment]
@lucianobosco also note that the http drivers do have an invaildToken function that can be overridden.

https://github.com/websanova/vue-auth/blob/master/src/drivers/http/vue-resource.1.x.js#L21

So actually, the 401 response should be working out of the box as that is the default. You could perhaps trying overriding that function and doing a console.log to see what's happening there though.

**Comment by lucianobosco** [comment]
> @lucianobosco also note that the http drivers do have an invaildToken function that can be overridden.
> 
> https://github.com/websanova/vue-auth/blob/master/src/drivers/http/vue-resource.1.x.js#L21
> 
> So actually, the 401 response should be working out of the box as that is the default. You could perhaps trying overriding that function and doing a console.log to see what's happening there though.

I guess your comment is also in regards to https://github.com/websanova/vue-auth/issues/643
So you think that it will be convenient to dispatch `this.logout()` from within HTTP driver instead by overwriting it?

**Comment by zorn-v** [comment]
If token refresh fails, actually next request "should" return 401
I never have problems with standard behavior in such case.
