### ISSUE TITLE
Checking roles return always false

### ISSUE THREAD

**Issue by emulienfou** [websanova/vue-auth#623]
Hello there, I checked your documentation and some issues related to that, but I cannot figured out how the roles checking is working.

Currently I have a JWT token where I added a role, and I wanted to use the `$auth.check()` method to verify if the current logged in user has the correct roles.

Here is my payload from the JWT token:
```json
{
  "iss": "http://localhost:8081/api/auth/refresh",
  "iat": 1611343250,
  "exp": 1611617892,
  "nbf": 1611614292,
  "jti": "25RUxOFBeTN9VXrd",
  "sub": 1967,
  "prv": "87e0af1ef9fd15812fdec97153a14e0b047546aa",
  "roles": [
    "full_admin"
  ]
}
```

And I'm currently checking the role with `$auth.check('full_admin')` and I also tried `$auth.check(['full_admin'])` but the methid returns always `false`.

Here is my configuration of Vue-Auth:
```js
Vue.use(auth, {
  plugins: {
    http: Vue.axios,
    router: router
  },
  drivers: {
    auth: driverAuthBearer,
    http: driverHttpAxios,
    router: driverRouterVueRouter
  },
  rolesKey: 'roles',
  tokenName: 'token',
  authRedirect: {path: '/login'},
  fetchData: {url: process.env.VUE_APP_API_URL + '/auth/user', method: 'GET', enabled: true},
  refreshData: {url: process.env.VUE_APP_API_URL + '/auth/refresh', method: 'GET', enabled: false, interval: 30}
})
```

**Comment by websanova** [comment]
They check happens against the user data not the token.

So you can try to `console.log($auth.user())` for instance. You would need to override the [`parseUserData`](https://websanova.com/docs/vue-auth/options/core#parseuserdata) option to pluck it out of the token which would require base64decode, hence why it's not included since it's a sizable chunk of code.

**Comment by emulienfou** [comment]
@websanova Thanks for the information. Tried to use `parseUserData` but same has other people, this option seems to not be triggered at all.

I need to update my login code like this to have the user's data accessible from `$auth.user()` otherwise it's empty:
```js
this.$auth.login({
        url: '/authenticate',
        data: {username: this.form.username, password: this.form.password},
        staySignedIn: true,
        fetchUser: true
      }).then(response => {
        this.$auth.user(response.data)
      }).catch(() => {})
```

After this change, both `$auth.user()` and `$auth.check('full_admin')` works!
However, it seems the data is lost when I reload the page.

Do I need to persist the data in some localStorage, cookies, ... or did I miss some code to have the same data after reloading the page?

**Comment by emulienfou** [comment]
Closing the issue, actually I needed to add this parts of code like you said, to have the data retrieved when reloading the page:
```js
parseUserData: function (data) {
    return data;
  }
```
