### ISSUE TITLE
Can't access to current logged user data from getters

### ISSUE THREAD

**Issue by devmansurov** [websanova/vue-auth#624]
I have `namespaced` store file which has like this `getters`:

    getters: {
        user() {
            return Vue.auth.user();
        }
    }

And when I see vuex data from browser recive like this data:

[![enter image description here][1]][1]

As you see in vuex I have user data but when I tried get it recive empty object:

    computed: {
      _user() {
        return this.$store.getters['auth/user'];
      },
      ...mapGetters({
         userGetter: 'auth/user',
      }),
    }

How I get correctly user info in this case? How I must save logged user data and access to it correctly using this plugin?

  [1]: https://i.stack.imgur.com/dhZya.png

**Comment by websanova** [comment]
Do you have proper usage of `$auth.ready()` or `$auth.check()`.

Also how about trying to display it in a template `{{ $auth.user() }} - {{ $store.gettes['auth/user'] }}`

Some basic debugging on your end would help :-)

**Comment by devmansurov** [comment]
> o

I tried use `$auth.ready()` and `$auth.check()` and both return true and in vuex getters auth property has user information but  `{{ $auth.user() }}` - `{{ $store.gettes['auth/user'] }}` return empty object like this `{}`. How I can solve this problem? Thanks in advance ))

**Comment by devmansurov** [comment]
> Do you have proper usage of `$auth.ready()` or `$auth.check()`.
> 
> Also how about trying to display it in a template `{{ $auth.user() }} - {{ $store.gettes['auth/user'] }}`
> 
> Some basic debugging on your end would help :-)

Here is my project https://github.com/devmansurov/vue-auth

I tried get current user using localStorage on each route change but it's bad practice. Pleace help me to get current user correctly

**Comment by websanova** [comment]
Should be fine then, not sure where you're going wrong.

Maybe try some random stuff like

```
console.log(this.$auth.user());

setTimeout(() => {
    console.log(this.$auth.user());
}, 5000);
```

Maybe the format of your response as well...

**Comment by devmansurov** [comment]
> setTimeout(() => {
>     console.log(this.$auth.user());
> }, 5000);

I tried after 10 second get user and get like this result but here doesn't has user info

![image](https://user-images.githubusercontent.com/51310839/105952355-4b04d900-6093-11eb-89bc-1cf04e7d1a9d.png)

**Comment by websanova** [comment]
oh, that's really weird.... you got something funky going on for sure,

It's even the right plugin installed? Maybe recheck the docs installation guide for your version.

**Comment by devmansurov** [comment]
> oh, that's really weird.... you got something funky going on for sure,
> 
> It's even the right plugin installed? Maybe recheck the docs installation guide for your version.

Yes, it is installed in my project. Here is my dependencies:

```
  "dependencies": {
    "@vue/cli-plugin-babel": "4.1.1",
    "@websanova/vue-auth": "^4.1.0",
    "axios": "^0.21.1",
    "core-js": "3.6.5",
    "vee-validate": "^3.4.5",
    "vue": "^2.6.11",
    "vue-axios": "2.1.5",
    "vue-resource": "1.5.1",
    "vue-router": "3.4.3",
    "vuex": "3.5.1"
  },
```

Are you seen my project in github? @websanova 

Project: https://github.com/devmansurov/vue-auth

**Comment by websanova** [comment]
How are you returning the user data? Maybe just need to try `parseUserData` option if you are not following the default format.

**Comment by devmansurov** [comment]
> How are you returning the user data? Maybe just need to try `parseUserData` option if you are not following the default format.

I return from my backend user data like this:

url: `auth/user`

Response: `json`

Example:

```
{
   "id":1,
   "name":"User",
   "email":"user@gmail.com",
   "email_verified_at":null,
   "created_at":"2021-01-21T11:39:06.000000Z",
   "updated_at":"2021-01-21T11:39:06.000000Z",
   "role":[
      "admin"
   ]
}
```

@websanova

**Comment by devmansurov** [comment]
> How are you returning the user data? Maybe just need to try `parseUserData` option if you are not following the default format.

I tried use something like this:

```
parseUserData: function(data) {
    console.log(data)
}
```

And get user data but how or where I must save recived user data so as not to lose when refreshing the page?

@websanova

**Comment by websanova** [comment]
Well the default for `parseUserData` is `return data.data`.

https://github.com/websanova/vue-auth/blob/master/src/auth.js#L138

so you may have to just do `return data` in your case.

```
parseUserData: function(data) {
    return data;
}
```
