### ISSUE TITLE
[vue-auth] Token doesn't store in session storage automaticaly

### ISSUE THREAD

**Issue by aszymkiw** [websanova/vue-auth#628]
Hello,
I updated vue-auth 4. I updated all config but when i try to log on my account, token don't write in my session store. I must to write on manual : sessionStorage.set('name_token',value).

But before it worked. Here my version : 
  import axios                 from 'axios';
  import { router } from '@/config/_helpers';
  import driverAuthBearer from '@websanova/vue-auth/dist/drivers/auth/bearer.js';
  import driverHttpAxios from '@websanova/vue-auth/dist/drivers/http/axios.1.x.js';
  import driverRouterVueRouter from '@websanova/vue-auth/dist/drivers/router/vue-router.2.x.js';
  
  import { 
    login,
    logout,
    refresh,
    user
  } from '../../_utils/api/auth/';
  
  // Auth base configuration some of this options
  // can be override in method calls
  export const authentication = {
    plugins: {
      http: axios,
      router: router
    },
    drivers: {
      http: driverHttpAxios,
      auth: driverAuthBearer,
      router: driverRouterVueRouter
    },
    options: {
      tokenDefaultKey: 'sp_token',
      stores: ['storage'],
      rolesKey: 'profile_id',
      loginData: { url: `${login}`, method: 'POST', redirect: '', fetchUser: false, staySignedIn: false },
      logoutData: {url: `${logout}`, method: 'POST', success: function () {this.$store.clearAll();}, redirect: '/', makeRequest: true},
      fetchData: {url: `${user}`, method: 'GET', enabled: true},
      refreshData: {url: `${refresh}`, method: 'GET', success: function(data){ localStorage.set('sp_token',data.data.sp_token)},enabled: true, interval: 30},
    }
    
  };

thank you for your help !

**Comment by websanova** [comment]
What version of vue are you using and how are you importing vue-auth?

https://websanova.com/docs/vue-auth/guides/startup#setup

**Comment by aszymkiw** [comment]
Thank you for your answer, i use vue 2. I tried vue 3 but i have ane error : dependency not found of vue for vue-auth.
And in my main.js, i import import auth from '@websanova/vue-auth/src/v2.js'; and i use : Vue.use(auth,authentication);

**Comment by aszymkiw** [comment]
Sorry to open this topic but i solved my problem. In my backend, i forget to add my header (i saw on a topic already closed here) : i had to my response : ->header('Access-Control-Expose-Headers','Authorization')->header('Authorization','Bearer'. $token);
