### ISSUE TITLE
Typescript example?

### ISSUE THREAD

**Issue by francoism90** [websanova/vue-auth#632]
```
// src/boot/auth.ts
import { boot } from 'quasar/wrappers'
import { api } from './axios'
import { createAuth } from '@websanova/vue-auth/dist/v3/vue-auth'
import * as driverAuthBearer from '@websanova/vue-auth/dist/v3/vue-auth'
import * as driverHttpAxios from '@websanova/vue-auth/src/drivers/http/axios.1.x'
import * as driverRouterVueRouter from '@websanova/vue-auth/src/drivers/router/vue-router.2.x'

export default boot(({ app, router }) => {
  app.use(createAuth({
    plugins: {
      http: api,
      router: router
    },
    drivers: {
      http: driverHttpAxios,
      auth: driverAuthBearer,
      router: driverRouterVueRouter,
    },
    options: {
      rolesKey: 'type',
      notFoundRedirect: { name: 'user-account' }
    }
  }))
})
```

Results in a lot of TypeScript errors:
```
Could not find a declaration file for module '@websanova/vue-auth/dist/v3/vue-auth'. '/srv/http/project/app/node_modules/@websanova/vue-auth/dist/v3/vue-auth.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/websanova__vue-auth` if it exists or add a new declaration (.d.ts) file containing `declare module '@websanova/vue-auth/dist/v3/vue-auth';`
...

Unsafe assignment of an any value.
```

I know this is written in JavaScript, I'm just searching for a workaround for these issues. I'm unable to add ignore the file as it isn't allowed and it's best practice. Do you have any good ideas? :)

Thanks!

**Comment by websanova** [comment]
Not quite sure, I'm not using TS, there was definitions file added a while ago, but I haven't checked that in a while.

https://github.com/websanova/vue-auth/blob/master/types/index.d.ts

Maybe start there?

**Comment by francoism90** [comment]
@websanova Thanks! Unfortunately I'm still learning TS, it seems a few things are missing from the types (createAuth, drivers, etc.), but I'm not that well knowledge about what should be defined, sorry.

**Comment by websanova** [comment]
ya, I think it just needs a few minor updates, should be able to follow what's there if you need to get it working right away.

**Comment by abraxxa** [comment]
I'm also interested in a typescript example.

**Comment by websanova** [comment]
@abraxxa  Well there is one right there in the repo, as mentioned above it may have some minor issues from some recent updates.

**Comment by abraxxa** [comment]
Are you referring to the index.d.ts file?
One issue is that createAuth doesn‘t return a typed object.
Another that some types include ‚any‘ which results in errors.
I‘m also a beginner regarding typescript and would like someone more experienced to join the discussion.

**Comment by abraxxa** [comment]
I'm still struggling to get this working.
The type definition for createAuth is now in the index.d.ts file, but it isn't used by the typescript compiler.
How do I have to import createAuth and the drivers to make that work?
Thanks!
