### ISSUE TITLE
this.$auth.token manual

### ISSUE THREAD

**Issue by nunob87** [websanova/vue-auth#633]
upgrade from version 2 to 4, but keep the vue 2 js, I can't get this to work, how can I activate the token manually?

this. $ auth.token ('bearer', res.data.api_token)

thanks

**Comment by websanova** [comment]
Did you follow upgrade guide?

https://websanova.com/docs/vue-auth/upgrades/3x-4x

**Comment by nunob87** [comment]
I have it running on an application, only I have another application where there is only login if there is a token, there is a token there is no token there is no session, I did this manually to keep the same plugin since this second application reuses most of the other's files

this. $ auth.token ('bearer', res.data.api_token), but now making this line, he does not keep the token in orders.

this. $ auth.login ({
           params: this.form,
           remember: false,
           autoLogin: true,
           staySignedIn: false,
           fetchUser: false
         }). then ((res) => {
           this. $ auth.token ('bearer', res.data.api_token)
         }, () => {})

thanks
