### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ghostlexly** [websanova/vue-auth#636]
Hello,

I just wanna say a big thank you to websanova for this awesome library.
It's does the job and it's better than a lot of libraries that i tryed before.

Thank you ;)

Regards,

**Comment by websanova** [comment]
good to hear, you welcome :-)

**Comment by lucianobosco** [comment]
+1 I'm using this library in all my projects since I found it. The latest version looks more complex to implement but once you understand how to do it it's clearly more robust than the previous one.
I couldn't be done this by myself. Happy to find you @websanova !

**Comment by websanova** [comment]
@lucianobosco awesome, thx :-)
