### ISSUE TITLE
Store entire user objects in LocalStorage?

### ISSUE THREAD

**Issue by derekphilipau** [websanova/vue-auth#638]
I want to store user objects in local storage (non-sensitive data), rather than reload/fetch all user data via vue-auth each time a new tab or window is opened.  It seems that vue-auth does not offer this functionality, vue-auth only stores tokens in local storage.  If I want persistence across sessions I will need to use something in addition to vue-auth like vuex-persistedstate.  Is this correct?  Thank you.

**Comment by websanova** [comment]
Yea, you should be able to do it manually.

> Set `fetchData.enabled` to `false`

https://websanova.com/docs/vue-auth/options/core#fetchdata

> Login/Register/Logout

Then do some manual stuff here, you will need to manually set the user wherever, I guess have some central place to run these updates through which would then just update the local storage.

**Comment by derekphilipau** [comment]
This makes perfect sense, thank you!
