### ISSUE TITLE
Could not find a declaration file for module '@websanova/vue-auth/dist/drivers/auth/bearer.esm.js'.

### ISSUE THREAD

**Issue by medina325** [websanova/vue-auth#639]
Ok you can close this issue, sorry!

**Comment by dev-mmk-sm** [comment]
I am also facing the same issue. Could you please guide me through on the steps you followed to solve it?
"Could not find a declaration file for module '@websanova/vue-auth/dist/drivers/auth/bearer.esm.js'. "

**Comment by medina325** [comment]
There's actually no problem to be solved in my case, the error was being caused by another part of the code. This is was just an "error" raised by vscode most likely because I had no tsconfig.json file in my project.
