### ISSUE TITLE
$auth.check() think there's a object if an array is given.

### ISSUE THREAD

**Issue by murum** [websanova/vue-auth#64]
If I do `$auth.check([5, 4, 3, 2])`.

Then row 44 in utils.js 
`if (typeof one === 'object' && typeof two === 'object')` passes.

I think this function should return false then since there's an array and not a object which is given to the function.

This could be changed to 
`if (Object.prototype.toString.call(one) === '[object Object]' && Object.prototype.toString.call(two) === '[object Object]')`

I'm unsure how that will apply with `this.watch.data[this.options.rolesVar]` since that might always be an array, and not a object or am I wrong here?

I would like to get a function to be able to send a array of id's which is OK for a given check. RIght now that's not possible.

**EDIT** 
The issue is working with `if (Object.prototype.toString.call(one) === '[object Object]' && Object.prototype.toString.call(two) === '[object Object]')` But that might break other options when you do something like `$auth.check({'role': 'user'}]` I'm not sure, you could test it?

**Comment by murum** [comment]
@websanova I made a PR.

**Comment by websanova** [comment]
Yes, it's merged already, just didn't push to npm yet...

**Comment by murum** [comment]
@websanova this is another thing, I made 2 PR's

**Comment by websanova** [comment]
Ok, this is all pushed up now `v2.2.1-beta`. Thx :-)

I've also started a small test script which only includes the compare function. So if you can think of any more cases we can drop them in there.
