### ISSUE TITLE
AdminLTE Navigation Broken

### ISSUE THREAD

**Issue by alibaba258** [websanova/vue-auth#647]
I`m using AdminLTE in my project. If i install and import the vue-auth package, my submenus won´t expand. If I remove the import statement from my code everything works fine.

Any ideas? Console shows no error messages. 

`"@websanova/vue-auth": "^4.1.1",
    "admin-lte": "^3.1.0",
    "axios": "^0.21.1",
    "bootstrap": "^4.6.0",
    "core-js": "^3.6.5",
    "sweetalert2": "^10.16.0",
    "vform": "^1.0.1",
    "vue": "^2.6.12",
    "vue-axios": "^3.2.4",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },`

**Comment by websanova** [comment]
Closing because no follow up and not enough info to do anything with this report.
