### ISSUE TITLE
auth0 support

### ISSUE THREAD

**Issue by OmgImAlexis** [websanova/vue-auth#66]
I'd love to be able to use this with auth0 and my own API backend but I can't seem to get it to work. Would it be possible to add a demo as the current info in the README isn't as clear as it could be.

I also noticed the `Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';` is this meant to be the authentication URL or the URL for the backend?

**Comment by websanova** [comment]
Well currently it only supports oauth2. Not really sure what auth0 is. Are you just trying to integrate login via Facebook or Google?

**Comment by websanova** [comment]
The url in the sample code `Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';` is just for demo purposes. This would be replace with your won api url.

**Comment by OmgImAlexis** [comment]
This makes so much more sense. I've been trying to use it with Auth0's JWT.
I'm guessing it only really works with oauth2?

**Comment by websanova** [comment]
Well the plugin supports her by default. Not sure what you're trying to do
here.
