### ISSUE TITLE
Install v2.2.x-beta

### ISSUE THREAD

**Issue by wcarron27** [websanova/vue-auth#67]
#I tried installing the npm module for Vue.js compatibility, and received the 1.5.x-beta module. When I looked through the node_module, there were no directories for the drivers. After checking the package.json, indeed I got version 1.5.1-beta. This code on github clearly has the drivers, but the npm module does not. Any advice is appreciated.

Edit: I tried a new approach: Git cloned this repo into my node modules, manually updated my package.json, and npm installed. I did end up with the code seen here in this repo, but it refuses to work, giving me this error message: 
    `vue-router.2.x.js?832c:22Uncaught` TypeError: Cannot read property 'beforeEach' of undefined(…)`

Really not sure what to do here, as I like your solution.

**Comment by websanova** [comment]
Right, so the drivers are for the 2.x version.

**Comment by wcarron27** [comment]
Yes, that part is clear. What I'm wondering is how to get the 2.2.1-beta via an NPM install. I'm trying to build an app using Vue.js 2.x and Vue-router 2.x and I'm struggling to find an auth solution that, well, just works.

I'll admit I'm not the best dev (can't even roll my own auth, lol), but your code makes a lot of sense, and I'd love to figure this out, regardless of difficulty. Any help on forcing npm to install the 2.2.1-beta is appreciated.

**Comment by websanova** [comment]
Well how did you install the 1.5.1-beta ?

**Comment by wcarron27** [comment]
I followed the advice on the readme by: uninstalling the currently installed version, then `npm install @websanova/vue-auth`, which left me with v1.5.1-beta

**Comment by websanova** [comment]
Do you have a package.json file? Better to add it in there, who knows what
npm is doing.

**Comment by wcarron27** [comment]
Ok, just cleaned my npm cache and installed via manually editing the package.json. Still returning errors of `Uncaught TypeError: Cannot read property 'beforeEach' of undefined at Auth.beforeEach`

**Comment by wcarron27** [comment]
Hey, I got it! Took a little fiddling. What happened was that I was exporting
`const router = new VueRouter`. I changed it to `const router = Vue.router = new VueRouter {`
and it worked. Just need a little coercion into it. Thanks for being so responsive to the issue and my questions. I really appreciate it!

**Comment by websanova** [comment]
Glad it you got it working. And you are not the first one getting stuck on
`Vue.router` needing to be set. I haven't had time to add some proper error
output to the drivers (or docs).
