### ISSUE TITLE
Oauth URL malformated

### ISSUE THREAD

**Issue by unicode-it** [websanova/vue-auth#672]
The URL cannot be parsed by the auth provider, because it contains a wrong '&' character at the beginning of the query params.

http://localhost:8000/o/authorize/?&client_id=client_id&redirect_uri=...

The bug is in function `oauth2`:

```
  for (key in data.params) {
    params += '&' + key + '=' + encodeURIComponent(data.params[key]);
  }

```

**Comment by unicode-it** [comment]
Could maybe fix like this: 
```
  let paramsArr = [];
  Object.keys(data.params).forEach((key) => {
    paramsArr.push(key + '=' + encodeURIComponent(data.params[key]));
  } );
  params = paramsArr.join('&');
```

**Comment by websanova** [comment]
alright, this is in `4.1.7`, thx!.
