### ISSUE TITLE
What refresh endpoint must do?

### ISSUE THREAD

**Issue by lhas** [websanova/vue-auth#68]
Hi, author! I really appreciate this plugin. Thanks for it.

I'm just curious about how i can implement the refresh endpoint.

I checked your server example with Laravel, but i'm implementing a Rails back-end.

I currently have a endpoint protected (only authenticated requests) who returns only a empty array []).

If user is authenticated and the token is valid, it returns 200.

If user is not authenticated or token is invalid, it returns 401 Unauthorized.

But i'm gotting this error when the token is invalid:

![image](https://cloud.githubusercontent.com/assets/1396448/21132778/eff50006-c0fc-11e6-954d-9c9ce7749506.png)

What can i do to solve this? Do you have any suggestions?

**Comment by websanova** [comment]
Well seems there are two separate issues.

1. You are getting unauthorized for the refresh request.
2. There is options fr undefined error.

For 2 that could be a bug with the plugin or some custom code.

For 1 would need more info.You can check if token is being snt with the
request in the first place. Also you can check if that refresh route is
consuming the token at all.
