### ISSUE TITLE
[Question] Authenticating users from external apps

### ISSUE THREAD

**Issue by lucianobosco** [websanova/vue-auth#680]
Context:
I have a route showing a dashboard with some statistics.
The route is restricted for `auth` users (non-public)
An Android/IOs app needs to use WebView to embed this dashboard.

The route definition:
```
{
        name: 'dashboard',
        path: 'dashboard',
        component: () => import('@/components/Home'),
        meta: {
              auth: true
        }
}
```

For my Vue app, I'm using the below code in my driver to attach the Bearer token
```
request: function (req, token) {
        this.drivers.http.setHeaders.call(this, req, {
            Authorization: 'Bearer ' + token,
            Accept: 'application/json'
        })
        this.drivers.http.setHeaders.call(this, req, {
            Refresh: this.token(this.options.refreshTokenKey)
        })
    },
```
I'm just wondering if Android/IOs apps could replicate the same by attaching `Authorization` header acting as logged-in users.

Assuming my route is https://www.mysite.com/dashboard and the external apps send the `Authorization: Bearer ...` header, do I have a chance to make this work?

Otherwise any advice will be appreciated.

**Comment by websanova** [comment]
Well the API is independent of any client app. Whether that app is a browser or some Android/IOs app you can still make the same requests to the API.

However, I don't do mobile dev, so not sure about specific details on that end.

**Comment by lucianobosco** [comment]
I wasn't clear enough. What I'd like to know is how this package recognizes an authorized user in order to let him navigate to the requested route having  `auth: true`. What this package expects from the app?
