### ISSUE TITLE
default tokenTimeoutOffset is not minutes but seconds

### ISSUE THREAD

**Issue by purepear** [websanova/vue-auth#7]
I believe that `tokenTimeoutOffset: 5 * 1000, // 5 minutes.` is seconds because setTimeout param is in milliseconds... so `5 * 60 * 1000` will be in minutes.

Edit: there were 2 questions here but i decided to create separate issues for them
Thanks :)

**Comment by ghprod** [comment]
Yes, `5 * 1000` its `5` seconds :+1:

**Comment by websanova** [comment]
This has been completely removed as it was quite a bit of code to parse out the token. This can be done manually now if necessary by disabling token refresh with:

~~~
expiredToken: function () { return false; }
~~~

Then do a manual `$auth.token()` call wherever you like, and then manually call `$auth.refresh()` based on whatever criteria you like.
