### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by ohohco** [websanova/vue-auth#70]
```
import Router from 'vue-router'
import Auth from '@websanova/vue-auth'
...
Vue.router = router

Vue.use(Auth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  tokenName: 'token',
  loginData: {url: '/signin', fetchUser: false},
  logoutData: {url: '/signout'},
  authRedirect: {path: '/signin'},
  http: axios,
  router: Router
})
```
at this line: 
`this.options.router._beforeEach.call(this, this.options.routerBeforeEach, this.options.transitionEach);`

**Comment by websanova** [comment]
What version are you using? Make sure you're up to the latest, this is
common issue from old version I think.

**Comment by ohohco** [comment]
`
"@websanova/vue-auth": "^2.3.0-beta",
"vue": "^2.1.0",
"vue-router": "^2.1.1",
`

**Comment by websanova** [comment]
ah, ok wait....You can NOT pass the router in like that. It's a driver not
the module. Please check the docs.
