### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by ghost** [websanova/vue-auth#705]

**Comment by gesbulukan** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)

**Comment by muhamadfatahabdulah** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgFrjZa5-jcSD3cf5y0jCZ16mc8GJlunhsiNDdjV1AF0Ka73TQ8vUBxpHgm_ZfHNgxxjusFSvxV6YnV_ZqfM4ag-P_r0FYxJvP6HPONDX8-3Kd4SsDkznaVS13Z-0_7uvsQSC7ViNZhdkMHVfRqufkm8Ki3mPrxJddIm2J47KuEAACccdCQVpmChlYqkd4/s1600/image_2024-11-17_135915957.png)](https://t.co/78Xb57KYwI)
