### ISSUE TITLE
Symfony using LexikJWTAuthenticationBundle and JWTRefreshTokenBundle

### ISSUE THREAD

**Issue by lsv** [websanova/vue-auth#72]
If you are using [LexikJWTAuthenticationBundle](https://github.com/lexik/LexikJWTAuthenticationBundle) and [JWTRefreshTokenBundle](https://github.com/gesdinet/JWTRefreshTokenBundle)

As your API provider, following should be used

```js
// vue-auth.js
Vue.use(require('@websanova/vue-auth'), {
    auth: require('./authtype'),
    refreshData: {
        url: 'user/refresh', // CHANGE THIS TO YOUR REFRESH URL
        method: 'POST',
        atInit: true
    }
});
```

```js
// authtype.js
const SPLITNAME = '--REFRESHTOKEN--';
const REFRESH_URL = 'user/refresh'; // CHANGE THIS TO YOUR REFRESH URL

module.exports = {

    request: function (req, token) {
        let splittoken = token.split(SPLITNAME);
        if (splittoken.length === 2) {
            if (req.url === REFRESH_URL) {
                req.body = {
                    refresh_token: splittoken[1]
                }
            }
        }

        if (req.url !== REFRESH_URL) {
            this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + splittoken[0]});
        }
    },

    response: function (res) {
        let token = '';
        let body = res.body;
        if (body.hasOwnProperty('token')) {
            token = body.token;
        }

        if (body.hasOwnProperty('refresh_token')) {
            token += SPLITNAME + body.refresh_token;
        }

        return token;
    }
};
```

As this module can not persist objects in localStorage, we need to return it as a string, therefor we add a splitter between the token it self and the refresh token

Also as the JWTRefreshTokenBundle requires the refresh_token as a payload (and dont need to authenticate with the real token) we change the request to have the refresh token in the payload.

**Comment by websanova** [comment]
I suppose you could use `this.options.refreshData.url` rather than the
constant value.

But I'm not quite sure why two separate names would be required for the
tokens. If you're sending back a token to refresh it already knows it's the
token. Why not just send them all back in the header?

Seems a bit strange of a scheme overall.

Rob

**Comment by lsv** [comment]
When you login you get 2 tokens, 1 the normal token, and 1 refresh token

```
{
   token: <token>
   refresh_token: <refresh_token>
}
```

I would normally save the object in localstorage, but then it requires the localstorage knows how to save objects, but the one used in this does not.

The <token> should be used until its expire, and the the <refresh_token> should be used to get a new <token>

I wasnt aware of using `this.options.refreshData.url` I will test it :)

**Comment by websanova** [comment]
Ok :-)

**Comment by pabloraissiguier** [comment]
I can't make this work out.

@lsv can you help me a little bit? I keep getting 401 when I call refresh. Seems that refresh_token is not being added to the request payload data.

I just tested with Postman and it works, so it's something messy with the frontend.

Did you add something extra besides this code?

Thanks!

**Comment by pabloraissiguier** [comment]
Just fixed.
If you use axios it should be:
`
req.body = {
    refresh_token: splittoken[1]
}
`
