### ISSUE TITLE
Does vue-auth support OpenID connect auth flows?

### ISSUE THREAD

**Issue by dflock** [websanova/vue-auth#75]
OpenID Connect is a set of specific auth flows, built on OAuth2: https://github.com/mspnp/multitenant-saas-guidance/blob/master/docs/appendixes/about-oauth2-oidc.md

It seems to be generally recommended to use the OIDC 'Implicit Flow' for client-side/single-page-apps. Does `vue-auth` support this? Presumably you'd need to use the `oauth2` method for this?

**Comment by websanova** [comment]
No idea about the open ID, but it does support oauth2.
