### ISSUE TITLE
Logout on _invalidToken does not redirect.

### ISSUE THREAD

**Issue by dobromir-hristov** [websanova/vue-auth#77]
OK this may have something to do with my last issue #76 
I just left my token expire, set it really short, like a minute. Then I did a request, and got a 401 token expired which is normal. Vue-auth caught that and as it should it deleted the token from local storage, but my app was left on the page, not getting redirected to the login or '/'.  This is a bummer as now I have to refresh the page or navigate somewhere to actually get redirected back to the Login page.

This is using latest version of vue-auth and Vue/vue-router/vue-resource.

**Comment by websanova** [comment]
What, happens if you just call $auth.logout() directly?

**Comment by dobromir-hristov** [comment]
If I do a this.$auth.logout() from a method instance all is good. If I change routes and the beforeEach hook fires from your plugin I get redirected and logged out as well. Only when I get a token expiration (or i mangle the token my self, just to test a bad token) I dont get redirected. If I try only $auth,logout() without the `this` I get an $auth is not defined error.

**Comment by dobromir-hristov** [comment]
[Here is my repo](https://bitbucket.org/terraweb/hybrid-app-2.0) that you can clone if you want. You can change the URL to the API or I can make an acc for you.

**Comment by websanova** [comment]
When your token is expired or mangled is your server specifically sending
back a 401?

**Comment by dobromir-hristov** [comment]
I am using the Laravel JWT package, the same as you are on your test server.

**Comment by dobromir-hristov** [comment]
OK follow up. I commented on this on the Vue-forum as well. If you use a fat arrow ES6 instead of a normal anonymous function in your interceptor you dont get `this` binded properly. From there it was downhill 😄 
Now the problem still remains where Vue-auth accurately detects 401`s and removes my token but does not redirect me, but then again here is a thought:
By default vue-auth`s logout func redirects to '/' which is index, correct? My app does not have a '/' instead I have a redirect that redirects me to '/modules', but this is where I actually test my tokens, so it may be redirecting properly, after logout, but then vue-router redirects back to '/modules', but since I am there, it gets confused. I will retest it later when I do the rest of the app and have more pages to test from.

**Comment by websanova** [comment]
By default the logout method should be going to "/login". However this can be overridden.

https://github.com/websanova/vue-auth#logout

I'm not really sure what your issue is now otherwise.

**Comment by dobromir-hristov** [comment]
Actually it is redirecting to '/' as stated in the docs. LogoutData redirects to the index :) I just tried to override the redirect property of the logoutData and it actually redirects now. Plugin works as it should and logs out as it should, I just had a redirect on the '/' route that was redirecting me to my current page atm.
