### ISSUE TITLE
why does refresh() and fetch() gets called synchronously?

### ISSUE THREAD

**Issue by biglanggwapoventures** [websanova/vue-auth#79]
When I do a hard refresh on my page, refresh() and fetch() gets called synchronously thus giving a 401 error. Here is the current flow:

1. refresh() gets called with current token
2. fetch() gets called using same token as refresh()
3. refresh() request arrives first so it immediately invalidates the token
4. 401 error on fetch() since its payload token is already invalidated 

Is there a way to alter this behavior? Like invoking fetch() only after refresh() gets called?

**Comment by websanova** [comment]
Yes, so the token "should" not expire immediately. It should live for a
while longer or this would potentially block other requests. It's not just
an issue during login.

If you really want to disable it you can set a flag in the loginData. Check
the docs.

Rob

**Comment by websanova** [comment]
This issue has been updated with some mods for refresh options. Please check docs here for more information.

https://github.com/websanova/vue-auth#token-refresh
