### ISSUE TITLE
Demo of Vue-auth-2.x  failing with error

### ISSUE THREAD

**Issue by BharatKalluri** [websanova/vue-auth#81]
I Cloned the repo and when I am trying to run the Vue auth 2 demo it shows an error saying 

```
ERROR in ./2.x.demo/src/app.js
Module build failed: TypeError: [BABEL] /home/bharat/Documents/Projects/Playground/vueLearn/vue-auth/2.x.demo/src/app.js: Invalid options type for foreign
```

Maybe I am missing something basic, but I cannot seem to find how to correct this error. 

Is there any tutorial as to how to use vue-auth, I cannot seem to find anything online. If not can anyone please post a tutorial on their blog and post a link to me.

**Comment by websanova** [comment]
Did you update the package.json?

**Comment by BharatKalluri** [comment]
what should be the package.json updated to @websanova ?

**Comment by websanova** [comment]
It's in the folder a 1.x and 2.x just updated the dependencies part and npm
install again.

**Comment by BharatKalluri** [comment]
Did that, still getting the same error

**Comment by websanova** [comment]
What's the error?

On Dec 31, 2016 18:26, "Bharat" <notifications@github.com> wrote:

Did that, still getting the same error

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/81#issuecomment-269860873>,
or mute the thread

**Comment by BharatKalluri** [comment]
```
ERROR in ./2.x.demo/src/app.js
Module build failed: TypeError: [BABEL] /home/bharat/Documents/Projects/Playground/vueLearn/vue-auth/2.x.demo/src/app.js: Invalid options type for foreign
```
The same error before @websanova ,
just asking out of curiosity, is sudo needed to run the demo?(I did run the commands using sudo)

**Comment by websanova** [comment]
Ok, well.

it just worked fine for me. Maybe this can help:

https://github.com/rollup/rollup-plugin-babel/issues/83

But can also be issues with npm, node version also....

**Comment by websanova** [comment]
I've also just bumped up the Vue 2 files to the latest, maybe that will
help also v2.3.1-beta.

**Comment by BharatKalluri** [comment]
Maybe this is not a module problem, but more of a npm problem. I am closing the issue.

It would be great if you wrote a tutorial on medium explaining how to use this with an example, would help a lot 😁

**Comment by websanova** [comment]
ya... no time :P

So it works for you now? Was it the node_modules or the latest version that
helped?
