### ISSUE TITLE
Vue Router must be set when using error with Nuxt.js

### ISSUE THREAD

**Issue by scottgrayson** [websanova/vue-auth#82]
I'm testing out Nuxt js and i'm not sure how to get access to the router when doing the setup for this package.  
This is what i was trying (could be alot wrong here):
```
import axios from 'axios'
import Vue from 'Vue'
import VueAuth from '@websanova/vue-auth'
import VueRouter from 'vue-router'

const http = axios.create({
  baseURL: 'https://api.dev/v1/',
  timeout: 1000
})

Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('./vue-auth-axios.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
})
```
Error message:
```
Error (@websanova/vue-auth): vue-router.2.x.js : Vue.router must be set.
```

Has anyone successfully used vue-auth with nuxtjs?

PS your laravel demo helped me alot also 👍

**Comment by scottgrayson** [comment]
https://github.com/nuxt/nuxt.js/issues/99
also posted on nuxt js

**Comment by websanova** [comment]
Yes, it must have Vue.router = ... set

https://github.com/websanova/vue-auth#install-2x
