### ISSUE TITLE
send data post

### ISSUE THREAD

**Issue by nunob87** [websanova/vue-auth#84]
The data is being sent by post the data, but also sends by get, but I want to disable the url data

example url:  /auth/login?email=test@gmail.com&password=12345678,

````
          this.$auth.login({
            params: this.form,
            rememberMe: true,
            redirect: '/',
            success (res) {
            },
            error () {}
          })
````

**Comment by websanova** [comment]
It's up to you the request data is just being forward to http driver. Maybe
try setting body instead of params?

**Comment by nunob87** [comment]
thank you, resolved
