### ISSUE TITLE
Token expire app displays just white screen

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#87]
Is there anyway to set something where if the token expires the user is redirected to the login page.  Because right now if the token expires and i fire up the app white screen is displayed with nothing

**Comment by guilhermewaess** [comment]
@kyoukhana did you override : authRedirect: {path: '/auth/login'},   
Maybe your authRedirect is a wrong route and the router will show a blank screen

**Comment by websanova** [comment]
Yes, this should be handled already, perhaps your routes or redirect is not set correctly.

**Comment by lucasm-iRonin** [comment]
@kyoukhana I think the problem maybe related to the missing callback which I've added in #97 . You can try my fork when you have time and let me know.

**Comment by websanova** [comment]
This should be working, are you using the latest version?

**Comment by websanova** [comment]
Also some would be nice to see some code, like how you are installing the plugin.
