### ISSUE TITLE
fetchUrl question

### ISSUE THREAD

**Issue by purepear** [websanova/vue-auth#9]
Also one more question. Why do we need 2 requests: 
loginUrl - get token
then
fetchUrl - get user data

Can't the loginUrl request provide both `{token: 'asadada.....', user: {id: 1, name: 'Jon'}}`
Or even add the user to the token payload.

Is there a particular reason for the second request? Flexibility?

**Comment by websanova** [comment]
Yes, this could be a possibility, but I think I will add an extra option for this soon

**Comment by websanova** [comment]
This can now be disabled in the `v1.0.x-dev` version.

However by default it will be doing the token refresh on each load. You can disable this by overriding the expiredToken method

~~~
expiredToken: function () { return false; }
~~~

If you set the token in the header or via param during the user (or any other) request it will automatically get sniffed out and set.
