### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#90]
This is the issue.  

If I login I can now access the routes that require authorization.  
If I close the browser and navigate the site to the root a 404 error will come up.
If I change the url path after the 404 I can access the routes that require authorization. 

I am not sure what is the best way to fix this.

**Comment by websanova** [comment]
hmm, will have to take a look.

**Comment by kyoukhana** [comment]
Ok so here is what was causing the problem.  If I had this

```
'/404': {
        component: (resolve) => { require(['./components/views/users/login.vue'], resolve); },
       auth:false
    },
```

I removed auth:false and it worked.
