### ISSUE TITLE
browser cache

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#91]
There is a issue lets say you are logged into your app.  Then you clear the browser cache.  The application should redirect to login if not authorized.

**Comment by websanova** [comment]
Not sure what you means. If you clear, then say click a link to another
protected route, it's not?

Do you have auth set on your routes?

**Comment by kyoukhana** [comment]
So If you clear the cache and click on a route that requires authorization it should redirect you back to login page.  Do you need auth: false, in all the route that don't require authorization

**Comment by websanova** [comment]
No, that wouldn't make sense. The test should be to click on a route that
has auth set to true or to some role value.

**Comment by kyoukhana** [comment]
In your application login then you will be redirected to your page that requires authorization.  Now clear the browser cache without closing the application tab.  You can still browse the pages that require authorization.

**Comment by websanova** [comment]
Ahh, I see what you mean now.

Well yes, the state is stored in the plugin so it would still work but
restrict any requests requiring authentication.

I suppose we could add a check for the token on each route change and if
missing reset the stored data.

Will try to get this in on the weekend.

**Comment by kyoukhana** [comment]
Also keep in mind lets say the network times out.  Something to consider also.  By the way you have done a lot of nice work with this module

**Comment by websanova** [comment]
ok, the browser cache (token disappearing) has been addressed in `2.6.1-beta`. For the network timeout I addressed that in the other issue you opened. But to reiterate this I think is kind of an app level thing as the timeout can happen at any time with or without the auth plugin.
