### ISSUE TITLE
authorization time out

### ISSUE THREAD

**Issue by kyoukhana** [websanova/vue-auth#92]
Lets say you are logged into the app after 60 minutes you click on a icon that requires authorization. It will logout but what happens the vue-router stops working.  I have to empty the browser cache then the routes start working again.

**Comment by websanova** [comment]
What do you mean, "it stops working"?

Like there is a bug, it redirects to logout and then what?

**Comment by websanova** [comment]
This should be handled at the app level as it can occur at any time (not just in the auth plugin). For instance a landing page loading properties or products index, etc, etc.

This is not meant to be a catch all plugin.
