### ISSUE TITLE
Overriding fetchData

### ISSUE THREAD

**Issue by hatzipanis** [websanova/vue-auth#95]
By default vue-auth is hitting `/auth/user` to fetch the user as per the docs. I want to override this to `/account/User`:

```
Vue.use(require('@websanova/vue-auth/src/index.js'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  rolesVar: 'role',
  registerData: {url: 'account/Register'},
  loginData: {url: 'account/Login'},
  fetchData: {url: 'account/User'},
  _parseUserData: function (data) {
    return data.result
  },
  logoutData: {url: 'account/Logout'}
})
```
But I'm getting a 404 and the route doesn't look quite correct:

`
/Login/Login?ReturnUrl=%2Fapi%2Faccount%2FUser
`

Am I missing something?

**Comment by websanova** [comment]
Should work, definitely the plugin is not doing any encoding. Maybe something with webpack or another interceptor/plugin you have installed that is recoding it like this?

**Comment by alireza-molaee** [comment]
I try to disable fetchData but i can't, is there any way to fetch data from login route and don't use fetch data?

**Comment by websanova** [comment]
Not sure what you mean, can you be more descriptive?

**Comment by litvinenkow** [comment]
can't fetch data too, in what parameter of response must be user data by default?
