### ISSUE TITLE
/auth/refresh path

### ISSUE THREAD

**Issue by wcarron27** [websanova/vue-auth#99]
Running into some trouble with the auth/refresh URL. Essentially, on protected routes, when the path is more than one level deep, refreshing the page kicks me out to the login page, like so:

Refresh works fine here: `localhost:3000/profile`
Refresh does not work here: `localhost:3000/articles/new`

The JWT is not destroyed, I can navigate back to a different page and refresh there and the user remains logged in.

The error in my console is this: `GET http://localhost:5311/articles/auth/user 404 (Not Found)`

As it appears, the route for the `auth/refresh` is relative to the current route. Is there a way I can set this to be absolute to the root directory/path?

I tried setting the following in the vue-auth config:
`refreshData: { url: '/auth/refresh', method: 'GET', enabled: true }`

The docs on this repo indicate that it defaults to ` { url: 'auth/refresh'... }`

**Comment by kyoukhana** [comment]
I turned refresh off.

**Comment by wcarron27** [comment]
So...just disable it? Does that force it to request auth/user? What other changes did you make? Or by just turning it off, it just relies on the current JWT in localStorage, which essentially solves the problem?

**Comment by kyoukhana** [comment]
I just turn it of forcing it to request login again.  In the end its suppose to be a stateless app you shouldn't' have to hit refresh

**Comment by websanova** [comment]
What version are you using?

Also maybe post.your routes so we can see.

**Comment by robsontenorio** [comment]
same problem.

```
    "@websanova/vue-auth": "^2.10.2-beta",
    "axios": "^0.16.1",
    "vue": "^2.2.6",
    "vue-axios": "^2.0.2",
    "vue-router": "^2.3.1"
```


Current route /teams/players 
NOT FOUND /teams/players/auth/refresh

But if i set to something

```
Vue.use(VueAuth, {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  refreshData: { url: '/authABC/refresh' } <------

})
```

it got right path

--> /authABC/refresh (but its not the right endpoint on backend)

**Comment by websanova** [comment]
Try without the forward slash.
